### ISSUE TITLE
[1.20.6] RenderLevelStageEvent AFTER_PARTICLES fires incorrectly

### ISSUE THREAD

**Issue by Tschipp** [MinecraftForge/MinecraftForge#10031]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.1.7

**Description of issue:**
I believe the `RenderLevelStageEvent` stage `AFTER_PARTICLES` is being fired incorrectly.
From `LevelRenderer`, `renderLevel`, line 1123 and 1109:
![image](https://github.com/MinecraftForge/MinecraftForge/assets/11649893/fac085c6-67ff-449b-ba41-f314c9d91afc)

I think the first `pFrustumMatrix` argument should be replaced by `poseStack.last().pose()`

**Comment by LexManos** [comment]
Where does poseStack.last().pose() come from? A bunch of things in 1.21 changed to get rid of the posstack. What was it in 1.20.6/2?

Do you have an example of a use for this event so that I can see what the use would be/do testing?

**Comment by Tschipp** [comment]
I use it in Carry On here to draw blocks/entities in third person:
https://github.com/Tschipp/CarryOn/blob/1.20/Common/src/main/java/tschipp/carryon/client/render/CarriedObjectRender.java#L181-L282
I've since converted the code to take a Matrix4f instead of the poseStack.

**Comment by LexManos** [comment]
So, looking at the commit history, and the code, looks like you might be right as that `poseStack.last().pose()` is used in the other calls.
However, Mojang has moved away from passing around the poseStack because it is redundant/unnecessary. So really the argument should just be nuked entirely.

IF we were to keep it post deprecation cycle, It should actually be reverted back to being the PoseStack and not the matrix. As it is more useful information. Tho it'd have to be nullable as there are some cases where it isnt avalible.
