### ISSUE TITLE
Forge is different from the original Eye of Ender detection, is there any way to change it back

### ISSUE THREAD

**Issue by lieyan520** [MinecraftForge/MinecraftForge#10150]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.11

**Logs:** not have

**Steps to Reproduce:**
Open an forge and use the Eye of the Ender

**Description of issue:**
In the vanilla, only one eye of Ender will be used when the right button is held down, and the movement speed will be very slow
But in forge, however, holding down the right button will continuously use the Eye of Ender, and speed will not be affected
 I was wondering if there was any way to change this mechanism back, I didn't see any files about the Eye of Ender in forge's change docs
The first video below is the original and the second one is forge

https://github.com/user-attachments/assets/ea19e82d-0728-4cc2-b1ad-3cfaca1ef3b7

https://github.com/user-attachments/assets/fd772717-b666-46c9-bf82-1b38a64f8b46

**Comment by LexManos** [comment]
So, looking into it, honestly I would consider this a vanilla 'bug'
They set a use time of 0 for eyes of ender but also use a use time of 0 for 'not using any item'
So you're stuck in a limbo state until you release the mouse.
But because I don't feel like having people argue over this i can re-add the bug.
