### ISSUE TITLE
[1.21.4] Wrong Update indicator 

### ISSUE THREAD

**Issue by Stein-N** [MinecraftForge/MinecraftForge#10280]
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.12

**Logs:** no logs

**Steps to Reproduce:**
 1. Create an instance with forge 54.0.12

**Description of issue:**
Forge is indicated to have an update available, when clicking on the link it refers to the 1.20.6 versions instead of the 1.21.4.

**Comment by Jonathing** [comment]
This is not an issue with Forge's update checker. The files site defaults to promoting the latest recommended build of Forge, and the current one is on 1.20.6.

If someone wants to, we COULD change it so that the link in Forge's mods.toml opens the files site at the Minecraft version it is currently running.

**Comment by Stein-N** [comment]
Oh ok, thought the client sends a request for the installed version to the server and gets an answer.
