### ISSUE TITLE
Block.slipperiness should have a position sensitive getter

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1342]
Signature: `(IBlockAccess, int, int, int)float`

Many of the same use cases as #1341. Also only accessed in locations where access to the x/y/z and world exist.

**Comment by mezz** [comment]
@AlgorithmX2, @amadornes, and anyone subscribed to this issue, can you weigh in?
It's a very old issue and nobody has implemented it, so I feel like it can't be that important.
An getter with entity param makes sense, but unless someone actually needs it for something interesting there's no value in adding it.
If this suddenly sparks your curiosity I'll keep it open, but otherwise this issue will be closed soon.

**Comment by amadornes** [comment]
It'd be interesting indeed. `isLadder` takes an entity in as well now, which means I can handle ladders per-multipart based on that entity's collision with the block, so it'd be nice to see the same for slipperiness :)

**Comment by mezz** [comment]
I'm just skeptical that anyone would even notice if 1/4 of a block was especially slippery.

**Comment by howtonotwin** [comment]
In a mod I'm working on, I have a block similar to ice that causes items to retain all of their momentum (perfectly slippery). Since `EnityItem`s multiply `slipperiness` by `.98`, setting `slipperiness` to `1` doesn't cut it; it has to be `1/.98f`. With a getter like this I can only expose this value to items, and have a saner value (< 1) for everything else. (Other entities actually multiply `slipperiness` by `.92`, but someone could make one that doesn't.)

**Comment by mezz** [comment]
@howtonotwin ~~I think that's a similar but different issue. The getter described here would still not know what is calling it.~~ Nevermind, people want an Entity parameter.

**Comment by mezz** [comment]
Well, I think you should make a PR and we can see how it turns out. The more supporting cases there are for this event, the better chance it has of being accepted.

**Comment by Tarig0** [comment]
Possible use case, an entity may be immune to slipping on a particular block, or an attribute on the player may designate how much they should be effected.

**Comment by mezz** [comment]
I think it sounds like it's worth making a PR for it.
