### ISSUE TITLE
[1.8] World.init() isn't called when hotloading a dimension.

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#1551]
When hotloading a dimension through the "DimensionManager.initDimension(int)", the method "World.init()" isn't called. This will then result is a null pointer exception when the world tries to tick the "villageCollectionObj".

For other modders with the same problem:
While waiting for a fix to the Minecraft Forge, this can probably be bypassed by calling the init method manually while listening to "WorldEvent.Load".

**Comment by Aroma1997** [comment]
I have the exact same problem. ( http://pastebin.com/xckNi0GV )

I can go to that Dimension and it gets initialized properly. However when I go to another dimension (Overworld) and then go to that dimension again, it will give me that error posted above.
I looked a bit into that and the problem is, a new Instance of the world is created, but the init() is not called, so therefore the game crashes, because the villageCollectionObj is null.
