### ISSUE TITLE
[Discussion] Entities with subtypes

### ISSUE THREAD

**Issue by hilburn** [MinecraftForge/MinecraftForge#1624]
The inclusion of a Wither Skeleton Entity to replace the vanilla single entity class - 2 distinct mobs system would, in my opinion, solve a lot of issues with handling mobs. 
No other entity in the game, in modded or vanilla Minecraft, has this kind of unique differentiator and it is entirely feasible to want to handle skeletons and wither skeletons as distinct without having to check if (entity instanceof EntitySkeleton && ((EntitySkeleton)entity).getSkeletonType==1)
There are two solutions as I see it:
The first would make use of existing ForgeHooks (spawnEntityIntoWorld) to replace any EntitySkeleton class wither skeletons that try to spawn with a subclass EntityWitherSkeleton. This would require minimal patching
The second would be to remove the wither skeleton code from EntitySkeleton altogether and move it into the subclass EntityWitherSkeleton and patch things properly such that it doesn't even attempt to spawn a EntitySkeleton classed wither skeleton
I'm happy to PR either of these fixes, but thought I would get some feedback on it before doing so, as it's a pretty major change to the Minecraft base, if a welcome one imo

**Comment by diesieben07** [comment]
How is this a "fix"? There is nothing wrong with the current system. What exactly do you think qualifies for a entirely new class? Do you want a separate class for every type of villager, too? Not gonna happen.

**Comment by hilburn** [comment]
There is a difference between villagers - which have different professions which merely control trades and textures and a pair of distinct mobs with differing AI, equipment, size, and spawning patterns. Your equivalence between the two is not appropriate.
Secondly, looking at mods which actually handle mobs generically, they all have to hardcode in solutions for wither skeletons. This is a sign of poor design and that there is in fact something wrong with the current system, and so should be rectified if it's possible to do so.

**Comment by diesieben07** [comment]
And... what is different between `isWither` and `instanceof EntityWitherSkeleton`?

**Comment by hilburn** [comment]
Well, to use one of the better universal modifiers for mods - MobProperties
It generates a JSON for each entity living class that is registered with forge, allowing people to modify the drops of that entity - it has to have a special is_wither_skeleton modifier for the Skeleton handler to be able to differentiate between the two mob types
Alternatively, EnderIO - which has a configurable power multiplier to spawn mobs with it's powered spawner, and operates on the basis of the entity name and would have to hardcode in a special handler for allowing differentiation between the two.
Finally entity instanceof EntityWitherSkeleton operates faster than entity instanceof EntitySkeleton && ((EntitySkeleton).entity).getSkeletonType()==1

**Comment by Cisien** [comment]
It isn't forge's place to rewrite how vanilla implements vanilla mechanics. In addition, changing this would break every mod that depends on the vanilla mechanic.

Yes, I may be bad design, hopefully mojang will address it at some point.

**Comment by hilburn** [comment]
It wouldn't break anything, as (entity instanceof EntitySkeleton && ((EntitySkeleton).entity).getSkeletonType()==1) still returns true
I actually made a small mod to test the concept that listens for EntityJoinWorldEvent and that cancels it and spawns a EntityWitherSkeleton in place. tested with MFR, EnderIO, MobProperties and InfernalMobs and they behaved normally

Finally - Forge very frequently rewrites how vanilla implements vanilla mechanics, else we wouldn't be able to do half the stuff we do with it.

**Comment by diesieben07** [comment]
- This would break people's save files
- The performance impact of the additional call to `getSkeletonType` is negligible and premature optimization

**Comment by hilburn** [comment]
1. depends how it was implemented, if it was done by editing the spawn entity forgehook, then a world trying to load vanilla wither skeletons would just automatically replace them with EntityWitherSkeleton
2. Yes, that is why I put it last on the list - it's not an important gain in terms of performance however it is in terms of generalisation.

**Comment by Nephroid1** [comment]
Hilburn, there might be mods that take advantage of the fact that Skeletons and Wither Skeletons are the same class. Your system might break mods if they use setSkeletonType() to convert between skeletons and wither skeletons directly without spawning them, or something similar. Testing a few examples is insufficient to prove that your change works for all mods.

I'd also like to mention that your point about performance gain is a bit naive. It's important to consider what extra work using your implementation would cause. For example, does the work saved by your "performance gain" offset the work that it takes to intercept every spawn entity event and check if a wither skeleton is actually being spawned? If not, then there isn't actually any performance gain.

**Comment by Wulfson** [comment]
> Your system might break mods if they use setSkeletonType() to convert between skeletons and wither skeletons directly without spawning them, or something similar.

Ex Nihilo does just that

**Comment by Crudedragos** [comment]
There have been modded entities with subtypes. MoCreatures 'BigCats' come to mind (don't know if it still does, haven't used it in awhile) as well as Project Zulu horses for awhile. I'm sure there are others. Its not as important to do anymore as we don't occupy vanilla slots, but it can still be useful to share certain logic.

As a third solution, we could make what is there easier to manage. Create generic methods for dealing with any entity witha  subtype: i.e. 
```
public String[] getSubtypes(); // return possible subtypes i.e. 'skeleton' and 'wither',
public String getSubtype(); // return current subtype i.e. 'wither' if getSkeletonType==1
public void setSubType(String subtypeToSetTo) // Set the subtype to what is provided
```

**Comment by hilburn** [comment]
I'm gonna try to answer these in turn - bear with me:
@Nephroid1 I have not found any - and have checked roughly half the mods concerning mobs in NEM including all of the major ones which is hardly a "few examples" - secondly with the shift to 1.8 they are going to have to do a rewrite anyway, IF there was such a mod, they could then change that implementation at that point in time for little extra effort. Finally the point was not "a bit naive", it was "a bit not-serious" however. But while I would argue that doing a single check on spawning an entity will generally prove overall to be more efficient than performing the check every single time you want to interact with an entity (casts are significantly more expensive than instanceof) but you're still talking ns either way and the difference is negligible.

@Wulfson - I thought Ex Nihilo did respawn the entity, otherwise they wouldn't have stone swords when they die...

@Crudedragos - I really like this idea actually - have an IMutliEntity or something and handle things through that

**Comment by hilburn** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/1624#issuecomment-68895342 
There is my reasoning as to why it would be better to split up the two - however I think that the idea of creating a Forge Interface for sub-typed entities as suggested by @Crudedragos [in this post](https://github.com/MinecraftForge/MinecraftForge/issues/1624#issuecomment-68943427) would be better as a more generic solution, although maybe using integers rather than strings to differentiate between the types would be better.
I was never trying to say that splitting the classes was the only way of doing it, it was just one way I saw of doing it which would prevent the 20 or so mods that deal with Wither Skeletons specifically/separately to Skeletons from having to hardcode that in.
Implementing that interface would allow people to create a more general isEntityOfType and spawnEntityOfType functions without having to clone from NBT or hardcode in a lot of trickiness - eg re: your initial point about villagers, saving a villager by NBT and then spawning a new one is currently the only way to create a villager of the same type - however this will mean the trades are the same as well which is generally undesirable - so spawnEntityOfType(entity, subType) would be able to produce a new "library" villager without cloning that aspect of them (similarly with equipment on other entities)

**Comment by Wulfson** [comment]
> I thought Ex Nihilo did respawn the entity, otherwise they wouldn't have stone swords when they die...

See here:
https://bitbucket.org/Erasmus_Crowley/ex-nihilo/src/a31e934bdf2bc29a5b8ac9b6dff2b938c2e21d3b/src/main/java/exnihilo/fluids/BlockWitchWater.java?at=master#cl-114

**Comment by Nephroid1** [comment]
> There is my reasoning as to why it would be better to split up the two - however I think that the idea of creating a Forge Interface for sub-typed entities as suggested by @Crudedragos in this post would be better as a more generic solution, although maybe using integers rather than strings to differentiate between the types would be better.

Unless I'm mistaken, isn't that pretty much what exists already? Skeleton already has types that can be identified with integers. For the other mobs, it would be easy for modders to extend those classes and add the relevant functions, right?

**Comment by hilburn** [comment]
@Nephroid1 it is **pretty much** what exists today, which is why it would be easy to implement and non-invasive, however it would have the rather large advantage that any mod interacting with entities only ever has to make 2 checks - what's the entity and what's it's subtype - as opposed to currently something along the lines of: what's the entity? is it a skeleton? what's it skeleton type? else is it a villager? what's it's profession? else is it a creeper? is it charged? else is it <some mod entity with some other subtype>? etc

@Wulfson - ah fair enough, TIL

**Comment by Crudedragos** [comment]
@Nephroid1 Having a single method to be called, irrelevant of the entity is not the same as having to call different methods on a number of different entities. Generic access to subtypes (and if there are any) allow it to be exposed in a manner like metadata for blocks. Could you image having to cast a block to its subclass (BlockGrass/Stairs/Ladder) to call a specific method to determine its metavalue?

Extending skeleton to have subtytpes is ridiculous. Creatures, WaterCreature, Ambients, or simple something not wanting to be seen as an EntityMob, IMob, or IRangedAttack should be able to have subtypes.

But concrete reasons / use cases matter. A reason to want to treat subtypes as if they are a unique entity is useful so that we can set data related to that entity (i.e. health/armor/drops) relative to the subtype. (By someone who isn't the entity author obviously). This is most evident in mods like MobProperties or JustAnotherSpawner which allow users to configure entity data.

In MobProperties, for example, it has a condition if_wither_skeleton. This allows separate actions to be taken for each type, such as making skeletons weaker while leaving wither as a suitable challenge. To support this the author of the mod must add support for every subtype desired. If a generic get/set method exists this kind of support could be done for gratis with an if_type check that accepted a String*.

In JustAnotherSpawner, the above also applies, but it would also be possible to assign custom data to each subtypes such as biomes to spawn in and spawn weights. So when a user wanted to make Wither spawn in another biomes they simple do the same thing they do for all entities, as opposed to having to write a nbt editing expression to change the skeleton to a wither after spawning. It would also them to have them spawn in the same biome and control their relative frequency the same as all other entities with the weighted spawn chance associated with spawn list entries.

The existence of getSubtypes() allows a log/file to be printed to inform users / validate what the possibilities are (like a NEI id dump) so that they are not guessing what they can print in.

* My preference for String over an int or other arbitrary data type for myself is that all my use cases are interacting with these by individuals who are not the original author of the entity and having sensible names that give some clue to their identity is incredibly useful at that point.

**Comment by hilburn** [comment]
I can understand wanting it to be readable, however I think numbers are probably the better way to go, for example if (villager.getSubtype()>4) //Modded Villager
but another method that would be useful would be a String getDescriptiveName(int subType) - to allow access to that data when you needed it

**Comment by Crudedragos** [comment]
True. But it does requires knowledge of the specific entity and at that point you could just cast to Villager access the type data (assuming its backed by an int) anyway. 

More importantly its more fragile, easily broken as new types are added (moreso if doing clever things). For the modded villager example, villager.getSubtype() == 5 would be different if a different combination of mods are added. But you can always check for 'CustomVillagerByMod1' or 'CustomVillagerByMod2' no matter if either mod is installed.

**Comment by hilburn** [comment]
True, but using the villager profession ID (which already has the requirement of being  unique integer) as the subtype would prevent such "morphing" of subtypes - beyond the villagers all vanilla mobs with variants are static, with no way for modders to add eg another type of EntitySkeleton to that class so the only other subtypes would be of their own creation.
For me the most pressing reason to use ints would be to keep the code clean, they are already used to actually store the variants so for example setSubType("villagerBlacksmith") would involve a HashMap<String,Integer> lookup and then a reversing HashMap<Integer,String> for getSubType() whereas using an int for the get and set type would bypass that, and then getTypeString(int type) would a) be less frequently called and b) only require one lookup table

**Comment by Nephroid1** [comment]
>Extending skeleton to have subtytpes is ridiculous. Creatures, WaterCreature, Ambients, or simple something not wanting to be seen as an EntityMob, IMob, or IRangedAttack should be able to have subtypes.

@Crudedragos 
I might have not said this clearly, but I meant extending other classes of other mobs. Not the skeleton class. So if they want a pig with more subtypes, they can make a custom class that extends the pig class.

Of course, there would be casting needed with this method, which might not be ideal if mods wanted access to arbitrary mobs from other mods. A solution for this would be to add the relevant get and set subtypes methods to the IMob (or whatever the most overarching interface/superclass is). Then you would only need to add those methods to the concrete vanilla classes. (Though this is more of a general mob quality of life improvement rather than a wither skeleton "fix" now.)

As for actual implementation details, I think integers is a better choice than strings. As far as modders are concerned, they can always use well-named integer constants to attach meaning. Strings are a bit clunkier to deal with; for example, "Wither" and "wither" are two reasonable string identifiers for the same thing, and it's arguably harder to find out that you made a slight spelling mistake than finding out that you used the wrong integer ID, especially once you start having lots of strings that you need to keep track of.

For displaying the names in game, there would be a method that converts integers to strings and back, but you'd still need this display method if you're using unique strings to identify subtypes too.

**Comment by Crudedragos** [comment]
I misunderstood your extends comment, apologies.

I've always imagined that these would likely end up dumped in the Entity class. We'd just be checking gettypes != 0 instead of instanceof. Not a real difference.

It should be General and not a real skeleton 'fix'. It's the difference between fighting and changing how vanilla does things versus making the best of it.

Both of my use cases described above involve end users editing configuration files. Named constants would not be used. Just as with block / biome / entity.

it's also likely not the author if the original Entity class interacting with it. Named constants then require you knowing what the class is anyway, using specific data that you've saved elsewhere to use a generic method on that entity. If you're being entity specific anyway you might as well cast and use it's accessor for it's internal data (integer, enum etc).

Validating user input is and auto corrected for case due to gettypes. What is easier to fix 
"Wither is wrong did you wither or skeleton"
Or
"3 is wrong did you mean 0 or 1"?

The use cases I describe are using the string as a unique identifier. A display does not and should not have to be unique. Multiple types of villagers may want to simply display add villager.

**Comment by hilburn** [comment]
Villager ID is guaranteed to be unique because like the old block ids, it broke stuff, if they weren't - however unlike blocks there are not only comparatively few professions (order 100) but they also have the full range of Integer to pick from - so the chance of clashing is pretty minuscule if you just smash the numpad a couple of times

Your comparison with blockIDs is apt I feel, because block ids are still there, they are just dynamically assigned by Forge, so an implementation of this would likely do the same, caching subtypes as they are registered with Forge.

@Crudedragos I'm somewhat confused by 

>The use cases I describe are using the string as a unique identifier. A display does not and should not have to be unique. Multiple types of villagers may want to simply display add villager.

Which I completely agree with, this is why an int based key with a lookup on the display name is preferable imo, the string shouldn't have to be unique, which is the premise you are basing a string based key system off. As for the infrequency of checking subtypes making the extra map.get() negligible - It's far less frequently that you're going to be outputting data to users (from your example, only when they actually try to configure stuff) which could be more easily handled.

Final point - I haven't yet found an example of a multi-type entity that uses anything other than a boolean or int as the type key - by using an int as the subtype identifier, you are minimising the amount of work that modders have to do (the hashmaps etc) and therefore increasing the chance it will be implemented properly, as all they'll have to do is wrap their current get/set type methods, either passing the int directly or passing type==1 / return type?1:0;

**Comment by LexManos** [comment]
Forge is not in the game of rewriting vanilla class hierarchy. 
From the very beginning, this isn't showing any need for a change.
We are not adding a abstraction layer to Minecraft, so a 'spawnEntity(Type, SubType)' isn't going to exist. 
As for the arguments of integer vs string, its moot, it will be string of some kind. [b]IF[/b] you guys come up with a concise idea, that doesn't add a million patches.

**Comment by mezz** [comment]
Minecraft 1.11 has a cleaner Entity hierarchy without cramming multiple entities into one class, so I think this issue is resolved.
