### ISSUE TITLE
[Suggestion] PlayerInteractEvent needs a Post variant

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#1631]
Making this issue mostly to talk it out with @bloodmc. 

In my use case, I need to be able to know if the RIGHT_CLICK_BLOCK action activated the block or used the item, so I can open a GUI in the latter case. This is currently impossible as the only way to do it would be to cancel the event and recreate all the code that happens after it. A Post variant of the PlayerInteractEvent would not be very difficult to add, and would fix mine and many other use cases.

**Comment by tterrag1098** [comment]
Problem arises here: https://github.com/TheCricket/Chisel-2/blob/master/src/main/java/com/cricketcraft/chisel/item/chisel/ChiselController.java#L85-L90

I have no way to know if the block "did" something (i.e. button). If it did, I should not be opening the GUI (as onItemUse was not called).

**Comment by ollieread** [comment]
I'd also have a use for this event.

I have an ability system using the PlayerInteractEvent. Right now, I just outright cancel the event to make sure nothing else happens. This means that if a players inventory is full they have to throw something away to actually access a machine/block.

This event would work wonders as I'd be able to see whether or not the block was activated, and wouldn't fall into annoying situations where I do things such as set my workbench on fire rather than open it.

**Comment by 28Smiles** [comment]
@tterrag1098 Couldn't you cancel the onPlayerInteractEvent if the player Interacts with a Block and fire the onBlockActivated method of the Block the Player clicked self, then you could check if it returns true, for interaction, or false, for non interaction. If it is non interaction you could open your gui?!

**Comment by mezz** [comment]
@tterrag1098 is this still an issue?

**Comment by tterrag1098** [comment]
Currently working on reimplementing this feature in Chisel for 1.10+, I'll let you know if the problem resurfaces or not.

**Comment by tterrag1098** [comment]
Confirmed, this issue is resolved by the existence of `PlayerInteractEvent.RightClickItem`, there is no longer any confusion between block activations and item activations.
