### ISSUE TITLE
[1.7.10] "Silently" catching entity tracking error log spam

### ISSUE THREAD

**Issue by erkro1** [MinecraftForge/MinecraftForge#1648]
I get this spam of messages that it can't track an entity which makes my game run very slow, does anybody know at which mod could be the problem?

full log:
http://paste.atlauncher.com/view/5774ff1b

**Comment by Cisien** [comment]
This happens when you remove a mod that added entities (mobs) to the game. Any chunk loaded after the mod was removed will cause this message. It will subside after all of the chunks that previously contained entities that no longer exist are loaded.

It would be nice to see this log message be hidden away in the stock log4j config though. (and I think this belongs in MinecraftForge/FML ?

**Comment by erkro1** [comment]
@Cisien Weird, i haven't really removed mods, only updated, and none really added or removed mobs.
Also where can I find that log file you're talking about, I can see a log4j2 file put I don't think that will give much information.

**Comment by erkro1** [comment]
@Cisien Could you still help me with this problem?

**Comment by LexManos** [comment]
[18/1/2015 15:39:54 PM] Caused by: java.lang.IllegalStateException: Entity is already tracked!
    [18/1/2015 15:39:54 PM]         at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]

Your world is corrupt, somehow two+ entities with the same ID are being added to the world tracking list.
This usually happens when you restore a backup or something causes entities to be saved in multiple chunks.
Or, a mod is breaking things.
However, this isn't on our end.

**Comment by karst** [comment]
I have this problem in the complete nether. Next to that I also get kicked for 'A fatal error occured' with this message in the console. I am using a server that has about 250 mods (yes I know that is a lot)

**Comment by erkro1** [comment]
@karst What version of EnderIO are you using? It has fixed for me like a few versions back.

**Comment by karst** [comment]
I see I use version 1.7.10-2.2.8.349

**Comment by erkro1** [comment]
I think version 354 should fix it (it says "#2027 Skeleton spawner in nether freezes game" in changelog).

You can get it here and try it out:
http://ci.tterrag.com/job/EnderIO/354/

**Comment by karst** [comment]
I updated and I don't crash in the nether anymore, thx for the help ;)

**Comment by erkro1** [comment]
Glad it worked! Have fun playing :D
