### ISSUE TITLE
Potions and Curative Items

### ISSUE THREAD

**Issue by hilburn** [MinecraftForge/MinecraftForge#1701]
Right: I would like to talk about a rework of potions and specifically curative items - I've given this a reasonable amount of thought and would be happy to submit the PR if this has support.

Currently I think Curative Items are handled poorly, the curative items list is set in the PotionEffects constructor to include the milk bucket. This means that even if you do add a curative item or otherwise modify that list, after the entity has been saved and reloaded, it will revert back to the single Milk list. The only way around this is to do something reasonably dodgy with the `potion.performEffect` method which checks the EntityLivingBase it is passed for the effect that called it and then modify that PotionEffects curativeItems if necessary. This is not ideal as it is a check that must be made every single tick the potion effect is active. Alternatively if you wanted to modify an already existing Potion's default curative items - you would need to create a TickHandler or ASM in something to do this modification.

My proposed solution for this is to move the curativeItems list to the Potion class, redirecting the existing curativeItem methods (get, set, is, and add) to `Potion.potionTypes[this.potionID].get...` - maintaining compatibility with anything that is currently modifying the list in the effects, but also opening up the methods in the Potion class for a cleaner solution.

Alternatively and arguably simpler, adding the curativeItem list to the NBT save/load for the PotionEffect would be a significant improvement as it would allow the modification of the curativeItem list when the effect is first applied and it would be retained through save/load cycles

I'd like to hear any feedback on this if you've got it

**Comment by LexManos** [comment]
Humm, yes, it isn't meant to be per-instance. It should probably be moved to the Potion singleton classes. And the old methods deprecated.

**Comment by hilburn** [comment]
Another thing, a minor performance gain (as well as neater code imo) could be achieved by changing:

    public boolean isCurativeItem(ItemStack stack)
    {
        boolean found = false;
        for (ItemStack curativeItem : this.curativeItems)
        {
            if (curativeItem.isItemEqual(stack))
            {
                found = true;
            }
        }
        return found;
    }

to

    public boolean isCurativeItem(ItemStack stack)
    {
        for (ItemStack curativeItem : this.curativeItems)
        {
            if (curativeItem.isItemEqual(stack))
            {
                return true;
            }
        }
        return false;
    }

It's not a particular worry as most things only have 1 or 2 things in their curativeItem list, but as you'd be changing the methods anyway I thought it might be worth pointing out

**Comment by LexManos** [comment]
Ah ya, that could be cleaned up a bit, i'll keep that in mind.

**Comment by chylex** [comment]
Having both suggestions might not be a bad idea either, some mods have features where negative effects are caused and need to be cured using special items or cannot be cured at all.

The problem there is that might cause conflicts when the same effect type is applied with different stats and the old one gets replaced, so if mods were able to re-create vanilla effects with different IDs, they wouldn't get replaced.

Basically it could be a map of vanilla potion IDs -> custom IDs that would cause the same effect, so instead of checking whether an entity has Potion.weakness.id, it would check if it has any of the ids from map.get(Potion.weakness.id). Getting the PotionEffect would grab either the one with highest level.

Regarding the amount of additional patches it would cause, I think that instead of replacing every usage, the EntityLivingBase potion collections could be replaced by custom ones that would follow the described behavior.

Any opinions on that (and potential problems I missed)?

**Comment by Alpvax** [comment]
I started writing a mod (Using a little ASM) that transferred potion effects to Attributes, both allowing for this sort of fine control with ease, and allowing people to have potion effects on armour implemented in a better way (you could have strength on your armour, and there would still be a point to making a strength potion. However, I hit a wall when it came to compatibility with the existing system (IRL commitments dragged me away). Its a suggestion if anyone wants to continue it, I can give you what I have, although it is still in a very early stage. (for example Regen / Degen were enacted per tick, with no damage indication, just using heal(float))

**Comment by bs2609** [comment]
I _think_ this is resolved by #3573, although as it's been over 2 years I can't tell...

**Comment by williewillus** [comment]
Yes, this can be closed now
