### ISSUE TITLE
Fortresses get regenerated when loaded vanilla world

### ISSUE THREAD

**Issue by irtimaled** [MinecraftForge/MinecraftForge#1747]
If you load a vanilla world and go to the nether the fortresses all get regenerated using the latest fortress generation algorithms.  This is because the WorldSpecificSaveHandler looks for the fortress.dat file in ./saves/world/DIM-1/data instead of ./saves/world/data

Initially raised on forum with screenshots... http://www.minecraftforge.net/forum/index.php/topic,28635.0.html

**Comment by LexManos** [comment]
That's the point of WorldSpecificSaveHandler, to make the save location World Specific {well Dimension specific}
Move your Foretress.dat over and it'll load fine.
Vanilla MC is considered bugged because multiple worlds overwrite the same files causing data loss. 
This has been fixed in Forge for years.

**Comment by irtimaled** [comment]
That's fine; I appreciate why this is done the way it is, but I would argue if there is an established place to store the dat files, dat files exist in that location, and Forge choses a different location then it should handle this by copying the existing files into the new location automatically.  I will send a pull request for this change.  If Forge doesn't handle these existing files well then existing nether fortresses and, more importantly, wither farms, will break when users decide to upgrade to Forge!
