### ISSUE TITLE
Extend Block IDs limit

### ISSUE THREAD

**Issue by Adaptivity** [MinecraftForge/MinecraftForge#1769]
Since 1.7.x MC no longer uses numerical IDs (For blocks and Items) and that's means no more conflicts. But IDs number still limited especially for blocks (Excluding enchantment, biome IDs).
So, since it's too late to change IDs number for 1.7.10, what about 1.8? This change will destroy existing worlds but since modded world conversion from 1.7.10 -> 1.8 ~~almost~~ impossible, what about extending Block IDs range right now?
I think it's best time to break compatibility with old worlds since no big mods released for 1.8 and not so many people playing in modded 1.8 (I think nobody playing, heh). And yeah, I've got few reports about reaching maximum IDs number in 1.7.10, yes it's not a joke. Thoughts?

**Comment by LexManos** [comment]
World transfer from 1.7.10->1.8 is nowhere near impossible.
And no we're not breaking id compatibility because that would break the thousands of tools out there that deal with the world files directly.
Having enough blocks loaded that you breach the 4096*16 id limit seems excessive in my opinion.

**Comment by Termin8or** [comment]
Adaptivity I suggest you use less individual blocks and just make variants, if this is affecting you directly

**Comment by Adaptivity** [comment]
@Termin8or I'm not a modder, just a user.
@LexManos There are 32k item IDs and this is too many. But having just 4096 individual block IDs, well just not enough since how many mods are out for 1.7.10.
As I say, I saw few reports about reaching maximum ID range. So, maybe consider a change in 1.8 since there are not so many mods? It wouldn't be easy and break some stuff but everything can be fixed, right? If you still won't implement it in any way, just close this issue.

**Comment by LexManos** [comment]
The answer is no, something this fundamental of a shift has to come from Mojang.
It is not without Forge's scope to dictate new world formats, network protocol, and save formats.
Technically in 1.8 there are 65535 block ids. Which is plenty enough. Modders just need to use things correctly and not be wasteful.

**Comment by tschallacka** [comment]
uhm, just to confirm, there are 65535 blocks that can be added before minecraft will complain? or are there still limits that limit it to 4096 what I seem to have gathered from a forum post out of 2013?

I might end up having a mod that adds roughly 200 blocks(a lot more if you count each variant as an individual block) and I don't want to have modpack makers to worry about the block id's if they add my block with some other mod that adds a lot of blocks.

Otherwise i'll have to do some tile entity magic, but that is slightly less performing and more memory hungry.

**Comment by williewillus** [comment]
4096 Block IDs, 16 metas per block ID = 65535 unique block+meta combinations. That's how its been since 1.2.5's Anvil format and will stay like that till Mojang changes it again (I feel like it'll be soon)

Just use metas

**Comment by tschallacka** [comment]
Ah, like that. Okay. Well, i was already using blockstates, ill just keep it in mind. Is there a way to detect if the max has been reached or will a fatal exception be thrown?

Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>



On Wed, Apr 6, 2016 at 10:27 AM -0700, "Vincent Lee" <notifications@github.com<mailto:notifications@github.com>> wrote:


4096 Block IDs, 16 metas per block ID = 65535 unique block+meta combinations. That's how its been since 1.2.5's Anvil format and will stay like that till Mojang changes it again (I feel like it'll be soon)

Just use metas

-

**Comment by iTitus** [comment]
I think GameRegistry will tell you. With a crash :P
FYI the block limit _will_ be increased in 1.10 ([source](https://www.reddit.com/r/Minecraft/comments/3tgqz4/whats_going_to_happen_when_all_block_ids_are_used/cx6sc47?context=1)).

**Comment by LexManos** [comment]
If the time ever comes, we'll adapt.
However its on Mojang to dictate the world format and network protocol so it's all on them.

**Comment by jredfox** [comment]
I can make a base class edit where is it located at? I can easily change the number to short if its an array or integer if it's just numbers. short is 32k. and integer well thats in the billions range. the reason why I can't do an int array is it will take more then 1g of memory alone to initialize it.  short doesn't take more then a couple mb so if it's an array it shouldn't be an issue for short, if it's just ids numbers then integer.

**Comment by raoulvdberge** [comment]
It's not as simple as changing the block class, you'll also have to change the network and save format, which is something Forge doesn't want to (understandably) do.

**Comment by williewillus** [comment]
@jredfox if you don't know what you're doing don't hack around 

these changes can only be reasonably made by mojang

**Comment by jredfox** [comment]
what about save formatting? could you tell me a bit more so I can coordinate the right conversion. Don't worry I am getting mojang's permission if the mod goes public .

**Comment by LexManos** [comment]
"If you don't know what you're doing don't hack around." There is no real reason to need this at this point and as stated, reformatting the save format is not in our hands.
