### ISSUE TITLE
[Suggestion] Improvement of OreDictionary using interface

### ISSUE THREAD

**Issue by hokutoMc** [MinecraftForge/MinecraftForge#1777]
I suggest two interfaces and a class to improve OreDictionary system. Below is my gist.
https://gist.github.com/hokutoMc/7912d68411395bc528ea

**Comment by LexManos** [comment]
So what you're saying is we create two separate registration pathways so that things get jumbled and processes repeated? I think not.
As for introducing the predicate system, Doing so just opens up a big can of worms in having to re-write all of the vanilla recipe handling systems to use predicates.
