### ISSUE TITLE
"Poisonous NBT" server vulnerability

### ISSUE THREAD

**Issue by coolsquid** [MinecraftForge/MinecraftForge#1806]
@ammaraskar discovered a bug where the client can generate "poisonous NBT", increasing the server load extremely and making the server crash with an OutOfMemoryException. The issue has been described in a more technical way [here](http://blog.ammaraskar.com/minecraft-vulnerability-advisory/). I know this is a Vanilla issue, but it's quite huge, so hopefully Forge can include a fix.

**Comment by KingLemming** [comment]
This has been known about for a long time by many of us.

Whitelisting pretty much solves it already.

**Comment by LexManos** [comment]
THere are a few potential fixes, but the issue isn't the NBT per-say. As that is limited to 2MB. It's the spam of packets thats the issue. As would be in any network protocol. The ONLY reason this is considered a 'vulnerability' is because of it's large payload to response ratio. Roughly 64:1, which in of itself isn't that big of a deal.

If he felt like it he could actually get the payload a lot smaller... {I did a test where it was 260 bytes -> 2 mb}
But yes as King says this is far from a "sky is falling" event.
If you have a proposition that would prevent the client from spamming packets let me know.

**Comment by DarkGuardsman** [comment]
May I suggest a way to monitor the source of the packets. Then have something that triggers and event call when the packet volume from a single source gets to high. This way a mod could be developed with the event to auto kick player's spamming packets

**Comment by cpw** [comment]
Pointless to try and protect IMO..

**Comment by cpw** [comment]
Lex, the compressed nbt string expands into a deeply nested nbt structure that blows out the memory..

**Comment by cpw** [comment]
Its not about network flood, directly. You can spam a few dozen of these packets and murder memory.. Protection in FML or forge would likely invalidate many nested nbt use cases in regular mods..

**Comment by DarkGuardsman** [comment]
I guess this falls in with Xray hacking and being difficult to prevent.

**Comment by LexManos** [comment]
cpw its about both network and nbt. I understand exactly what is going on.
His MAIN 'exploit' was fixed, by Mojang limiting incoming NBT to 2MB.
Which he simply got around by spamming the packet.
It's not a combination exploit and NOT just NBT.
The NBT has been handled, it's the packets that are the issue right now.

**Comment by cpw** [comment]
He can still construct a custom pipeline in FML/netty to compress/decompress the packet request, leveraging the 'best' of both worlds, kinda. Its a dumb attack tho and only affects only servers with no other security for long..
Its not like its information exposing, its simply a dumb dos attack that will likely result in quick white listing on any victim server. The server will likely not even suffer data loss..

**Comment by ammaraskar** [comment]
>His MAIN 'exploit' was fixed, by Mojang limiting incoming NBT to 2MB.

It wasn't, mojang tried to fix it but didn't actually test it. It turns out tag list ends were considered to not take up any space. With a single packet you can make the server use up more than a gig of memory, not much spamming required.

**Comment by Kubuxu** [comment]
Spigot fixed it with small (very small) patch [patch](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/Spigot/commits/52df9dd70f0) for 1.8.

**Comment by LexManos** [comment]
That doesn't seem to be a 'fix', however, been derping around with it all day because I had nothing better to do. And I can't actually reproduce it in any feasible manor. The concept is sound, but i've got my client pumping out 4TB worth or NBT data to the server every second and the server is chugging along just fine... The stacks that this targets are only short lived stacks that the packets discard when they are done, and the GC eats them up. Can't get a single case where it actually functions. Tested on the smallest servers I could find with the crappiest CPUs.. and nothing.

**Comment by ammaraskar** [comment]
That's interesting, you mind showing me the code you're using to generate the nbt you're sending? I very specifically use LIST TAG ENDs. Aside from my personal testing I've got two independent reports [here](https://www.reddit.com/r/2b2t/comments/32tj93/thanks_for_the_heads_up_i_guess/) and [here](https://www.reddit.com/r/admincraft/comments/32t9si/hey_radmincraft_i_found_a_security_vulnerability/cqefpn8) that it works fine.

**Comment by LexManos** [comment]
Was able to tweak my code a bit and get it generating invalid nbt that caused the server to freak out. But using normal mechanics didn't I was hoping not to have to serialize it myself.
Anyways, it does indeed allow you to eat memory, and this shows where A LOT of NBT data isn't being counted by the size tracker. Guess i'm going to have to go in and dissect all the NBT readers.

**Comment by ammaraskar** [comment]
>Lists do not have a END tag as they are length prefixed.

That's exactly the thing, you can put multiple END tags in lists, and it wont account for the size.

**Comment by LexManos** [comment]
oh ha, a list of type END wouldn't read anything from the data stream ha!
Damn that means my generic fix won't work.
The SizeTracker is in of itself very poorly implemented. There should be no reason to manually count 90% of the data. As hooking into the DataInput functions would be far easier. Just need to think of a way to allow for external incrementing of that.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/de066a86da281d381b0e3ab9e83682720327049c
I hate doing it this way, I would prefer to do something like this: https://gist.github.com/LexManos/6054f1ae2fc1937633df

**Comment by chibill** [comment]
Well mojang fixed this finally. As a 1.8.4 release.

**Comment by LexManos** [comment]
It's fixed in Forge as well by the previous commit. We're a bit more lenient than 1.8.4 but it accomplishes the same thing. It doesn't address the plethora of other ways to crash the server via the client. But as this one is the trend of the day the fix is in.
Whenever cpw gets time he will backport it to 1.7.10 as he is the one in charge of that.

**Comment by cpw** [comment]
Should be back ported to 1.7.10 this weekend. What a DUMB waste of time..

**Comment by minecraft8997** [comment]
Hello! Is it fixed in Forge 1614 (1.7.10)?

**Comment by ravenbuilder934** [comment]
Don't necro old conversations.

**Comment by minecraft8997** [comment]
> Don't necro old conversations.

It's really important for me. I can't update to the newer versions. Sorry

**Comment by diesieben07** [comment]
1.7.10 is no longer supported by Forge.

**Comment by minecraft8997** [comment]
This vulnerability seems to be fixed in Build 1376
