### ISSUE TITLE
No mipmapping with forge 

### ISSUE THREAD

**Issue by Brottweiler** [MinecraftForge/MinecraftForge#1825]
Another bug report... This is while using only forge, with no extra mods. I also have Mipmapping set to 4 (max) in the settings.

# With Forge 
![2015-04-24_17 43 13](https://cloud.githubusercontent.com/assets/1613137/7322654/af4787de-eaa9-11e4-8b16-f64d1c2f4e87.png)

# Without Forge
![2015-04-24_17 43 50](https://cloud.githubusercontent.com/assets/1613137/7322656/b4848e4a-eaa9-11e4-95d2-461abcf0cab4.png)

**Comment by fnuecke** [comment]
FWIW, I ran into this issue not too long ago (though it was definitely *not* caused by Forge itself in that case). The reason then was that there was some texture loaded into the atlas that had a size that was not a power of two. Maybe there's some texture your version of Forge loads into the texture atlas that has an odd size? Or you're running a resource pack that does?

**Comment by Brottweiler** [comment]
@fnuecke I just tested using the **default resource pack**, but I still don't have mipmapping with Forge. I am using `11.14.1.1334`, which is the currently recommended Forge build.

**Comment by Brottweiler** [comment]
Welp, I tried using the **latest** version, `11.14.1.1392`, and that doesn't have the issue.

**Comment by LexManos** [comment]
Fry Broke it: https://github.com/MinecraftForge/MinecraftForge/commit/93cd9722b031997e57387832ecd5d4159418c9e6
Fry Fixed it: https://github.com/MinecraftForge/MinecraftForge/commit/46b1b82f13005c0d3c2f66832ffb0a477caa2131
