### ISSUE TITLE
Forge 1408 and Bungeecord

### ISSUE THREAD

**Issue by devryb** [MinecraftForge/MinecraftForge#1891]
I setup a test server with just forge 1408 and same with the client.
I downloaded the latest bungeecord and tried to connect to my test server.

The client gets this message:
http://puu.sh/hX7Zk/56f0bdc797.png

Client log:
http://pastebin.com/Hub6jA6r

Server log:
http://pastebin.com/xpCkrebh

Bungeecord log:
http://pastebin.com/3RJzbDPH

**Comment by devryb** [comment]
Doing these exact same steps with 1403 the client connects fine

**Comment by devryb** [comment]
Even more interesting is i can put 1403 on the client and connect to a 1408 server on bungee just fine so it was a recent client change that broke things it looks like

**Comment by LexManos** [comment]
Most likely a hardcoded version issue on BungeeCord's end.
Functionally nothing changed, the FML repo was just merged into Forge's

**Comment by devryb** [comment]
Hopefully, that will make it an easy fix then.  Logged in both places for completeness

**Comment by dualspiral** [comment]
This is something I'm working around on the Bungee end now, but for completeness' sake, Bungee is tripping up over [this commit](https://github.com/MinecraftForge/MinecraftForge/commit/686db5e5eb53fd4ca29e8da40312891d872a36ec). Bungee looks at the build number, and checks to see if the build number is over 1209. Because it is now hardcoded to 99 in Forge, this check fails.

I'll add a specific exception into BungeeCord for this.
