### ISSUE TITLE
[Suggestion] API for forge to hook into as secondary modloder for M3L

### ISSUE THREAD

**Issue by Prophious** [MinecraftForge/MinecraftForge#1894]
well there is a new modloader that will allow for tall worlds(the mod name is tallworlds) so i was wondering if there would be a way to link the compatibility with M3L(MAGIC MOJO MOD LOADER, current minecraft version is 1.8.3, still in beta atm)

ya see the mods that it will run are different then what forge uses for minecraft, like chunk rendering and generating, so basically once that modloader is done it will be able to have tall worlds with alot of forge mods like thaumcraft and tinkers construct to name a few

i do not own M3L or "tall worlds" mod, i am just a 3rd party trying to get compatibility with the mod/modloader and forge

i personally would help if i knew what to do and how to do it.... but i have very little programing experience and none in java(but will be learning soon)

best of luck to both teams here, maybe we can get some epic games going here

**Comment by Spartan322** [comment]
Well seeing as M3L is unfinished and isn't really that wide spread, nobody is gonna really care about it until it sees more use.

**Comment by LexManos** [comment]
There are hooks already in place for them to 'hook in'. 
Its on his end to be compatible with us. Why he chose to create a custom mod loader when there are already existing and fully functional ones who knows.
As for the 'tall world' stuff, last I looked at it was intrinsically incompatible with most mods due to how deeply it changes vanilla. But meh.
