### ISSUE TITLE
SplashProgress.start() fails to create splash.properties if config folder is missing

### ISSUE THREAD

**Issue by jikuja** [MinecraftForge/MinecraftForge#1913]
Forge creates config folder too late(1) and creation of splash.properties fails at first run. Forge/FML should ensure that required folders are present. Is SplashProgress.start() correct loading stage to create config folder or should it be done even earlier?

And log file: https://paste.ee/p/jiCw1

1 ~~probably when Configuration.load() is called first time~~ `<@fry>PrinceCat: not really; the config folder should be created in Loader.initializeLoader"`

**Comment by tterrag1098** [comment]
Seconding this issue, you can see the problem here. http://pastebin.com/2QwK3gX8

Splash is started here: https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java#L199

But the config/mods folders are not guaranteed to be initialized until `Loader.initializeLoader()` is called (which is called from `Loader.loadMods()`. This is however, called after `SplashProgress.start()` so the config folder does not exist, causing the above error. Maybe the initial mkdirs() should be done at the beginning of `FMLClientHandler.beginMinecraftLoading`.

**Comment by kashike** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/commit/90a88efd8aa589811fe3bfac971bbea5a9394b3b

**Comment by Actuarius** [comment]
@tterrag1098 closed this issue
