### ISSUE TITLE
Disabling splash screen removes debug information thrown by SplashProgress.start()

### ISSUE THREAD

**Issue by jikuja** [MinecraftForge/MinecraftForge#1914]
If user or pack author decides to disable splash screen, Loading screen debug info will be also removed. Is it possible to print that information even if splash screen is disabled? It will make easier to e.g. check if user's java use discrete GPU or integrated and if course it can be used to check if user hasa unsupported/bad GPU.

**Comment by LexManos** [comment]
That debug info is for the splash screen itself. So not printing it is intentional.
We could print a billion things for 'debug' purposes, but we dont because it'd just be spammy and useless in most cases.
The only reason this is special cased is because this is way before normal errors can be thrown and show themselves.
