### ISSUE TITLE
AccessTransforming fails to take into account inheritance

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#2027]
Which is relatively easily implemented by changing the storage structure to this:
```java
	private static HashMap<String, String> superClasses;
	private static HashMap<String, Modifier> classAccess;
	private static HashMap<String, Modifier> fieldAccess;
	private static HashMap<String, Modifier> methodAccess;
```

With keys on Access maps being `<internal classname>`/`descriptor` e.g., `net/minecraft/entity/Entity/func_70041_e_()Z` for methods or `net/minecraft/entity/Entity/*` for fields. Looking up super classes while transforming via:

```java
			for (MethodNode mn : cn.methods) {
				int access = mn.access;
				for (String owner = cn.name; owner != null; owner = superClasses.get(owner)) {
					Modifier m = methodAccess.get(owner + '/' + mn.name + mn.desc);
					if (m != null) {
						access = m.getFixedAccess(access);
					}
					m = methodAccess.get(owner + "/*()V");
					if (m != null) {
						access = m.getFixedAccess(access);
					}
				}
				mn.access = access;
			}
```

To limit full parsing of classes before entering this, avoiding trying to transform classes whose superclasses have no entries ClassReader's `getSuperName()` can be used to flesh out the super-access map while the game loads (classes are always loaded in the appropriate order) and verify a specific class will have no entries.

To avoid every AT doing this, as many as possible should be condensed into a single transformer class, primarily usable on mods that are using the FMLAT manifest entry. Regular core mods will have to convert over to calling some form of manual registration function, or otherwise start using FMLAT like non-core mods, but do not require immediate updating to work with these changes. Leaving the current class for core mods to use, and creating a new one with the proposed changes would limit memory damage caused by core mods using the old method.
Additionally, doing all access transforms from a central transformer would dramatically reduce overhead of transforming: far fewer redundant byte parsing operations will occur.

Fields should not check super, merely for themselves and `*` as fields are not virtual, and identical fields can appear on subclasses and be fully independent of the super's field.

**Comment by diesieben07** [comment]
I personally highly disagree with this. ATs are a hacky workaround for something that is already solved elsewhere (Reflection or if you really need the speed Java 7 MethodHandles).
The only valid usecase (imho) is making a private method public so that it can be overridden in a subclass and for that you do not need this.

Making this hacky system of bytecode manipulation even more complex is not a useful thing to do, imho.

**Comment by LexManos** [comment]
I'm reluctant to do anything that encourages ASM hacky behaviors, ATs being one of them.
This has no guarantee to work, doesn't deal with the recursiveness of trying to figure out how far up the parent tree things should go.
If you're doing anything with ASM being explicit is better than implied fancy things.

**Comment by skyboy** [comment]
You walk up the parent until there are no more parents in the map, which takes a trivial amount of time. 110 ms for all that's in the CoFH ATs, distributed across class loading.
All this does is fix a problem that people have been complaining about for more than a year, for needing things like `Entity.canTriggerWalking` public, without it people will be doing even *more* of the hacky ASM you are so deeply concerned about people doing to work around FML not doing it for them.

**Comment by LexManos** [comment]
I've accepted the fact that people like you will do bullshit ASM hackary.
There is literally nothing I can do about it without destroying Forge.
Congrats, you have me over a barrel here proceed to do as you wish.

Mods can AT things, they shouldn't need to but they can.
This is a compromise that we've done to prevent the bitching of people who would rather use ASM hacks then the tools civilized java gives you.

And your superClasses simply will not work, this doesn't take into account that NO classes are NOT always loaded in the same order. The classloader can be recursed many times to gather and flush out all the dependencies that a class needs.
It also doesn't even bother to care about interfaces because that would just make things too crazy.

Point is:
Will you system work? Sometimes
Is the tradeoff of saving a few lines in a config file worth the hassle and potentially broke shit that comes with? No
Should mods be ATing things because they feel they know best? No
Can I do anything to stop stupid coremods from doing crappy asm? No
Did you come at this wrong, trying to force me to accept your ASM crap without any profiling data, implementation, understanding of the classloader, or, well anything? Yes.

Options are:
Accept this: Waste my time writing it myself, trying to figure out how I can force the classloader to do things it isn't designed to do. Try and deal with weird ass multi-directional inheritance. Hope that this is all worth that MINUTE performance improvement during load.

Or
Don't Accept this: Modders have to explicitly define what methods they want to transform. Costs them nothing. Will have issues with others mods anyways, but the same bugs that people have needed to deal with for years.

I like option number 2. Anyways there are ways WITHOUT ASM that you can do anything you want to do with a access transformer and still keep some semblance of performance/compatibility.

Let me repeat this ASM and ATs ARE A HACK, they should be a last resort!

**Comment by skyboy** [comment]
Class are always loaded top down. Entity is always loaded before EntityLivingBase is always loaded before EntityLiving is always loaded before EntityCreature, and so on. This is a requirement. Additionally interfaces never need to have ATs applied to their methods, interface methods are *always* public.

As for implementation? Assuming you understand how the `String, String` HashMap works above, this is the implementation: https://github.com/skyboy/bearded-octo-nemesis/blob/master/src/immibis/bon/AccessTransformer.java#L49-90 I don't include extra logic to avoid transforming things that don't require it, but that's just some small additional state and stepping through the super map after creating the ClassReader and before creating the ClassNode, nothing complex.

This is not a complex problem, and it solves the problem of needing to reinvent the same damn thing in every mod that requires it over and over and over. The point of forge. There is no problem for me, I can have this implemented into CoFHCore in a matter of minutes, but the entire point is to solve this problem for everyone at the same time.

**Comment by LexManos** [comment]
I dont give a shit anymore Skyboy, just fucking PR it like you know you should of in the first place instead of talking about random shit.
Fucking dont care about ASM PEOPLE SHOULD NEVER BE USING ASM AND YOUR FUCKING THREATS OF DO THIS OR ILL ASM YOUR SHIT PISSES ME OFF.

**Comment by cpw** [comment]
@skyboy ok, the problem is, that the transform order of classloading is NOT the same as the ultimate "define" order of the classes. ClassLoader.defineClass will ensure that superclass is loaded and defined before it completes. However, transform is not *necessarily* called in that order.

The define happens after all transforms have been applied to the class bytes. So if a subclass is requested, it will have "transform" called on it *before* the super is ever requested by the classloader. This means we can't do what you say - we can't track all possible supers in a magic map in the AT transformer, and you won't be able to do better either - without hacking ClassLoader itself to force it to transform there (good luck with that, by the way - I think you're gonna be paddling deep into shit creek if you try).

Your code above would break if, for example, something requested Class.forName("MySubClass") without having ever referenced Class.forName("MySuperClass"). There's a whole pile of corner cases like this, such that a "general" system would just break.

If you feel we're wrong, please, build a demonstration. You don't need anything more than LaunchClassLoader, and some test code. If you can demonstrate transform(super) always occurs before transform(sub), then great! However, the reason things like deobftransformer work the way they do is because I believe you will find that that is not always true.

Also, the other idea I had, and is defeated by graph theory, is the idea of defining an absolute visit order such that every super is loaded before any sub. The problem is interfaces mean that there is no disjoint acyclic graph - there are cycles that cannot be broken - and so there will always be a degenerate case where super is called after sub.

Sorry dude. It seems a simple request, and the BON mostly works because it's seeing a well defined subset of the whole class graph. The generalization is not possible however, in my opinion.

**Comment by skyboy** [comment]
@cpw Noted, tested, verified, and [corrected](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/asm/CoFHAccessTransformer.java#L67-88).

**Comment by cpw** [comment]
@skyboy I would expect to see random class circularity errors from that. Doing random class.forname inside a transformer might also deadlock, since you're already in a class loading cycle - if this is triggered by a define class, for example. In my opinion this code is a high risk of weird bugs, as such I wouldn't want to investigate issues while this coremod is present..

**Comment by skyboy** [comment]
@cpw Circularity errors are caused by loading things in the wrong class loader, which is why I'm being  explicit with it, and further limiting damage by not letting clinit run until it's accessed by something else. Additionally, these transformers run before define class runs and threading-related multiple class loads should already be handled by the class loader, and not be problematic.

Worst damage is that someone defines a class with so many supers that a stack overflow occurs, but since the JVM would crash on that too for the same reason (just with more recursion permitted in a 'pure' loader) it's a non-issue.
