### ISSUE TITLE
Valid return type for IFluidHandler

### ISSUE THREAD

**Issue by nevercast** [MinecraftForge/MinecraftForge#2085]
In the case of dynamic tanks, is it correct to return an empty array of FluidTankInfo or null?
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/IFluidHandler.java#L81

The documentation does not say either way, I assume that an empty array is correct. Some mods do not obey this. 

As the owners of the API, it's your convention. Which should be used to imply no tanks are available on a tile that supports fluids?

**Comment by OvermindDL1** [comment]
In my opinion (how I have used it before) I return null if there are no tanks on that block and return an empty array if there are tanks in the block but none accessible on that side.  Bad bad bad convention in my opinion, but java is null happy for some utter stupidity.
I would say that it 'should' return an empty array if empty, but the interface does not enforce that, thus I would say return an empty array, but always check if null because of java stupidity.

**Comment by nevercast** [comment]
@KingLemming Would you kindly care to share your opinion on the correct API use? Cheers

**Comment by mezz** [comment]
You should return an empty array if you have no tanks on that side, and always check for null.
["Be strict in what you send and tolerant in what you receive."](https://en.wikipedia.org/wiki/Robustness_principle)

**Comment by williewillus** [comment]
That probably should've gone on the javadoc for the method (at least on the cap version) :P

**Comment by mezz** [comment]
I marked everything that's nullable on the capabilties

**Comment by mezz** [comment]
This is documented better with the new fluid stuff, so this issue is resolved.
