### ISSUE TITLE
[Feature] Nether Fortress Rooms

### ISSUE THREAD

**Issue by necrogami** [MinecraftForge/MinecraftForge#2150]
I know there are hooks in forge to add structures to villages. I was wondering if it was possible to add rooms to nether fortresses.

**Comment by vpontin** [comment]
Not responsibility of Forge. Go poke a mod dev to create this.

**Comment by heldplayer** [comment]
@vpontin Fairly certain necrogami is asking for hooks that allow developers to add structures to nether fortresses, in the same way developers can add structures to villages.

**Comment by vpontin** [comment]
Well its not already possible. If not, sorry

**Comment by LexManos** [comment]
You can already do this by reflectively adding on to the weight arrays in the the Structure class.
However a cleaner way of doing this would be worth looking into.
Something more unified for all structures instead of each individual structure type {yes villages are structures in this sense}
I will look into it after we finish the 1.8.8 uptake {which should be soon}
If someone else wants to take a look at it before then feel free to discuss it here.

**Comment by Gaelan** [comment]
This might want to wait until 1.9, because it does some structure-related refactoring (the structure block). Not sure how extensive the code changes there are.
