### ISSUE TITLE
Block.getFakeTileEntity(World w, BlockPos pos)

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2182]
Forge should add a

    public TileEntity getFakeTileEntity(World w, BlockPos pos)

to Block, which would let Blocks provide a non-ticking TE which doesn't get saved. A dummy/proxy TE.

See [this convo](https://www.reddit.com/r/feedthebeast/comments/3skad4/18_colossal_chests_simple_multiblock_chests/cwy2e4t?context=3) for why this is useful.

**Comment by ds84182** [comment]
Non ticking is already implemented but not saving is not. I would suggest
that this would be better suited to be tied into the already existing tile
entity implementation, just giving tile entities the ability to request to
not be saved it something of the likes.

**Comment by SoniEx2** [comment]
But that would still add overhead both when doing World.getTileEntity (and other TE manipulation stuff) and when ticking tile entities (because you have to skip a TE in the TE list).

This (my suggestion) only adds overhead if there's no TE and only if you're doing a getTileEntity. And even then the overhead is tiny (only a method call).

**Comment by ds84182** [comment]
... Or maybe just put all tickable tile entities in a list and call them
and expect mods to not turn ticking on and off dynamically.

**Comment by heldplayer** [comment]
Instead of making tons of issues saying "Forge should do X", why not provide an implementation of what you want and create a pull request.

**Comment by LexManos** [comment]
Possible but would change the design of how TEs are stored and still have the overhead of making transient objects... For this particular use case you could always have createNewTileEntity return an invalid tile entity so it isn't added to the world list.
We've wanted to split the ticking and non-ticking TE list for ages, however we can't due to mojang expecting everything to be in the same list.
It's something to look into if it can be done without breaking fundamental vanilla mechanics/assumptions. Maybe in the future if I have time.

**Comment by cpw** [comment]
Are you asking for a proxy tile entity? One that would be associated with another real in world tile entity, but proxied to other locations?

**Comment by skyboy** [comment]
@LexManos There's no requirement to split the ticking and non-ticking lists. You can maintain the vanilla list of everything for compat, and introduce a second list of only the ticking tiles. Overhead is roughly equal to an additional pointer and a half per ticking tile in the world, but at 6-12 bytes each it's not that significant: ~36 kilobytes on x64 for 3k ticking tiles. Imperceptible against the regular noise of garbage allocations.

**Comment by diesieben07** [comment]
Isn't the two list approach what vanilla does already? In 1.8 I see two (three actually, but one doesn't count) TileEntity lists in the World class. loadedTileEntityList for every TE and tickableTileEntities for all ticking TEs.

**Comment by SoniEx2** [comment]
@diesieben07 That... still has overhead when manipulating tile entities.

**Comment by diesieben07** [comment]
Yes, TileEntities have overhead. That's impossible to avoid. What is your point?

**Comment by SoniEx2** [comment]
@diesieben07 getFakeTileEntity would have 0 overhead on most tile entity operations, except getTileEntity.

**Comment by diesieben07** [comment]
I do not understand why you cannot have the TileEntity save to disk. A simple TileEntity which is simply stored in the chunk without any additional data and an ID of lets say length 16 takes up 34 bytes. If you seriously care about 34 bytes I don't know how to help you.

**Comment by SoniEx2** [comment]
It's not about RAM/space overhead, it's about CPU overhead.

**Comment by diesieben07** [comment]
CPU overhead would imply you don't want your TE ticking. Which you do by not implementing IUpdatePlayerListBox (or overriding canUpdate in pre 1.8).

**Comment by SoniEx2** [comment]
CPU overhead when manipulating TileEntities in a chunk, with multiple hoppers, pipes, etc which constantly call getTileEntity.

**Comment by diesieben07** [comment]
getTileEntity is pretty much just 2 map lookups. I do not see how your "getFakeTileEntity" helps to speed this up.

**Comment by SoniEx2** [comment]
Uhh... 2 map lookups?

I thought it was a list?

**Comment by diesieben07** [comment]
Actually read the code, man.
getTileEntity looks up the chunk and then calls Chunk.getTileEntity, which is a lookup on the BlockPos in a HashMap.

**Comment by skyboy** [comment]
@diesieben07 I had assumed because separating them was mentioned that 1.8 still did the universal list.
The only performance impact of non-ticking tiles then is if they're created during the world tick, and only if they're created in great numbers.

Additionally, the particular logic running in this case doesn't appear to make sense. One would guess it's to deal with chunks unloading, but nothing should be attempting or able to set a tile entity into a chunk that's not loaded in the first place.

Partially unrelated: the forge patch for an NPE in `setTileEntity` seems to imply the async chunk loading may be preventing synchronously loading a chunk. This patch may orphan the tile, leaving it in the world lists and unable to unload, causing all kinds of havoc as it continues to get updated in a chunk that's not loaded.

**Comment by Actuarius** [comment]
@williewillus closed this issue
