### ISSUE TITLE
[1.7.10] Unable to change logoTexture without changing Forge or MC jar files

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#2226]
The splash.properties file provide options to change the logoTexture.
From what I could try, the related file can only be read from the Minecraft.jar or modpack.jar.
Changing resourcePackPath has no visible effect whatsoever.
I can't find any example or documentation about this.
This was tested with 7.99.39.1566-1.7.10.

**Comment by ChioriGreene** [comment]
I had a similar issue but after digging in the Forge source code I realized it's impossible to load a custom logoTexture from anywhere besides FML or minecraft.jar because no mods have been loaded yet when the Splash Screen is initialized. Not sure if anyone will find a way around this one day but for now I think putting your custom splash in modpack.jar (Reminder, distribution of minecraft.jar is against the EULA) will be your only option.

**Comment by williewillus** [comment]
This is working as intended: http://minecraft.gamepedia.com/1.7.4#General_2
Mojang logo now exempt from resource packs

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by williewillus** [comment]
If we actually want the splash screen to support alternate logos, we can reopen but seeing as this is a kinda fiddly grey area with brand and stuff (mojang consciously clamped this down), I doubt we will.

**Comment by LexManos** [comment]
We may remove it, but it's not a big deal. Best i'll do is poke @RainWarrior about it and he'll remove it if he cares.

**Comment by ghost** [comment]
how to change the logo?

**Comment by LexManos** [comment]
You cant
