### ISSUE TITLE
[1.7.10] (10.13.4.1566) Dispensers don't equip armour to correct slot

### ISSUE THREAD

**Issue by tehFoxx0rz** [MinecraftForge/MinecraftForge#2243]
I was trying to make an auto-armour equipping station and noticed that the dispensers were acting funny, equipping helmets to the chestplate slot and chestplates to leggings slot, and kicking the leggings and boots into your inventory.

I removed all my mods to try again and found it was still happening.  I was originally using Forge 1.7.10-10.13.4.1558, but updated to the latest (1566) to see if it had been fixed, but alas, the bug still seems to be there.  Hope this can be sorted out soon!

Pictures to demonstrate:
https://dl.dropboxusercontent.com/u/66131226/title.png
https://dl.dropboxusercontent.com/u/66131226/2015-12-06_11.50.26.png

**Comment by ThePsionic** [comment]
#1649

**Comment by Spartan322** [comment]
No more updating to 1.7.10 as far as I'm aware

**Comment by ganymedes01** [comment]
Yeah, but, imo, seen as this is a bug forge introduced they should probably open an exception =P

**Comment by Spartan322** [comment]
unfortunately, most of the management treats 1.7.10 as obsolete and deprecated, trying to push people to 1.8 (which few people actually want, and I blame that crappy incomplete model system on). Due to that, they have stopped pretty much doing anything for 1.7.10 (and I swear if 1.9 doesn't give us full control again, I'm opening a 1.7.10 branch of forge that will be receive updates)

**Comment by chibill** [comment]
First off the way it is now is perfect. Just people love to have more
control and end up causing bigger problems. 1.9 will just be more model
stuff as that is better and also forge has all you need to replace your old
stuff. You just have to learn how to use it..

**Comment by ganymedes01** [comment]
Please, lets not deviate from the subject here

**Comment by williewillus** [comment]
@Spartan322 stop trying to start flame wars in irrelevant tickets

**Comment by cpw** [comment]
Well, I was thinking about pulling this, but since people are being dicks, I guess I'll just going the dickishness party and say no.

Seriously, no one has commented from forge, until now. This looks like a proper bug introduced by forge. When I have time to review it, I'll think about pulling it. The fact it's barely been reported in the two years since it occurred, is indicative of how much people have actually cared (that is: not at all)

**Comment by ganymedes01** [comment]
Barely reported? wtf? There's even a PR to fix it that's been open and ignored since january XD

**Comment by tehFoxx0rz** [comment]
This seems like a bug which would be easy to fix (especially since there's a pull request), and I'd think that, possibly even moreso if 1.7.10 is "finished", then simple bugs like this should be cleared up so they won't need to be a problem anymore :)

**Comment by TheDoctorSoda** [comment]
I don't think having a bug being "barely reported" is a justifiable reason to ignore a bug. Do you *want* duplicate bug reports?

**Comment by EzerArch** [comment]
Also reported at the MCFF:
* http://www.minecraftforge.net/forum/index.php/topic,26714.0.html
* http://www.minecraftforge.net/forum/index.php/topic,28881.0.html

Please, consider this bug breaks a vanilla feature used in a redstone contraption fairly known in the community: [Automatic armor equiper](http://google.com/#q=minecraft+automatic+armor+equiper).

Sorry for any trouble. :heart:

**Comment by LexManos** [comment]
-.- People STOP BEING CUNTS.
Yes its a bug, yes the old reports were closed BECAUSE IT WAS FIXED.
As I stated in my posts we've had this change since ~1.5 and for some reason it's popped in and out several times across the years.
Something seems to of re-introduced this bug. It's a really stupid one that Mojang SHOULD fix but they do not.
And cpw's response is more along the lines of 'Well I was going to pull this right now but I read the comments and get nothing but beratement and harassment from you guys bitching about all the hard work I've put into this thing so screw you i'll do it later.'
He's just to Canadian to say it that way. {Hell even I've filtered some of the language I wanted to use}
And anytime someone comes and bitches about 1.8 or "If 1.9 isn't 1.7.10 i'm just gunna make my own Forge, with blackjack and hookers!" 
It does nothing but piss us off and make is ignore anything you say from then on because you've demonstrated yourself to be a lazy/childish idiot.

Shit falls through the cracks. I only do a Issue sweep every so often. Especially something like this that WE HAVE FIXED MANY TIMES BEFORE its easy for the reports to fall through the cracks. Just the other day I remembered this issue report and went and tested it and HAD NO ISSUE {Made a shitty dispenser and pressure plate thing}. When I had time I was going to come back here and try and get more information. 

And just so you know, #2187 was closed for being a duplicate report. This one is being closed for the same reason. As well as just being full of nothing but bitching and harassment.

If you notice #1649 is the only one actually reported *mostly* correctly. It has the fix as a PR, it explains the issue {tho not well}. The MAIN reason it didn't get pulled in was because 
1) it was during out 1.8 update process 
2) it has the whole "Haven't checked, but this most likely affects 1.8 as well." Which means "I can't pull this in until I've gone through and verified wither it has any effect on our current version."
3) As stated we've fix this MANY times before, I could of sworn it was working fine in the current 1.7.10 version.

As for #2187 and this, they are added to the 'need to do more research' pile simply because they are NOT PRs. 
The PROPER way to report this is to go through githubs awesome search feature and see if the issue has been reported before:
http://puu.sh/lPYnS/305425baa4.png
"Oh look it has, AND it's a PR! I guess the Forge guys must of just forgot about it. Lets remind them by replying to the PR with my additional information!" Unlike forums. Necroing PRs on github IS a good thing. People here should be smart enough to be certain if their issues are the exact same. If it is more information on that issue is good.

Anyways rant over, the take away: 
Don't duplicate posts, use the same issue/PR it brings it back to our memory so we can look at it again.
Do keep all information about issues together instead of spread across issues.
Don't be a cunt about shit you are to lazy to understand.
Don't be a cunt by saying that all of our time over the last year has been wasted because you're to lazy to learn.
