### ISSUE TITLE
BlockSlab single-variant issues

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2300]
This is more of a convenience issue report, but I felt it was major enough to warrant asking about it.
BlockSlab currently enforces the implementation of two abstract methods: getVariantProperty and getVariant. The former returns an IProperty, and the second maps an itemstack to a value for that IProperty. This is used to determine if two single slabs are matching so you can place a single slab onto another one to make a double slab.

The problem, however, is if we have a bunch of single-variant slab blocks. I am porting a mod where each slab type has its own full block ID, and I don't want to change this due to backward compat. Therefore, my only solution is to either make dummy properties for each one, which I don't yet know the side effects of.

Is there any way to make this less of a roundabout hassle? Perhaps patching in null checks in the placement logic and allowing us to return null for these two methods here

**Comment by LexManos** [comment]
BlockSlab is a construct that states that it is a 1/2 height block which can be placed either on the top half or the bottom, AND when placing two together can be combined into a full block.
This isn't something that should be broken because you need a convenience feature. Allowing nulls here would break the contract that these functions have in place and would force every modder out there to support nulls because you want to misuse something....

The better option would be to use your own Block subclass, that mimics BlockSlab minus the combine feature.
