### ISSUE TITLE
OBJ loader flips UVs

### ISSUE THREAD

**Issue by purpleposeidon** [MinecraftForge/MinecraftForge#2356]
http://www.minecraftforge.net/forum/index.php/topic,35618.0.html

**Comment by williewillus** [comment]
This is a non-issue. Flip-V exists precisely because some modelers choose to export in a format with v's reversed (DirectX). The OBJ loader is not "flipping" anything. It loads what's there. And since openGL uses a different v system than DX, textures get flipped. That's what that flip-v is supposed to fix, by mirroring everything so you get what was originally intended
