### ISSUE TITLE
Tile Entities always receive one extra tick after their chunk unloads

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2363]
In Chunk.onChunkUnload(), TE's that must be removed are marked for removal in the world by adding them to tileEntitiesToBeRemoved list, to be removed in the next tick.

The problem is, in the next tick, in updateEntities(). All TE's implementing ITickable receive their tick BEFORE the tileEntitiesToBeRemoved queue is processed, meaning all unloading TE's receive an extra tick AFTER their chunk unloads.

This causes all sorts of nonsensical crashes such as: http://pastebin.com/MEnBgF4y. (crash since my TE is ticking after the chunk has unloaded and can't check it's block space for the right variant)
Of course, that can be mitigated by throwing block checks everywhere, but I somehow don't believe that TE's should be receiving ticks anymore when their chunk and all block info is gone. After all, it is made sure that the appropriate block is set *before* the TE starts ticking, so why not after?

(As a side note because I just remembered: This happened to me in 1.7 as well, in a TE that ticks IPedestalItems inside it, passing a world and x, y, z. The items would call world.getTileEntity(x, y, z) to get the TE itself back and would get null instead.)

This issue has probably been present in previous versions of Minecraft, but in hidden form due to the meta simply being 0 for unloaded block coordinates. With states however, it's obvious that it's an issue.

Thoughts?

**Comment by LexManos** [comment]
This is how minecraft has worked for years. The chunk unloading is done by the chunk save threads and the like.  The entire point of that secondary list is to make sure we dont get concurrent modifications while looping over the TEs.
Changing the fundamental threading of minecraft because you're to lazy to put safety checks in a system that you should know you get extra ticks in is bad.

**Comment by diesieben07** [comment]
I must say "this is how it's been for years" and "this is because of this implementation detail" are not valid reasons to mark an obvious bug as "won't fix". Just my opinion.

**Comment by williewillus** [comment]
Aw okay :P
Would switching the positions of the tick loop and removal loop really break everything though?

**Comment by LexManos** [comment]
Okay this is a "Can't fix - Threading issues" not a "Won't fix"

**Comment by maxanier** [comment]
Sorry for bringing this up again, but I've stumbled across the same issue. After investigating it a little bit, I can't see why this cannot be fixed. There is a much simpler solution than switching the positions of the loops.

`if (this.isBlockLoaded(blockpos) && this.worldBorder.contains(blockpos))`

is already checked before the tile is ticked. Unfortunately the `isBlockLoaded(blockpos)` calls `isBlockLoaded(blockpos,true)` which allows empty chunks, WorldClient always returns true then (WorldServer ignores that value).

Just adding the `allowEmpty` parameter as false in the update loop, fixes the issue by preventing ticking tiles from unloaded chunks. I've tested it ([here](https://github.com/maxanier/MinecraftForge/commit/b37f3f26e3f499515f8f127f475e8d02ecd32e2e)) and it works.
Since I cannot think about any way how this cause troubles, I don't know any reasons why this should not be fixed. Thereby modders would not have to make a check every time they want to access the block state (every tick).

**Comment by williewillus** [comment]
I did not see that, if it really is that simple I'm all for it

We have to make sure isBlockLoaded(pos, false) doesn't accidentally cause new chunks to generate/load, though. If it does, doing `isBlockLoaded(pos, !world.isRemote)` is a safer version

**Comment by maxanier** [comment]
After taking a third look, I'm still pretty sure that it should cause any trouble. But your isRemote check might be better for future Minecraft changes.

**Comment by maxanier** [comment]
Guess nobody watches closed issues. I will create a new one later
