### ISSUE TITLE
Problem with TileEntity.onLoad

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#2365]
I'm trying to use onLoad to replace if(firstTick) as the documentation suggests.
However, when the server starts, it seems like the chunk with the tile entity is not yet fully loaded when onLoad is called. I am trying to get the block state at the tile's position, which results in a StackOverflowError:
http://pastebin.com/e11YCSwW

**Comment by ljfa-ag** [comment]
Any update on this? For clarification, this is a simple example to trigger the problem on a tile entity when the world is loaded:
```java
@Override
public void onLoad() {
    worldObj.getBlockState(pos);
}
```
I think retrieving blocks in the tile's vincinity is a reasonable thing to do when it gets loaded, so right now onLoad() is not really a replacement for if(firstTick).

I'm not sure how to fix this problem, the call to onLoad must be moved somewhere else to make sure the world is already loaded.

**Comment by williewillus** [comment]
@cpw ?

**Comment by shadowfacts** [comment]
This is still a problem and causes a `StackOverflowError` ([crash report](https://gist.github.com/shadowfacts/72d9a64084a84214c927)) because when `onLoad` is called the chunk doesn't appear to have been loaded yet. 

1. `onLoad` called for the first time
2. block is retrieved from the world
3. chunk isn't loaded so the game loads the chunk
4. `onLoad` is called again
5. repeat 2-4

This means I still have to check for the first tick in `update`, which completely defeats the purpose of `onLoad`.

**Comment by cpw** [comment]
Not possible to access the world in general during onload. The world is only valid during ticking. There is no place to fire a first run event that supports onload and valid world that isn't just if (firsttick). Your te is valid, and you can query your state through the state values on the te itself.

**Comment by ljfa-ag** [comment]
Well that's unfortunate, it's not even possible to get the block state at the tile entity's very position.

I think then it should at least be documented in the javadoc that it's not a full replacement and you can't do everything that you could do on the first tick.
