### ISSUE TITLE
[1.8.9] GameRegistry.makeItemStack does nothing with size input

### ISSUE THREAD

**Issue by VapourDrive** [MinecraftForge/MinecraftForge#2376]
The function makeItemStack(String itemName, int meta, int stackSize, String nbtString) in GameRegistry has stack size as an input and says in the function comment it will use it, but just builds a stack with stacksize of 1.
You can see it here https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java#L572

**Comment by Victorious3** [comment]
No response to this? The issue has been around forever and its clearly unwanted behavior.

**Comment by Spartan322** [comment]
Lex usually ignores an issue unless you submit a PR, there are rare cases for 1.8.9 where the problem is bothered with by them because they are busy doing other things right now, I suspect Lex's response is going to be "PR it or its not happening" or something like that, if you know where and why that's happening, then it should be easy

**Comment by VapourDrive** [comment]
Thanks @iLexicon
I probably should have just set up a pr myself but I didn't realize that was the status quo for something this small.

**Comment by LexManos** [comment]
This is in my ever expanding chrome tablist of 'Shit to do when I get a chance' But it keeps falling behind other things that are more important.
