### ISSUE TITLE
Mods crashing when launching Minecraft in Eclipse

### ISSUE THREAD

**Issue by EXTER7** [MinecraftForge/MinecraftForge#2427]
When launching the client in Eclipse several mods error during the construction stage.
The mods that errored where located in the 'eclipse/mods' directory. This started happening after updating to Forge 11.15.1.1724

[Client log](http://pastebin.com/7TA7CVsP)

**Comment by GirafiStudios** [comment]
Tried updating Biomes O Plenty, since that is what is crashing? You're over 100 versions behind.

**Comment by matthewprenger** [comment]
Does this exact mod set work in a normal MC instance (not in dev)? If it does, I suspect f3c2eb8e9cda873678d0e2308e4b7904fe8e3d61 may be causing this because of: `at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1684)` in the stacktrace.

**Comment by LexManos** [comment]
That may be causing it, someone should really start working on a implementation of that.
I know he may hate me for pinging him but I think @Mumfrey may have a solution as hes done a lot of work with this type of issue.

**Comment by Mumfrey** [comment]
This could at least be partially related to #2423 as well, since it also seems like something which is happening since the recent changes in the deobf transformer.

> That may be causing it, someone should really start working on a implementation of that.
> I know he may hate me for pinging him but I think @Mumfrey may have a solution as hes done a lot of work with this type of issue.

Heh, don't worry Lex I already hate you obviously. In Mixin I have to side-load classes to generate the hierarchy information needed to transform mixins, and I fixed the `getCommonSuperClass` issue using a [ClassWriter which leverages](https://github.com/SpongePowered/Mixin/blob/initphase/src/main/java/org/spongepowered/asm/mixin/transformer/MixinClassWriter.java#L51-L74) that [existing information](https://github.com/SpongePowered/Mixin/blob/initphase/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java) to perform the superclass lookup. Using cached class metadata like this has benefits and drawbacks, but I don't believe the drawbacks exist in your scenario because you don't care about the methods in the classes, only the class hierarchy itself.

The quick and dirty solution is to dispense with all that and just implement (at least in the short term) a writer which just returns `java/lang/Object` in all cases. That should at least fix it for now and then a better solution can be created.

I'd be happy to provide a stripped-down implementation of the way Mixin does it though if that's going to be useful.

**Comment by LexManos** [comment]
Ya the true cause of the issue is that the Eclipse Compiler is outputting invalid bytecode and seince we're now running against EVERYTHING it's getting issues because ASM is trying to validate the classes on rebuild.
And ya I was thinking a dirty hack would just be to use Object, but I honestly dont know what the issues would be in that, would it decrease performance to much or what would it effect.

**Comment by Mumfrey** [comment]
> Ya the true cause of the issue is that the Eclipse Compiler is outputting invalid bytecode and seince we're now running against EVERYTHING it's getting issues because ASM is trying to validate the classes on rebuild.

Yeah, JDT's support for java 8 is sketchy to say the least. However it doesn't really help that ASM's frame generator has ... shortcomings. If you're able to pull #2423 that'd be great because at the moment any lambdas with generics just cause eclipse to shit itself as well.

> And ya I was thinking a dirty hack would just be to use Object, but I honestly dont know what the issues would be in that, would it decrease performance to much or what would it effect.

My understanding is that it shouldn't have much of an impact, at least not in the scenario we're talking about. Certainly any possible collateral damage is limited by the fact that this code is only going to run when the recalc frames thing is enabled. If you take that approach in the short term just to get stuff moving, it doesn't rule out replacing it with something better down the line anyway.

**Comment by LexManos** [comment]
Slight update, tried to just return Object and the entire JVM proceeded to explode. So that's a no-go. A simple solution may just to do a less invasive transformer. It's looked into but no guarantees when there will be a proper solution.

**Comment by Mumfrey** [comment]
Damn that's a pain, back to the drawing board. If I get a spare minute I'll look at making a simpler standalone version of the side-loading thing I mentioned above, as I know that works.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by Actuarius** [comment]
@diesieben07 added labels [Regression]
