### ISSUE TITLE
[Suggestion] More standardized rotateBlock method.

### ISSUE THREAD

**Issue by darkevilmac** [MinecraftForge/MinecraftForge#2450]
Currently in forge/vanilla there is a default method for rotating blocks, it's left up to modders how this behaves. This can cause issues for modders who want to rotate things in an orderly manner, clockwise on the Y axis for example isn't really guaranteed if someone was to call rotateBlock like this:

```
rotateBlock(worldIn, posIn, EnumFacing.UP);
```

What I'm proposing is a much more unified implementation for rotating blocks to make things like http://github.com/darkevilmac/MovingWorld much simpler to program.

My current thought would be something along the lines of the following:

```
/**
* Rotate the block on the axis specified in either clockwise or counter clockwise.
* For example if this method was called on a furnace with the Z axis the block would rotate one
* unit either clockwise or counter clockwise depending on the value of the boolean cw.
* If the block rotated/can rotate return true, if not return false.
*
* @param world The world
* @param pos Block position in world
* @param axis The axis to rotate around
* @param cw If true rotate clockwise, if false rotate counterclockwise
* @return True if the rotation was successful, False if the rotation failed, or is not possible
*/
rotateBlock(World world, BlockPos pos, EnumFacing axis, boolean cw)
```

A method like this would be relatively simple to implement as well as fix the many varying methods of rotations used by modders at the moment.

**Comment by williewillus** [comment]
If a furnace is facing east and I want it to face west, how then would I do that with your new method?

**Comment by ShetiPhian** [comment]
@williewillus the same way you do now, call rotate twice on the Y axis, only difference is you now require a boolean.

Say you wanted it to be south, you call rotate once with the boolean true, and if you wanted north you call it once with the boolean false, (rather then calling the old way three times)

Clockwise Rotations by Axis
X-Axis: North > Down > South > Up
Y-Axis: North > East > South > West
Z-Axis: East > Down > West > Up


@darkevilmac
With a flag for direction there is no longer a need for the face only the axis is needed.
rotateBlock(World world, BlockPos pos, EnumFacing.Axis axis, boolean cw)

**Comment by iTitus** [comment]
What if you have a block which only has two possible rotations (like an anvil). Then something wants to rotate it 2 times (as you described) to rotate it 180 degrees. What happens?
Does it rotate 360 deg (which the other thing does neither expect nor want)? Or does it not rotate at all (because it cannot rotate 90 deg)? Or does it rotate 180 deg because it magically sensed what the other thing wanted to do?

You can play the same game with any block which has a number of rotations in one axis != 4 (which is the default)

**Comment by ShetiPhian** [comment]
@iTitus
If the block can face another way each call would rotate it, on the supplied axis, one step either clockwise or counter clockwise.

For the anvil Y would rotate it from north to east, then another would rotate it from east to north.
The boolean value wouldn't matter, and X and Z axis would do nothing.

A sign would also ignore x & z but y would rotate it:
N > NNE> ENE > E > ESE > SSE > S > SSW > WSW > W > WNW > NNW

Now lets assume a block can face a cardinal directions and has 5 sub styles
The y-axis would rotate the block N > E > S > W 
The x and/or z would change styles 1 > 2 > 3 > 4 > 5

Setting the boolean false would reverse the orders.

**Comment by iTitus** [comment]
So the result of the method cannot be predetermined without hacky checks - the same result as the old method has.
IMHO this method is as good as the old one. What are the exact advantages for use cases?
Please explain why you want to specify which clock-direction the block rotates.
Some mods alway rotate the block to the clicked face or away from it. And that is better for their blocks because of specific side configurations (eg IC2 storage blocks)

**Comment by darkevilmac** [comment]
The main reason for this suggestion as you asked is this: https://github.com/darkevilmac/MovingWorld/blob/master/src/main/java/darkevilmac/movingworld/common/chunk/assembly/ChunkDisassembler.java#L248

Currently with MovingWorld I have to hack things in to rotate blocks, as it is now there's really no reasonable way for me to rotate the blocks properly.

On another note the proposed method just makes more sense. When you're going to rotate something along an axis you don't flip it around, then flip it to the left, then flip it around, then repeat. No you rotate it on the axis specified in an orderly manner.

Just as a side note, the old method could still be left in, but named something a little more descriptive like flipBlock.

**Comment by iTitus** [comment]
I think @amadornes did something similiar with Framez

But the idea of having two methods, one for rotating around an axis and another one for rotating to a side sounds interesting.

**Comment by LexManos** [comment]
The old method is not 'flipBlock' It's rotating. The problem with this whole thing is that you can't define what is a valid rotation. See the whole issue with signs and having 16 directions not 4. These functions also do not give any garentee that the final rotation will be valid. So it's up to the block to decide if it cares. 

Seriously there is no way to make this sane or uniform because blocks are all different.
All you're really proposing is adding a 'This function should attempt to rotate counter clockwise' to the existing javadocs instead of making a whole new function.

**Comment by darkevilmac** [comment]
Why not make a method returning the amount of units required for a full rotation then.

For example

```
/**
* Return the amount of times rotateBlock would need to be called to do a full rotation along the 
* specified axis.
*
* @param worldIn the world the block resides in
* @param posIn the block's position in world
* @param axis the axis we want the information for
*/
int unitsForFullRotation(World worldIn, BlockPos posIn, EnumFacing.Axis axis)
```

It's not like this is an impossible issue to fix, as it is now it could be improved with some fairly minor changes. If you were to give me the okay I'd be more than happy to try and implement it myself.

**Comment by williewillus** [comment]
That kind of thing really isn't worth a patch in my opinion

**Comment by LexManos** [comment]
Because that return value has no meaning because things can change and potentially make that number change.

**Comment by darkevilmac** [comment]
@LexManos Not really sure what you mean by that, this method is in the block, it's not like its cached, it changes depending on the block. Ya, that's why it's in the block method. I might just not understand what you mean though so could you elaborate?

**Comment by williewillus** [comment]
he means that all of this is on a very per-block basis no matter how you look at it

**Comment by darkevilmac** [comment]
That's why the proposed change affects the Block class, mods can override the method.

**Comment by williewillus** [comment]
so what's wrong with overriding the method that's aklready there?

**Comment by darkevilmac** [comment]
What's wrong now is that there's no useful default implementation for me to use. The method I'm suggesting would allow you to continue doing what you're but also make things substantially easier for me as well as other modders who want things to rotate clockwise. Just as an example some steam engines getting broken: http://imgur.com/a/MWSiN

**Comment by williewillus** [comment]
there's not supposed to be a "useful default implementation" because every block has its own implementation details.
unless you can write something that covers a big vast majority of cases (which the preexisting method already does)
the behaviour of rotateblock has always been 'whatever the block makes of it'
trying to introduce and enforce something else isn't going to work (how are you going to enforce that it's going to have a useful effect in every block? that a modder won't forget to implement it?)

**Comment by LexManos** [comment]
num = torch.getnum(pos)
break block at pos + 1,0,0
num2 = torch.getnum(pos)
num != num2.
Point is, the only feasible way to do this is just to ask the block to rotate itself.
Trying to guess what that rotation means will not work.

**Comment by heldplayer** [comment]
The least that can be done is at least add a parameter to indicate _which_ direction you would like to rotate in. Right now lots of mods rotate clockwise, and lots of other mods rotate counter clockwise.

(Tagging @amadornes because Trajectory could really do with a non-ambiguous version of the rotate method)

**Comment by amadornes** [comment]
Rotation along the positive  direction of any axis is supposed to be clockwise and rotation around the negative direction is supposed to be counter-clockwise. This has been the more or less accepted standard for a long time and, although it's not really clear at first and some documentation could be added, it's the general way to go about doing it.
