### ISSUE TITLE
Modding-Optimized Language Localizing

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#2460]
Right now, when there isn't a localization for a language, it always defaults to the en_US localization, even if there are different variations of the same language available, which would be closer to the language than English. Mojang has no reason to fix this, as they have support for all of the languages included with Minecraft. However, with mods, usually there are only 2 or 3 localizations available.
Here's an example of how this change would affect the way it works: Player is running the game in es_MX. Game searches for a localization, doesn't find one, so it would check for other es localizations, rather than jumping straight to en_US.
This would be convenient for both modders who don't have people to translate to every single language variation for them, and for non-English speaking users, who often don't see localizations in their language, even if one is available.

**Comment by LexManos** [comment]
This is all configurations whatever you use to export your localizations can have this tree if you want.
Re-writing the system to have a priority list would be a pain, especially when you try and define that priority...

The system is simple right now, all it does is load the enUS maps, and then load whatever language you specify overriding the map values. At runtime there is no tree like you want.

**Comment by williewillus** [comment]
Tangentially related: The old LanguageRegistry was marked for removal in 1.8 a long time ago, and probably should be

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]

**Comment by elifoster** [comment]
The priority list would not need to be explicitly defined. It would simply match identical languages by the language code rather than the language code _and_ the country code. The langs are already formatted in a simple way `language_COUNTRY`. I don't know a whole lot about how languages are loaded, but if it's not done stupidly to begin with this really wouldn't be that complicated and would be _really_ useful for people whose first language is not English.
