### ISSUE TITLE
Block remapping not working

### ISSUE THREAD

**Issue by hea3ven** [MinecraftForge/MinecraftForge#2491]
Remapping a missing block with the FMLMissingMappingsEvent event is not working because after the remap is processed, the blocks get overridden with a BlockDummyAir, even if the remap was successful.

**Comment by williewillus** [comment]
I'm still getting this issue in the latest 1851 build. More details in a bit

**Comment by williewillus** [comment]
Removing some blocks from Botania since Quark/Vanilla now has them. 
I have a remapper that detects a MissingMapping with name "botania:prismarine" and then calls m.remap(Blocks.prismarine).
Upon reloading the world, the botania prismarine block disappears instead of being replaced with Minecraft prismarine

**Comment by hea3ven** [comment]
Continued in #2768.
