### ISSUE TITLE
BiomeEvent.GetVillageBlockID not firing for doors, and biome = null for village well

### ISSUE THREAD

**Issue by topisani** [MinecraftForge/MinecraftForge#2499]
When i use the following function:
``` java
    @SubscribeEvent
    public void onGetVillageBlockID(BiomeEvent.GetVillageBlockID event)
    {
        event.replacement = Blocks.stone.getDefaultState();
        if (event.replacement != null) {
            event.setResult(Result.DENY);
        }
    }
```
i get this:
![2016-02-25_11 18 18](https://cloud.githubusercontent.com/assets/3133596/13316841/29cec90a-dbb2-11e5-9701-ea2c4235fb33.png)
everything but the door has been replaced with stone, meaning the event doesnt fire when placing doors.

I am using forge 1.8.9-11.15.1.1756

also, `event.biome` is `null` for all blocks in the well in the middle of the village.

**Comment by LexManos** [comment]
Oh look another screenshot taken at night so its COMPLEETLY USELESS as we can't see jack!

**Comment by heldplayer** [comment]
Increased brightness of the image:

![Screenshot](http://i.imgur.com/2MexI20.png)

**Comment by topisani** [comment]
Sorry about that, and thank @heldplayer

**Comment by GotoLink** [comment]
Null biome for wells is the way vanilla does it. Wells always generate the same, independently of biome. And do not contain the biome information.

**Comment by topisani** [comment]
You are wrong about that. In vanilla wells are made of sandstone in deserts.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by ezterry** [comment]
There is a special function to update the is_desert flag for the well in 1.8+ (it was broken in vanilla 1.7.10) a similar update logic is needed for the forge event,

Doors are hard codded into the buildings at present and not sent to the block swap function (since it used to be only oak).. and since there are two pieces may need some care.. might glance at how its being done in the 1.10 snapshots so its more forward compatible.

**Comment by LexManos** [comment]
I think I will say we will be leaving the doors as is, The system will EVENTUALLY be going twards schematics instead of raw block placements. And there will be hooks in places for that.
However. I don't see Doors being important enough to warrant their own new event because that is what it would take because doors need special facings and different states for the top and bottom.

However I can fix wells.

**Comment by kappin** [comment]
> Oh look another screenshot taken at night so its COMPLEETLY USELESS as we can't see jack!

Wow, that sort of incredibly rude sarcasm isn't going to encourage contributions. I've just lost all desire to contribute and work with you to improve Forge.

**Comment by williewillus** [comment]
Bye then?
You have never opened any issues or PRs here so I'm not sure what contributions you're talking about.
Besides what he said is true the dark screens are useless.
Lock pls

**Comment by heldplayer** [comment]
It's a thowaway account, joined today and only thing they've ever done is that comment.

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by kappin** [comment]
Yeah I'm a throwaway account.
Way to go, though. Basically someone criticised you and you got rude. 
The OP spent time getting a bug report together. In the end, she helped you fix a bug.
Perhaps something more nice and encouraging to someone contribute again would be `Thanks for your report. Could you please post a photo in day time so we can see what's going on?`

I'm disappointed by the MinecraftForge community's response to this

**Comment by RainWarrior** [comment]
I'm sorry you feel this way, @kappin. Being nice gets hard when you deal with a lot of people, especially young, and anonymous, and over the internet (not you specifically, in general). Nothing you said here comes across as constructive so I'm gonna lock the discussion now.
