### ISSUE TITLE
[1.9] Minor crash bug in BlockCrops

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2555]
In BlockCrops.getDrops() the blockstate property field `AGE` is used directly. However, beetroots were added in 1.9 which use a different age property, so the game crashes whenever getDrops is called on beetroots. The solution is to replace direct access to field `AGE` with a call to getter `getAge` (bad name -.-) which returns the appropriate age property to use

**Comment by cprevoe** [comment]
Just adding a bit more info as I'm also affected... My tests always show the exception but the exception does not always result in a server crash. The exception does stop beetroots from dropping though. To reproduce:

1. Start a world with you in survival mode (bug only occurs in during the drop - not in creative)
2. Give yourself a hoe, beetroot seeds
3. Plant beetroot seeds.
4. Harvest beetroot seeds.

I haven't figured out how to force a crash instead of just the exception in the logs.

Tests were done with:
  - Vanilla (no exception).
  - Forge 12.16.0.1770 (exception)
  - Forge + BiomesOPlenty (exception + exception with a crash (depends on the world)).

I did save a BOP world where this causes a crash if someone wants to hunt the crash down.

**Comment by tterrag1098** [comment]
This should be closed
