### ISSUE TITLE
[1.9] Group visibility control via OBJModel.OBJProperty/OBJModel.OBJState not working

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#2568]
It appears controlling model group visibility using the `OBJModel.OBJProperty` with an `OBJModel.OBJState` defining the names of the group to render - as [demonstrated in the "Tesseract" test block](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/test/java/net/minecraftforge/debug/ModelLoaderRegistryDebug.java#L249) - no longer works in 1.9-12.16.0.1767-1.9. All groups are always visible, regardless of the configuration of the `OBJModel.OBJState`.

**Comment by fnuecke** [comment]
After some more investigation, this is at least related to [this `FIXME`](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/client/model/obj/OBJModel.java#L1493).

From what I understand, in 1.8 there was a dedicated `OBJModel` instance per visibility configuration, whereas in 1.9 there's (currently) only one global instance, which once caches its quads based on the parameters of the first call and then that's that. I also gave uncommenting [the `scheduleBake` call](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/test/java/net/minecraftforge/debug/ModelLoaderRegistryDebug.java#L271-L272) a shot (for science), but the `state` stored in the `OBJModel` is not an `OBJState` but a `MultiModelState.PartState` so it doesn't even go into checking the visibility info.

What did "fix" it was grabbing the `OBJState` from the passed `IBlockState` and not caching the quads, but that's obviously terrible from a performance standpoint; are there any plans on where and how caching for visibility configurations should happen now? If nobody is working on this I can look into it and prepare a PR.

**Comment by shadekiller666** [comment]
@fnuecke 1.9 Forge is still being worked on, so things may be broken. 
The current released version of the OBJLoader (both in 1.8 and 1.9) has a bug with how group visibilities. I have updates for the OBJLoader awaiting review in a pull request to fix this bug (as well as a few others), though the updated version can be downloaded and used in mods before it gets pulled into forge. The 1.9 version of the updates can be downloaded [here](https://github.com/shadekiller666/MinecraftForge/tree/1.9_OBJLoader/src/main/java/net/minecraftforge/client/model/obj). To use the updated version instead of the one in the current release of forge, in your mod's preInit() method, call ModelLoaderRegistry.registerLoader(), and pass in the updated version of OBJLoader.INSTANCE, then call OBJLoader.INSTANCE.addDomain(<modid>.toLowerCase()), then use the loader as normal.
Along with the updates to the OBJLoader, the test mods have also been updated (code [here](https://github.com/shadekiller666/MinecraftForge/blob/1.9_OBJLoader/src/test/java/net/minecraftforge/debug/ModelLoaderRegistryDebug.java), blockstates/models [here](https://github.com/shadekiller666/MinecraftForge/tree/1.9_OBJLoader/src/test/resources/assets/forgedebugmodelloaderregistry). If you have any questions using the updated version, I am often in the #minecraftforge irc channel.

**Comment by fnuecke** [comment]
Cool, glad to hear this is already being worked on! It's just something I noticed while testing the 1.9 waters (which were otherwise pretty smooth sailing), good to know I can just relax and wait for it to be fixed :-)

**Comment by williewillus** [comment]
Redirect to 2801

**Comment by Actuarius** [comment]
@williewillus closed this issue
