### ISSUE TITLE
1.9: Nether Portals copy already generated overworld chunks into the Nether

### ISSUE THREAD

**Issue by blay09** [MinecraftForge/MinecraftForge#2570]
Tested on Forge 1767 - when stepping through a Nether Portal, the overworld chunks that have already been generated are copied into the Nether, causing this to happen:

![Screenshot](https://cloud.githubusercontent.com/assets/1933180/13890339/2f2d89fe-ed4b-11e5-840f-8f2d07ff2f2e.png)

Tried the same in a Vanilla instance and the problem does not occur there.

**Comment by williewillus** [comment]
dont seem to be "copied" per se, rather the wrong ones are loaded and sent. If you modify the chunks you'll see that the changes get synced to the copy in the nether as well xD

**Comment by heldplayer** [comment]
Also noteworthy that the exact same thing happens for the End.

You can end up with Overworld, Nether, and End chunks in the same "world".

**Comment by williewillus** [comment]
Did fair amounts of investigation into this.

The worlds seem to be intact in memory, but when saving they *all get saved to the overworld*. Every dimension. Confirm by going to the nether then checking your world files. There's no DIM-1.

A test case to confirm my suspicions:
1. Make redstone ready superflat world. Switch to peaceful mode.
2. Teleport to 0, 0 and build a portal exactly there (it makes testing a lot easier).
3. Punch a cow into it. There's a bit of lag, which shows that the cow did indeed go to the nether in memory, causing nether chunks to generate in memory.
4. Relog as soon as you can. Everything around you is darkened, but it's still sandstone. That's because the nether never saved.
5. Go through the portal. You'll see a haphazard scattering of nether and overworld chunks, and you should be back at the portal you just went into. The cow should be nearby.
6. Spam a bunch of experience bottles in the "nether", then take the portal back. The orbs aren't there in the overworld, again because the nether hasn't saved.
7. Go back to the "nether", spam a bunch of experience bottles, then pause the game to force a save. 
8. Go back to the "overworld", orbs are now visible.

Also, this image: https://gyazo.com/9ba034af8e43b221a63b6df7baf9068b

According to @diesieben07, the reason is DimensionManager.createProviderFor is not called. Instead, DimensionType.createDimension() is called, which somehow receives the overworld for everything? Not sure of the details here.

Hopefully it's enough to get a fix for this very amusing but very bad bug :P

**Comment by diesieben07** [comment]
No, it doesnt reeceive the overworld for everything. It just fails to call the (forge added) `setDimension` method in WorldProvider. This causes the field to stay uninitialized at 0. So DimensionManager thinks every world is dimension 0.

**Comment by williewillus** [comment]
Ah yes, so this would be fixed by doing `provider.setDimension(dimensionIn)` right after this line: https://github.com/MinecraftForge/MinecraftForge/blob/1.9/patches/minecraft/net/minecraft/world/WorldServer.java.patch#L13

**Comment by williewillus** [comment]
Or, fixing DimensionManager.createProviderFor and patching that back in
