### ISSUE TITLE
[1.9] Ambient Occlusion applies wrongly to some models

### ISSUE THREAD

**Issue by 42Scope42** [MinecraftForge/MinecraftForge#2652]
See https://imgur.com/a/fU0qF
It seems to be faces that do not fill the side of the block (or possibly do not fill the side of the declared block size, I haven't checked).
Disabling Forge Light Pipeline makes it somewhat better but still noticeably off at times.

**Comment by RainWarrior** [comment]
Is it a normal json model, or are you using a custom one?

**Comment by 42Scope42** [comment]
Normal json model. If I use a texture that is transparent except for the part where I want the face and set the face element to full 16x16 it renders properly, if I set the face element to just the size I want the face the AO messes up.

**Comment by RainWarrior** [comment]
AO is sampled at vertices, so there's not much that can be done to fix this in general case (since for the strips it's dark at the sides, but bright in the middle), at least until the next version of the forge pipeline; what you may do instead, is split the long strips into smaller chunks ( top-middle strip is 7 json elements, and not 1 (you can probably get away with using less, but see below)): 
![fixed model](http://i.imgur.com/ODRSeHh.png)
In general, it's not a good practice to have t-junctions in your models, since it messes up a lot of vertex-sample-related things:
![T-junction example](http://i.stack.imgur.com/ZVkPV.gif)

**Comment by 42Scope42** [comment]
Not sure I understand how you're suggesting I fix it, particularly to do with t-junctions.
I have [this](http://pastebin.com/1HqUh8PZ) model with [this](https://imgur.com/rlG1Ncb) texture.
Changing
"from": [ 0, 15, 0 ], "to": [ 16, 16, 16 ],
to
"from": [ 6, 15, 6 ], "to": [ 10, 16, 10 ],
is what makes the AO go wrong.
