### ISSUE TITLE
Digging particles missing where they shouldn't be

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2700]
Pictures and code speak more than words.

Picture: http://imgur.com/uUT4AEa

JSON: 
This JSON is modeled directly after the vanilla 1.9 multipart wall blockstate JSON:
https://github.com/williewillus/Botania/blob/97495a913d487893beea23649e6fc9d40858d6a2/src/main/resources/assets/botania/blockstates/prismarine0Wall.json

Block breaking particle works correctly, block digging particle is missing.
You could argue that this is how the MultiModel currently generates its variants, but I think this is fixable. After all, vanilla walls all have proper digging particles.

**Comment by Actuarius** [comment]
@williewillus assigned @RainWarrior

**Comment by williewillus** [comment]
vanilla's MultipartModel seems to just steal its particle texture from the first multipart/submodel

**Comment by RainWarrior** [comment]
So, this problem is caused by a combination of 2 things:

1. Particle doesn't use getActualState, so you end up with a wall block with all properties set to false
2. When all properties are false, you end up with no model defined; vanilla multipart model does indeed default to the first defined predicate - which is a hack, since there's no "defaults" block there you can use.

In the V1 blockstate format the natural solution is to put the model with the correct texture in the "defaults" section. This is done in the forge wall example, and works as expected.

**Comment by williewillus** [comment]
in the wall example you have to manually check and remove the base model, which is blegh. I suppose I could use a dummy empty model just to set "particle" though.

**Comment by williewillus** [comment]
Some update on this just for posterity:
I solved this by setting a base variant with a dummy model, then setting the "particle" texture variable to "#wall". Somehow it still managed to get the correct texture as the particle
