### ISSUE TITLE
Invisible mobs

### ISSUE THREAD

**Issue by ensirius** [MinecraftForge/MinecraftForge#2738]
This is a long time bug with custom mobs.  First time i saw it on 1.4.7. Now on 1.7.10. Sometimes single mob goes invisible. You can't see it until rejoin game. You can hear it. Other players correctly see mob. Problem was found using DivineRPG.

**Comment by covers1624** [comment]
I don't mean to be rude but.
1.7.10 is no longer in development, so it is almost instant close for that.

**Comment by ensirius** [comment]
Many mods not have 1.8+ versions.

**Comment by robin4002** [comment]
Many modder should update their(s) mod(s).

**Comment by ensirius** [comment]
About what this discussion? This bug persists for years already..and it's magically fixed on 1.8/1.9?

**Comment by AEnterprise** [comment]
1.8 introduces alot of rendering changes so i sugest you confirm the bug on 1.8 and make sure it's a forge bug and not a mod bug, then it can be investigated, if not it's probably fixed or a mod bug

**Comment by ensirius** [comment]
How can it be mod bug if mob spawn depends on forge? :D

**Comment by AEnterprise** [comment]
it all depends on the mod and how 'custom' the mob is, not everything is handled by forge

**Comment by ensirius** [comment]
Please leave this issue kid and call real devs. thx.

**Comment by iTitus** [comment]
Please Mr., be kind.

**Comment by heldplayer** [comment]
Give exact steps to reproduce this issue on 1.8 or 1.9. If required you can zip up a world where this happens.

Is it consistent that it only happens with mobs from one mod? Most likely it's the mod doing something wrong.

Does it happen to multiple mod mobs? Possible it's a Forge issue, get steps to reproduce it.

1.7.10 is no longer being developed and there are no bug fixes anymore for that version. (mostly because it's ancient)

Lastly "X happens sometimes with Y in old version Z" is a pretty worthless bug report, and calling somebody a "kid" and not a "real dev" is pretty rude, especially seeing as you're not a developer and they are.

**Comment by ensirius** [comment]
Closed, because ppl can only talk shit. As useslly, i will fix forge/mod devs shit by myself. gl forge community.

**Comment by LexManos** [comment]
Ya, stop being a twat.
1) Your failed to provide ANY useful information
2) They are all correct, 1.8 is over a year old, no reason you should be using 1.7.10. And on top of that if this WAS a Forge issue then it would of been detected 2 years ago.
3) "Fuck you guys i'll hack your shit cuz I know best" isn't helpful. Don't be stupid.
Anyways, use the forums to actually figure out what you're talking about before coming here.
