### ISSUE TITLE
Small hitbox

### ISSUE THREAD

**Issue by Lucraft** [MinecraftForge/MinecraftForge#2749]
When the width of the player's hitbox is 0.06 or below, you can't get near a block without getting pushed away. It happens in 1.8.9 and 1.9 versions of forge.

**Comment by LexManos** [comment]
Exactly how close are you expecting to get to a block.. Are you morphing into the size of a ant or something? There is only so small we can work out for clipping I think you've just found the smaller edge. 
Not sure we should care about something that small as being pushed out of blocks IS an intentional mechanic of the game.

**Comment by x0rp01s0n** [comment]
actually i found out why, the hitbox gets set to the smallest possible size every tick and then back to the smaller size, so technically you clip into a block for a milisecond thats what "glitches". not a clipping bug at all, your hitbox is actually 1 tick bigger than it seems. 
maybe this isnt as intendes as it seems @LexManos it still exist to this day.
i am also trying to acomplish this with newer versions of forge.
