### ISSUE TITLE
Lightning Bolt Spawning can't be intercepted by events

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2754]
World#addWeatherEffect can have an event fire/cancel to mitigate this.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by yrsegal** [comment]
This is still relevant.

**Comment by williewillus** [comment]
this looks easily patchable, just fire EntityJoinedWorldEvent in World.addWeatherEffect.

**Comment by yrsegal** [comment]
This is still relevant, as it has not been patched.

**Comment by LexManos** [comment]
Submit a PR as you seem to be the only one who cares about it.

**Comment by Deriboy** [comment]
I submitted a PR here: #5290

**Comment by Deriboy** [comment]
This is still relevant because lightning bolt spawning still can't be intercepted by events. 
The pull request to fix this is still open, has been approved by a couple of people, and is assigned to @tterrag1098, so presumably this is still in the process of getting merged, at which point this issue can be closed.

**Comment by Unnoen** [comment]
Issue can be closed, PR merged: https://github.com/MinecraftForge/MinecraftForge/pull/5290
