### ISSUE TITLE
Block remapping completely broken

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2768]
Block remapping is completely, utterly broken. Interferes with existing idmap.
Forge 1865 (latest at time of writing)

1. I don't receive my missing mappings in MissingMappingEvent if I just call get(), I have to call getAll() and search for my modid, but this is not the main issue
2. Upon remapping, definitely does not work correctly as the blocks I specified are not substituted in world. Random other blocks from my mod are substituted instead.
3. Code: https://github.com/williewillus/Botania/tree/MC19/src/main/java/vazkii/botania/common/core/Remapper.java
4. Before: A bunch of my blocks. I'm interested in remapping the second row of prismarine stuff from Botania to Quark or Vanilla
5. Results: Other blocks from my mod get randomly substituted, even for blocks I'm not remapping. The IDmap shits itself essentially

Pics: http://imgur.com/a/UJMHX

Log: http://pastebin.com/tXLt14hk

cc @cpw

**Comment by williewillus** [comment]
Further note: In the log there's a warning about some quark slab being registered twice, I can attest that that is not Quark's problem and is a remapping problem. If I disable all remappings except for the ones to vanilla blocks I get that same warning for minecraft:prismarine

**Comment by hea3ven** [comment]
I debugged this a bit and the issue and the issue happens only for blocks/items that were already registered in the world's registries before.

First the registry complains [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.java#L418-L422) because the PersistentRegistryManager blindly tries to add the block/item to the registry, even if it is already in the registry. Which then causes [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L454-L457) exception to be raised because newId (the id of the target of the remap) and remap.id (the original id of the block/item to be remapped) are different. I tried commenting out this check, and the item remapping worked fine, but the block remapping failed, it remapped to a random block. Which makes me think there's something missing in the block's  registry to support it. I'm gonna leave it to @cpw, since I don't know enough of the registry to fix it.

**Comment by williewillus** [comment]
Lex told me the registry didn't really support this manner of use, but nevertheless I think it should be fixed as it's useful for mods whose functionality/blocks have migrated to other mods or to vanilla

**Comment by LexManos** [comment]
Its not possible to fix unless we add a map walker to that stage of the process and remap every chunk.
Which as it sits there are no current plans to do.

**Comment by williewillus** [comment]
Closing since my actual issue is better represented by #2825
