### ISSUE TITLE
[1.9] Aliases not working properly

### ISSUE THREAD

**Issue by Ordinastie** [MinecraftForge/MinecraftForge#2771]
See https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.java#L300-L302.
It expects to get `null `if the `ResourceLocation `is not found, however, `super.getObject()` does this : 
`return (V)(v == null ? this.defaultValue : v);`

Not sure if checking for `defaultValue `instead of `null `would have undesired side effects.

**Comment by LexManos** [comment]
Non-issue because default value is never possible to be set in FML controled registries because we override and never call the register function.
So unless someone is hacking into the private field of that class the value will always be null and the result would be:
`return (V)(v == null ? null : v);`
