### ISSUE TITLE
[1.9] Need hook for Potion in ingame HUD

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2774]
Potions can have custom sprites/textures in the inventory by overriding the provided Potion.renderInventoryEffect hook.

However, there is no such hook in GuiIngame.renderPotionEffects (which renders the new 1.9 ingame HUD potion effects)

The only way to use a custom sheet there is to do it the old way (bind in getStatusIconIndex) which in turn messes up the background rendered behind the icon

**Comment by heldplayer** [comment]
It might be useful to change potion effect sprites to use a generated sprite sheet instead of having to use the hardcoded GUI + locations.

This would also prevent needing to rebind the texture every time it needs to be changed.

I've been wanting to make a PR to do that, but haven't gotten the time to do it :/

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]
