### ISSUE TITLE
Vanilla chests are blocked by lower half slabs

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2820]
Steps to reproduce: 
1. Place chest
2. Place lower half slab on top
3. Cannot open chest
4. Try same in vanilla, can open chest

This is because Forge changed the chest to check isSideSolid(DOWN) 

Idk of a solution that satisfies everyone but just putting it here for now

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by LexManos** [comment]
Not a bug.

**Comment by williewillus** [comment]
It's a discrepancy with vanilla though?

**Comment by bookerthegeek** [comment]
Would this not also block upside down stairs?

**Comment by diesieben07** [comment]
No, it would not @bookerthegeek. Forge makes it so the bottom side of the block above the chest is checked. The bottom side of an upside down stair is not solid, hence the chest can be opened.

@williewillus Yes, it is a discrepancy, but so is every other bugfix forge does.

**Comment by LexManos** [comment]
The bottom side of NORMAL stairs is solid so it does block the chest.
And yes this is a difference between vanilla and forge. And yes we COULD special case vanilla block's and reintroduce this 'feature'. But instead we fix the bug correctly and call it good.
The options are break our side solid framework. Or special case vanilla stairs. If we go the special casing route we have to deal with updating to special case all mod shit as well.
It's much preferred that the game stay as is and hope that mojang will EVENTUALLY fix the bug on their end.
This has been the case since ~1.2.5 and only a handful of people care. The rest like the mechanic so we're keeping it.

**Comment by atimholt** [comment]
It’s a bug. Don’t be so pig-headed.

**Comment by williewillus** [comment]
Yes, and check the changelogs to see that this has been fixed in 2569+

**Comment by mezz** [comment]
I missed the "conversation" but for anyone wondering in the future, this was fixed in https://github.com/MinecraftForge/MinecraftForge/pull/4584
