### ISSUE TITLE
Forge (accidentally) circumvents Mojang blacklist

### ISSUE THREAD

**Issue by Gaelan** [MinecraftForge/MinecraftForge#2845]
Players on the newly-blocked servers have discovered that the blacklist doesn't work under Forge, probably because it has custom [version].json files that haven't been patched to use Mojang's fork of Netty. We probably should switch to Mojang's fork so that we don't become "that mod that lets you get on servers." What's the official stance on this?

I think this is the relevant section from the JSON files:

```json
{
  "name": "com.mojang:netty:1.5",
  "downloads": {
    "artifact": {
      "url": "https://libraries.minecraft.net/com/mojang/netty/1.5/netty-1.5.jar",
      "sha1": "d1d6353c80a1ec29299352128890654a80dbf8ec",
      "size": 7804
    }
  }
},
```

**Comment by williewillus** [comment]
What blocked servers? Mojang removed that in pre3

**Comment by Gaelan** [comment]
@williewillus They re-added it as a patch to Netty. It affects everything 1.7+ now.

**Comment by matthewprenger** [comment]
Just as a clarification. `com.mojang:netty` isn't a fork of the `io.netty:netty` dependency in the sense that it contains all of netty. `com:mojang:netty` only contains one class `io/netty/bootstrap/Bootstrap` (which contains the blacklist). Since `com.mojang:netty` comes first on the classpath, it overwrites the `io/netty/bootstrap/Bootstrap` class from `io:netty:netty`. Sources [here](https://libraries.minecraft.net/com/mojang/netty/1.5/netty-1.5-sources.jar)

**Comment by Gaelan** [comment]
@matthewprenger Ah. I was confused about why both were on the class path.

**Comment by LexManos** [comment]
We've been informed, as it sits 1.9.3/4 dropped today so we'll work on that. 
The reason we specified netty is because Mojang were shipping two different versions. And the one on the server broke things.
We've already talked to the necessary people and will be doing best effort to deal with it.
