### ISSUE TITLE
No way to add a tintindex to a obj/b3d model texture

### ISSUE THREAD

**Issue by robotgryphon** [MinecraftForge/MinecraftForge#2851]
With vanilla, it's possible to specify that an element uses a particular tintindex. This would be very helpful to add to OBJ/B3D models, so machines and various complex objects could tint areas based on states and tile entities.

By implementing this, I could certainly get rid of a few TESRs and improve performance. Imagine a tesseract that has an area for active/inactive- that could use tintIndex. Or, for a mod I'm working on, a bed has separate sheet and blanket colors. Tint Index could be used to separately color those textures without the use of a TESR.

**Comment by KnightMiner** [comment]
What is wrong with the tintIndex parameter of IBlockColor.colorMultiplier? I would assume that does what you need

**Comment by williewillus** [comment]
@KnightMiner he's saying that there's no way of specifying them in B3d/OBJ models like you can in JSON (where you have "tintIndex" in the faces of the model)

**Comment by KnightMiner** [comment]
Ah, I see. I misread his issue as "only works on vanilla blocks"

**Comment by ostenvighx** [comment]
Updates?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]

**Comment by desht** [comment]
So this has been languishing for a while...

I've been having a play with this, and I have a suggestion, based on some code I put together for a mod, which could be a candidate for a Forge PR (but I'd like some input first).

The code in question can be seen at:
https://github.com/desht/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/client/TintedOBJLoader.java
https://github.com/desht/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/client/TintedOBJModel.java

and is mostly a rip-off of `OBJLoader`and `OBJModel`, with the following changes:
* The blockstate "custom" field now also has "tintmap" subfield, which allows groups from the .obj file to be mapped to a tintindex.   This is a JSON map of string to integer, e.g. `{ "group1": 0, "group2": 1}` ~~Format is `"<groupname>:<tintindex>,..."` - see https://github.com/desht/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/client/TintedOBJModel.java#162 (note, this should be JSON, really - just a proof of concept here)~~
* `TintedOBJModel.Group` and `TintedOBJModel.Face` now have a tintIndex field, inited from the custom data above (the tintindex is passed into the faces when they're set up by the group object)
* The `tintIndex` field from the `Face` is included when the baked quads are built - https://github.com/desht/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/client/TintedOBJModel.java#L1393

Since the tintindex is part of the baked quads, the normal `IBlockColor` mechanism can then be used for tinting the model.  This seems to work quite nicely from the testing I've done so far.  Obviously I'd rather have this functionality in `OBJModel`/`OBJBakedModel` in Forge than have custom classes with a lot of duplicated code...

Oh, and a sample blockstate file: https://github.com/desht/pnc-repressurized/blob/master/src/main/resources/assets/pneumaticcraft/blockstates/vortex_tube.json

**Comment by williewillus** [comment]
the tintmap should be a proper json map instead of some pseudo-mapping format stuffed into a string imo

**Comment by williewillus** [comment]
By doing that the json parser does all the hard work for you and you don't have to manually reimplement splitting the kv pairs, extracting the key/value, etc.

**Comment by desht** [comment]
Yes, that would be nicer for sure, and not too much more work. But you'd agree the basic concept (using customData to define obj-group -> tintindex mappings) is sound?

(I did this the quick & dirty way since customData is a `Map<String,String>` - `GSON.fromJson()` will work here though)

**Comment by desht** [comment]
Updated TintedOBJModel and vortex_tube.json to use JSON for the tintmap.

**Comment by marvin-roesch** [comment]
I've planned on introducing something similar to @desht's solution to Forge itself for some time now. Rather than requiring going through a blockstate file and its custom section, I intended to introduce a model-related metadata section for `mcmeta` files, which would then allow mapping individual groups to a tint index.

An alternative approach would be to abuse some material properties for tint indices, as most of them are useless in the MC pipeline anyways. This obviously would be a bit of a hack, but it would allow more granular control over which faces get which tint without having to split a model into groups and it would actually allow defining tint indices from within a model editor.

Note that I might not get around to this any time soon, I merely wanted to keep this issue from being closed for mere staleness.

**Comment by MajorTuvok** [comment]
This will take a bit longer stale, as said in the previous comment
