### ISSUE TITLE
[1.9] Chunks should not be rendered untill the TileEntities loaded from the server have worldObjs initialized

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2855]
Otherwise, null checks have to be put everywhere and the code becomes an annoying mess. This can be handled cleaner on the Forge side - perhaps adding a small delay before a chunk is rendered?

**Comment by kayila** [comment]
This appears to be a problem with 1.8.9 as well. I've seen the same problem when developing one of my mods.

**Comment by HenryLoenwind** [comment]
It is not just rendering. The load-from-nbt method is also called before a world is set. So TEs that need some world interaction to initialize are a pain, because you either have to do it in your update() or your setWorldObj(). Also, when being loaded from the save, calling any method on a neighboring TE can crash if that one has no world yet. You're not even safe in your 1st update(), your neighbor may still be world-less...

**Comment by diesieben07** [comment]
> The load-from-nbt method is also called before a world is set.

This has always been the case and is not something that can or should be changed. Reading from NBT is purely data deserialization.
> Also, when being loaded from the save, calling any method on a neighboring TE can crash if that one has no world yet. You're not even safe in your 1st update(), your neighbor may still be world-less...

I would be interested to see the code that causes this. If you have obtained a TE from the world it should have the world set...

**Comment by AlexIIL** [comment]
Tile entities only have the world set when they are added to the chunk object. Unfortunately if you add a tile entity to the world in the middle of the ticking all existing tile entities then it doesn't set the world object until the next tick. A fix would be to set the world object to the tile in both ```` World.setTileEntity(BlockPos pos, TileEntity tile) ```` and ````java World#addTileEntity(TileEntity tile)````

**Comment by asiekierka** [comment]
Fixed in 1.9.4
