### ISSUE TITLE
Bug with new Bucket texture!

### ISSUE THREAD

**Issue by xMrVizzy** [MinecraftForge/MinecraftForge#2858]
When i draw all bucket textures in x32 (bucket_base, bucket_cover, bucket_fluid), bucket_fluid looks very big in inventory! (Look at screenshots)
![screenshot_1](https://cloud.githubusercontent.com/assets/7906418/15270439/55854cde-1a39-11e6-8dcc-baf3a3b73289.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7906418/15270437/55849582-1a39-11e6-8c03-9d340c7699bc.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/7906418/15270438/55852402-1a39-11e6-8510-637141193fc3.png)

**Comment by williewillus** [comment]
optifine?

**Comment by williewillus** [comment]
though I remember someone mentioning that the universal bucket breaks in all non16x RP's

**Comment by LexManos** [comment]
Mind upload the resource pack to tet with?

**Comment by xMrVizzy** [comment]
Okay!

**Comment by bonii-xx** [comment]
Will take a look when I find the time

**Comment by ChunHin** [comment]
I am able to reproduce it.
I debug it a little bit and find this code in the class ModelDynBucket
`
if(fluid != null) {
    fluidSprite = bakedTextureGetter.apply(fluid.getStill());
}`
I also find this code
`
        if (liquidLocation != null && fluidSprite != null)
        {
            TextureAtlasSprite liquid = bakedTextureGetter.apply(liquidLocation);
            // build liquid layer (inside)
            builder.addAll(ItemTextureQuadConverter.convertTexture(format, transform, liquid, fluidSprite, NORTH_Z_FLUID, EnumFacing.NORTH, fluid.getColor()));
            builder.addAll(ItemTextureQuadConverter.convertTexture(format, transform, liquid, fluidSprite, SOUTH_Z_FLUID, EnumFacing.SOUTH, fluid.getColor()));
        }
`
And then a check their height and width
Everything is 32 * 32
_except one_
**fluidSprite** 16 * 16 ---> I use texture "minecraft:blocks/water_still" to debug it

1. Fluid's still texture's width must be at least bucket's width * 1(This case 32) and flow texture's width must be at least bucket's width * 2(This case 64). This not a really good way to solve that problem because modders' fluid texture must be remake. It is nearly impossible to do that.
2. Or will have to scale the bucket texture(This case 32 * 32) to 16 * 16. That will be a better way to do that.
