### ISSUE TITLE
New type of loot entry: oredict name

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2903]
I'm not sure of the details of implementation, but I think it would be great if, in addition to the loot entry types we have now of "table" pointing to another loot table, "item" pointing to an ItemStack, and "empty" pointing to an empty table, we could also have "oredict" which takes an oredict name.

Things to consider:

* What happens if nothing is under that OD name?
    * Throw?
    * Force table writer to specify another entry (non-OD?) to be used instead?
* Which OD item to choose when generating loot?
    * Probably just the first

**Comment by ezterry** [comment]
I'd expect an ore dict name with no entries to behave the same as specifying a block that didn't exist.

The better question is how to generate the loot... behavior ought to be consistent but depending on the type of item in the ore dict you will probably want to:

a) favor the entry from a particular mod (such as a particular type of copper) by default first entry may work in a pinch since without input from the pack creator/end user its as good of guess as any.
b) get a random entry from all possible (such as a particular type of dye.. including modded substitutes such as Floral Powder)

For map makers b is more interesting since you could specify the block directly for a..  For a mod added table I'm less sure.

Could of course use the type to implement both. ("oredict:default" vs "oredict:random"?)

**Comment by LexManos** [comment]
Oredict is not designed for getting the exact itemstacks.
There is no mechanic for that and if we tried to introduce one it would just devolve into modders stroking their egos and hacking the internals to make their own item show up.
Not gunna happen.,
