### ISSUE TITLE
[1.9.4] ItemSword should have an alternate constructor that takes attack damage & speed as params

### ISSUE THREAD

**Issue by SuperGeniusZeb** [MinecraftForge/MinecraftForge#2912]
Similar to the alternate ItemAxe contructor recently added, ItemSword should also have an alternate constructor that takes attack damage and (or at least) attack speed as parameters, as it is currently only possible to make a sword with a custom attack cooldown by extending ItemTool, and this is not a sufficient workaround as it causes custom swords to not be able to use the new sweep attack that was added to swords in 1.9. (This is similar to axes with custom attack speeds made before the addition of the alternate constructor being unable to use the shield-breaking function. It might be possible to get it working using events, but this would be unintuitive.)

**Comment by williewillus** [comment]
You don't need to do that. Just extend itemsword and override getAttributeModifiers

**Comment by LexManos** [comment]
the only reason the Axe constructor was added was due to how the existing axe constructor was written, that it ERRORED when using a custom material. And mostly to stop the bitching from people who got really annoying because they were to lazy to understand how the tool system worked.

This on the other hand, as described, can be controlled with the material, and overriding that one function. These are standard programming practices for modifying the behavior of an existing class when you create a new instance so I'm leaning more twards use the standard approach instead of hacking in an limiting alternative.
