### ISSUE TITLE
Recipe sorter crashes Server on startup

### ISSUE THREAD

**Issue by Alrawn** [MinecraftForge/MinecraftForge#2962]
Server ran fine with all mods except forestry_1.9.4-5.0.8.141.jar. adding that made the server crash. disabling forge's recipe sorter works as a workaround.  [crashlog ](https://github.com/ForestryMC/ForestryMC/issues/1295)

**Comment by GirafiStudios** [comment]
This is not a Forge issue. Some mod is not registering their IRecipe in the RecipeSorter. I noticed you had Bagginses, what version are you using of that?

**Comment by Alrawn** [comment]
the latest version [Bagginses-1.9.4-2.4.2b](http://minecraft.curseforge.com/projects/bagginses/files/2305380)

**Comment by GirafiStudios** [comment]
That is not it then. You should have somewhere in your log where it says "Unknown recipe class", or something like that.
Btw. this should go on the forums, not the issue tracker.

**Comment by Alrawn** [comment]
sth like this?

> [12:39:50] [Server thread/INFO] [FML/Forge]:   Unknown recipe class! forestry.core.recipes.ShapedRecipeCustom Modder please refer to net.minecraftforge.oredict.RecipeSorter
> [12:39:50] [Server thread/DEBUG] [FML/Forge]:     Parent Found: 24 - net.minecraftforge.oredict.ShapedOreRecipe
> [12:39:50] [Server thread/INFO] [FML/Forge]:   Unknown recipe class! nl.lang2619.bagginses.items.BagRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
> [12:39:50] [Server thread/DEBUG] [FML/Forge]:     Parent Found: 12 - net.minecraftforge.oredict.ShapelessOreRecipe

**Comment by LexManos** [comment]
Ya, not a Forge issue modders need to register their classes in the sorter to make it sane and to make sure everyone's recipies work together correctly.
And Girafi is right, you should use the forums before coming here.

**Comment by sfPlayer1** [comment]
This is still without doubt a Forge bug, registering sorters is just a workaround. The implementation of net.minecraftforge.oredict.RecipeSorter.compare(IRecipe, IRecipe) violates the transitive relationship constraint of Comparator if there's recipes using the UNKNOWN category:

> The implementor must also ensure that the relation is transitive: ((compare(x, y)>0) && (compare(y, z)>0)) implies compare(x, z)>0.

Imagine 3 recipes, one shaped, size 3, one shapeless, size 1, one unknown, size 2. Comparing unknown with the 2 others may yield the following order because of the sizes:

> [shapeless < unknown], [unknown < shaped] -> shapeless, unknown, shaped

Comparing shapeless and shaped yields:

> [shaped < shapeless] -> shaped, shapeless

I believe this is easily fixed by moving UNKNOWN behind shaped and shapeless:

```
Category c1 = getCategory(r1);
Category c2 = getCategory(r2);
if (c1 == SHAPELESS && c2 == SHAPED) return  1;
if (c1 == SHAPED && c2 == SHAPELESS) return -1;
if (c1 == UNKNOWN && c2 != UNKNOWN) return 1;
if (c1 != UNKNOWN && c2 == UNKNOWN) return -1;
if (r2.getRecipeSize() < r1.getRecipeSize()) return -1;
if (r2.getRecipeSize() > r1.getRecipeSize()) return  1;
return getPriority(r2) - getPriority(r1); // high priority value first!
```

Additionally getRecipeSize isn't strictly required to yield constant results, it'd be advisable to avoid querying it more than once using a cache as in getCategory/getPriority.
