### ISSUE TITLE
[1.10/1.11] uvlock and uv mapping does not work correctly

### ISSUE THREAD

**Issue by HanFox** [MinecraftForge/MinecraftForge#3040]
Using Forge 1996.

If uvlock is true and you try to flip a texture using UV the texture will not flip.

This is not how uvlock should work. It's meant to just stop the texture itself from rotating around when a model is rotated in the blockstates, but still allow UV manipulation.

Below the left block has uvlock false and the right block has uvlock true.

Vanilla:
http://i.imgur.com/gz6SgxW.png

Forge:
http://i.imgur.com/pxjYo1n.png

**Comment by RainWarrior** [comment]
Please show your model and texture files.

**Comment by HanFox** [comment]
Here: [Forge-uvlock.zip](https://github.com/MinecraftForge/MinecraftForge/files/333574/Forge-uvlock.zip)

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by EskiMojo14** [comment]
I'm also experiencing this issue. Fixing it would be great. (Using 2089)

**Comment by HanPrower** [comment]
Is there any news about a fix, @RainWarrior ?

**Comment by HanPrower** [comment]
Still an issue in Forge for MC1.11.

**Comment by HanPrower** [comment]
Still an issue in 2226.

**Comment by HanPrower** [comment]
Still an issue in 2322.

**Comment by HanPrower** [comment]
As per the announcement for rotting issues ... @mezz ? 

Broken MC functionality.

**Comment by mezz** [comment]
This is assigned to @RainWarrior, there is not much I can do besides poke him more.

**Comment by mezz** [comment]
The best way to solve an issue like this is probably to submit a PR.

**Comment by HanFox** [comment]
I don't work in Java so that's never happening.

You'd think broken base MC stuff would be a priority. I guess there's no intention to fix it then.

**Comment by HanPrower** [comment]
I don't see how telling me to submit a PR helps. I don't work in Java.

It's MC functionality that has been broken for nearly a year now.

@LexManos if you want to delete comments fine, but at least have the balls to take some responsibility.

**Comment by LexManos** [comment]
I do have the balls to take some responsibility. I deleted your comment because it was nothing but a child's tantrum. Quit with the insults.
I've notified fry about this.
He is the one who has to solve it because I don't know what is going on with the rendering.
I have ALWAYS admitted I am shit when it comes to rendering. That's why we have fry.
If anyone else wants to step in and help out they can we are open to all PRs. 
Remember this is a project run by all volunteers, if you want something done faster step up and help.
Until then best I can do is keep hounding Fry. 

Locking so that @HanFox Doesn't post more personal insults. If someone wishes to help make a PR.
