### ISSUE TITLE
Gradle needs to be run as administrator 

### ISSUE THREAD

**Issue by Dijkstra1** [MinecraftForge/MinecraftForge#3049]
When i run gradle setup decom workspace, I need to run with the sudo prefix, from the linux terminal, I do not have this issue with windows, do not know if this is a forge thing, more likely it gradle, between you and me I think gradle is evil, we definitely do not see eye to eye must of the time.

**Comment by GirafiStudios** [comment]
Wrong repo you have reported this to. Sounds like it is a problem on your side though - I know people using Linux for modding and they don't have the problem.
I would suggest trying to ask about help on the Minecraft Forge forum - but setting up the workspace is done with Forge Gradle, so you would need to report it here: https://github.com/MinecraftForge/ForgeGradle, if it is not an issue on your side.

**Comment by kashike** [comment]
This is an issue on your side. If this was actually an issue, there would be hundreds of reports of this occurring.

**Comment by williewillus** [comment]
I run gradle as a normal user fine and it does not ask me to sudo

**Comment by Illyohs** [comment]
Im able to run gradle as a normal user and so are most other people so this sounds like a PEBCAK problem. How did you install gradle?

**Comment by LexManos** [comment]
So 1) This is not the correct repo, this is Forge, not ForgeGradle
2) You do not need admin access the only place gradle reads/writes from is the user home directory, and you can change that as needed.
It sounds more like things are messed up permissions wise on your end. Do some debugging and seed if you can figure it out.
If not go to the forums and people may be able to help you, I highly doubt this is an issue caused by us.
