### ISSUE TITLE
EnumPlantType need as big fat warning

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3078]
EnumPlantType needs a big fat warning to never switch() on any field/variable/parameter that is of that type.

If you don't understand why, you just have proven that that warning is indeed needed.

**Comment by Leviathan143** [comment]
Is this net.minecraft.block.BlockDoublePlant.EnumPlantType or net.minecraftforge.common.EnumPlantType?

**Comment by killjoy1221** [comment]
Instead of saying it's broken, you should help us to debug it. Give some examples of what doesn't work and we might be able to figure out what's wrong.

Instead of putting a big fat warning on that class, we should try to fix it.

**Comment by LexManos** [comment]
Its not needed, its mainly just that the enum itself is designed to be expanded by modders if they ever need to add a new type.
Doing so after a class which has a switch on it is loaded would cause index out of range errors due to how enums are implemented in java.
I'm not seeing how this needs a 'big fat warning' tho.
