### ISSUE TITLE
ItemCraftedEvent produces unexpected behavior

### ISSUE THREAD

**Issue by chazwarp923** [MinecraftForge/MinecraftForge#3100]
I use the ItemCraftedEvent to add simple recipes using damage values, which i have done since 1.7 and up until 1.10 (granted i jumped from 1.7.10 to 1.10.2) it worked flawlessly. However, now, using virtually the same exact code i used in 1.7 doubles the stack size of one of the stacks involved in the recipe. I have tried many solutions to try and get around this but all have been mere band-aid fixes to the real problem and none have really worked. I have tried logging he various parts of the logic flow and at all points on my end it comes up sound, even to the very last line in my event handler. So after days of testing and frustration i can only assume that somewhere in the code that fires ItemCraftedEvent a bug was introduced between 1.7.10 and 1.10.2. I have tested on both forge 2011 and 2014. My event handler can be found [here](https://github.com/chazwarp923/Unified-Items/blob/58f43b0be5def0fa093ffa2abe9114bf59188a58/src/main/java/tech/chazwarp923/unifieditems/event/ItemCraftedEventHandler.java)

**Comment by LexManos** [comment]
Big jumps like this are not just 'omfg my old code compiles ship it!' changes.
IIRC sometime in this range the recipe system switched to a full 'give me the entire resulting inventory' system.
So your handlers are most likely better off being re-written as normal IRecipe classes.
On top of that, we have no idea what anything else in your environment may be doing.
If you think this is a Forge bug try getting it reproducible with the least amount of code possible, and 
I would suggest going to the forums and verifying that it is a issue before you bring it up here.
I'm doubting it is one on Forge's end {not complletly dereguarding, i'll be taking a look when i get back in the state} but severly doubting because the behavious would cause all items to be duplicated when you craft ANYTHING in MC.. which obviously isnt the case so..

Anyways go to the forum and see if you can track it down, if not come back with a smaller self-contained test case.

**Comment by chazwarp923** [comment]
I'll try re-writing them as IRecipe's and see if that works, the only reason i thought it might be a bug was that in my handler i never use any multiplication so i didn't see how my code could possibly be the one causing the stack size to double. Anyways thanks for your time and patience.
