### ISSUE TITLE
[1.10] Removing a mod sometimes turns some of the removed mod's blocks into blocks from other mods

### ISSUE THREAD

**Issue by Nentify** [MinecraftForge/MinecraftForge#3101]
I can't really do much more explaining than that. I removed RFTools and the generator turned into upside down Tinkers Stairs. I removed another mod and the block turned into a Forestry Moistener instead of simply disappearing/being deleted/set to air.

**Comment by LexManos** [comment]
This is caused by other mods hacking in and destroying our registry, Sadly there isnt anything we can do and we've tried yelling at certian mod authors but that gets us nothing.
We have rigorously tested our registry system and it is indeed fine. I would make a backup of your world and keep trying to load it with different mod combinations till it stops happening and yelling at the mod thats causing it.

Sadly the log wont tell you anything because these mods dont often log useful information when they purposfully break our stuff -.-

**Comment by malte0811** [comment]
Just out of couriosity: what exactly do people hack (I assume they manually assign block id's or something like that?) and why do they do so/what does the hack do apart from breaking stuff?

**Comment by LexManos** [comment]
Nothing of use.

**Comment by williewillus** [comment]
Rftools and forestry are pretty major with authors active with forge. Doubt this is their doing.

I recall the registry having issues when mods are removed and with substitutions, though I have no sample cases. If I have time I'll try to reproduce this

**Comment by josephcsible** [comment]
I think there may be something to this. I can consistently reproduce this issue with just Forge's own test/debug mods, by doing the following in a Forge development setup:
1. Change ENABLE to true in ModelFluidDebug.java
2. Start Minecraft
3. Create a superflat world
4. Put in the test fluid, the test gas, and the milk fluid
5. Quit Minecraft
6. Change ENABLE to false in ModelFluidDebug.java
7. Start Minecraft again
8. Load the superflat world
9. Choose yes when it says the forgedebugmodelfluid blocks are missing
At this point, there were "test animation" blocks in place of the milk, and "custom wall" blocks in place of the test fluid. (The test gas seemed to correctly disappear.)
