### ISSUE TITLE
Cannot spawn Husk without using deprecated methods.

### ISSUE THREAD

**Issue by queekusme** [MinecraftForge/MinecraftForge#3137]
Inside of the Zombie Entity class (net.minecraft.entity.monste.EntityZombie) the function (which works) to spawn a zombie with a variant type of husk is deprecated

> @Deprecated //Do not use, Replacement TBD
    @Nullable
    public ZombieType func_189777_di()
    {
        return ZombieType.func_190146_a(((Integer)this.getDataManager().get(VILLAGER_TYPE)).intValue());
    }

The forge documentation indicates that Forge intentds for modders to use Villager Professions and although func_189777_di works to spawn a husk, modders cannot guarentee that it will remain.

Please can the TBD be removed from this and a final system be implemented which can handle both Villager Professions and the ability to spawn a Husk and normal zombie variants.

**Comment by asiekierka** [comment]
To be honest, Forge probably won't /remove/ Mojang functions.

**Comment by LexManos** [comment]
We never REMOVE functions.
And I haven't decided what the replacement for getType()ZombieType is yet.
Also, that's not the function you use to set the type to use, you use setType(ZombieType) which yes is deprecated.
Because again, I haven't decided the best way to split villagers from other zombie types.
For now use that method but DO NOT use it for villager type zombies.
