### ISSUE TITLE
[Feature Request] Built in OreDict for fences

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#3138]
Basically what the title says, now that vanilla minecraft has added multiple wooden fence types Forge should probably add in some fence oreDict values (fenceWood for wooden fences and fence for all fences and walls).

**Comment by KnightMiner** [comment]
If that is added, so should oredicts for the fence gates and doors.

**Comment by Madsthunder** [comment]
And trapdoors ;)

**Comment by ostenvighx** [comment]
There are two trapdoors.. also who uses doors and fence gates in recipes?

**Comment by KnightMiner** [comment]
I've seen doors used to make wooden lockers and alike. It basically just ends up with what people want for their recipe

**Comment by Da-Technomancer** [comment]
I've seen fences used in the recipe for wooden scaffolding in IC2.

**Comment by BluGen** [comment]
The structural upgrades for the better barrels of the JABBA mod do too.

**Comment by ostenvighx** [comment]
Yes, people use fences. But I haven't seen fence gates tho. And trapdoors.

**Comment by BluGen** [comment]
In the FTB Infinity Evolved pack (1.7.10) are 15 crafting recipes that uses trapdoors and two recipes from railcraft that use fence gates. Equicalent fences, fence gates and trapdoors can't be used for this recipes, only the oak vanilla ones. It might be custom recipes for this pack, but they do not look unusual.
Please correct me if this doesn't apply to newer minecraft versions anymore.

**Comment by LexManos** [comment]
I am always against adding more things to the oredict because it's just a "Add ALL THE THINGS!" type deal. If modders want the oredict then they can add it. Have them agree on a name and they will all work together.
Thats how modders usually do it. If there is an issue defining a name Forge can come in an set the final word but the way we have it setup there shouldnt be any issue adding the same thing to the oredict multiple times, so modders can just do that. Or they could check if it exists first and dont add vanilla if they dont need to.

Typically when it comes to adding things to the oredict we don't do 1 item at a time, we do "here are 15 things that are commonly used in these mods from vanilla"

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by Madsthunder** [comment]
Actually no, 1.13 will bring trapdoors and buttons for the rest of the wood types. I think that those additions will apply to this issue in the very near future.

**Comment by KnightMiner** [comment]
It also brings the vanilla tag system which already marks doors and trapdoors

**Comment by Madsthunder** [comment]
You know what, I completely forgot about that
