### ISSUE TITLE
[1.10.2] Filter out unusable sub-commands in CommandTreeBase#getSortedCommandList

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3252]
`CommandHandler#getPossibleCommands` takes an `ICommandSender` argument and only returns commands usable by the sender. 

`CommandTreeBase` should have a similar method for its sub-commands, either instead of or in addition to the current `CommandTreeBase#getSortedCommandList` method.

For now, I'm using [this](https://github.com/Choonster/TestMod3/blob/b81059e91e999800be9ecae889c89177c755308a/src/main/java/choonster/testmod3/command/CommandTestMod3.java#L52-L67) in my mod.

**Comment by LatvianModder** [comment]
Aw man, I forgot about the params. Not sure if lex would merge another small change like this, when it would basically be the same as you are doing. Also, if you have a help command, I dont think you are doing it right.. /help <cmd> should already cover all commands

**Comment by Choonster** [comment]
`CommandTestMod3Help` is a sub-command of `CommandTestMod3` that displays the usage of all sub-commands.

The vanilla help command only displays the usage of the base command, which doesn't include every sub-command.

**Comment by Choonster** [comment]
Is this likely to be added or should the issue be closed?

**Comment by Choonster** [comment]
Any update?

**Comment by mezz** [comment]
I think the best solution is one you suggested, adding a new `CommandTreeBase#getPossibleCommands` method next to `CommandTreeBase#getSubCommands`. It will filter out the ones that can't be executed by the current player. 

The implementer should leave the current `getSubCommands` method as it is, since mods may already depend on it, and look for places where it can be used to simplify the existing code a little. For example, when I last updated that file, I made the tab completion filter out commands that can't be executed by the current player.

**Comment by Choonster** [comment]
This will be fixed by #4927.
