### ISSUE TITLE
[1.10.2/1.11] Custom models for compass/clock do not rotate

### ISSUE THREAD

**Issue by HanPrower** [MinecraftForge/MinecraftForge#3264]
For some reason the override predicates for time and angle are ignored when fully custom models are used.

Attached is an example resourcepack (due to them being from PureBDcraft I've thrown random colour on the textures so as to not breach its license):
[Forge_Compass-Clock.zip](https://github.com/MinecraftForge/MinecraftForge/files/479057/Forge_Compass-Clock.zip)

**Comment by bs2609** [comment]
Just to clarify, does this work in vanilla Minecraft?

**Comment by HanPrower** [comment]
Yes, it works perfectly fine in Vanilla MC.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by HanPrower** [comment]
Any news about this? Some pretty basic functionality being broken here.

**Comment by HanPrower** [comment]
Still an issue in Forge for MC1.11.

**Comment by HanPrower** [comment]
@LexManos I see you assigned @RainWarrior back in October, but he hasn't made a commit since June.

I'm not sure if he's just the "models" guy or something, but is there any chance someone else can take a look at this and https://github.com/MinecraftForge/MinecraftForge/issues/3040 instead of it quietly being ignored?

It's some pretty core vanilla Minecraft stuff being broken.

**Comment by bs2609** [comment]
@RainWarrior (fry) is currently away, and has been for a while. They ought to be back on the 16th, so you _might_ see some progress then.

It's also worth pinging @mezz, as they're coordinating issues/PRs now.

**Comment by mezz** [comment]
I do not have enough time right now to look into this myself, but I can review and help clean up a PR submitted by anyone in the community.

**Comment by williewillus** [comment]
Pinned it down but not sure of a good solution.

Offending area: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/client/model/ModelLoader.java#L536-L539

`hasItemModel` only returns true if the model inherited from "builtin/generated", meaning that custom shapes don't get get their overrides retained at bake time. `bakeNormal` is instead called, which is a forge method and does not consider ItemOverrides.

I would start by looking at how vanilla handles this, because this resource pack seems to work for it.

**Comment by williewillus** [comment]
(ignore my prior post, I missed some of the logic in bakeNormal, which should make it work, so I have no idea why it doesn't)

**Comment by HanPrower** [comment]
Nice thanks @RainWarrior :+1:
