### ISSUE TITLE
PlayerInteractEvent: no way to **actually** cancel on the client

### ISSUE THREAD

**Issue by BlayTheNinth** [MinecraftForge/MinecraftForge#3272]
There is currently no way to truly cancel a player interact event on the client, making the client-side firing of the event nearly useless.

https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/patches/minecraft/net/minecraft/client/multiplayer/PlayerControllerMP.java.patch#L106-L107

I know it's [intended (see bottom-most note)](https://github.com/MinecraftForge/MinecraftForge/pull/2604) but it's a problem and does not match up with any other event or hook. I cancel something on the client specifically because I **don't** want the server to handle it. There should have never been confusion on this in the first place.

I have a client-only mod that makes torches from your off-hand[ only placeable if you're carrying a tool in your main hand](https://github.com/blay09/ClientTweaks/blob/master/src/main/java/net/blay09/mods/clienttweaks/tweak/OffhandTorchWithToolOnly.java#L25-L40). Of course that doesn't work correctly in multiplayer now, because the client always sends the block place packet, even when cancelled.

I'm not sure what the correct solution is to fix the event behaviour now that it's out and used and changes could break compatibility. Maybe there's the option of combining `@HasResult` and `@Cancellable`? But I really don't see why you would want to ensure the event being handled on the server when it's cancelled on the client.

@williewillus

**Comment by williewillus** [comment]
I'm willing to change this if lex is, but I specifically requested comments from people over and over and no one said anything :/

**Comment by Ruukas97** [comment]
Are you sure there is no way?
I am not saying there is, but try looking at those:
net.minecraft.client.Minecraft.rightClickMouse()
net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock()
If you look at the second method, the client will actually send the packet, if the event is cancelled.
Perhaps you should compare the item in each hand and use EnumActionResult instead of canceling the event.

**Comment by williewillus** [comment]
There is no way, his problem is legitimate (I designed it)

Still shouldve brought it up not-4months later :p

**Comment by LexManos** [comment]
For note, the ideal solution would be to just remove this event from the client side and let the server handle it.
Rolling back as necessary.
This is preferable because it reduces the complexity of this code path and moves the client closer to a dumb-client design which is preferable.

**Comment by shartte** [comment]
I can see some reason to pre-analyze if an interaction is possible on the client side to avoid hitting the server for it, but I agree on the complexity issue. I solved my issues by moving all logic to the server side for now.

**Comment by BlayTheNinth** [comment]
That wouldn't be a solution though because I'm specifically talking about cancelling on the client with the mod not being present on the server.

**Comment by williewillus** [comment]
Okay here's the deal with the client: you need this event clientside to do any useful advanced interaction manipulation.

What happens is, the server is really dumb with regards to interactions. It just executes what the client says to execute in individual packet handlers and that's it. 
The client is much smarter. When you right click, the client tries each one of these in order until one works (each of which has its own packet):
- Interact with entity with raytrace (armor stand)
- Interact with entity (horse, creeper, etc.)
- Use block (furnace, crafting table, etc.)
- Use held item (bow, potion, food, etc.)
- Repeat all, for off hand

The key part here is that the client is responsible for going from one of these to the next and stopping on success.

Let's say I have an evil enchant that prevents any interaction when applied on an item and that item is held. I have it in my main hand, with a block in the off hand.

If I try right clicking the client will attempt each interaction, get canceled, and try the next one (which is the current behaviour from getting canceled, but I'm trying to change it with #3041), ultimately failing and the block in my offhand is used. A packet is sent to the server for each step that is canceled by design to make the server events not depend on the client (this is a point of debate and I was thinking of getting rid of this)

If we get rid of all the patches on the client, then it'll say "okay! use this cursed item", send a packet to the server, and stop. Now if we cancel on the server, the client won't go on to use the block in the offhand, and we have no clean way of telling it to continue an interaction it thinks has already completed.

**Comment by LexManos** [comment]
Wow, Mojang really screwed the pooch on this basic design.
Is it vanilla behavior to send each packet reguardless of if it actually passed or not?
If so then we have to keep that behavior, however stupid it may be.
But if its vanilla behavior to just send the single packet for the specific action taken then we should go that route, and I am failing to understand why it was sending the extra packets in the first place...

**Comment by williewillus** [comment]
yea, all of these cases (see Minecraft.rightClickMouse and the methods it calls)
simply shoot a packet off to the server immediately, before chugging along and processing clientside

**Comment by BlayTheNinth** [comment]
We have other client-side events that are cancellable and won't execute Vanilla behaviour if done so, why would the same not apply here?

**Comment by williewillus** [comment]
I don't understand what you mean?

**Comment by williewillus** [comment]
We "give the server a chance to handle it" regardless the client event's result because that's how **vanilla** does its interactions, and I followed suit, and no one brought it to my attention when I was making it.

**Comment by BlayTheNinth** [comment]
I was referring to Lex's point of having to keep sending the packet to preserve Vanilla behaviour.

Compare this to GuiScreenEvent.MouseInputEvent; we can cancel that one in an inventory and whatever slot-click may have happened will not be sent to the server, even though Vanilla would have sent a slot click packet without the event patched in. 

This here is the same, it's basically just a more specific MouseClick event (when fired on the client-side). Considering this event is fired on a user-action, it only makes sense to give the user client initial authority over whether it's actually sent to the server.

**Comment by BlayTheNinth** [comment]
This is still an issue, I just don't have time to deal with it myself at the moment. I tried in the past, but it resulted in having to move event calls for some of the PIEs and things got messy if I recall correctly.

To recap in short: it's impossible for client-side-only mods (e.g. modded client on Vanilla server) to cancel the PIEs because the packet to the server is sent even when they're cancelled.

I might be the only one currently suffering from this, so it's not a big deal. If anyone wants to fix it, go ahead, otherwise I'll probably get around to it in February/March.

**Comment by Gamebuster19901** [comment]
You're not the only one affected by this. I'm making a client only mod which allows the player to play using a controller. The vanilla behavior for placing blocks is annoying when using a controller, so I with to change that behavior, but I cannot due to this issue.

The only way I can think of to fix this is to intercept the packet that the client is trying to send and silently swallow it. Unfortunately this appears to require netty, and I don't have much experience with that.

It also appears that BlockEvent is affected by this.

**Comment by Gamebuster19901** [comment]
I'm can think of a few instances where a modder may want to cancel the event on the client side, but still send the packet to the server.

Maybe we could some sort of stopPacket field to the event, and if it's true and EnumActionResult is DENY, the packet doesn't get sent.

This would allow vanilla behavior to be preserved by default, but we could also modify it if necessary.
