### ISSUE TITLE
Crash when Entering and Exiting the nether

### ISSUE THREAD

**Issue by DatrixTHLK** [MinecraftForge/MinecraftForge#3310]
Crash Report: https://gist.github.com/DatrixTHLK/11a39704a03ebf39817bcb5c04c802e2
FML Log: https://gist.github.com/DatrixTHLK/549556754dab9774a83a32ae2173bf2d
Minecraft 1.10.2
forge: 12.18.2.2125

**Comment by diesieben07** [comment]
Please reproduce without any mods, or at the very least without all those coremods...

**Comment by DatrixTHLK** [comment]
I removed all the mods, except for liteloader and their mods and no crash. 
Added back 'coremods' no crash.
I will get back to you on this once I figure out which mod it is. (No mods are causing issues with this in a newly generated world.)
This issue is now closed.

**EDIT 4:10am:** When in a new world the game doesn't crash going through a nether portal. I'm going to try it in my old world. 

**EDIT 4:41am:** I think the mod in question is Howling Moon, however, I will need to test out if that is the case to see if that assumption is correct.

**EDIT 5:02am:** Nope not Howling moon. It mentions something about a potion effect. I have regeneration effect on me could that be related to the crash. If so, it has to be Armo(u)r Reborn. Going to test that theory now also,

**EDIT 5:22am:** Nope not that theory either. Tried in a newly generated world but no crash happens. Well, I'm out of ideas.

**Comment by DatrixTHLK** [comment]
I have tested without mods adding back a few at a time after 5 hours of sifting through them. This is the second time I have done this 'test'. 

Referencing Issue [#24 of CyclopsMC/Everlasting Abilities](https://github.com/CyclopsMC/EverlastingAbilities/issues/24)

**Comment by LexManos** [comment]
Ya, it sounds to me like something you have is adding invalid potion effects.
You need more information before we can do anything and posting here for normal debug isn't gunna work because honestly I doubt its Forge's fault until you can provide a way to reproduce.

the line is crashing on is: 
`return (this.getDuration() <= 32147 || p_compareTo_1_.getDuration() <= 32147) && (!this.getIsAmbient() || !p_compareTo_1_.getIsAmbient()) ? ComparisonChain.start().compare(Boolean.valueOf(this.getIsAmbient()), Boolean.valueOf(p_compareTo_1_.getIsAmbient())).compare(this.getDuration(), p_compareTo_1_.getDuration()).compare(this.getPotion().getLiquidColor(), p_compareTo_1_.getPotion().getLiquidColor()).result() : ComparisonChain.start().compare(Boolean.valueOf(this.getIsAmbient()), Boolean.valueOf(p_compareTo_1_.getIsAmbient())).compare(this.getPotion().getLiquidColor(), p_compareTo_1_.getPotion().getLiquidColor()).result();`

Now this is a big crazy line that can have LOTS of nulls in it, but the two big ones is if someone adds a null potion effect to your player, or if they add a invalid potion effect that has a null potion.
There isn't much we can do here to figure out your issue unless you can reproduce it.
I can EASILY write a crappy mod that causes Forge to explode on this line, but it's NOT Forge's fault, it'd be my crappy mod's fault.

**Comment by DatrixTHLK** [comment]
The potion effect is nausea. The mod in question then is more than likely Everlasting Abilities. Sorry to have bothered you.
