### ISSUE TITLE
[Suggestion] Trim data structures at model bake

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3333]
`SimpleBakedModel.Builder` uses `ArrayList` instances for storage. When `makeBakedModel()` is called, we could use `ArrayList.trimToSize()` to minimise any excess memory used by these arrays. (Or an immutable copy could be used)

This could potentially save a few megabytes of memory use without much cost.

**Comment by bs2609** [comment]
OK, following up on a request for some data. On a plain Forge client, with no other mods:
- 9,066 `SimpleBakedModel` instances
- 15.70 MiB retained heap (unpatched)
- 14.46 MiB retained heap (patched)

Works out as 1269 KiB saved, which gives an estimate of 140 KiB saved per 1000x models.

**Comment by williewillus** [comment]
Yeah, I don't think that's worth it.
Can you get data on a big pack like ATM?

**Comment by bs2609** [comment]
OK, here's some data for the All The Mods pack.
- All The Mods (normal)
  - 108,168 `SimpleBakedModel` instances 
  - 271 MiB retained heap 

This suggests 14.8-21.4 MiB savings, depending on scaling. I'll post more numbers if I can get the pack working with a modified Forge.

Edit: Calculation suggests 25.73 MiB memory footprint reduction (did some heap dump analysis)

**Comment by bs2609** [comment]
@williewillus, what's the procedure you used to get data for #3246? (mostly how to run a modpack with modified Forge)

**Comment by williewillus** [comment]
I used gradlew build to get an installer than ran it to create a vanilla launcher instance, and copied the mods over from modded launcher

**Comment by williewillus** [comment]
Either way I don't think this will be worth it. Shrinking the array backing the list means recopying all of the elements, which could really hurt load time on big packs for a paltry memory gain

**Comment by bs2609** [comment]
It's one extra copy for some arrays, many of which have already been resized multiple times during the model baking process. I just don't think that loading times will be "really hurt" by this. Compared to disk I/O, it's negligable.

**Comment by williewillus** [comment]
yes, but the gain is so small it doesn't justify adding yet another computation per model.

How much memory does it save precisely on ATM?

**Comment by LexManos** [comment]
The memory savings are so small it doesn't matter. And this is not a PR so meh.
The main issue is the unpacked vs packed argument of  #3246 which I agree with except for the fact that there doesn't seem to be a system that is both memory and CPU efficient.
What I have instructed @RainWarrior to do is create a configuration option where users can sacrifice CPU time for memory by unpacking/repacking things on the fly instead of keeping them unpacked. 
As memory is cheap these days these options won't be enabled by default but should address our REALLY low end users. 
Once @RainWarrior gets it in this will be addressed. So closing for now as hes aware.
