### ISSUE TITLE
[1.10.2] Client command can be execute without "/"

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3352]
From this forum : http://www.minecraftforge.net/forum/index.php?topic=43050.0

Forge : 1.10.2-12.18.2.2118

**Comment by LexManos** [comment]
Not a bug, its a specifically requested 'feature' to allow for soft-coded prefixes.

**Comment by AEnterprise** [comment]
i would argue that this is a change in vanilla behaviour and can lead to unintended behaviour, if a server admin just sais "stop" to ask someone to stop doing something he/she actually shuts down the server and needs to reboot it

**Comment by Choonster** [comment]
@AEnterprise  While this could lead to accidental command execution, that specific scenario isn't possible.

This only applies to client-side commands registered with `ClientCommandHandler`, server-side commands registered with the server's `CommandHandler` still require a leading slash to be executed from chat messages.

**Comment by AEnterprise** [comment]
alright then it won't be that extreme and thus less dangerous but can surely be confusing

**Comment by diesieben07** [comment]
I argue that this is a bug. Server-side commands only work when prefixed with a slash and there is no way to achieve this with client-only commands, since there is no way to check if the command was invoked without a slash and in that case emulate the normal "send chat" behavior (which would be a silly workaround already).
If there is a client-command named "hello" there is no way to send a chat message that starts with "hello".

**Comment by LexManos** [comment]
And thus is the dangers of writing stupid client side commands.
Either way this isnt a bug as I said its a specifically requested/added design feature.
The only thing I can see here is if someone cares enough they can write a config option to force the requirement of / for a command to run.
But that would have to be configurable as there are mods like the IRC mod that use this feature.
