### ISSUE TITLE
[1.10] GetVillageBlockID event working inconsistently

### ISSUE THREAD

**Issue by Zeno410** [MinecraftForge/MinecraftForge#3358]
The GetVillageBlockID does not get called for Smithies or Churches and, especially oddly, only for some blocks in a well:

![2016-11-04_20 26 21](https://cloud.githubusercontent.com/assets/5322776/20027331/5ff2027a-a2ce-11e6-9e3a-79066723e626.png)

If it's not immediately apparent, the cobble around the water and the cobble on top of the fenceposts was correctly converted to a mod cobble but the outer ring of cobble is still vanilla.

Small and medium houses are treated properly.

Possibly relevantly, while trying to confirm the bug, I encountered GetVillageBlockID being called on a block that had already been converted.

**Comment by LexManos** [comment]
Sadly, this is a vanilla thing.
The GetVillageBlockID is fired in the spot where the game looks for biome specific village blocks.
The places that don't fire this event, such as the part of the well you found, is not biome specific.
If we were to go through and cleanup this code it would require literally hundreds of changed lines and make Forge's world generation different from vanilla's. Which is not acceptable.

The HOPE is that in 1.11, or something Mojang will eventually cleanup this code so that we can fix this without ungodly code changes.

**Comment by Zeno410** [comment]
So they changed it for 1.10? This has worked fine in 1.6, 1.7, and 1.8

**Comment by LexManos** [comment]
Yes they changed it for 1.10.
