### ISSUE TITLE
Unable to Get Entity From Entity Part Under EntityInteractEvent

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#3378]
Version: 1.10.2

Unable to Get Entity From Entity Part Under EntityInteractEvent. There is no method in the world class nor they entity class to get the entity in the world from it's part and the event.target that is in the entity interact event returns an entity part. So I can't set the entity dead or do anything with the ender dragon with right clicking an item at all.  So there needs to be a method to get mob from mob parts in the world or just correct that event.target in the first place. I don't feel like coding a mess to get the nearest entity since that might not always return the entity with parts. I want accuracy and this fixed please.

Mods like lycanites mobs and other mobs that are bigger by default probably use entity parts if they did it properly so please fix this.

**Comment by williewillus** [comment]
this isn't a problem with Entity interact event.

I would change the title to "Entity Parts should know their parents"

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3377

**Comment by mezz** [comment]
`EntityDragonPart` has a public final field `entityDragonObj`, which is the ender dragon.
It is separated out this way intentionally, the parts forward damage to the dragon and nothing else. That's just how the dragon is built.
If you really need to kill the dragon instantly instead of doing damage, you can check that `entityDragonObj instanceof EntityLivingBase`, cast it, and kill it in whatever maniacal way you want.

**Comment by jredfox** [comment]
No it's not just the ender dragon it's all entities that have multiple parts and doesn't have a generalization of anything defined different for every case. for example orespawn

**Comment by mezz** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/307

**Comment by mezz** [comment]
`EntityDragonPart` is a generalized solution for multipart entities, it just needs a better name.

**Comment by mezz** [comment]
@jredfox show me your code and what you want to do, and I can work with you on a solution.
Without that, I do not understand what you are talking about. We need to be on the same page.

**Comment by jredfox** [comment]
I don't have any code to apply there is non besides getting entities from the bounding box. JC I believe uses the multi part entity inteface as well.  I don't think it will be the same dragonobj every time as that object might not be accurate if they don't extend entity part. They might implament the interface but, don't necessarily have to use that class as it is pretty basic.  I am saying just make a method or registry hashmap something that forces modded multi part mobs to be able to get the entity from it's part.

**Comment by mezz** [comment]
This is an existing standard way for entities parts to expose a public reference to their parent, which is exactly what you need.
If anyone isn't using this entity class for their parts, you should encourage them to, so that you can get the parent entity from the part.
There is nothing very limited about this, they can extend it just like they extend entity.
All you have to do is check `part.entityDragonObj instanceof EntityLivingBase` and then use it as a living entity.

**Comment by jredfox** [comment]
Entity Dragon part class will discourage enough people even me from extending that class.  You could simply try to fix the issue by making them register which will have a method to get the entity from it's part by using that interface and then patch vanilla. work with forge

**Comment by mezz** [comment]
This is being renamed soon in MCP so that it has nothing to do with dragons, you can see the issue I linked earlier. There is no reason not to use it, there is nothing to fix.
