### ISSUE TITLE
[1.11 - 2153] Sending FMLProxyPacket from Forge server to vanilla client causes DC

### ISSUE THREAD

**Issue by chylex** [MinecraftForge/MinecraftForge#3422]
Ran into this issue porting 1.10.2 code (where this worked fine) to 1.11. The mod works on either client or server separately and is not required to have installed in both, but it does attempt to communicate with the other side at several points.

Using `FMLEventChannel` to [send packet to all players or a specific player](https://github.com/chylex/Better-Sprinting/blob/1.10.2/src/main/java/chylex/bettersprinting/system/PacketPipeline.java#L54) causes a server error if the client is vanilla, which makes the client disconnect.

Here is an except from the [server log](https://gist.github.com/chylex/18ea1603c46f8f3896d856e95b4cbc8c) that shows an error in `NettyNetworkEncoder`, where it could not determine FMLProxyPacket's packet id and threw a "Can't serialize unregistered packet" exception. In this case, the packet is sent immediately after the client joins, but the client gets disconnected even when sending it later (for ex. after running a command).

```
[23:03:31 INFO]: Connection received without FML marker, assuming vanilla.
[23:03:31 INFO]: [Server thread] Server side vanilla connection established
(...)
[23:03:31 INFO]: §e§r§echylex§r§e joined the game§r
(...)
[23:03:31 DEBUG]: OUT: [PLAY:null] net.minecraftforge.fml.common.network.internal.FMLProxyPacket
[23:03:31 DEBUG]: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
[23:03:31 INFO]: chylex lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
```

If I understand this, FMLProxyPacket should be converted to custom payload packets, which is not happening in this particular case. This is mainly a problem when trying to send a packet to all players on the server, where some of them have Forge installed and some don't, which would cause all vanilla clients to DC.

This is not an issue if either:
- both client and server are modded (of course), the client does not need to have the mod installed
- client is modded, server is vanilla, and client sends a modded packet to the server
- in previous versions of Minecraft, between 1.10.2 all the way back to 1.7.10, where the same code has been used

(Note: I have modified the mod to check for mod presence on all clients before sending them the packets, but I can upload an older 1.11 build that causes the issue)

**Comment by LexManos** [comment]
If you can write up a small test mod that I can look into it tomarrow.

**Comment by chylex** [comment]
https://www.dropbox.com/s/aw6vsemb8f5ha5s/ForgeNetworkTestMod.zip?dl=1

Contains both compiled .jar that works in 1.11 and 1.10.2, and the source code. Tested it and confirmed that a vanilla client joining a Forge server with this mod will get kicked only in 1.11.

**Comment by LexManos** [comment]
Finally got time to sit down and test out your test mod.
And it doesn't work on 1.10.2.
Both get the unserializeable error.
And looking at the network registration, I can't see how it would work in your tests ever...
We don't seem to have any filters for trying to send a FML packet to vanilla clients.
I'll see if I can figure out how to filter that out, or make it so that things don't error.
Vanilla clients should never get FML packets.

Side note, Tho I apreciate your writing a test mod, THIS is what a test mod should look like. No Fluff no nothing:
```
@Mod(modid = ForgeNetworkTestMod.MOD_ID, name = ForgeNetworkTestMod.MOD_ID, acceptableRemoteVersions = "*")
public class ForgeNetworkTestMod
{
    public static final String MOD_ID = "forgenetworktest";
    private FMLEventChannel channel;

    @EventHandler
    public void onPreInit(FMLPreInitializationEvent e)
    {
        if (e.getSide() == Side.SERVER)
        {
            MinecraftForge.EVENT_BUS.register(this);
            channel = NetworkRegistry.INSTANCE.newEventDrivenChannel(MOD_ID);
            channel.register(this);
        }
    }

    @SubscribeEvent
    public void onPlayerLogin(PlayerLoggedInEvent e)
    {
        if (channel == null)
            return;
        PacketBuffer buffer = new PacketBuffer(Unpooled.buffer());
        buffer.writeByte(0);
        channel.sendTo(new FMLProxyPacket(buffer, MOD_ID), (EntityPlayerMP)e.player); // disconnects vanilla clients
    }
}
```

**Comment by cpw** [comment]
Err, the server is disconnecting, because the FMLProxyPacket handler isn't in the pipeline for some reason. It should always be present on all connections, vanilla or modded, so it can translate between proxypackets and (what used to be) 250s. The client doesn't care one jot about a 250 packet that has an unknown identifier (Mojang got that bit right, at least) and just ignores it. This problem is all in the server.

Edit: further commentary
[23:03:31 DEBUG]: OUT: [PLAY:null] net.minecraftforge.fml.common.network.internal.FMLProxyPacket
This should NEVER happen. Something has directly sent the fmlproxypacket to the vanilla channel, without running it through the fml packet handler first.

**Comment by kashike** [comment]
@cpw Perhaps related to https://github.com/MinecraftForge/MinecraftForge/commit/62ec59103abd22d86d8f1b5154457a55a1dc93aa?

**Comment by LexManos** [comment]
Ya, probably, I fucking hate netty shit.
Either way its fixed now.

**Comment by chylex** [comment]
Ah, I was using an old version of 1.10.2, didn't even realize the bug could have been introduced back then. Thanks for looking into it and for the side note, I'll keep it in mind.
