### ISSUE TITLE
Any version past 2110 takes 20 - 25 mins on step 7/7 Texture uploading and mipmap

### ISSUE THREAD

**Issue by HotdogDaddy** [MinecraftForge/MinecraftForge#3430]
Issue Description:
Any version past 2110 takes 20 - 25 mins on step 7/7 Texture uploading and mipmap

What happens:
Since updating past forge 12.18.2.2110 when my laptop gets to step 7/7 Texture uploading and mipmap it takes 20-25 minutes to finish that step.

What you expected to happen:
With 2110 it would take 5 secs or so on Texture uploading and mipmap

**Comment by LexManos** [comment]
Go to thew forums are do some trouble shooting before posting here.
And follow the rules as this is a useless report because it has NO information we can use.
The change for 2111 is literally one opcode. So i'm not seeing how it could cause you so much issues.
https://github.com/MinecraftForge/MinecraftForge/commit/1eee6cd38282a80958444ee5979eb9cbe55ff509

**Comment by HotdogDaddy** [comment]
It was suggested by someone in the IRC channel to come here after I had tried multiple things to see what is causing this. 
When I downgrade and use any version of forge before 2111 it loads fine. When I use any version after that it takes 20 - 30 minutes or more to log in. I have tried unistalling curse deleting profile ... I did fresh install of win 10. 
I have tried versions 
2106, 2107, 2109, 2110 .... all worked 
2111 through 2119, 2125, 2132 2139  2140  2147 2151
