### ISSUE TITLE
[Request] SlotClickEvent

### ISSUE THREAD

**Issue by XFactHD** [MinecraftForge/MinecraftForge#3443]
I have an item that should only be placed into the inventory or the main hand but not into the offhand. As nobody on the Forge Forums was able to help me, I suspect that there is no easy way to achieve this. Therefore it would be nice if there was either an event for when an inventory slot is clicked and/or a method in the Item class that checks if the item can be placed in this EntityEquipmentSlot (kinda like isValidArmor but more generic).

**Comment by AshIndigo** [comment]
I used IInventory#decrStackSize to achieve this when I needed code to run when an item was removed from a slot.

**Comment by XFactHD** [comment]
I need to block interaction with a slot I have no internal access to (the offhand slot) so that solution is not viable.

**Comment by mezz** [comment]
Why do you need to make your item impossible to hold in the offhand?

**Comment by XFactHD** [comment]
Because it doesn't make much sense to hold two heavy assault rifles and shoot them accurately. It would also need even more special handling for aiming.

**Comment by mezz** [comment]
Why not just deactivate it when it's in the offhand?

**Comment by XFactHD** [comment]
I haven't thought about that, I'll try that and report back if it isn't enough.

**Comment by AEnterprise** [comment]
a slotclick event also wouldn't help at all, you could still put the item in your offhand by putting it in you main hand and then pressing F

**Comment by XFactHD** [comment]
I could cancel the InputEvent for that case.

**Comment by mezz** [comment]
I think this idea is generally bad practice because it would really break player's expectations. They would think it's a bug, not a feature, because every vanilla item and every other modded item can be held in the offhand. 

Items like the pickaxe do not work in the offhand, so making your rifle not work in the offhand would be perfectly in-line with player expectations. You can hold 64 cubic meters of gold in your offhand and still mine with the other hand, so I'm not sure it matters how big the assault rifle is ;D

**Comment by XFactHD** [comment]
Generally I agree that the size and weight of the gun doesn't matter in MC but when you want to replicate an FPS game in MC as good as possible, it does matter.

**Comment by mezz** [comment]
I understand what you're saying, I was just being cheeky.
