### ISSUE TITLE
[1.11] ItemStack.onItemUse decrements held ItemStack not selected stack

### ISSUE THREAD

**Issue by oitsjustjose** [MinecraftForge/MinecraftForge#3487]
So, I believe this is a Forge bug as I've tried it with both the ForgeHooks version *and* the version shipped in the ItemStack class. My code does the following after looping (checking to see if the held item is a tool, and then finds a torch in your inventory and attempts to place it).

It places the torch just fine, but the held tool's stack count is decremented, not the Torch stack.

[My class, for reference, in the likely event I'm an idiot](https://github.com/oitsjustjose/V-Tweaks/blob/1.11/src/main/java/com/oitsjustjose/vtweaks/event/itemtweaks/TorchHelper.java#L39)

**Comment by Choonster** [comment]
This happens because `Block`/`Item` interaction methods no longer receive an `ItemStack` argument, instead they receive an `EnumHand` argument and use the `ItemStack` in that hand.

Calling `ItemStack#onItemUse` for an `ItemStack` that wasn't held was probably never defined behaviour, but now it will almost never work.

You should set the player's held item to the torch by changing the `InventoryPlayer#currentItem` field before calling `ItemStack#onItemUse` and resetting the held item back to the previous value.

The last three arguments of `ItemStack#onItemUse` are the coordinates that the block was clicked at, not the coordinates of the block in the world. Use `PlayerInteractEvent.RightClickBlock#getHitVec` for these.

Comparing things by their localised names is a bad idea. Compare `Item` instances instead.

**Comment by williewillus** [comment]
Additionally use Itemstack.isEmpty instead hard comparing with the field. And likewise use ItemStack.EMPTY instead making your own invalid stack

**Comment by oitsjustjose** [comment]
Are there new mappings out? I'm on snapshot_20161111 and Forge 13.19.0.2178 and I can't find ItemStack.EMPTY or any isEmpty methods.

Also, as far as the potential that this won't be supported - is that set in stone? I'm not one to argue about program design, but I will bring up that my mod is certainly not the only one that attempts to use and permute another stack using the held stack (see Actually Additions and IC2)

**Comment by shadowfacts** [comment]
New snapshot mappings are published daily with version numbers in the form of `snapshot_YYYYMMDD`. So today's would be `snapshot_20161203`.

**Comment by Choonster** [comment]
There's no explicit statement that only a held `ItemStack` can be used, but the design of the vanilla interaction code reflects this. `ItemStack#onItemUse` is only ever called for a held `ItemStack` and `Item#onItemUse` has no access to the `ItemStack` that called it other than as the player's held item.

**Comment by mezz** [comment]
It's misleading that `onItemUse` is a method on `ItemStack`, it should probably be a static helper method somewhere else, but that's just how it's written in vanilla. This is unlikely to get changed.

**Comment by oitsjustjose** [comment]
Alright, that's fair. I've re-implemented it in a much nicer way than replacing the held item and un-replacing it....

Closing this issue, fair points from all. There are ways to do it that are still clean, just not as easy as it was :)
