### ISSUE TITLE
[1.11][Request]Sorting RegistryEvent.Register and applyObjectHolders

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftForge/MinecraftForge#3508]
I think RegistryEvent.Register needs to be sorted.
For example, when I want to register a potion type which has some non-vanilla potions gotten from field with ObjectHolder, the field is null.

Code:
```java
@Mod(modid = PotionMod.MODID)
@EventBusSubscriber
public class PotionMod{
    @ObjectHolder(MODID)
    public static class POTIONS{
        public static final Potion potion = null;
    }

    @ObjectHolder(MODID)
    public static class POTION_TYPES{
        public static final PotionType potion_type = null;
    }

    @SubscribeEvent
    protected static void registerPotions(RegistryEvent.Register<Potion> event){
        event.getRegistry().registerAll(
                new SamplePotion().setRegistryName(MODID, "potion")
        );
    }

    @SubscribeEvent
    protected static void registerPotionTypes(RegistryEvent.Register<PotionType> event){
        //"POTIONS.potion" has not been assigned yet.
        event.getRegistry().registerAll(
                new PotionType(new PotionEffect(POTIONS.potion)).setRegistryName(MODID, "potion_type")
        );
    }
}
```

Even if you assign in an event, the order of events is alphabetical, so it is not necessarily not null when you want to use it.

**Comment by LexManos** [comment]
Yes this is something i've discussed with cpw, and right now we've decided not to go that route. 
For any objects that you need to rely on other registries for, creating them elseware {pre-init} would be the way to go.
It is a problem that i'd be interested in seeing if there is a proper solution for.
But the problem is finding out what order things should be sorted in, 1/2 of modders would need it one way 1/2 would need it another. 
So for now, it's going to stay, we may address it in later versions.

**Comment by CrafterKina** [comment]
OK, I see.
Thanks for your quick reply.
