### ISSUE TITLE
Is there anyway to distinguish a MobSpawner spawning event from a Normal Natural spawning event?

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#3703]
Since canEntitySpawnSpawner also check canEntitySpawn, I have no way to know if the Entity is being spawned by MobSpawner or Normal Natural spawning routine.

**Comment by zlainsama** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/59a3b3cc79e4908ae060aa96fe5e540d8d5d73ab/src/main/java/net/minecraftforge/event/ForgeEventFactory.java#L191-L202

**Comment by Leviathan143** [comment]
Help with Forge belongs on the [Forge forums](http://www.minecraftforge.net/forum/index.php?board=73.0.html), not the git repo.

**Comment by williewillus** [comment]
there used to be a spawner event but it got broken and subsequently renamed.
might be worthpatching one back in

**Comment by zlainsama** [comment]
There are mods that their main purpose is to filter mob spawning, and since MobSpawner do checks in the same event, they start to mess with MobSpawner.
My [mod](http://minecraft.curseforge.com/projects/peacefulsurface)([source](https://github.com/zlainsama/PeacefulSurface)) is one of them.
A separate event or a way to check if the event is posted by a MobSpawner would allow intended behavior(do not filter MobSpawner).

**Comment by HenryLoenwind** [comment]
If someone wants to do some work on those events: A late event, just before the mob is actually placed into the world, that still allows cancelling and allows moving the mob around would really be nice.

**Comment by LexManos** [comment]
@HenryLoenwind So you mean like EntityJoinedWorldEvent 
@Everyone else, so all you're asking for is a boolean isSpawner() function on CheckSpawn? Seems like someone could write a simple PR for that.

**Comment by williewillus** [comment]
doesn't SpecialSpawn fire right before joining worlds?

**Comment by HenryLoenwind** [comment]
I just looked at findChunksForSpawning() and I think it is a bit messy how the vanilla checks and those two events are mixed together. However:

* EntityJoinWorldEvent is a bit late, you cannot change the chunk the entity is added to anymore. Also, it gets called for a metric ton of different things.
* SpecialSpawn only can mess with the entity's onInitialSpawn(), so it could change the location (but that then is checked again for collisions which cancel the spawn), it cannot cancel the spawning (other than setting the location to something that collides on purpose)

What I imagine would more along the lines of CheckSpawn.Pre and CheckSpawn.Post. Pre where the CheckSpawn is at the moment and Post just before the call to spawnEntityInWorld(). Maybe even with Pre having a result of "skip those vanilla checks" (I don't need that, but I could think of plenty of useful things to do with that).

Background: I have 2 use cases for this: The Inhibitor Obelisk would be better if it used energy per prevented spawn. But it is called before the vanilla checks for location, light level and stuff, so the energy cost would be unrelated to real preventions. The Relocator Obelisks wants to move spawning mobs to the obelisk. We do that by storing a copy of the entity and checking later (TE tick) if it exists in the world, moving it then. Again because of the vanilla checks---we want to move mobs that actually spawn, not everything that may possibly spawn.

**Comment by zlainsama** [comment]
I suggest
- A object holder for events, it can be null when not required and added/attached in real-time by event handlers, it can be used to pass additional objects or information to next handlers or later phases/sub-events. It can be pre-populated with information like if it is posted from canEntitySpawnSpawner.

And two additional Event.Result type
- OVERWRITTEN, you can pass some objects to said object holder to allow things like change to a Zombie when a Cooked Chicken Item is being spawned into the world. This could solve the problem like Flux Networks killing Redstone Item just to spawn a Fire-proof one.
- SUPERSEDED, treat it as ALLOW but do NOTHING, let the mod's event handler do their things like spawning entities into the world. This might require adding Post events to all the events.

or make them like Cancelable: Overwritable; Supersedable?

This might require a lot work to go through all the events, but it should be compatible with current system.

**Comment by bs2609** [comment]
Can this be considered resolved by #4075?

**Comment by zlainsama** [comment]
Yes, I think so. I forgot about this. Sorry.
