### ISSUE TITLE
Block model vertex lighting optimization

### ISSUE THREAD

**Issue by thecodewarrior** [MinecraftForge/MinecraftForge#3754]
If a mod has a high-vertex model in addition to any kind of non-trivial code in the `getLightValue` function it can cause a huge amount of lag. Non-trivial code being something like getting the light value from the tile entity (as MCMultipart did.)

A lot of this is from memory, so it may not be 100% of the story, but I believe the biggest problem I saw was in the `VertexLighterFlat.updateLightMap` function, where the light value of the block is queried for every single vertex.

It seems like a relatively simple fix, it appears that just some simple caching could massively decrease the number of calls to `getLightValue`.

**Comment by williewillus** [comment]
is there a specific block or mod this can be tested against? the change is trivial to make but need to verify it

**Comment by williewillus** [comment]
also, I don't see the part where you're talking about. VertexLighterFlat only calls to the world/blockstate for light once

**Comment by thecodewarrior** [comment]
I don't have a simple test case, but if I'm right you would just need to get a relatively high-poly OBJ model for it (to simulate a complex json model without having to make one) and get the tile entity in the getLightValue method. 

The problem is that it calls  `getPackedLightmapCoords` for each vertex, and you'll find that it in turn calls `state.getLightValue(source, pos)`.

**Comment by thecodewarrior** [comment]
Should I try and make a test case for this? It should only take like twenty minutes once I get to it.

**Comment by mezz** [comment]
Please do.

**Comment by thecodewarrior** [comment]
All of these tests were performed on a 16x16x16 grid of 1/2px cubes, totaling just under 100,000 vertices. Stress testing!

![2017-03-27_00 52 46](https://cloud.githubusercontent.com/assets/5467669/24346074/ba374988-1287-11e7-890a-1de12fb06b65.png)
I made this simple setup and profiled each combination for five minutes.


![untitled](https://cloud.githubusercontent.com/assets/5467669/24345306/50767daa-1284-11e7-8838-9f3577b4f024.png)
This is using the forge pipeline with just a return statement from the light method ("non-laggy" mode in the test mod) It was pretty laggy, but I still got ~2 FPS.

![untitled 2](https://cloud.githubusercontent.com/assets/5467669/24345659/fbdcb1a4-1285-11e7-811c-a63fc864d5d9.png)
This is using the forge pipeline with a tile access and 50 HashMap accesses using an Array as the key. ("laggy" mode in the test mod) This one lagged so hard I had to hot-swap `false &&` into the "should be laggy" check in order to turn off the clock.

![untitled 3](https://cloud.githubusercontent.com/assets/5467669/24345902/124c6eb0-1287-11e7-83e9-630cff8e50de.png)
This is using the vanilla pipeline with just a return statement from the light method ("non-laggy" mode) I barely noticed any lag here.

![untitled 4](https://cloud.githubusercontent.com/assets/5467669/24346111/db5e2186-1287-11e7-95a5-f0477aeaa622.png)
This is using the vanilla pipeline with a tile access and 50 HashMap accesses using an Array as the key. ("laggy" mode) This was far less laggy than with the forge pipeline.

Here's the mod source and a built version of the mod. They are for Minecraft 1.11.2, latest forge (13.20.0.2260) and latest MCP (snapshot_20170326). [vertex_light_cache_lag.zip](https://github.com/MinecraftForge/MinecraftForge/files/871779/vertex_light_cache_lag.zip)

**Comment by mezz** [comment]
Based on the performance data here, I think the most relevant metric is the number of calls to `getLightValue`. Can you create a comparison between the number of `getLightValue` calls vanilla makes vs the number of calls Forge makes on your test block for a single chunk rebuild?

**Comment by williewillus** [comment]
If you have a fix made why not make a pr for it as well?

**Comment by mezz** [comment]
I think there is no fix here, just vanilla vs forge lighting pipelines.

**Comment by thecodewarrior** [comment]
I think the performance difference is because while the vanilla renderer calls `getPackedLightmapCoords` once per quad, the forge one does it once per vertex. At least with the forge engine it would be as simple as caching the return value so further uses while rendering that block won't call the method repeatedly.

**Comment by thecodewarrior** [comment]
Just ran a test, with the vanilla renderer (which still isn't optimal in this regard) it [edit: `getLightValue`] is called 24,577 times for the block, which is roughly the number of quads in the model, but the forge one calls the method 98,305 times, which is roughly equivalent to the number of vertices.

A little bit of caching could help a lot here, not only in the case of models with complex `getLightValue` methods, but the `getCombinedLightmapCoords` method does more than just return a value, it also has to check the light in the world, which although small, can and does have a performance impact. (as shown by my "non-laggy" test, where the light method simply returned a value.)

**Comment by bs2609** [comment]
How does `VertexLighterSmoothAo` compare to `VertexLighterFlat` here?

**Comment by thecodewarrior** [comment]
The forge renderer calls it 18 times, and the vanilla calls it 229,393 times.

**Comment by thecodewarrior** [comment]
I feel that this could be a huge point of optimization, right?

**Comment by mezz** [comment]
There may be a good reason it does things this way, the gains here are still theoretical until we have a PR to test. It looks promising though, I think it's worth pursuing.

**Comment by thecodewarrior** [comment]
`this.confidence++;`

:D

**Comment by bs2609** [comment]
@RainWarrior do you have any thoughts?

**Comment by thecodewarrior** [comment]
I know that asie added a feature to FoamFix that was at least inspired by
this, which might could be used as a reference.

**Comment by bs2609** [comment]
As a related issue: `VertexLighterFlat.updateLightmap()` calls `getPackedLightmapCoords()` for multiple differerent positions, but always using the same blockstate.
For comparison, the values of `getPackedLightmapCoords()` used by `VertexLighterSmoothAo` are obtained by `BlockInfo.updateLightMatrix()`, which calls `world.getBlockState()` for each different position, instead of reusing the same state each time.

I don't know if this is an intended difference, but if not, it's another reason to have a more unified implementation for this.

**Comment by thecodewarrior** [comment]
This is still an issue in 1.12, and is horrific when calculating AO for more than a couple hundred vertices. Even on flat shading it's a problem, even with the default minecraft light value function, which is just a simple return statement. 

Here's a WarmRoast stack trace for the model with flat shading, the only one that was tolerably laggy
![untitled](https://user-images.githubusercontent.com/5467669/28254664-8d9239c2-6a63-11e7-88b4-fabbce5ea610.png)

If you want to see the mod used, it's here: https://minecraft.curseforge.com/projects/catwalks-3 The models don't look very complex, but internally they are split into quadrants, which dramatically increases the quad count. The maximum however is only ~100 quads per block.

**Comment by PhiProven** [comment]
During discussion of #4199 I came up with another approach for solving this issue and #2773. I'll restate it here roughly:
Instead of using `getLightValue` for the minimum brightness, we could also use the result of the lighting engine, as this already accounts for the source light of the block (IMHO it even makes more sense to use the overall light value from the lighting engine as minimum, instead of designating a special role to the source light. For the lighting engine, it doesn't matter if a block gets its light level through neighbors or from its own source light; hence it shouldn't matter for rendering either). This value should be passed as additional parameter to `getPackedLightmapCoords` (or alternatively should be accounted for at callside).
This approach has the advantage that it completely eliminates the calls to `getLightValue` and hence solves the performance problem and the problem with non matching `state`-`position` pairs (and also all related concurrency issues).
Unfortunately, there are also some disadvantages:
* The minimum light value should be calculated without accounting for neighbors (ie. ignoring `useNeighborBrightness`), otherwise the faces of slabs, farmland, etc. may be too bright. `IBlockAccess` doesn't expose anything to query this information. We would need to add a parameter to `getCombinedLight` (which would be a breaking change as all implementations would need to account for this change) or pass that information through the `lightValue` argument (eg. `lightValue == -1` means ignore neighbor brightness)
* It's quite a bit of patches. But that's probably the case for other solutions as well.
* Falling light sources (eg. sea lanterns) are rendered dark, whereas they are bright in Vanilla. This is also the case for the current implementation of `getLightValue` which exists for a couple of years now, so I don't think that would be too much of a problem.

What are your opinions on that approach?

**Comment by PhiProven** [comment]
I've uploaded a draft of what I had in mind [here](https://github.com/Mathe172/MinecraftForge/tree/cleanup_getLightValue_rendering). Should I post that as PR?
Unfortunately, I'm not very familiar with the rendering code, so I wouldn't mind if someone with a bit more experience could look at it before I post it as PR.

**Comment by bs2609** [comment]
This should hopefully be resolved now #4358 is merged.
