### ISSUE TITLE
Manipulating the ItemStack in ItemCraftedEvent doesn't work when shift clicking to craft

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#3780]
I tested the following code, and when regular clicking to remove the result, it worked fine, but when shift clicking, it does not.
`@SubscribeEvent
    public void itemCrafted(PlayerEvent.ItemCraftedEvent event){
         event.crafting.setCount(64);
    }`

Tested with Forge 1.11.2-13.20.0.2255

**Comment by diesieben07** [comment]
Modifying the crafting result is obviously not intended with this event. Doing so results in the weird visual glitch of the item changing _after_ you took it out of the crafting grid.
I argue this is not a bug, but using the event wrong.

**Comment by LexManos** [comment]
I would agree with that considering the event was first created to simply post achievements from crafting items.
Modifying them mid-event was never intended.
Beyond that when shift clicking there is not a single ItemStack that is created, instead a fake copy is created and then any slots it can fill in are filled. This would cause issues in the stacking code, potentially modifying the NBT of already created items because it tried to stack with it.

Now, I don't know your particular use case, but there is something about auto-claiming things, this should be done in the IRecipe itself.

**Comment by XFactHD** [comment]
I know this has nothing to do with the OPs use case but what about mods like NoMoreRecipeConflict that let the player choose the recipe output of any recipe that has multiple different outputs (like compressed sand from ExtraUtilities and ExCompressum)?

**Comment by The-Fireplace** [comment]
@diesieben07 @LexManos If it isn't meant to modify the stack, then perhaps the behavior should always be to not modify the stack. Either way, the behavior for shift+clicking with this event should not be any different than the behavior for regularly crafting items.

**Comment by The-Fireplace** [comment]
I maintain my case that the behavior of that event should be consistent no
matter if you're shift+clicking or regular clicking to craft.
