### ISSUE TITLE
Clients crashs when breaking a tool

### ISSUE THREAD

**Issue by Wugand** [MinecraftForge/MinecraftForge#3825]
In the newest Forge Version (1.11.2 - 13.20.0.2264) every client, which breaks a tool lost connection to Server.

Client-Log:
https://pastebin.com/yJjQ2f9X

Server-Log:
https://pastebin.com/SbkQqjSZ

Test-Enviroment:
Dedicated Server, no Mods, Server and Client an newest forge version

*Playing at SinglePlayer-Mode everything works fine (and the break sound gets played)

**Comment by Madsthunder** [comment]
I just love how when one bug gets fixed, another one instantly pops up #3821

**Comment by Wugand** [comment]
I updated forge espacially for this fix, but no, it's more worse now.
Note: The Tool break sound is playing befor the client disconnects.

**Comment by mcenderdragon** [comment]
It seems like something is of with the SPacketParticles at the client side, so the netty thread crashes and the connection to the server gets closed.

**Comment by LexManos** [comment]
Interesting I specifically tested all usecases. Including on dedicated server and local client. This error is typically the result of a malformed packet. And I didn't touch the packet format itself..

**Comment by JDLogic** [comment]
@LexManos the SPacketParticles packet uses the particle enum to determine the number of particle arguments. In the case of ITEM_CRACK that number is 2 because the stack metadata needs to be sent if the item has subtypes.

**Comment by LexManos** [comment]
That seems to be the case yes, Which leads to another issue, ALL other instances of spawning ITEM_CRACK only pass in a single argument... Mojang, why you so bad at your own thing!?
Oh, wow, digging more into it, Mojang hacks the parameter count by doing int i = p_178902_15_.length > 1 ? p_178902_15_[1] : 0; ... So that parameter length is only a 'max' value.. fun...

Still curious why it worked fine on the dedicated server for my tests.. will look more into it.

**Comment by mcenderdragon** [comment]
Confirmed as working.
