### ISSUE TITLE
[Future suggestion] Optimized calc light for range of blocks

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3848]
I noticed that forge and minecraft don't have optimized method for recalculating light in block range (volume).
As a said before #3841, #3842 it works very slow
I think that it can be done with Dynamic programming based on already calculated information for each block in that range.
I'm not pro in this, so I don't know exactly how light calculations works. Can you give me information?

**Comment by williewillus** [comment]
you can look at the light calculation source yourself :P

**Comment by ghost** [comment]
it's little bit obfuscated, but ok

**Comment by mezz** [comment]
This could be useful, recalculating light levels is very slow in a lot of cases.
It's especially bad for stuff like worldgen trees, which recalculate light for every leaf block placed.

**Comment by mezz** [comment]
You should leave this open even if you are working on it so we can discuss it and keep track of progress.

**Comment by ghost** [comment]
I solved this using breadth first search - Levite algorithm now it works much faster for block region.
I believe that it miss somehting like heightmap or sky-map at this moment.
https://github.com/ternsip/StructPro/blob/8fce163380c6950e20183bf566c4c3d23e5c0a98/builds/1.10.2/src/main/java/com/ternsip/structpro/Universe/Cache/Universe.java#L141
This function can be adapted for forge.

**Comment by PhiProven** [comment]
Maybe I'm wrong, but I don't think that your algorithm produces the right result:
You essentially recalculate the light values for the whole volume `(wx, wx + width, ...)`, but you only take into account the blocks inside that region. This means that the boundary probably gets the wrong values. I think you have to exclude them from the reassignment.
Also, Vanilla doesn't subtract 1 from opacity, but clamp it to 1. There are also two types of light, BlockLight and SkyLight, which have to be calculated separately.

I don't think that you should explicitly implement relighting for a volume of blocks, as that requires you to set these blocks at once, as well. This essentially means that you have to adjust quite a bit of worldgen code, etc. to make use of this.
I think a better way to go with this, is to queue relighting inside `setBlockState` instead of carry it out immediately, until the light value is explicitly queried or until the end of the tick. This way, you can just continue to call `setBlockState` and it will be affected by the optimization. Then the algorithm would look something like: Determine all blocks that are lighted from the queued blocks and reset the light value for those. Then relight all those blocks (going from brightest to darkest neighbor in order to make the iteration as efficient as possible). This is essentially how Vanilla does it, just optimized for multiple blocks instead of just one.

I'm currently trying to write a version of this myself. Hopefully, I can provide some results tomorrow.

**Comment by ternsip** [comment]
Thanks. And can you describe more detailed how to queue block relight?

**Comment by ternsip** [comment]
I have some rocks on that way. For example, if I procrastinate light calculations to later ticks then putting 5-6 schematics around force players and server to start stuttering. That's looks very annoying, so the best way in that case - immediate all changes.

**Comment by williewillus** [comment]
I have no idea how the lighting calculation itself works, but I know that MC randomly goes around and enqueuers' lighting rechecks for each chunk. Maybe we could defer light updates during block set then "weight" those locations more in Chunk.enqueueRelightChecks so MC naturally rechecks the light for us? Just an idea.

**Comment by ghost** [comment]
Is there any way to recalculate light for entire chunk? Or is it very slow? I tried resetRelightCheck, checkLight, etc, but it's all not work for me or works very slow.

**Comment by williewillus** [comment]
Well "recalculating light for entire chunk" **is** expensive. You just checkLight everywhere, which is exactly what the random relght checks do

**Comment by ternsip** [comment]
"This is essentially how Vanilla does it, just optimized for multiple blocks instead of just one."
Can I see code fragment?

**Comment by PhiProven** [comment]
Just a small question @mezz:
I think the easiest way to code this PR is to rewrite most of the lighting internals and remove the Vanilla chaos. Vanilla does all sorts of random checks and screws with the light cache for skylight, so leaving this code in, results in some very unpredictable behavior. Rewriting it, makes it much more understandable, as the main lighting updates then happen at one place, instead of ~5.
Is it ok to rewrite the internals, which thus makes the patches quite large?
If so, what should I do with the old code?
* Delete it (which results in large patch files)
* Leave it as dead code
* Comment it out
* Move it to some unused `...Vanilla` method

**Comment by williewillus** [comment]
I don't think rewriting it is in our best interest unless it's found to provide massive (like really massive) performance gains. The complexity of finding all the vanilla code, removing it, making sure it stays removed in new versions, and reimplementing the exact same logic is not worth a marginal increase in speed

**Comment by PhiProven** [comment]
Then I don't see how this optimization could be implemented.
Vanilla lighting is spread out over several methods. If I understand the code correctly, only one of them is really doing the core calculation and the others just corrupt the light cache (which probably is the cause of some lighting bugs). I think, all of those could be extremely simplified by just doing the necessary work (which is just a few lines) and then calling the core method, instead of screwing a little with the light cache and then leaving it corrupted.
If those strange methods stay in, I can't really tell what happens if some other parts of the code are changed, since every calculation relies on the cached light values which are messed up by those methods.

**Comment by williewillus** [comment]
then I don't think we should do it. 
we can't say for sure that those methods are "strange" or are "corrupting the light cache" because we are looking at a decompiled deobfuscated codebase. They may very well be doing exactly what they're supposed to do if we had the original source names. but we don't.

**Comment by PhiProven** [comment]
All I can tell from the code is that the light cache is left in an unstable state, ie. even if no fruther block change occurs, the light map will still need some check cycles until it reaches some steady state (ie. a state which does not have some phantom light sources). Maybe that is intended, but I don't see why phantom light sources should add any beneficial graphical effect.
It's true that I have to guess what the code is intended to do. If all sorts of weird lighting bugs are indeed on purpose, then those methods cannot be simplified. But assuming that those are indeed bugs and that the underlying light model is simple, then I think that they are too convoluted and can be simplified a lot.

**Comment by ghost** [comment]
I'm pretty sure that light issues have a direct effect to the game performance. Changing even one block cause massive light recalculating. I agree that code not optimized, but it's enough to resolve just light calculations. Because light just spreads in 4 sides in simple grid and decrease it's own value by opacity.
Obviously region recalculations can be simplified, but minecraft sadly not supports that. It's can be solved using modified BFS or even faster. PhoPro95 what is the more performant way to do that than BFS?

**Comment by Niko-sk2x** [comment]
Vanilla lighting code is very confusing, and not very fast, but there are reasons why it is the way it is.

I'm rewriting MC lighting code for my cubic chunks mod, and based on what I know it's nowhere near as straightforward as it seems to just fix it, and have one small place that deals with light updates. I was able to isolate lighting to a few places, but they are essentially what vanilla already has.

Worldgen (population) lighting frequently NOT calculated when the block is set because the necessary chunks aren't loaded yet (17 block radius needed). There is actually a separate piece of code that handles it (as I remember it, I would need to look at the code again).

This means they are queued for later. This is in part what can cause (rare currently) client lighting glitches - the queued updates for neighbor chunk may not be calculated yet when chunk is being sent to client/

Then there is the first light, calculated iirc somewhere around population time. This is another weird place. It can only be fully calculated when chunks in 2 chunks radius are loaded. And until then vanilla tries to relight these chunks every tick until it succeeds. Which would never happen for the edge chunks if vanilla didn't have a bug in enqeueRelightCheck (or queuedRelightCheck?) in Chunk, which causes it to load neighbor chunks after some time, spread over many ticks. And this is what allows light to be calculated near the edge chunks, making it possible to send them to client, leaving only one chunk border that isn't sent to client until enough surroundign chunks are generated.

The way vanilla handles sunlight updates for single block changes is confusing even to me and I just rewrote it from the scracth without even trying to understand what vanilla does (and ended up with code that is probably even more confusing and inefficient). But I know for sure that if enough neighbor chunks are loaded and the state was consistent to begin with before block update, it will always\* leave it in consistent state.

Another source of potential lighting glitches is how World.checkLightFor works (\* - this is the exception to leaving light cache in consistent state) - it tries to correct other light sources as it goes, but it also has a cutoff after 16 blocks. The first one is necessary for light updates to be fast when updating each block separately, and the second one is necessary for sunlight updates to work at all with the first one, and yet they are conflicking with each other. Future light updates on these additionally-updated light sources won't do anything (because checkLightFor doesn't see anything to update), leaving the border where that update cut off as is until some random change later causes it to update (this is fixable, but not easy, and it may or may not be faster).

In the end I don't think there is a viable way to get some big performance gains in MC lighting update code, maybe except just queueing checkLightFor updates and spreading them out over many ticks. Even doing many of them at once won't give big performance improvement because it updates other light sources as it goes. Updating multiple of them at once is almost definitely a good idea when this is going to be fixed, I already have code that can do many at once in my mod (and I was able to get it's performance for single block updates to almost the same as vanilla). 

If Forge could clean up the way lighting works that would be awesome news for me, but considering my lack of luck here, I don't think it will happen.

**Comment by PhiProven** [comment]
For experimantal purposes I have removed most of the unnecessary (at least I think it is) Vanilla code regarding skylight and instead let it call my custom version of the general light engine which is capable of doing light updates for multiple blocks at once.
With this, large structures can be placed much faster (placing a hollow 30x30x30 stone cube is more or less instant but takes several seconds for Vanilla). Also some serverside lighting bugs seem to be disappeared.
Unfortunately I couldn't yet fix some of the client side lighting bugs, but I'm working on that.

**Comment by PhiProven** [comment]
Apparently, some clientside lighting bugs arise from the fact that a large number of block updates is sent as `SPacketChunkData` instead of `SPacketBlockChange` (or `SPacketMultiBlockChange`). Single block changes (or more precisely up to 64) explicitly call `setBlock` on the client which then calls the relight code.If the whole chunk is sent, the blocks are wrtitten directly to the internal storage and no relighting occurs. Lighting updates don't mark a section as being modified.
Thus, if a large number of blocks is changed in a single tick, eg. via `fill`, then the lighting updates are neither sent to the client nor processed there.

What's the best way to go with this?
* Leave it as it is? (ie. desynchronized to the server)
* Marking sections as being modified for light changes? (probably results in higher use of bandwidth, though whole chunks shouldn't be sent that often)
* Doing a full relight on the client? (probably results in a bit higher CPU usage, but again, whole chunks shouldn't be sent that often)
* somehow tell the client to do the relights for the specific sections?

For testing purposes I'm currently just marking the section dirty. With this, my code seems to produce the right results (without some Vanilla lighting bugs) and to be much faster for spawning large structures

**Comment by Niko-sk2x** [comment]
I didn't think of making a platform when considering what could cause performance improvements. Right,  in this case it is much more efficient. And it may even cause some performance improvements for gvenerating trees (in vanilla that's about the only common structure that causes a lot of skylight updates).

**Comment by mezz** [comment]
About patches:
Replacing the full vanilla class and deleting all their code is not going to be accepted, it makes porting the changes more difficult.
However you can add little one-line hooks at the beginning of vanilla methods like this to hijack them:
`if (true) return net.minecraftforge.blah.myMethod();`
Even doing it this way, it may not be accepted if it's too invasive or the performance improvement is too small. Try to keep changes as limited as you can.

**Comment by williewillus** [comment]
Even then, I would be very wary. Patching in one line hooks then reimplementing the same logic elsewhere means that we aren't immediately aware if the vanilla function changed, and have old logic reimplemented

**Comment by PhiProven** [comment]
Some infos and questions on the current state of my implementation:
Worldgen performance is not affected, as more or less no light checks are performed during chunk population because the neighbor chunks are not loaded, as @Barteks2x pointed out.
However, spawning large structures after worldgen gets a lot faster (spawning a 30x30x30 hollow stone cube takes several seconds in Vanilla and is almost instant with my implementation). Furthermore, some Vanilla lighting gltiches are fixed, so I think it's worth considering, even though worldgen performance is not improved.
There are some Vanilla bugs that are harder to fix and I would like to hear your opninions on how to best resolve them (or if they should be fixed at all):
* Lighting glitches can occur at the boundary of the loaded area because light/darkness can't be spread to/from unloaded chunks. To ensure correct lighting, the chunk boundaries have to be rechecked whenever a chunk is loaded. Unfortunately, this is quite expensive and took for me ~1 min (32 chunk render distance). Spreading those checks out over several ticks will therefore probably take forever, so I wouldn't do that.
As these glitches only occur at the boundary of the loaded area, it's unnecessary to do the checks for all chunks, so a lot of computing time can be saved by flagging the necessary ones. Is there some way to store this flag? Can we just add an entry for that to the chunk NBTs? `Chunk.isLightPopulated` could be used as indicator, but resetting it to `false` after the chunk is populated could have some unforeseen sideefeccts, so I would prefer a new entry.
* When the whole chunk is resent to the client because of too many block updates (>64), light checks are not performed. This is notable if spawning large platforms in the air. Then the ground will only appear dark on the client after a world reload. Also when spawning a large cube of `sea_lantern`s  (or something else), the neighbor chunks won't get brighter on the client.
My best proposal to fix this is to relight the entire chunk (and its boundaries) if it is resent (but not if it is sent for the first time as this woud cause too much lag, as stated above).
Not performing the checks when the chunk is initially loaded leads to the same glitches as mentioned in the firs tpoint. Unfortunately, we cannot pass a flag in the `SPacketChunkData` so the solution of the first one will not work here. But I think we can leave this potential source of lighting glitches, as they are hopefully (...) rare.
* Sections that contain no blocks are not sent to the client, even if they have non trivial lighting. This causes some client side lighting glitches for things adjacent to those sections. Can we just send those to the client? Or would there be some problem with that?
* Lighting updates seem to be passed to the renderer very rarely by Vanilla. The lighting notifications are processed by `RenderGlobal.updateClouds()`, but only if `chunksToUpdate` is empty, which seems to be the case only rarely (I don't really know, what this field exectly does). This means that chunks won't be re-rendered only because of lighting changes; there has to be some other trigger.
This can be observed by placing light sources on the ground. (At east for me) the light will then often not spread accros chunk boundaries. You have to look straight up in the sky (or straight down to the ground), for the light notifications to be processed. The number of pending light notifications is listed in the debug screen as `L:`. Could this checks for `chunksToUpdate` being empty be removed?

What are your opinions/suggestions on those points?

**Comment by mezz** [comment]
You should keep your PRs as small, clean, and separated as you can. 
If you submit a giant change that fixes all of vanilla lighting, I will not be able to effectively review it.
Find one issue and target it, make a PR, and then move on to the next problem.
