### ISSUE TITLE
Not really documented anything

### ISSUE THREAD

**Issue by ReXtrem** [MinecraftForge/MinecraftForge#3892]
Not a real documentation. Everything has to be googled. Badest documentation ever faced...

**Comment by tterrag1098** [comment]
http://mcforge.rtfd.org

**Comment by williewillus** [comment]
> Badest documentation ever faced...

then help us fix it

**Comment by NoFuchsGavin** [comment]
Why should a guy who does not understand what the code does have to write documentation about it. Do you work like this? Anyone who writes an API has to document how to use it. Even more important is it for an open source. How do you think Apache or Spring got this big? By writing no documentation? Nobody will use an APi if they do not understand.... They will move on without it instead. And for a modding api modders like me or others will not continue due it's frustrating to search hours to find deprecated code examples from 2014., which are not working anymore.... So yeah every commit a develop does has to include updating the documentation as well, otherwise the documentation will never be up to date with the implementation...

**Comment by NoFuchsGavin** [comment]
It's not hate.... It's truth....
