### ISSUE TITLE
[Feature] Factory functions for tile entities and entities

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftForge/MinecraftForge#3902]
The current system relies on the presence of a specific constructor when deserializing an entity/tile entity. This is not very flexible, disallowing techniques such as partial application. I suggest the entity and tile entity registries should support factory functions similarly to how ParticleManager does.

As a bonus, the default factory function could cache the constructor and fail fast if it is missing or inaccessible.

I specifically suggest this because it is necessary for [dependency injection](http://stackoverflow.com/questions/130794/what-is-dependency-injection), something I use quite frequently.

I could make a PR for this, just making sure it is something that could be accepted.

**Comment by LexManos** [comment]
1) It's not needed for dependency injection depending on how you do it. That article is a bit off from the broad strokes of the idea
2) The entity registry does: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/registry/EntityEntry.java#L74
3) The TileEntity registry could potentially do something to support that, however, I'm of the opinion that ito shouldn't due to the massive paths the could cause issues due to the excess or lack of data. The current solution of creation and then reading data from NBT has to be done due to the fact that at creation time, the NBT isn't accessible in 1/2 the places. It's just something you got to deal with.

**Comment by JamiesWhiteShirt** [comment]
1. Indeed. I use dependency injection to ensure dependencies are satisfied, which is a little trickier without factories. Not impossible, of course. In most cases it can be achieved with subclasses. The true problem is that a tile entity registration requires a static entity. You cannot register new tile entities dynamically. Admittedly that might not be desirable since they are mapped by class.
2. Oops, shouldn't have looked at 1.10.2
3. I think most would agree that the factory should not be dealing with NBT in the first place for the reasons outlined. However, would you be opposed to let tile entities have something equivalent to `EntityEntry#newInstance(World)`?

**Comment by LexManos** [comment]
It would mean re-writing the TileEntity registry which is non-trivial. For what really is a no-benefit.
You can do what you're wanting to do without this.
