### ISSUE TITLE
GuiEditArrayEntries.addNewEntry doesn't support custom array entry class

### ISSUE THREAD

**Issue by copygirl** [MinecraftForge/MinecraftForge#3947]
Even though `GuiEditArrayEntries` supports custom entry classes [in its constructor](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/client/config/GuiEditArrayEntries.java#L69-L85), which I imagine would work for fixed sized arrays, [`addNewEntry`](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/client/config/GuiEditArrayEntries.java#L131) doesn't seem to support instantiating new custom entries.

**Comment by BlayTheNinth** [comment]
This was fixed in #3697, your links are going to an outdated repository (FML code is just inside the MinecraftForge one now).

There is still one other issue with the class in that it's doing an [incorrect call to .toString() in the constructor](https://github.com/MinecraftForge/MinecraftForge/blob/52409e15cfbc93ad7f201ed283ed3ea918cb18af/src/main/java/net/minecraftforge/fml/client/config/GuiEditArrayEntries.java#L80). I didn't get to PRing a fix for that one yet.

**Comment by copygirl** [comment]
Okay, that's what went wrong. I was doing a google search to find the class, made sure I'm on the right branch and saw "MinecraftForge" but didn't pay attention to the repository name.
