### ISSUE TITLE
DataSerializers.OPTIONAL_ITEM_STACK has wrong signature

### ISSUE THREAD

**Issue by dshadowwolf** [MinecraftForge/MinecraftForge#3980]
This might arise from vanilla code, but from its introduction through to 1.10.2, at least, net.minecraft.network.datasync.DataSerializers.OPTIONAL_ITEM_STACK has had a signature of "public DataSerializer<Optional<ItemStack>>" - when working on doing a proper port of BaseMetals to 1.11 (in preparation for it to move to 1.12) it was discovered that the signature is now, apparently, "public DataSerializer<ItemStack>" - while none of the other items that start with "OPTIONAL" and once were, in the past "DataSerializer<Optional<E>>" have had a similar change.

**Comment by williewillus** [comment]
Not sure what your paragraph is really talking about since the types don't match what you're saying, here's a more concise way to state the problem:

`OPTIONAL_ITEM_STACK` should be renamed to `ITEM_STACK` in 1.11 and above because stacks are no longer nullable.

which is an MCP problem and should be reported to https://github.com/ModCoderPack/MCPBot-Issues/issues, not forge

**Comment by dshadowwolf** [comment]
Ah, okay - makes sense.

Had not realized that ItemStack was no longer Nullable - and the name was the same, but changed from being Optional<> unlike the rest of the items still listed as Optional<>
