### ISSUE TITLE
Can't launch forge with mods installed [1.12]

### ISSUE THREAD

**Issue by stefan7080** [MinecraftForge/MinecraftForge#4072]
I can launch Forge without any mods, but as soon as I add a single mod it crashes at the initializing stage.
Tried some older versions as well but they all crashed: https://pastebin.com/iehDSGit

**Comment by supertassu** [comment]
Caught exception from Chest Transporter (chesttransporter)

Does it crash without chest transporter?

**Comment by stefan7080** [comment]
Yes it does

**Comment by stefan7080** [comment]
Then it says the issue is on More Furnaces side.
Also tried with just Chance Cubes and then blames that mod..

**Comment by marvin-roesch** [comment]
First, please refer to the [forums](http://minecraftforge.net) for tech support in the future. The mods you use were compiled with an older version of Forge. The registry rewrite introduced binary incompatible changes and mods need to update accordingly.

**Comment by stefan7080** [comment]
As I said. I used other versions of Forge and they didn't work either. I am posting this here because I think this is not on the mod authors their side

**Comment by marvin-roesch** [comment]
You'd have to use Forge version 14.21.0.2347 or below in the meantime until the mods update to 14.21.0.2348 or later, considering that's when the incompatible changes were introduced. It *is* neither Forge's nor the mods' fault, it's simply a binary incompatibility that is bound to happen this early in the development cycle. Since this is a user problem, you still should use the Forge forums in the future, since this repo is solely for developers and actual Forge bugs.

**Comment by stefan7080** [comment]
Why do the mods ask for version 59 or higher then?

**Comment by stefan7080** [comment]
forge-1.12-14.21.0.2359 that is

**Comment by stefan7080** [comment]
But fine I will make a post on the forum and wait ages for someone to reply

**Comment by marvin-roesch** [comment]
You probably have some mods that were updated to accomodate for the registry changes (JEI comes to mind) while others have not. Simply accept the fact that you have to wait for now until the 1.12 environment becomes more stable.

**Comment by stefan7080** [comment]
Oh okay then, thanks for helping me anyway. I will wait for mods to update ;)
