### ISSUE TITLE
[1.12] RegistryEvent.Register<EntityEntry>#getRegistry() cannot be used for mod entity registration

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#4096]
So, it seems we cannot use the `RegistryEvent.Register<EntityEntry>` event's getRegistry() to register the entities since that register() method only adds it to the ForgeRegistry but it doesnt create the `EntityRegistration` that is needed for mod entities.

To register an entity, we still need to call `EntityRegistry.registerModEntity()` to register our entity. While this works just fine, its a bit misleading since all the other event's work fine by registering things via `event.getRegistry().register(...)`.

I'm not sure if it is easily solvable with the current event system, but I'll leave that to more intelligent people than me :D

For now I'll just use the event but use EntityRegistry to register my entities.

**Comment by sokratis12GR** [comment]
Yes, I can confirm that right now the `event.getRegistry().register(...)` is registering the entity, but it doesn't register it in EntityRegistration, which makes it so you would need to register it via the old ways of registering the entity, because otherwise you wouldn't be able to use things such as `addSpawn`, `removeSpawn`, `addLootTable` and so on.

**Comment by LexManos** [comment]
Sadly, the EntityRegistry is only half the information that is needed for Entities, so yes you will need to register the other half of the information for entities to work.

**Comment by sokratis12GR** [comment]
The point is that you can't use the events right now, because it will only make the mobs register, in the game but not have the ability to be changed, i.e the entity will not be in the EntityRegistration which would make the usage of methods like these:
![image](https://user-images.githubusercontent.com/12274096/27767994-9be2ca9a-5f10-11e7-94b1-6d0458997b1a.png)
To not have any functionality/effect on the registered entity via the event.

**Comment by LexManos** [comment]
And whats stopping you from calling the non-registry register function from inside the register event?
Ya it can be looked into more tightly binding those two systems. As we control most of it. But ya. The old stuff should still exist. Just call it like you normally would, just in the event.

**Comment by bs2609** [comment]
Is #4408 a suitable solution (#4447 notwithstanding)?
