### ISSUE TITLE
[1.12] Could not find method log spam

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#4102]
Some example logs : https://pastebin.com/1swZWqfi
Using Forge : 2382 - Dev Environment

**Comment by HenryLoenwind** [comment]
1. For support, use the Forge forum
2. Are you under the impression that the same thing happens for everyone else? If not, did it occur to you that it might be a good idea to actually include information about wt... you're doing?

**Comment by SteveKunG** [comment]
Note : I'm not installed other mods while testing....

**Comment by GirafiStudios** [comment]
This happens on an clean 1.12 workspace with Forge 14.21.0.2382. No additional code running.
From what I can tell, it started happening in Forge 14.21.0.2381, because of this added line: https://github.com/MinecraftForge/MinecraftForge/commit/93025510aec90cb89c4bc24eb8759a4aa5f6e215#diff-0d5fbfe5a2d8cc695738c40565be525cR119

**Comment by LexManos** [comment]
Yes, Mezz screwed up, it is supposed to eat that error without message. He changed the for unknown reasons.

**Comment by KnightMiner** [comment]
Would it be worth switching it to debug, or is this error entirely useless?

**Comment by LexManos** [comment]
Its entirely useless it runs up the class tree to see if the method is an override, quite often it's not.
