### ISSUE TITLE
advancements: control advancement progress from code

### ISSUE THREAD

**Issue by AEnterprise** [MinecraftForge/MinecraftForge#4189]
Something that is missing in the current advancements system (that cannot be done in any way using just JSON) is having a progress on unlocking an advancement from a single criteria.

If you for instance have an advancement to place down every pipe that exists but addons could also add pipes you currently cannot make an advancement that includes the orignial set of pipes but also addon pipes. The addon could technically override the advancement on it's own but this then breaks again with 2 addons.

An alternative (might) be to still have seperate criteria for each of these but have an event where mods could attach extra criteria to existing advancements

Opening an issue instead of a PR for feedback first if this would even be accepted and what the prefered way of implementing this would be.

**Comment by JamiesWhiteShirt** [comment]
Not familiar with the advancements right now. Making a guess, though: Could #4182 be relevant here?

**Comment by AEnterprise** [comment]
could be relevant but that is about adding advancements at runtime, this would be adding criteria to already existing

and now i think of it: maybe also even adding rewards? especially for recipes it might be usefull for addons or such (or other mods that integrate with each other) to be able to hook into existing advancements and 'unlock' their recipes with others from a mod (for example an addon adding an electric engine could add that recipe as reward for the advancement that gives the recipe for the combustion engine)

**Comment by magneticflux-** [comment]
@AEnterprise Since the theoretical main pipe mod controls the API of the addons, couldn't it maintain a registry of all pipes? I doubt the addons would want to concern themselves with making sure the advancements of the main mod are correct. I think this theoretical example would also serve to prove why #4182 is needed, since it would not be possible without being able to generate the list at runtime after the addons have gone through registration.

**Comment by williewillus** [comment]
the `criteria` is just a field in `Advancement`. A stopgap would be to, after advancement are loaded (`ServerStartedEvent`?), reflect the field and set it to another map with new criteria. Same for `requirements` (which you can just mutate since it's an array)

Of course, a better way is probably desirable.

**Comment by AEnterprise** [comment]
yes the main mod would have a registry of all the pipes and could do this with a single criteria and requirement

what i would like to do is to be able to show progress on how many you placed and how many more you need without having to resort to hacks like reflection

another usecase (that might be even better) would be distance based advancements. For example another mod could an advacement for traveling 1000m with a modded vehicle. allowing to do that in a single trigger that then could report it's progress for in the advancement screen (like traveled 487/1000, placed 10/15 pipes, ...) would allow making advancements in a clean way that can report progress back to the user.
