### ISSUE TITLE
Add StepSoundEvent

### ISSUE THREAD

**Issue by thecodewarrior** [MinecraftForge/MinecraftForge#4209]
I think an event to allow modifying step sounds would be great. From what I can tell it'd just be a hook in `Entity.playStepSound` that would allow replacing or canceling the sound. The event could probably just be passed the entity and the pos "underneath" the entity. 

The specific use case is, in my case, a block that has a collision box 0 px thick at y=0 (it's a catwalk. It has sides and a floor, all 0 px thick.) The problem with this is that the step sound for the block _below_ the catwalk is used, or no sound if there's air below it. I had to hack around for probably two or three hours before I got a working solution, while a single hook could have solved it in five minutes. 

It would also allow custom "coverings" like snow. For example, someone could make a "dead leaves" block that would play a crunching sound when walked over, or quite easily make it so walking through reeds or some other plant plays a swishing sound. In addition, a sound could be played in the event itself, allowing step sounds to be stacked.

**Comment by williewillus** [comment]
You can already set custom step sounds using `Block.getSoundType`
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/block/Block.java.patch#L1376-L1387

**Comment by williewillus** [comment]
also, what do you mean by "0 px thick"? If all three of the dimensions you mentioned are "0 px thick" then your block just has no collision box, right?

**Comment by thecodewarrior** [comment]
I mean that the player's y value is at the bottom of the block. Minecraft checks the block 0.2 blocks below the player, so it checks the block below the catwalk.

```
 vv- player stands in here
|  |
|__|   __ player's y level
####
####
####
```

**Comment by thecodewarrior** [comment]
The 0px thick is on the Y. It's a plane at the very bottom of the block. Specifically so walking onto a catwalk you don't jump up in Y, you stay on the same plane.

**Comment by williewillus** [comment]
could you make use of `Block.onEntityWalk` in your scaffold block and play the sound there?

**Comment by thecodewarrior** [comment]
No, because that won't trigger. It triggers for the block 0.2 blocks below
the player. Also I wouldn't be able to stop the other block's sound.

**Comment by jabelar** [comment]
It seems that the root issue is really that thin blocks aren't handled properly. The event would still be a hack because you'd still have to check a bunch of stuff like whether there is a thin block above that should really be setting the sound type. It seems to be that a more "proper" fix would be to handle the case of thin blocks properly either by checking for thin bounding box, maybe by adding an isThin() method to Block and adjusting math accordingly where applicable. 

On the other hand, a SoundStepEvent is still useful.  I'm just pointing out that it isn't really a targeted way to solve the problem as stated.
