### ISSUE TITLE
[1.12] Controlling visibility of OBJBakedModel Groups

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#4226]
According to the OBJBakedModel code, it should be possible to hide certain groups in an OBJ model by defining a proper IModelState.

It seems, there are 2 options: 
* `OBJModel.OBJState`: this class is deprecated - but also doesnt work. `getQuads()` checks the blockstate for an AnimationProperty - if it has one, the state is wrapped in an `ModelStateComposition`. Because of this, the *instanceof* check in `buildQuads()` is always false: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/client/model/obj/OBJModel.java#L1342
* any other ModelState implementation: `buildQuads()` calls `IModelState.apply()` on the AnimationProperty modelstate with a new HiddenModelPart. The issue is, all IModelState/IModelPart implementations just check if that exact ModelPart is present. HiddenModelPart neither overrides equals() nor hashCode(), therefore it cant be present anywhere else.

The only workaround I was able to find, was implementing my own IModelState and set it as the AnimationProperty value. In `IModelState#apply()` I call `Models.getParts()` (not used by forge?) on the passed modelpart and check the name. This works fine.

If it is intended to create your own IModelState to handle obj group visibility, could we invert the logic in https://github.com/MinecraftForge/MinecraftForge/blame/1.12.x/src/main/java/net/minecraftforge/client/model/obj/OBJModel.java#L1338?
Currently, we need to return an `TRSRTransforms` instance to hide the group and Optional.Empty to show it. This is counter-intuitive.

**Comment by ShetiPhian** [comment]
Wouldn't have seen this post if the stale bot didn't draw attention to it.

I'm currently using a copy of OBJModel.java also with a single line changed.
Didn't create a pull request in 1.11 as it breaks expected behavior, and forgot about it when breaking changes where being accepted for 1.12.

In the buildQuads(IModelState) method I changed this:
```
if(modelState.apply(Optional.of(Models.getHiddenModelPart(ImmutableList.of(g.getName())))).isPresent())
{
    continue;
}
```

to this:
```
Optional<TRSRTransformation> transformation = modelState.apply(Optional.of(Models.getHiddenModelPart(ImmutableList.of(g.getName()))));
if(transformation.isPresent() && transformation.get() == TRSRTransformation.identity())
{
    continue;
}
```

<notes I made beside the change, likely to post with a pull request>
Items pass TRSRTransformation.identity when a part should not be rendered and the example code for hiding parts on a block instruct the usage of TRSRTransformation.identity but the old check only looked to see if a transform was applied, this blocked the ability to apply transforms to block parts you want to keep visible.
