### ISSUE TITLE
[1.12] Another strange Netty crash

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4285]
Similar to #4219, but not quite the same.

That issue (fixed by #4220) led to this exception:
```
java.lang.ClassCastException: Cannot cast net.minecraft.client.network.NetHandlerLoginClient to net.minecraft.client.network.NetHandlerPlayClient
```

This issue, as seen here (https://github.com/MinecraftForge/MinecraftForge/issues/4219#issuecomment-317061214), has a different exception:
```
java.lang.ClassCastException: net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$ServerHello cannot be cast to net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$ModList
```

I've just experienced this issue myself with a Forge dev environment, no mods installed (branched from build 2444).

Here's a copy of the [fml-junk-earlystartup.log](https://gist.github.com/bs2609/ed95784e887a777c1f484142fad63cb1) file (the error is [here](https://gist.github.com/bs2609/ed95784e887a777c1f484142fad63cb1#file-fml-junk-earlystartup-log-L3936-L4041))

**Comment by bs2609** [comment]
Also see this [forum thread](http://www.minecraftforge.net/forum/topic/59913-handshakemessagehandler-exception/).

**Comment by bs2609** [comment]
Update:

I was able to get the issue to consistently occur by inserting a delay before the return [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeServerState.java#L50).

@Barteks2x had a look at the issue - it appears to be a race condition caused by https://github.com/MinecraftForge/MinecraftForge/commit/3fee319bc0513bd06ce956019a15308fb829ce65, which means this probably does need a rethink.

**Comment by Niko-sk2x** [comment]
I want to explain what is the cause exactly, and get some feedback for submitting a PR, which fix would be better.

Before the commit https://github.com/MinecraftForge/MinecraftForge/commit/3fee319bc0513bd06ce956019a15308fb829ce65 `fireUserEventTriggered` was called from `handlerAdded`. The way before this commit made the old version work with a hack (that still had a different race condition, the hack should have been applied in `handlerAdded`). The change made it called directly from the server thread in `insertIntoChannel` instead of the server netty thread as `handlerAdded` did.

This means that the server can send a `ServerHello` packet to the client from`START` handshake state **from server thread**. And sometimes, before [this method](https://github.com/MinecraftForge/MinecraftForge/blob/1e85c6b2e8cbbc2265d2cdac2dfdfa892e6520e4/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeServerState.java#L44-L51) returns the server receives a reply from the client, which is going to be processed in netty server thread, regardless of whether the new state has been set. Then the `START` state sends the `ServerHello` packet again, but since client now has the next state and the code just happens to actually use the packet, it crashes.

So here are a few ways I came up to fix it:
 * Revert commit https://github.com/MinecraftForge/MinecraftForge/commit/3fee319bc0513bd06ce956019a15308fb829ce65 and move the reflection hack to `handlerAdded`. The downside is that it's a reflection hack, and work has been done already to make the new way work correctly. On the other hand this way (without the hack) has been tested over the years and is known to work reliably
 * Less of a hack but still not a very good way would be to set the state to `HELLO` [here](https://github.com/MinecraftForge/MinecraftForge/blob/1e85c6b2e8cbbc2265d2cdac2dfdfa892e6520e4/src/main/java/net/minecraftforge/fml/common/network/handshake/HandshakeMessageHandler.java#L63) before the method returns. This way by the time the packet is sent the new state will be already set. This should entirely fix the race condition, while keeping 2 threads involved. I didn't test this way yet
 * Add `instanceof ServerHello` check before [this](https://github.com/MinecraftForge/MinecraftForge/blob/1e85c6b2e8cbbc2265d2cdac2dfdfa892e6520e4/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeClientState.java#L99) line and if it succeeds, call the `HELLO` state accept, and return. The packet can't be just ignored because then the server `HELLO` state will never actually be called, the packet actually needs to be resent. I don't know if it causes any side effects but it seemed to work for me
 * Rework all the handshake state code to always set the new state before sending any packets. This effectively does the same thing as the second solution, but in potentially cleaner way. But it's also more work
 * Somehow schedule [this code](https://github.com/MinecraftForge/MinecraftForge/blob/1e85c6b2e8cbbc2265d2cdac2dfdfa892e6520e4/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L182-L186) to run in server netty thread but after `handlerAdded`?

Which one should I submit as a PR?

**Comment by Niko-sk2x** [comment]
I investigated it further, and it seems like `setAutoRead(false)` should make the issue go away, but I think I hit this issue there: https://github.com/netty/netty/issues/3633
