### ISSUE TITLE
1.12.1 Recipes using ore dictionary have a higher priority than custom ones 

### ISSUE THREAD

**Issue by Liahim85** [MinecraftForge/MinecraftForge#4415]
Recipes using ore dictionary have a higher priority than custom ones added via code, rather than through .json.
Example: You can not add a recipe using the four planks from the mod. Always at the output gives a crafting table.

**Comment by LexManos** [comment]
Recipes added via code have lower 'priority' then jsons due to registration order.
There is no priority system or sorting anymore. Stop using code recipes.

**Comment by Liahim85** [comment]
What about complex recipes?
Using NBT, etc?

**Comment by marvin-roesch** [comment]
You may specify your own recipe and ingredient factories to introduce custom recipe types that could handle NBT, for instance.

**Comment by Liahim85** [comment]
Excuse me.
I added a recipe using .json, but as a result I still get a crafting table.

How can I add my planks to the ore dictionary and at the same time use them in custom recipes?

**Comment by LexManos** [comment]
That might actually be something that we need to look into. As I said, there is no 'priority' system in recipes anymore due to their re-write. 
Their 'priority' is the order in which they are added.
I'll think about it, right now its a major issue due to the guidebook. We would have to write something that every time the recipes were reloaded it would check for conflicts and add in dummy recipes that didn't overlap.
Thats a major performance hit. I'll see what I can do, but no promises right now.

**Comment by Liahim85** [comment]
Thank you. Hopefully, this can be done.

**Comment by wjrogers** [comment]
I know this issue is somewhat stale, but as far as I can tell, the situation hasn't changed in the meantime. (I've been struggling to sort out conflicts between Natura and vanilla wood plank recipes -- trap doors, pressure plates, buttons, etc. -- in my modpack.)

Seems like the vast majority of use cases would be improved by making ore dictionary ingredients lower priority than specific itemstacks. You mentioned the current "priority" is simply the order the recipes were added. Does that mean there's a list of recipes that gets searched in order for a match? Is it naive to suggest that, when recipes are reloaded, you sort that list by number of recipe inputs that reference the ore dictionary? That would help a lot without requiring conflict detection or dummy recipes.
