### ISSUE TITLE
[1.11.2] Mipmap flickering issue

### ISSUE THREAD

**Issue by chaNcharge** [MinecraftForge/MinecraftForge#4475]
This is a weird issue and very hard to reproduce, but basically what happens is after a few minutes of gameplay, the mipmapped textures start flickering. For example, I set mipmap levels to 2, then I see the mipmaps function as normal. After a little bit, usually after searching something in JEI or traveling dimensions, they start flickering (for one second, it shows the mipmaps, the next second, its gone, and repeats itself every 0.5 seconds to a second) I cannot get any video footage as my computer cannot handle it, and there's a similar issue [here.](http://www.minecraftforge.net/forum/topic/26802-18-forge-flickering-treesglass-minecraft-18/)
Forge version: 1.11.2-13.20.1.2513

**Comment by mezz** [comment]
Thanks for the report!
I have seen this as well but never narrowed it down to find the cause.
It does not seem to happen with just Forge and Minecraft with no mods, so it is unlikely to be a Forge issue.
If you can replicate this problem with just Forge and no mods, we can continue here. Otherwise you should close this issue and go to the forge forums to try to figure it out.

**Comment by covers1624** [comment]
DE was known to cause this but i believe @brandon3055 fixed the issue if im not mistaken. Provided you have DE installed that is. Also this is probably best suited to a forum post instead of here as you have mods installed.

**Comment by chaNcharge** [comment]
Oh, there is a forum! Sorry, I'll post issues there next time, I didn't see it at first, sorry.
