### ISSUE TITLE
help wanted: Suggestion

### ISSUE THREAD

**Issue by lilgandhi1199** [MinecraftForge/MinecraftForge#4518]
**I wrote this code to solve a problem of finding out the current exhaustion level...** 
FoodStats shit = player.getFoodStats();
                  float count = 0.1F;
                  float total = 0.0F;
                  int prev = shit.getFoodLevel();
                  while (shit.getFoodLevel() == prev) {
                      shit.addExhaustion(count);
                      total += count;
                  }
                  //difex will equal how much exhaustion has raised since last tick
                  float exhaust = (float) (4.0 - total);
                  float difex = exhaust-exhaust2;
                  float exhaust2 = exhaust;
                  //returning it to value previous of the check
                  shit.setFoodLevel(prev);
                  shit.addExhaustion(exhaust); 

**exhaust = the current exhaustion level**
or you could just add this under FoodStats class within net.minecraft.util...
/**
     * Get the player's exhaustion level.
     */
    public float getExhaustionLevel()
    {
        return this.foodExhaustionLevel;
    }

**Comment by liach** [comment]
So you want forge to expose a field in `FoodStats`?

**Comment by lilgandhi1199** [comment]
I'm new to java. I think it's a variable though

**Comment by liach** [comment]
A variable in a class is a field. Correct.

**Comment by lilgandhi1199** [comment]
Ok, yes please.

**Comment by liach** [comment]
@mezz Can you tag this with `help wanted` first? I may work on it later when I have time.

**Comment by williewillus** [comment]
this isn't a bug
edit: if you want access just use an AT or reflect it

**Comment by lilgandhi1199** [comment]
I saw that suggested back in 2013....
Why do any methods exist if I can just reflect everything?

**Comment by lilgandhi1199** [comment]
@liach also it's not any work. Just gotta copy and paste it in with your next release

**Comment by williewillus** [comment]
here's the other side of the argument: should we add getters and setters to every private field everywhere?
patching them in is only done if it's an extremely common field in an extremely common object.

**Comment by lilgandhi1199** [comment]
what is the point in having the fields if we can't change them or even read them?

**Comment by williewillus** [comment]
which is exactly what AT's and reflectors are for.

**Comment by lilgandhi1199** [comment]
Forge by itself doesn't modify the function of minecraft so what value do you add besides the modification of minecraft functions?

**Comment by liach** [comment]
@lilgandhi1199 AT means access transformer, a concept related to java bytecode editing. It aims to change a private or protected field to a protected or public field, so that outside users or subclasses may use those fields.

**Comment by lilgandhi1199** [comment]
I'm not arguing that point...

**Comment by lilgandhi1199** [comment]
Why do I have forge installed if not for simple modification of core minecraft functions?
Edit: You just said it yourself. java, not forge

**Comment by liach** [comment]
Or you can look up Java Reflections on search engines and use it as a way to get the values.

**Comment by supertassu** [comment]
> Why do I have forge installed if not for simple modification of core minecraft functions?


This repository's description literally says it: 
"Modifications to the Minecraft base files to assist in compatibility between mods."

**Comment by lilgandhi1199** [comment]
yes and compatibility is built off the basis of them all accessing and setting values through the same medium. Which is what I'm asking for

**Comment by covers1624** [comment]
This has turned in to an argument of why java is the way java is and why forge does what it does, it should be moved to the forums.

**Comment by lilgandhi1199** [comment]
Copy and paste. That is all. Thank You

**Comment by LexManos** [comment]
Forge is run with VARY limited manpower, and EVERY change we do adds a lot more maintenance costs then you expect. This is just the nature of Minecraft and working in a decompiled world that changes every version. There are also almost 12,000 fields in Minecraft alone. Adding a getter this way for all of them would just be infeasible. For that reason it was decided to expose and encourage the use of simple built in java mechanics. There are many ways to go about doing this, it all has a cost tho. So you have to decide which is the best for the situation you are in. This is how programming works. But yes they are correct that this all should be on the forums instead of on here. 

If you guys decide that a few modders would like read only access to this field we can add it in. But it has to actually be thought out and requested properly. With understanding of the maintenance costs. Note: We are working on a new system that actually lowers the cost of Forge's patches so things may be able to be exposed easier. But that's still in the works. 

So please, do not come here bitching about why things are the way they are. When you freely admit you have no idea and have not tried to learn why the system works how it works. If you have a real request that has been thought out. Feel free to come back after discussing it with other mod devs on the forums.
