### ISSUE TITLE
[Request] Shear Event

### ISSUE THREAD

**Issue by primetoxinz** [MinecraftForge/MinecraftForge#4562]
It would be very useful to have a Shear Event to allow changing the results of shearing sheep and any other actions caused by right clicking shears (not sure if there are any).

If someone else were able to put a PR together for this what would be very helpful to me. Otherwise I will do it eventually.

**Comment by HenryLoenwind** [comment]
There are plenty, just look which classes implement IShearable.

BTW: It may be a good idea to fire the event from a default implementation of IShearable.onSheared() that relays to a new IShearable.onShearedImp(). Otherwise you'd need to fire the event from 13 different places.

BTW2: As the onSheared() does change the world, you may want to fire a cancelable Pre event and a non-cancelable Post event with the result list.

**Comment by LexManos** [comment]
Why no just use the item use event? I'm not a fan of making events for each item that is used.

**Comment by primetoxinz** [comment]
I want to be able to replace the wool items from sheep regardless if it was ItemShear, for instance if a machine sheared the sheep.

**Comment by mainrs** [comment]
@primetoxinz what are some machines that would be able to use sheers? I saw that XU2 has some kind of activator but I can't find any other block.

**Comment by Cyprex** [comment]
@SirWindfield anything that can automate right-clicking with a tool?

**Comment by Alpvax** [comment]
@Cyprex Wouldn't that also fire the item use event?

**Comment by mainrs** [comment]
Yep, it actually should fire it. Since most of those machines function like a pseudo player.
