### ISSUE TITLE
Exception loading model/blockstate

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4567]
Please have a look at the following issue:

https://github.com/APengu/SolarFluxReborn/issues/27

I'm trying to get rid of error messages in the fml-client-latest.log. The mod author says they are normal as he is not using models but rendering, so it seems there's a case where these error messages are unnecessary.

**Comment by SquidDev** [comment]
From what I can tell, the Solar Flux Reborn author is bypassing Minecraft's model system through use of a core mod. There isn't much Forge can do in this case.

**Comment by ghost** [comment]
Would you say the Solar Flux Reborn author should be able to prevent that error message somehow?

**Comment by canitzp** [comment]
He could simply add a empty json and there error should be away. I don't think that forge implements a method to disable this for special blocks/items

**Comment by LexManos** [comment]
We do not support or endorse people using coremods. Especially ones who have not even bothered to try and find a vanilla/forge solution.
He is responsible for any issues that arise not us.
There are solutions for him that does not involve coremods, and doesn't show this error. So talk to the author.

**Comment by ghost** [comment]
> Any software bloating the log file with untreated errors is bad software, no matter wether it's working or not.

> Forge does this too, if you hadn't noticed. Examples include Dangerous Alternate Prefix errors, which we can only mute on our end, and are 99% of the time false positives, 

> First of all, the forge devs know about it and have known for months now, and as it's not fixed they either care as much as we do or think it's working as intended

What are these "Dangerous Alternate Prefix errors", and why aren't they not fixed yet?

Discussion -> https://github.com/BetterWithMods/BetterWithMods/issues/669

**Comment by LexManos** [comment]
It’s a warning message when people create items/blocks that are not named for their mod. This IS a problem. Most modders screw this up which is why the warning is there.

**Comment by DaedalusGame** [comment]
unless there's a more obtuse method for aliasing, which is a forge feature for all registry impl now iirc, i'm pretty sure we're aware of what we're doing

**Comment by LexManos** [comment]
You are the 1% then I have contemplated making a secondary setRegistryNameAlias method that only logs a small warning. Because there should ALWAYS be a log when overriding other peoples things. But the fear is people who don’t know better will copy pasta that and break things even more. 

Another idea I had was to hold the stack in setRegName and then throw the error on registry.add if it isn’t a override. But that would cause multiple warnings for the same thing as the registry gets reloaded every world load/join. So that’s something to consider. 

There are some solutions that *may* work for people. But they need to be discussed and thought through. All the responses I’ve gotten however are “shut that shit off it’s crap and annoying!” And I’m sorry but that’s not a valid argument.

**Comment by ghost** [comment]
Isn't there any standard or codex within the Minecraft modding community to avoid such childish stuff?

I mean, it's like employers ensure quality: you stick to the codex or you don't, but you have to choose. People outside the codex won't get a job. There's a reason why successful people do it that way.

Do you have a codex? Reasonable rules the people can swear on?

**Comment by diesieben07** [comment]
The Minecraft modding community is largely made up of 10 year olds who either copy-paste code from some crappy YouTube tutorial (who's creator copied it from some text tutorial from 2012) or use things like MCreator. There is no reasonable way to ensure a standard. All you can do is print giant warnings if people do stupid shit. And regardless, people still do it and then people like you go to Forge to say to turn the warnings off.

**Comment by DaedalusGame** [comment]
First of all, successful people don't swear on the codex, these people are called employers.
Secondly, as I already said before, comparing Minecraft Modding to any kind of professional enviroment is a fallacy. There's no community guidelines and the moment there are, I'll probably hightail outta here because this community was built by people who specifically and deliberately broke the rules over and over again to build fun things to play with.

Also to put this back into perspective, we're here having this dumbass discussion because you complained about what amounts to essentially 12 lines of logspam *on startup*. It's not even ingame where there could be a danger of hitting the 1mil line log limit. And then you tried to reason that kind of pettiness with some false equivalence of product quality.

In closing, there's no problem with reporting actual structural issues that will cause problems down the line, or actual visual or gameplay bugs ingame if you find them. There is a problem with reporting issues like this, where there's absolutely no detriment to the player or packmaker experience by them.

**Comment by ghost** [comment]
> First of all, successful people don't swear on the codex, these people are called employers.

Those are the ones who make the standards. And because they can make standards and have people swear on them, they are successful.

> Secondly, as I already said before, comparing Minecraft Modding to any kind of professional enviroment is a fallacy.

No, a comparison can't be a fallacy, as it's a neutral act. The comparison shows that assuming the community is a professional environment is a fallacy. This doesn't mean there can't be professionals doing professional stuff as an example to the rest of the community. I'm talking to the forge devs here. I have the impression you want to have it at least semi-professional, building upon rationality and good arguments and so on, but you totally lack to be a good example. You even don't have standards, or if you have some, you don't tell them to the people. Instead, you fear the destructive power of the 10 year olds.

> There's no community guidelines and the moment there are, I'll probably hightail outta here because this community was built by people who specifically and deliberately broke the rules over and over again to build fun things to play with.

So you think there only can be fun if the rules are broken? I see it like this: Break the bad rules, so you can make new things, and keep the good rules, so you can make the good things you already have even better.

> And then you tried to reason that kind of pettiness with some false equivalence of product quality.

Me reporting an error that can be fixed within a few minutes is a pettiness, that's right. The dumbass discussion began when you were unwilling to fix it, and I still don't understand that. A solution was already posted. I assume it's a solution because it sounds legit.

The real problem here seems to be that you people are annoyed by each other and therefore want to have it bad. "No, I don't fix A because they don't fix B." That's so stupid.

> There is a problem with reporting issues like this, where there's absolutely no detriment to the player or packmaker experience by them.

There is a detriment, but you have to extrapolate into the future to see it.

Ignoring logged errors is an arbitrary decision about what is an error and what is not. Arbitrary because you can't distinguish between real errors and the other ones through obvious criteria. They are all called errors. People who don't know the arbitrary ruleset will report these errors, because they are called errors, leading to you ignoring it and justifying your ruleset again and again. Over time this leads to people thinking they can't rely on the logfile. Could be an error or not, who knows. Ignoring the errors becomes common, and this makes the overall quality of the mods worse over time.

On the other side, people like the forge devs fear that development, thus making the errors and warnings bigger and bigger. This annoys the ones who are ignoring them and makes them angrier over time.

None of the sides fixes the real issue. The real issue is the absence of common sense in the shape of good guidelines.

"Break the bad rules, so you can make new things, and keep the good rules, so you can make the good things you already have even better."

**Comment by DaedalusGame** [comment]
lmao

**Comment by covers1624** [comment]
This is minecraft modding not a fucking tripple A game, we do this for free and because we enjoy it. If you want standards you are looking in the wrong place.

**Comment by LexManos** [comment]
Alright enough of this stupid argument. We do have 'standards' that we try and push people to use. Proper registration, initialization and data structure. Which is why we have the warnings about improperly names entries, and missing json files. 
However you will NEVER change the mind of coremodders about what they think is right. So it's not worth it to try.
It has been told, and demonstrated that he can do what he wants without causing false log spam. but he does not want to try. So leave it at that.

As for the comparison between Minecraft Modding and 'successful companies', yes that is a false/unfair comparison. Diesieben is correct, that our community is mostly filled with amateurs, and people who honestly do not want to even try to learn how to do things correctly. There are however a few genuine people out there, who make great mods and help raise up the community and bring the platform forward. Daedalus is not one of those. There is no point in arguing with him. I would suggest avoiding his mod.
