### ISSUE TITLE
Coremod running on wrong minecraft version should crash the game instead of being ignored

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#4611]
Minecraft does crash when same happens for a normal mod. Why are coremods different there? If anything, not loading a coremod can only be worse. Forge has 3 possible ways to handle the situation:
 * Crash the game
 * Load the coremod anyway
 * Ignore the coremod

Crashing the game would make figuring out what is the issue very easy. It's not really that obvious from the log when someone has wrong MC version, and somehow the mod still loads but coremod doesn;t, leading to confusing crashes later on.

Loading it anyway would probably defeat the purpose of a version check there.

I also think there should be a way to bypass these version checks manually with a commandline option, but that is probably a separate issue.

This issue coupled with Minecraft not always quitting when it crashes, and the log not containing the actual crash log makes figuring out such user reported issues much harder than they should be.

**Comment by Niko-sk2x** [comment]
Why the "confused" and "thumbs down" reactions?

What is actually good about the current behavior? I haven't seen any instance where ignoring a coremod for wrong Minecraft version would be the right thing to do, and wouldn't make figuring out what is the issue harder.

**Comment by JamiesWhiteShirt** [comment]
I agree that the current behavior is weird, but I am not so sure about the suggested solution. In your case, does the issue stem from the strict Minecraft versioning of loading plugins? I've had issues with that, where people install a 1.12 version of a mod in 1.12.2, and the loading plugin fails silently.

What could be done is adding minecraft version range support for loading plugins and/or making mods explicitly depend on loading plugins so that the dependency can be unsatisfied and the dialog appears.

Implementing this would be a breaking change. I suspect there could be mods working around the strict versioning by bundling multiple loading plugins in order to support 1.12, 1.12.1 and 1.12.2 with the same build.

**Comment by liach** [comment]
@Barteks2x There exist cross-version coremods, such as one that works in both 1.9.4 and 1.10.2.

**Comment by Niko-sk2x** [comment]
@liach Yes but that can be done by marking one with actual supported version range. And one would still probably want it to crash when loaded, say, on 1.11.2 instead of failing silently. At the very least, it could first ignore it and then as early as possible in the loading screen, show an error message with an option to continue anyway or to quit (or just an error message just like with normal mod).

If someone doesn't want the version check, just don't specify version.

@JamiesWhiteShirt The "breaking change" part could be worked around as I said but actually including an error screen that allows the user to select "continue". I also don't see a clear way to have multiple IFMLLoadingPlugins in one jar, it would have to be done with dependency extraction.

**Comment by bogger33** [comment]
if you're gonna do an error screen with a continue button, why not do one that has a button for "delete mod" as well as "load mod anyway", the latter with a "remember my selection" setting, if you wanted to be real fancy about it.

**Comment by Niko-sk2x** [comment]
Well, I don't really have enough time to make the PR myself (I still have 3 PRs, with one being into forge, planned to do). So for now I will probably just remove version check from my coremod completely.
