### ISSUE TITLE
Redstone Flux Mod - Command line issues

### ISSUE THREAD

**Issue by WCJ277** [MinecraftForge/MinecraftForge#4625]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
im also told theres a way to solve it
    To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.
Only issue is i have no idea how to find the command line and it seems like no one else does either. I dont get why its saying anything about old APIs as ive installed the latest releases of RF, CoFHcore, Thermal foundation, and the other official thermal packs for minecraft 1.12.2

**Comment by KingLemming** [comment]
1) This isn't a Forge issue.
2) You need to find the mod which adds the outdated API. YES, you have one.
3) That command line argument should only be used if you absolutely know what you are doing. Since you don't know how to invoke it, that suggests that frankly, you do not.

Please pay attention to point 2. Figure out what mod is being bad, and remove it.
