### ISSUE TITLE
Blockstate "defaults" ignores rotation

### ISSUE THREAD

**Issue by fscan** [MinecraftForge/MinecraftForge#4650]
Since version 2576 forge ignores the rotation transform entry in the "defaults" block. Vanilla "y" is also ignored.
Our issue is with rotation, other transforms may be affected but i haven't checked.

Maybe related to https://github.com/MinecraftForge/MinecraftForge/commit/867698eb544666bb7f1f77c8a90ef9a49d337098 ?

**Comment by mezz** [comment]
@boq can you take a look?

**Comment by williewillus** [comment]
the linked commit only affects the animation system, it shouldn't have anything to do with normal transforms specification

**Comment by boq** [comment]
Probably related to other commit from that release, #4268.

Bit of guesswork suggests that you have noticed this issue on [this model](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/src/main/resources/assets/appliedenergistics2/blockstates/wireless_access_point.json). Since it uses a) submodels and b) rotation by 180, this seems like issue fixed by #4629, which causes transform to be applied twice.

**Comment by fscan** [comment]
Thanks, i'll test it when it's merged.

**Comment by fscan** [comment]
Thanks, it's fixed now.
