### ISSUE TITLE
Not supported,modified Version of Forge...

### ISSUE THREAD

**Issue by UnlegitUnicornZ** [MinecraftForge/MinecraftForge#4668]
When I open Forge: release.1.7.10-Forge10.13.4.1614-1.7.10
it is fine, mods are all loaded. But when I then open the Singleplayer (with mods, or without) it crashes and this pops up.
What can I do about this?
(I have tried to reinstall Forge 1.7.10 but it did not work)
![2018-01-08](https://user-images.githubusercontent.com/35235686/34687930-9f6b3518-f4b0-11e7-9af9-df13eedf24f2.png)

 :(

**Comment by diesieben07** [comment]
The error message simply means that you are using a modded version of Minecraft (because you have Forge installed), which is not supported _by Mojang_. However you are also using 1.7.10 which is ages old and longer supported. Stop using it.

Moreover this issue tracker is for actual issues with Forge, not tech support. Please use [the forums](http://www.minecraftforge.net/forum/).
