### ISSUE TITLE
add Hook for Fluids/Liquids mixing with blocks

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/MinecraftForge#4751]
Currently there is no hook for when a fluid mixes with another block that is not air, or another liquid.

Would it be possible to implement a hook in BlockLiquid#checkForMixing() and add a similar method to BlockFluidBase (or even better make BlockFluidBase extend BlockLiquid)?

I'd be willing to work out a patch, just asking beforehand if such a fix would be implemented or if there is another solution to that problem.

**Comment by jabelar** [comment]
There are already a couple PRs looking to address this. My fluid overhaul PR #4619 allows you to selectively indicate which fluids can mix with lava or mix with concrete powder. Another PR #4627 is creating an event to fire whenever a mixing causes a new block placed in the world.

Since you're interested in fluids, I would love if you could look at my PR and test it out.

**Comment by UpcraftLP** [comment]
Closing this issue since #4627 *should* have fixed this.
