### ISSUE TITLE
Proposal regarding 1.13

### ISSUE THREAD

**Issue by AllPermission** [MinecraftForge/MinecraftForge#4779]
After Minecraft 1.13, we should not update forge to any later versions. This may seem like a crazy idea, but it would solve many problems. First of all, it would allow modders to continue updating their mods, without having to worry about the next update breaking everything (cough cough 1.8). This would also be great for users as they could always use most mods that have been updated, without having to worry about some mods only releasing updates for the new version, and some still stuck on the old version. And also, the last update sucked ****, pretty much parrots. colored blocks, and some other stuff, not really anything to break all the mods about is it? Mods like Et Futurum have added some modern features to 1.7.10, and another mod added the elytra. If we don't update to the latest version, we will never again have to deal with versioning incompatibilities when Mojang releases a new version, and modders won't have to rewrite their mods because of them.

**Comment by ichttt** [comment]
I'm definitely against this. With every minecraft update, the internals of minecraft improve as well. Also this is currently the only time forge itself can make changes that break mods. On top of that, there are many mods that are client-side only and you can connect to vanilla servers with them. It makes a lot of sense always trying to stay on latest minecraft, even if it seems tedious. Believe it or not, but the 1.8 changes were a good thing performance-wise, and your opinion of the latest updates is you own, and not necessary that of others. You can stay on 1.7, but don't expect any support from forge or mod authors. Tl;Dr: I hope most people will agree that we should try to stay on latest minecraft whenever possible.

**Comment by HenryLoenwind** [comment]
9 people format their hard drives every 6 months without backing up their data---and like it.

It has been 2 full years now that I have spent the majority of my free time updating Ender IO to new Minecraft versions. I am tired. I have ideas for so much new stuff I want to implement, but as it looks now I won't get to them because 1.13 will be out before we manage to finish to 1.12 upgrade.

But all in all, this "issue" is in the completely wrong place. Try reddit or the forum. Or write a blog.

**Comment by DarkGuardsman** [comment]
I believe we need to keep updating with Minecraft. Keep in mind when I say this I'm a diehard 1.7.10 developer right now but even I know this is stupid. As new versions have massively improved the quality of life for making mods. This can be seen in state system, rendering, JSON, and capabilities. All which have been introduced due to an evolving environment and updates from MC.

Now that being said, if you want developers to worry less about updating. The real solution would be to build a strong API into forge or a forge mod layering over forge. Then building the mods for that API rather than MC or forge itself. As this will remove a majority of the work required by developers. 

Add to this much stronger documentation and a community willing to support developers. Then updating should not be an issue as much as it is currently. Since a developer could just lean on the community and its wonderful documentation to update their mods.

**Comment by ServantGirl** [comment]
I can see where you're coming from though, for sure. As a player its annoying when an update that- compared to some of the seasoned mods- adds very little and unexciting content, fragments the version stability of all the major mods. I've been there where I was like "Phhht well fuck... Id'd rather have this mod than that update..."  Which seems like a common case since there are offical tekkit packs over 2, 3 or more years old.

Thankfully the flexibility of Minecraft allows for such a thing~ So its a good compromise.

I do like improvements to api...  One thing I dislike is 'changing shit that isn't broken' like changing shit that is already simple and works perfectly -.-

As long as the version spread doesn't get TOO wide we should be able to tolerate transitions, though. And as they said, be rewarded for it with a more stable game.

**Comment by Zidane** [comment]
Anyone who champions "Just stop updating it, it'll be fine!" literally has no clue or does not care about the state of the game engine as a whole.

1.13, ignoring the aquatic stuff, is an update that is needed to ensure that Minecraft can actually continue as a whole just the same as 1.8 was or 1.6 was or 1.3 was...you name it. Software is an evolution, it is never finished but determined to be "good enough" or retired for something better. The current game engine of Vanilla has serious problems and while 1.13 doesn't fix all of them, it goes a hell of a ways to doing so.

I've never gotten the mod mentality of picking up their pitchforks and whining about how the update will break their mod and how Mojang shouldn't touch it and how everything is fine. Should we go back to pre 1.3 and enjoy client/server separation? No? Why is this any different? When you mod a commercial project out of your control, you accept that you either learn to work in lockstep with Mojang or stick to an old version and become a minority.

Its not like I am unsympathetic to the pain of a mod upgrade. I have a massive mod I do for a single server and a few side mods I help maintain and a monster of one that is SpongeForge that will cause us hundreds of hours to perform the update (perhaps thousands across the whole team). I get it and my team gets it but we bear it because the community needs Mojang to keep fixing the flaws with the base game engine else the game has no future.
