### ISSUE TITLE
Custom Fluids missing faces again

### ISSUE THREAD

**Issue by temp1011** [MinecraftForge/MinecraftForge#4799]
This seems similar to https://github.com/MinecraftForge/MinecraftForge/issues/1984. Examples in https://github.com/ForestryMC/ForestryMC/issues/2036. Only happens when fluids are same material so I don't know what should be rendered/what to fix.

**Comment by bs2609** [comment]
See `BlockFluidBase#shouldSideBeRendered`:
https://github.com/MinecraftForge/MinecraftForge/blob/4242f89c75d3d4a38737848a37383561eed8ec27/src/main/java/net/minecraftforge/fluids/BlockFluidBase.java#L449-L452

Could be fixed in #4763 if you can think of a 'correct' replacement - it should probably either change to comparing `Block` instances, or some other functions should switch to checking materials.

**Comment by HenryLoenwind** [comment]
When/if that PR gets pulled that adds all those properties to Material so any Material can mimic all aspects of water, this would automatically be solved by using a unique Material for each liquid.

With foresight into the fluid changes in 1.13, I'd recommend against changing this comparison.
