### ISSUE TITLE
Use an interface for unlocalized name methods

### ISSUE THREAD

**Issue by Terrails** [MinecraftForge/MinecraftForge#4844]
I think this would be really helpful to some people and myself since the registry system I use (before passing the IForgeRegistryEntry into the event) basically checks for unlocalized name of a IForgeRegistryEntry... there's a lot of instanceof and casting here since I need to get the unlocalized name and then set it again after I format it to my liking. It would also be good if Potion and Enchantment getName() methods were renamed to getUnlocalizedName(), also I noticed to Potion#getName is the only method that doesn't add a prefix to the name, so it makes sense to it gets changed to `"potion." + this.name`. It would be good if this was implemented in 1.13.

**Comment by williewillus** [comment]
> if Potion and Enchantment getName() methods were renamed to getUnlocalizedName()

use this repo to suggest name changes https://github.com/ModCoderPack/MCPBot-Issues/issues

> gets changed to "potion." + this.name

forge really isn't in the business of editing vanilla code for no reason. this would break all vanilla lang files everywhere, since many places in the vanilla code just call `translate(potion.getName())` directly.

as for the original problem, it's just a problem with java not having an open enough type system to implement interfaces/protocols/traits for foreign types. unless you switch languages, you'll probably have to just deal with it. Unless we add some unlocalized name methods to `IForgeRegistryEntry`, but not all entry types need unlocalized naming.

**Comment by Terrails** [comment]
Oh yeah I forgot about vanilla, but wouldn't something like this for an interface be enough?
`interface IUnlocalizedName<T extends IForgeRegistryEntry<T>>` Then it just gets implemented where its needed?

**Comment by LexManos** [comment]
>since the registry system I use (before passing the IForgeRegistryEntry into the event) basically checks for unlocalized name of a IForgeRegistryEntry

Why?
Also, every registry entry has a unique entry name. You can use that.

**Comment by Terrails** [comment]
I check if I added a modid to the name and add it if its needed, the same if I forgot "potion." in the potion name. I know I could make a "base" class but I thought this would probably do better.

**Comment by LexManos** [comment]
Ya that's your code style needing helper methods. We're not gunna impose things on others for that. You should sanitize your names when you create your instances not elseware.
