### ISSUE TITLE
Scripts problem client/server

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4867]
u see it all here https://github.com/CraftTweaker/CraftTweaker/issues/517

**Comment by mezz** [comment]
If I'm reading that right, Jared is saying that your script needs to also be on the client for it to work.
The fact that it is not synced from server to client any more is intended behavior by CraftTweaker and not a bug.
Include your script in your files distributed to clients and it should work. This is not a Forge issue.

**Comment by HenryLoenwind** [comment]
Background: As far as I understood it, craftTweaker had to drop runtime recipe manipulation because of the recipe changes and Forge not really allowing recipes to be added after startup. Syncing recipe changes at server connect is part of that.

Please understand that mod authors who had to change/drop a mod feature in a version update because of Forge/vanilla changes very often get bombarded with bug reports from players that want those features back. This leaves us quite salty at times.
