### ISSUE TITLE
Support for server-only entities

### ISSUE THREAD

**Issue by mkarneim** [MinecraftForge/MinecraftForge#4870]
I'd like to report that the support for server-only entities has been broken in Forge for Minecraft 1.12.

Yes, server-only entities have been supported in Forge for Minecraft 1.11 and 1.10 (and maybe earlier versions - but i haven't checked that), although I'm not sure if this support was there by intension.

Please note that this issue only affects players  _running Forge on their client_. 
Not affected are players _running vanilla clients_!

Players with Forge on their client get the following error message

    "Fatally missing registry entries"

(and are prevented from connecting to the server), when trying to connect to a modded server
that has a server-only mod installed, which has some "server-only" entities.

I already have [reported details about this issue at the Forge forum](http://www.minecraftforge.net/forum/topic/63883-fatally-missing-registry-entries/).
I understand that, according to @diesieben07, this was never supposed to work.

But I wonder if it would be possible to add this feature by intension, especially because it already works for vanilla clients, since vanilla clients just don't check for missing entity IDs during the connection handshake.

**Comment by mezz** [comment]
Sorry but I can't really think of a good reason to have server-only entities.
I looked through the thread and it sounds like you could use a tick handler and your own system for keeping track of what tasks to do at each location, without needing entities.

**Comment by mkarneim** [comment]
I am sorry too.
So it seems that having a mod out there that want's to add server-only entities is not a good reason for Forge, although is a modding framework.
This, and my discussion [here](http://www.minecraftforge.net/forum/topic/63883-fatally-missing-registry-entries/) and [here](https://github.com/wizards-of-lua/wizards-of-lua/issues/171) makes me really disappointed.

Just to be clear. I understand if you don't want to support stuff that is against your idea of this project. I myself do not accept every change request in my open source projects.

However, I always can show the point where the new feature breaks existing features, or where it will break future features. I would be perfectly fine with a decision like this if I just could understand it, you know, like a programmer can understand things if you point him to the fact that makes something a contradiction. But so far that's not the case.

In fact, I think I can see where the misunderstanding lies, and why you might not see why a "SpellEntity" is a entity at all. I tried to help to clarify this. But I wonder if you even read my description of what our "SpellEntity" is. I really gave a bunch of good reasons, but so far I got no specific reactions to these points. Not really helpful. I even pointed out that vanilla Minecraft clients have no problem with our server code, but nobody seems to be interested into this. Can you tell me, why vanilla clients have no problem with our code, but Forge clients should have?

I appreciate any hint that makes me understand this.
I'd even appreciate more an open discussion about this topic.

**Comment by mkarneim** [comment]
A solution for supporting server-only entities could be the following change:
1) Before sending the entity IDs to the client, the server could filter out those IDs 
a) that belong to mods that are not installed at the client AND 
b) that belong to mods that marked as server-only.
2) Currently we use the ```acceptableRemoteVersions="*"``` to mark out mod as server-only. Probably it makes sense to add a new annotation element that marks the mod explicitly as "server-only".

I guess the relevant class to implement 1) would be ```net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState```.

**Comment by raoulvdberge** [comment]
Do you have any other reason why you need this besides "it used to work"? I've read your forum post, and "server side only" entities aren't the way to go.

(Also, Forge shouldn't be changed just because you don't want to do a refactor.)

**Comment by Adrodoc** [comment]
@raoulvdberge We argue that it should work, because it works in vanilla. If a client does not have forge installed it works, as soon as the client installs forge it stops working. Why do you think `"server side only" entities aren't the way to go`? Just because it does not work currently or is there another reason why you think so?

**Comment by mkarneim** [comment]
> Do you have any other reason why you need this besides "it used to work"? I've read your forum post, and "server side only" entities aren't the way to go.

What kind of reason do you need? I have many reasons...

If you really want to read that much, here we go.
I'll try to write them down for you.

1) We started working on this mod 2 years ago. One year later we had a working prototype for MC 1.10. Then we decided to rewrite it from scratch in order to include automated tests in order to be able to upgrade our mod easily with every new version of MC and Forge without doing all that time-consuming manual testing. Also we upgraded the code for MC 1.11.2. We have finished this work just now, two years later. The last step was to upgrade to MC 1.12.2. Can you imagine how it is for us to work 2 years on a project like this, having done all right, I mean making a prototype and adding automated tests, just to find out that some not-backward-compatible change in forge prevents us from doing a proper release?

2) We are fine with refactoring our code for several reasons. This includes increasing the code quality, fixing errors (including errors in design), adding new features, and applying changes needed because of changes in the underlying frameworks and libraries. So it's not that we don't want to refactor our code (or that we couldn't do it - in the end we have a good test coverage that allows us to refactor our code all the time). We just don't want to do it just because someone says it to us without being fine with the reasoning.

3) You said ' "server side only" entities aren't the way to go', but you give no reason for it. I would really like to understand it. Why is it wrong? It would be far easier for both of us if I just could understand the reasoning behind it. I guess you have technical reasons, like feature-breaking things. Can't you just point me to them? You don't need to argue with me if I just could come to the same conclusion by looking at the facts. I am a professional software developer. I understand technical constraints when I see them. (I just wonder where they could be since our tests in two years with many alpha testers never showed any unexpected break down of the server nor the clients, nor any other unexpected behavior.) 
So you can see, I am not really fine with accepting some hidden reason, and I guess you aren't either. In my other life I am working at a research and development facility and I am used to comprehend reasoning rather to be confronted with some "higher" decision.

4) I have good reasons for wanting spells to be entities. I already listed them in this thread and at the other two places mentioned above. However, I can repeat some of them if you want - and add some more.
First of all, I want to talk about some game design reasons. We want to create a magical world that not only includes creatures but also wizards and spells. We think of a spell of some "entity" that is summoned / casted by some wizard using words, gestures, or magical items. When a spell is casted it exists right there where it was created. It normally has local effects only - like entities do. It has a position, it can move, it can follow players, it can analyze the block at it's position, it can replace it, and so on. A spell can "walk" though walls, but perhaps some wizard has a spell the can lock other spells down? We want to support all this.
Second, there are technical reasons. Since we subclassed Entity, a spell can do anything an entity can do. It can be a "CommandSender", for example, it can query other entities using a selector, including range criteria like "r" or "rm", which are interpreted relative to the querying entity. A spell has some attached AI, in our case that is the spell's source code, that defines how this spell behaves inside the word. This AI is executed step by step from the spell's update() method.
Third, we already have written some kind of API documentation that can be used by wizards that want to learn how to cast spells. There we tell them that a spell is just like any other entity in the world, and because of this, all functions that can be used on any entity can be used on a spell as well. Alone this fact is a good reason, at least in my understanding, to reflect that in code also. If you talk about it like that, it is obviously a good reason to also implement it like that. Since we "think" of a spell as an entity, extending the Entity class is just the natural way to do it.

5) Let me ask you the following: would you still say that extending "SpellEntity" from "Entity" is wrong if we had a client-side representation of it, for example, some particle cloud or some rendered model using Open GL? Or would you implement this a tick listener as well?
And what do you think would the guys from Mojang do when they decide to add a spell that has a position, belongs to a dimension, can move around, can interact with entities, and so on? Would they add something that simulates an entity? Or would they just subclass Entity?

6) Our mod is meant to be server-only, because we want to support as many Minecraft clients as possible. We do not want to force players to install a client-side mod just to play on a server "powered by the Wizards of Lua". 
We think it would be sad, if players using client-side forge mods would be excluded from connecting to servers running our mod. But with the current version of Forge for MC 1.12.2 it is like that. Forge players can't connect to our servers, BUT vanilla clients just can! 

7) We chose Forge instead of Bukkit because we wanted to enable server owners to install Wizards of Lua together with some other mod, like Thaumcraft or the like. If we didn't wanted that we also could have written a Bukkit plugin. But we explicitly decided that we wanted to add our mod to the Forge sphere. It would be just a shame - any very sad - if that decision would be what kills our mod because the Forge architects decide that server-only entities are a bad idea.

8) Bukkit supports server-only entities. Of course it is like that, since Bukkit is a server-side and server-only Minecraft server framework. So my question is: if Bukkit can support server-only entities, why should Forge not support it?

9) We were very happy that Forge added support for server-only mods some time ago, because that was what we needed to create our mod. We also checked (by writing a prototype) that our ideas were technically compatible with Forge. We checked that with Forge for MC 1.10 and 1.11. So we guess that the last change that broke the support for server-only entities just was done accidentally.

10) We have identified the code parts that are responsible for the non-backwards compatible change. I our opinion this change is technically a good one, since it did a great effort of refactoring the relevant code. But, we also think that it went one step too far by preventing to client to connect to a server just because some missing IDs. Just look at the code. The FMLHandshakeServerState sends all IDs to the client, even those IDs, that belong to mods that are not installed on the client. It is completely clear that these IDs would be unknown at the client side. Why sending them?
Why not excluding them? I am not talking about not sending IDs if it makes sense. Just don't send entity IDs from mods that are marked as server-only. It would require just a little if-else statement to support server-only entities. And there wouldn't be any bad side effect. It's no big effort. We think that this is another good reason for doing it.

11) Let me quote  @LexManos [talking about core mods]( http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/ ):
> Sadly core modding is still a thing. As always we request that you guys attempt to work with us to get changes into Forge instead of core modding it yourself. 

Well, this is what we are doing here. We think it is a good idea that Forge supports server-only mods, and that these mods are allowed to create server-only entities. If the members of the Forge team decide that they don't want to include it into Forge, than we can't do anything about it. What we did was asking you.
So maybe that means that we have to write a core mod for this little feature.

12) The motivation behind the Wizards of Lua is to give kids an environment where learning to code is fun for them AND makes sense. For the first part we think that Minecraft is the right thing. Almost all kids know Minecraft and like to play it. The second part is more difficult, since Kids are normally not "working", like in a job, so they don't need a computer to automate things they are doing. But if you look closer, you can find something that is like "work" for kids, which could be automated: doing things in Minecraft. I talk about creating big structures, and digging in the dirt to find ores, managing a farm, and so on. This can be automated by computer programs, hence it makes sense for kids to write some code that a) is fun to write and b) just saves them a bunch of minutes (or even hours) of stupid repeatable work. Just imaging a small program, which we call spell, since this sounds more kid-like, and effectively is really a good analogy, that consists of 3 for-loops that create a huge pyramid. The program is written in half an hour (or less), but it save you something like 2 hours per pyramid. This is what we want the kids to understand: programs are used to automate processes and to save time. And that it is fun to write that code. 
We think that having more kids in the world with a good knowledge of computer programming would be very helpful for societies the next couple of decades, since the digital change not only has great benefit but also some great danger. More people knowing what a computer can do (and can't), will be better in making the right choices.
Alright, this last point is not technical, it is just emotional. Maybe you want to support this, so I tell you.

Let me know if there is something unclear. I am happy to clarify it.
Of course I would be very happy if this effort in writing that all down would change how you think about this issue.

**Comment by raoulvdberge** [comment]
Let me respond.

1 - While I understand that putting lots of work in a mod and then having to refactor it all  is annoying, you just have to accept it. I had the same with my mod. In the end, I saw the fun in it. "It's a lot of work to refactor" isn't a good rationale for a change in Forge.

2 - Entities are meant to exist both on the client AND the server, and isn't an unreasonable assumption by Forge.

3 - See the reason above. (Also, your occupation isn't really relevant to this discussion.)

4 - What you are saying here is correct, it makes sense to have them as entities. But then accept the fact that entities have to exist on the client as well.

6 - That isn't a valid reason. You are developing a Forge mod. Forge mods that behave like you describe should be active on both client AND server. You can write server-side only Forge mods as well. But that doesn't fit your use case.

If you want that architecture, you need to accept the limitations of rewriting your spells to go in a tick handler.

8 - Because Forge is not Bukkit.

9 - Forge supports server side mods, and server side spells as well only if you rewrite them to be tick handlers instead of entities.

11 - This is EXACTLY what Lex hates. Mod authors threatening to write core mods if they don't get what they want.

12 - I get your point, but I don't see how it's relevant to this discussion.

**Comment by mkarneim** [comment]
What about 6)?

**Comment by raoulvdberge** [comment]
I adressed 6. You might have to refresh, I did an edit since Github was messing up the numbering.

**Comment by mkarneim** [comment]
So you voluntary don't want to support server-side entities?

**Comment by raoulvdberge** [comment]
Yes, because there is a better approach to your problem. Also, I'm not the one in charge of Forge, so I don't make any decisions. I'm just contributing to the discussion.

**Comment by mkarneim** [comment]
So I guess that - at least we two  - do not come to the same conclusion.

I can see that you say that server-only entities are not supported because you don't want to support it. That is completely fine for me.

Not wanting something is a valid reason.

Same for me.

**Comment by raoulvdberge** [comment]
We kind of come to the same solution - where - the entity approach is 100% correct for your use case. But, then you need to accept that those entities will be present on the client as well.

The part where we do not come to an agreement is your approach of supporting multiple versions by making your mod server side-only. If you *really* want to do that, then you need to use tick handlers and prevent creating synced objects like entities.

But maybe the Forge maintainers think differently about this. I'll leave it to them.

**Comment by mkarneim** [comment]
>  If you really want to do that, then you need to use tick handlers and prevent creating synced objects like entities.

This, for the first time, looks like a technical reason for me. If there is a constraint, I'll accept it.
Thank you.

Do I understand it right, that there is a syncing problem between server and client for entities with unknown IDs?
What are the effects? I couldn't see them in two years.

**Comment by bytemage** [comment]
When the client crashes in some cases maybe it's a good idea to make it more robust.
Especially when the vanilla client doesn't crash in the same cases.

The Spell entities were created with the framework provided by Forge and they did work well at the time. Now the Forge framework changes for different reasons and Spell entities become a problem. Claiming that Spell entities are bad and should be implemented differently is just lazy. It's was not the reason for the change, and shifting the responsibility is just the lazy way out.

A dev with some self-respect would aim to make the client as robust as possible anyway.

**Comment by mkarneim** [comment]
Just saw this now:

> 11 - This is EXACTLY what Lex hates. Mod authors threatening to write core mods if they don't get what they want.

Not my intension. Just did what Lex said and asked for it. 

Asking != threatening.

Just to be clear here, I only opened this ticket just because I read [his post](http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/). Because before I already had the impression that it possibly isn't worth the effort.

As of now, I think we will make our release with some ugly work-around, in order to get the mod out.
After this we will dig into the code and analyze what is the best solution, both, in terms of time and compatibility.

And well, If there is no other opinion from Forge members, I think you might as well close this issue.

PS: And btw, what is threatening in writing a core mod anyway?

**Comment by raoulvdberge** [comment]
@bytemage 

Your post would  be correct if it were a bug in Forge, but this is Forge crashing *deliberately* because the code is used in the wrong way.

A dev with some self respect ensures the approach and code is correct, and will make the framework crash when used incorrectly.

> Claiming that Spell entities are bad and should be implemented differently is just lazy.

I'm not claiming spell entities are bad. I'm claiming serverside only spell entities are bad.

**Comment by mkarneim** [comment]
> Do I understand it right, that there is a syncing problem between server and client for entities with unknown IDs?
What are the effects? I couldn't see them in two years.

Oh I forgot, if you have some knowledge about this, it would be really helpful if you'd share it.

**Comment by LexManos** [comment]
Server side entities have caused:
Rendering crashes when the client tries to update some generic entity data that relates to location/culling.
Client-Server desyncs such as missed block placements, or interactions due to the sever and client disagreeing on where blocks are places.
The client's ability to overstep protected areas and move into illegal spaces server side.
User experience issues such as the player will be suffocated/moved around by 'invisible' entities.
There are many many edge cases where having the client disagree with the server just screws things up. 

Yes, Bukkit gets away with 'server side only entities' because it really doesn't care what happens to the client, and doesn't have to deal with assumptions the client/mods make.
Just because it doesn't hard crash doesn't mean it isn't screwing up.
Vanilla will silently ignore the spawn packet of unknown entities in SOME cases. But if you do anything to update those entities it COULD cause crashes.
To do things properly we would have to write some complex system that introduced the ides of 'unsynced' entities. 
Find and intercept every location in the mess that is the MC codebase that deal with sending entity information to the client. 
Hope that mods don't interact with the server side entity in any way that needs something on the client.

Your 'solution' to flat out filter registry entries that are from 'server side' mods:
1) wouldn't work as there isn't a 1:1 ratio of registry entry to mod, and no way to generically know which is TRULY a server-side only thing, or just a screwed up mod/install.
2) Defeats the entire purpose of the Forge controlled registry system which is to make sure the client and server both know what is happening to the registry and can communicate in int ids.

>So maybe that means that we have to write a core mod for this little feature.

That IS threatening, and it's EXACTLY what I hate this shit.

Long story short, your hack to 'get all the benefits' of a Entity comes with all the downsides as well. If you're an Entity we treat you as a Entity and we do all the things on the client that needs to be done to prevent the vast amount of crashes/UX issues that could because by you screwing it up.

If you want to do it properly, make the entity a real entity and require a client side mod if the user has Forge installed.
You *can* hack around and hope vanilla client's don't crash, and they may very well not until the user gets into these edge cases. 
If you're exposing this stuff to users via LUA you're having to work with Obfusicated/SRG names which are completely user unfriendly, so you'd be better off writing some form of wrapper around any objects you expose to the LUA. 
Your 'benefit' of being able to call commands can work with anything that implements ICommandSender and provides proper location information. 
There are ways to do it right, hoping things don't screw up on the client.

**Comment by mkarneim** [comment]
Looks that I finally got some response that makes some technical statements.
> Server side entities have caused:
Rendering crashes when the client tries to update some generic entity data that relates to location/culling.
Client-Server desyncs such as missed block placements, or interactions due to the sever and client disagreeing on where blocks are places.
The client's ability to overstep protected areas and move into illegal spaces server side.
User experience issues such as the player will be suffocated/moved around by 'invisible' entities.
There are many many edge cases where having the client disagree with the server just screws things up.


I didn't know that. We haven't seen anything like this in two years.
But if that's really true we have to fix this.
Thank you for that.
I will look closer into it. Do you have some pointers into code? Some reproducers?

> Yes, Bukkit gets away with 'server side only entities' because it really doesn't care what happens to the client, and doesn't have to deal with assumptions the client/mods make.

That's interesting. I wonder how they get away with this.

>>So maybe that means that we have to write a core mod for this little feature.

> That IS threatening, and it's EXACTLY what I hate this shit.

No, it's not. Where would it affect you?

**Comment by jabelar** [comment]
Like most arguments, this is mostly one of semantics. The term "entity" is controversial because it already means something that is explicitly synced in the current system. Of course the term "entity" could be used more generically, but let's keep the term specific to the Minecraft concept.

The actual issue that is trying to be addressed here is that you're really asking for a tickable object that can be server-only but also has a sense of position and maybe some other entity-like things, but you don't want any client-side awareness for it, meaning it cannot have any user interaction including visual, audio, or clicking on. To be honest, that is sort of a limited use case, but I can understand it having some use.

But do we really need a Forge hook for this. There is already a server tick and world tick event. So you could create your own collection / registry of a tickable class and then just tick them yourself.

So I understand why you might want something like this, but not clear to me that it is worthy of a Forge interface. If there were lots of mods that for some reason were limited by the current tick handling hooks, then maybe.

**Comment by mkarneim** [comment]
Alright, we will try to migrate our mod to use the tick handler.
I'll give feedback about how that went.

However, I still think it's kind of strange that vanilla clients can connect to our server while forge clients can't. I guess if you wan't it to be more "secure" in the sense that you want to prevent all that scary stuff that LexManos talked about, you might want to do the checking server-side so that vanilla clients do also profit from it.
