### ISSUE TITLE
Ender Dragon's XP drop doesn't trigger LivingExperienceDropEvent

### ISSUE THREAD

**Issue by Insane96** [MinecraftForge/MinecraftForge#4910]
I have this code
```
if (!(event.getEntityLiving() instanceof EntityDragon))
	return;

System.out.println("EnderDragon Dropping XP");
```

In a LivingExperienceDropEvent. The event doesn't trigger when the dragon drops XP

**Comment by Eragonn1490** [comment]
I’m not an expert. But how I read this was..

If it’s not an instance of entity enderdragon print that.. unless I’m reading it wrong.

**Comment by TehNut** [comment]
You read that backwards. 

Are you sure the dragon itself drops the experience? I haven't looked, but I believe the experience is dropped after the fact when the structure is generated.

**Comment by LatvianModder** [comment]
There is a special dragon fight class that manages everything, it probably drops it. It also doesn't drop like from normal entities, it rains for a bit

**Comment by LexManos** [comment]
Yes, he is correct, the Ender dragon specifically overrides it's death handler to do the special death animation. Along with the fight manage handeling it.
Could of sworn this was all controlled by the fight manager.
However, this isn't as simple as just throwing the event into EntityDragon.dropExperiance. As that wouldn't provide very much control.
The TOTAL experience is unknown as it spreads the exp out over ticks.
We can do some basic math, it does it every 5 ticks from >150 until tick 200. So, (49/5)*x*0.08 + x*0.2F.
I SUSPECT that it only doing it 9 times instead of 10 is a bug. As that would make sense (10*.08+.2==1)

Then again I could be reading this all wrong. One idea would be to create a new field to store/calculate the total exp only on the first deathTick.
Needs some thought. What do you guys think?

**Comment by williewillus** [comment]
this might not be as flexible as people want, but maybe just go for simple: just fire the event once for each "batch" of XP it spawns? the value is known for each batch in this case

**Comment by Insane96** [comment]
There's still no way to hook XP dropped by Ender Dragon as of Forge 1.12.2-14.23.4.2705
