### ISSUE TITLE
World-default fluids are not stitched, cause pb textures

### ISSUE THREAD

**Issue by DaedalusGame** [MinecraftForge/MinecraftForge#4929]
Worlds can have default fluids that are swapped into the registry instead of the global default when a world is loaded, but only the global default fluid is actually stitched into the atlas. This leads to a load-order issue where dependent on mod setup worlds can have fluids with missing textures.
somehow I forgot to report this when I discovered it months ago.

**Comment by KingLemming** [comment]
This should only be the case if mods are being stupid and not properly registering their fluids and associated resources.

**Comment by HenryLoenwind** [comment]
King, I remember seeing your fluids at least once with missing textures when fine-tuning our compatibility...

**Comment by KingLemming** [comment]
Sure about that? My textures get registered no matter what. If you can provide something reproducible, please do. Otherwise that smacks of hearsay nonsense.

**Comment by DaedalusGame** [comment]
Wrong, this happens with ALL fluid registrations. Unless you want to declare that literally all mods are doing it wrong. Thermal Foundation doesn't have the issue because you're stitching the fluid textures yourself, which is certainly *not* the proper way. It's just a workaround to the above issue. So in other words, you think this isn't an issue because you already worked around it.

**Comment by KingLemming** [comment]
Actually no, there isn't any logic where fluids automatically have their textures stitched. If mods aren't stitching the textures, they are in fact doing it wrong, yes.

Mods have had to stitch their fluid textures since 1.6. This hasn't changed. The issue you are seeing here is if a mod determines that they are not the "canonical" fluid and then skips registering their textures, which is all kinds of incorrect.

**Comment by KnightMiner** [comment]
The thing is, mods don't need to register their textures. If a mod registers a fluid which does not conflict, they never have to see the texture stitch event at all, Forge registers it all for them. Sure, you could [manually register your textures](https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/init/TFTextures.java), but the fact that it works if you don't as long as there are not conflicting names says something is done wrong in Forge. Either Forge needs to never register the fluid textures or always do it (and honestly, every other resource in Forge or vanilla Minecraft that uses textures automatically registers them, so why should the fluid registry be inconsistent?).

**Comment by KingLemming** [comment]
That's not my experience actually - without explicit registration, they don't show. There are no naming conflicts. Again, it's been that way since 1.6 and I can find nowhere in the Forge code where any fluid resource locations are stitched by default.

Let me be clear here - Fluid, and not Fluid Block. Blocks which have associated textures get stitched, because that's the Block. I'm talking about Fluids. Here's what happens if I comment out my texture code:
![2018-05-15 11_43_20-minecraft 1 12 2](https://user-images.githubusercontent.com/2118598/40067871-3284b044-5835-11e8-99d7-1509a62ef454.png)

Some buckets have textures - those fluids have blocks associated. The others do not.

**Comment by LexManos** [comment]
> Forge registers it all for them.

Where? From my understanding, and from the words of the Guy who wrote it {See above} Fluids that do not have associated Blocks/Items do not get stitched. Because only Blocks and Items get stitched. I don't recall anywhere that extends the stitcher system to fluid textures. 
If you think it is a bug in Forge, then write a PR.

**Comment by bs2609** [comment]
I think people are referring to things like this: https://github.com/MinecraftForge/MinecraftForge/pull/4070

**Comment by LexManos** [comment]
Has nothing to do with Fluids.

**Comment by KingLemming** [comment]
Given that things are now registered in a specific, known, time frame, it's reasonable to have a PR that will automatically register these textures for Fluids.

My issue with this issue is that it's an inaccurate description of what may be considered the root cause.

**Comment by MajorTuvok** [comment]
This issue should still be relevant - as to my knowledge there haven't been any changes regarding this yet.

**Comment by LexManos** [comment]
As it sits, it's not a issue. As it's behaving as intended, as described by the guy who write it. 
That being stated if you wish to submit a PR to spec out how to define the proper textures and auto-stitch them then we can look at it.

**Comment by KingLemming** [comment]
It's behaving as coded, anyways. It's something we can look into for 1.13.
