### ISSUE TITLE
Dynamic bucket does not use FluidStack-sensitive fluid.getColor().

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4948]
This prevents the enabling of the Forge Universal Bucket for fluids which rely on said sensitivity, such as fluids with NBT data that determines color.

**Comment by bs2609** [comment]
As far as I can see, there's two things required here:

* Adding tint layer support to the bucket model.
* Changing the universal bucket to use this with the `FluidStack`-sensitive colour getter.

The first change is fairly easy to do without issues.

The issue is that making the second change "correctly" will require changes to any other mod which uses the dynamic bucket model, or else they'll break.

This is because you want to use an `IItemColor` handler to have the appropriate context. Adding this to the general bucket requires removing the colour tint from the model, otherwise it'll be applied twice. However removing the tint from the model requires the other items using the model to have their own `IItemColor` handlers, or else the colour tint won't be applied at all.

The fluid block model also has a similar issue to this second point (it already supports tint layers since #3938). However, in this case it's less of an issue as there's a separate `Block` instance for each fluid there, allowing for different `IBlockColor` implementations. Mods which need this can register an `IBlockColor` handler for their specific fluid block and can have the base `Fluid.getColor` return no tint (white) to prevent the double-application issue. This saves mods which don't need the special handling from having to register an `IBlockColor` handler.

In the case of the Forge bucket, there's only a single item involved, so it can only have one `IItemColor` handler.

**Comment by asiekierka** [comment]
>However removing the tint from the model requires the other items using the model to have their own IItemColor handlers, or else the colour tint won't be applied at all.

The way it currently works is that a Map<String, IBakedModel> cache maps Fluid objects to their IBakedModels, and the tint is applied during the baking process. The new way would involve applying the tint with IItemColor based on the stack-specific coloring.

There's two ways to do it in a non-backwards-compatibility breaking manner:

* (ugly) Add the color to the model cache's unique key, and make the HashMap a Guava cache. This will, however, not scale favorably memory-wise. I propose another solution:
* Add a version marker of some kind (say, a new method) to the ModelDynBucket class, defaulting to old behaviour (for mods using the class on their own) but toggleable to new behaviour (for the Forge's own universal bucket). The new behaviour simply prevents assignment of the tint on the model's texture, paving way for an IItemColor to be used. Then, deprecate said method for 1.13+, where only the "new" behaviour would be used.

**Comment by bs2609** [comment]
I had my own idea, which you'll be able to see in a minute (when I finish writing it up).
