### ISSUE TITLE
Allow users to bypass checksum discrepancy test

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4998]
Minecraft version: 1.12.2

I installed minecraft forge, everything works fine, but I hate the copyright text that appears on title screen saying "Copyright Mojang do not distribute", so I edited `.minecraft/versions/1.12.2/1.12.2.jar/blr.class` file in order to remove such string. I also deleted manifest directory and everything works properly with vanila minecraft (the string is successfully removed), but when i enable minecraft forge, I get error

```
There is a binary discrepancy between the expected input class blr (blr) and the actual
class. Checksum on disk is 105c8dfe, in patch 37509bef. Things are probably about to go very
wrong. Did you put something into the jar file?
```

I know exactly what I am doing, please is there a way to disable such check and simply load minecraft normally?

**Comment by mezz** [comment]
Set the system property `fml.ignorePatchDiscrepancies` to `true` to bypass the check.
You'll still get the log but it will try to run the game. There may be other errors but you're on your own there, what you're trying to do is not really standard or even reasonable sounding...

**Comment by ghost** [comment]
@mezz 

Where to set `fml.ignorePatchDiscrepancies` to true? I'm not developing a mod. Do I need to pass it as command line argument to minecraft launcher, or where I am supposed to configure that property? Thanks.

**Comment by mezz** [comment]
I think what you are trying to do is a very bad idea and I'm not really willing to help you more with this, sorry. Please look for help somewhere else.

**Comment by ghost** [comment]
> look for help somewhere else

ok, I don't even know why I asked it here. I should have realized so far that people who develop proprietary software or who develop mods for proprietary software (or games) think that users are idiots. In my opinion, if user is modifying jar file or any binary file, he knows exactly what he is doing, I really don't see any purpose for checksum, it doesn't make sense at all.

**Comment by trvsapjiac** [comment]
Nevermind, I found solution myself.

**For anyone who is facing the same problem:**

The solution is to write the following string in JVM arguments in the minecraft launcher:

```
-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true
```

then it works properly.

**Comment by LexManos** [comment]
Your use case is assine, and screw you for trying to remove credit to those who have spent countless hours to create the system you enjoy. You will find no help here. and again a giant screw you for trying to remove credit to the authors of this software.

**Comment by trvsapjiac** [comment]
@LexManos 

Wow, I am surprised. Your vocabulary ("screw you") is so non-professional and childish that I am really surprised why do you consider yourself a serious developer or member of some team here. I'm not going to report you, but I hope you realize that, when you grow up, you will need to reconsider your tone when you speak to people.

Also, deleting comments is not nice. What are you trying to achieve?

But anyway let me respond to your nonsense in your last comment.

> Your use case is assine

I have no idea what "assine" mean. What are you trying to say is not clear to me.

> and screw you for trying to remove credit to those who have spent countless hours to create the system you enjoy

Not everyone agree with copyright laws. There are some people who think that copyright is nonsense. I am one of them. Basically, only physical object can be sold (house, vehicle, house gadgets, etc). But, information cannot be sold. It means books, songs, videos, games, softwares, etc are free by default, independent of the choice of the author. Therefore, "stealing" such goods are not against my moral laws, and I will keep doing it. But, since the copyright is nonsense, I don't want to see copyright notification in the pirated softwares (games) I'm using.

They spent countless hours, that's true. And they spent those countless hours developing something I enjoy, that's also true. But, that is still not a reason for me to respect them. I will keep "stealing" their software and sharing for free, as long as their software is protected by copyright laws.

> You will find no help here

I realized it. But I found help myself and I want to share for other people who may face the same problem. Don't delete my comment. In my comment, I explained how to do it for other people who may have the same problem in the future. There is no reason to delete my comment, it doesn't violate Github terms of use and didn't break any copyright laws. I didn't share serial keys, or cracked minecraft launcher, or premium email and password, etc. I just shared a simple command line arguments. And I'll repeat it here.

Basically, the solution is to put the following string in your JVM argument in the minecraft launcher (any patched launcher from the pirate bay works fine):

```
-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true
```

Then launch minecraft and no it should work even if you modify the `blr.class` file (don't forget to delete meta inf forlder).

> and again a giant screw you for trying to remove credit to the authors of this software.

Why so many anger? How much did Notch paid you to talk like that?

---

## Some additional info for future visitors who may face the same problem

If you don't like the copyright norification, then follow these steps in order to remove it:

1. Extract `blr.class` from `1.12.2.jar` (using winrar for example)
2. Open it using some hex editor (I would recomment HxD, it is free)
3. Find string `do not distribute`
4. Replace the whole copyright message with bytes 0x20 (it represents ascii space)
5. Save the file
6. Put the file back to `1.12.2.jar`
7. Delete META-INF folder from `1.12.2.jar`
8. In JVM arguments put `-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true`
9. No copyright message will appear. Enjoy your pirated and free software, don't let them convince you that you need to pay before you can play

**Comment by UpcraftLP** [comment]
@trvsapjiac what's your MC username btw?

**Comment by MajorTuvok** [comment]
Honestly, Lex has all aright to be angry at you... Why the hell do you want to take those credits away from hard working people solely because it doesn't look like you want it to?!? That is childish on my opinion!!!
@Lex I'd recommend closing this Thread to further replies before anyone starts yelling at each other even more than before...

**Comment by ghost** [comment]
I agree with you Major Tuvok that there is no need for further discussion here. I just tried to explain my ideas as simply as possible, if someone still disagrees, that's fine. People are different.

I'm hereby closing further discussion, as long as nobody deletes my comments. But if you delete my comments, be sure that I will not remain quiet. Leave my comments here and don't worry about this thread going out of control. This is my last comment, I already said everything I had to say. After all, you have freedom to think whatever you want, but be aware that some people think differently.

**Comment by mezz** [comment]
This is an issue tracker for bugs in Forge, an open source project.
This is not a place for tech support, and it's definitely not an open forum for pushing your personal agenda and threats. I'm deleting your long comment promoting piracy, take it somewhere else.
