### ISSUE TITLE
Considering using jcenter mirror instead of hosting in MinecraftForge

### ISSUE THREAD

**Issue by LasmGratel** [MinecraftForge/MinecraftForge#5044]
A huge amount of players reported that they cannot download libraries at full speed (usually 10KB/s), and that was extremely annoying.
I found that in <version>,json the maven repository url is manual specified, so how about changing them into jcenter(jcenter.bintray.com) and reduce hosting resources in that way?

For instance,
```
{
	"name": "com.typesafe.akka:akka-actor_2.11:2.3.3",
	"url": "http://files.minecraftforge.net/maven/",
	"checksums": [
		"ed62e9fc709ca0f2ff1a3220daa8b70a2870078e",
		"25a86ccfdb6f6dfe08971f4825d0a01be83a6f2e"
	],
	"serverreq": true,
	"clientreq": true
}
```
Simply change (I know it was auto-generated) `"url": "http://files.minecraftforge.net/maven/"` to `"url": "https://jcenter.bintray.com/"`

**Comment by diesieben07** [comment]
The Forge repo is used for good reason. We cannot expect jcenter or maven central, etc. to take the huge traffic that is caused by Forge installations without complaining.

**Comment by LexManos** [comment]
We're talking terabytes a day. Not to mention the protection against Mojang screwing up the launcher again. We take the hit because we can.
I'm also not sure what users you're getting that are saying they are getting 10KB/s. Out metrics show the average user download to be more along the lines of 1.6MB/s.
However, if others in the community wish, they can become mirriors in a few ways.
If you are making a modpack, Include the libraries, simple as that.
If you're a server host, All I need is a flat folder with FTP access. Maven servers are a flat file system so they don't require any external software to manage. I just request the FTP account so I can manage the files myself.
The installer has had support for mirriors for libraries for quite some time. It's just nobody has stepped up to provide any. And the ones that have have ran away when even 10% of Forge's traffic hit their servers.

**Comment by liach** [comment]
`10KB/s` is the download speed people get in China. Even if they use VPN, the network is not significantly faster.
