### ISSUE TITLE
Replace the config folder with data packs

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5062]
As stated above, my idea is simply to stop using the config folder in favor of the newly introduced datapacks.
The config files would be placed in data/modid/config to better organize them, or in data/forge/config to have essentially the same behavior as before.

**Comment by LatvianModder** [comment]
Im for `data/modid/config`. All mod related stuff should go in its own folder, not forge's imo

**Comment by KingLemming** [comment]
I approve of this.

**Comment by diesieben07** [comment]
This was discussed during FAP 2018 and a layered (global, per world, etc.) config system based on TOML is going to happen. But I cannot find the markdown file that was used during the recording.

**Comment by liach** [comment]
hmm, some config changes break registries (enabling blocks, items, entities, etc) However, I believe we should keep config minimal and only keep for this case

**Comment by williewillus** [comment]
> hmm, some config changes break registries

how's that prevent this from happening? just parse configs before registering things and it should work the same as before

anyways, what was the rationale for choosing TOML? Not particularly against the format, but want to know what the reasons are.

**Comment by liach** [comment]
@williewillus What I mean is that on the client side, when the game is in main menu, the registries are already ready (blocks, items, etc.); however, if a world has a custom data pack, the mod needs to disable/enable certain blocks or items that are differently configured in the default data pack. Will we do such reloading of registries every time we enter a world like this?

**Comment by ghost** [comment]
Yeah, i didn’t think of that.
But why did you choose TOML instead of JSON?

**Comment by Daomephsta** [comment]
@SonicLC The main reason for not using JSON, as far as I'm aware, is that it doesn't natively support comments.

**Comment by ghost** [comment]
Oh right

**Comment by vico93** [comment]
But will Forge enforce the use of TOML for configs or the mod dev could choose to make his configs JSON-based?
The problem with TOML IMO is it will sighly difficult modpackers work because its yet another standard to use (but honestly its better than "what the format? MS INI?" currently used for most configs.

**Comment by Daomephsta** [comment]
@vpontin TOML configs would be replacing the current Forge config format, they're wouldn't be an additional option. They should actually ease pack development as you'll be able to validate configs. 
There's never been anything stopping mod devs from using whatever config format they want, all Forge does is provide an option that should serve most mod dev's purposes, since configs are widely used.

Also, if I recall correctly, the Forge devs plan to talk to some pack devs and users about TOML before they make it the Forge config format.

**Comment by quat1024** [comment]
As much as I love this idea (and love the idea of Forge & mods embracing data packs as much as possible), like people said above with config values that affect registries, it doesn't work very well with config values that require the world or game to be restarted, right? Data packs are `/reload`able at any time; not all config values are.

**Comment by williewillus** [comment]
@quat1024 to that I raise the point that it's no \*worse\* than the existing solution - the value is changed, but the effects don't apply til a restart

also, most options that need restarting have to do with registry entries, so I say we should just focus work on hot-reloading registries properly

**Comment by liach** [comment]
@williewillus Be aware that the data pack can be per save; on the dedicated server (which has only one save) it is fine, but on the client what should we do for those per-world data packs with values requiring a restart?

**Comment by ghost** [comment]
@liach Maybe when you enter a save/server with a different datapack than the general one, the game restarts with the data of that world, but once restarted you automatically enter it.

**Comment by liach** [comment]
Well, I am somehow concerned because restarting the game takes a lot of time, especially on those poor devices.

**Comment by KnightMiner** [comment]
My main concern would be that data packs don't load soon enough for all configs that need to do registry related things. I think it would make sense to keep using the config folder for global configs, then use data packs for the per world ones. I think anything in a data pack should be expected to be able to change on the fly.

**Comment by Claycorp** [comment]
Looking at this from another side, What **must** be registered or not registered to enable/disable it? Is there other options than relying on registering or not for this part?

When I was doing pack work in 1.10 most mods didn't even offer options to outright remove items anymore. Most of them just removed recipes or relied on Mine/CraftTweaker for item and block removal via recipe. Thus I don't see Items/Blocks being the real issue.

Mobs could be dealt with at spawn time. (If this doesn't harm performance.)
Not sure about all worldgen options but we do have structures that are part of datapacks so some of it will be avoidable for sure.
What else will cause issues? I don't see anything other than Items, Blocks and Entities brought up and I don't know all the ins and outs on this topic as it's a large area.

**Comment by liach** [comment]
Some mods have modules that can be disabled or enabled. And those involve different items' availability.

**Comment by Claycorp** [comment]
Why wouldn't they be able to move away from registry changes between A or B? You can make blocks/items drop based off A or B and make recipes to match. Worldgen/Mobs can do the same, Give it a zero chance to spawn in A and X chance to spawn in B. If someone has A,B,C,D,E,F,G,H,I to deal with perhaps breaking the mod up into more simple mods would be beneficial to everyone. I know lots of people who would rather have three mods instead of one large one because they don't want 90% fluff for that 10% useful bit they want to use. 

If you have an example of why you 100% must change what you register then you could change my mind but without examples showing it must not change, I firmly believe this is doable.

**Comment by LexManos** [comment]
It has been the stance of Forge for A LONG TIME. That people should ALWAYS register everything.
And just disable access to the things they dont want via recipes or whatever.
This way the client has a Superset of all available resources that the server then can tell them what subset they will be using for that session.
As for the entire concept of this 'issue'. Data packs are not magic, they don't magically get synced to the client, they dont magically make every config option runtime applicable.
So the only thing that you're suggesting is renaming the config folder, data....

**Comment by ghost** [comment]
Ok, i’m closing this then.
