### ISSUE TITLE
Entities aren't created properly on the client when using factories

### ISSUE THREAD

**Issue by Cadiboo** [MinecraftForge/MinecraftForge#5096]
http://www.minecraftforge.net/forum/topic/65847-forge-1122-142342747-bug-with-spawning-entities-that-have-the-same-class-but-different-names-construction-factories/

**Comment by LexManos** [comment]
1) Actually put context information in the git post, linking the forum is fine, but people shouldn't have to go the forums to get the basic context.
2) This is intentional design of Minecraft's entity system.
Everything is run based off entity class. You're only actually registering one spawn value because the registry is based off class.
This isn't a bug its your misunderstanding of the entity system.
