### ISSUE TITLE
ConcurrentModificationException in EntityTracker.tick()

### ISSUE THREAD

**Issue by SuperKael** [MinecraftForge/MinecraftForge#5143]
I have made a sword that hits all enemies in an AoE around the direction you are facing when you use it. It works great, but there's a problem. Very rarely, when killing multiple enemies simultaneously, the game crashes with a ConcurrentModificationException, as the EntityTracker.entries set is modified while being looped through in the first for loop of the EntityTracker.tick() method. I have little idea as to why or how this is happening, I can only speculate - but I do know that it could be fixed simply by making a copy of the entries set in the tick() method and looping through it instead.

**Comment by SuperKael** [comment]
I don't know how hard it is for Forge to modify vanilla methods, so I hope I am not asking too much by this. It just seems like this is a problem with Minecraft, rather than one with my mod.

**Comment by liach** [comment]
you need to post your test code and entity tracker code snippet to prove your point.

**Comment by SuperKael** [comment]
I don't have any Entity Tracker code, as I don't have any entities. In fact, I don't actually know what an Entity Tracker does. As for the code that causes the problem... The client is determining who to attack, and then sending a packet for each target. Then the packet calls a custom version of player.attackTargetEntityWithCurrentItem, which has had the line which applies the cooldown removed for each target. So again, I am doing nothing weird. I am certain this behavior is not, at least not entirely, my fault. The fact that it's so rare and random...

**Comment by JamiesWhiteShirt** [comment]
This is very much a case for the forums and seeing the actual code would make it possible to debug, but I think we could solve this momentarily anyways. The issue will likely be closed momentarily.

The issue is likely on your end. My theory is that concurrent modification is done to the entity tracker by a network thread and the game tick. You are supposed to work around this kind of issue by keeping message handling in sync by scheduling tasks. You can consult the documentation for how this is done in practice: https://mcforge.readthedocs.io/en/latest/networking/simpleimpl/
