### ISSUE TITLE
Transformers cannot transform themselves.

### ISSUE THREAD

**Issue by Hallowizer** [MinecraftForge/MinecraftForge#5165]
https://github.com/MinecraftForge/MinecraftForge/blob/fcd00bd4af61a640c54715bdce79455ecedd9060/src/main/java/net/minecraftforge/fml/relauncher/IFMLLoadingPlugin.java#L89

Hi! I just noticed that the javadoc linked says that transformers should be in the transformer exclusion list, because they might end up transforming themselves otherwise. While this seems like a big problem, if you think about the steps to the process, what happens is that the transformer class is loaded first. The transformers that were previously registered transform it, unless it is in the transformer exclusion list. Then, the class is instantiated, and finally, the transformer is added to the transformers list. Because of this, it is not possible for a transformer to transform itself. If a transformer somehow ends up transforming itself, then an internal error has occurred. It does not make sense for a transformer to be loaded, then told to transform itself, then loaded a second time.

**Comment by LexManos** [comment]
While you are technically correct that it wont transform itself, if you notice the javadocs doesnt use the term 'itself' because its more referring to dependancies and other things that arnt explicitly the transformer class. 
Either way this is a non-issue, just declare your exceptions correctly. And, its all moot in 1.13 anyways.
