### ISSUE TITLE
[1.13-pre] findJarPathFor fails if path of the jar contains whitespace

### ISSUE THREAD

**Issue by Librazy** [MinecraftForge/MinecraftForge#5236]
I built a working forge 1.13-pre and it starts if path to `.minecraft` contains no whitespace. But it fails to start with [URISyntaxException](https://github.com/MinecraftForge/MinecraftForge/files/2577345/URISyntaxException.log) if there is whitespace in the path.

I suggest adding some escape for whitespace (and maybe other chars?) in [findJarPathFor#L76/#L78](https://github.com/MinecraftForge/MinecraftForge/blob/5110796591e6b21769039f054d2a456972d5ae58/src/main/java/net/minecraftforge/fml/loading/FMLCommonLaunchHandler.java#L76).

**Comment by mezz** [comment]
I think the issue here is that we decode the URI at all, it should be left encoded.
`java.net.URI#getSchemeSpecificPart` returns a decoded scheme-specific part of the URI.

It looks like you came to the same conclusion and made a PR, so I'm linking it to the issue here:
https://github.com/MinecraftForge/MinecraftForge/pull/5237
