### ISSUE TITLE
[1.12.2] EntityEvent.EnteringChunk repeatedly fired during jumping

### ISSUE THREAD

**Issue by BoskoVojinovic** [MinecraftForge/MinecraftForge#5322]
Here is my server-side code:
```@SubscribeEvent(priority = EventPriority.NORMAL)
	public static void onEnterChunk(EntityEvent.EnteringChunk e)
	{
		if(e.getEntity() instanceof EntityPlayerMP)
		{
			Main.msgString((EntityPlayerMP) e.getEntity(), "Now entering chunk: " + e.getNewChunkX() + " | " + e.getNewChunkZ());
		}
	}
```

`Main.msgString` just formats the message before sending it to the player.
When moving on a y=constant plane, this works fine.
If I jump in the middle of a chunk the message(for entering that chunk) gets sent somewhere between 4 and 20 times in a row, I couldn't notice any patterns with the number.

EDIT: the plane I was jumping on is right beneath the vertical chunk border, but still the event should be fired exactly 2 times right? Once going up through the border and once going down. But it's almost never 2....Also if the game internally keeps track of the Y chunk coordinates, why does this event only have access to X and Z?

Forge version: 1.12.2-14.23.5.2768

**Comment by LexManos** [comment]
Interesting, Doing some testing myself, I consistently get 4 events fired per jump.
All on the server side, however two are from the server world's simulation, and then two are from the client sending explicit 'set position' commands.
As networking is run off thread it would make sense that the packets are a bit desynced.
As for why you're getting chunk added events for Y only changes. This is due to how Mojang decided to implement the sub-chunk mechanics.
They actually have the entity remove, and then add itself back into the chunk when it changes Y sections.
We *could* filter this out. But there really isn't much need. We *could* also expose the Y position as the entity.chunkPosY is for the OLD chunk when this is fired..

**Comment by BoskoVojinovic** [comment]
I got around the Y thing, just checked if the X and Z didn't change so that's cool.
I also tested a bit further and found more weird stuff. Flying around works fine every time, but again, jumping creates more problems:
If I'm mid-jump while passing the X or Z chunk borders, occasionally(about 15% of the time) the event will fire 3 times(forth, back, forth), and I have no idea how to fix this elegantly. I need a faction-like chunk claiming mechanic for my mod, so sending 3 messages to my players when they change chunks is a bit confusing. Any ideas?
