### ISSUE TITLE
[1.13] Specific y-levels in water behaves like you're in air.

### ISSUE THREAD

**Issue by SilverDavidMC** [MinecraftForge/MinecraftForge#5341]
When being in water with a y-level of x.37847 or similar where your eye level is above the surface of water, the game treats it like you're in air. Instead of water behaving as a full block when water is above it, it always behaves as a surface source block. The behavior is similar to the screenshot shown, but pretend the end portal frames are water sources with air gaps.

![2019-01-10_23 01 07](https://user-images.githubusercontent.com/15661705/51012713-9390de80-152c-11e9-8326-cc62ce09ffaa.png)

**Comment by williewillus** [comment]
could you check if the problem happens in vanilla?

**Comment by SilverDavidMC** [comment]
Already tested. This same bug occurs in one of the 1.13 snapshots, but not the full release.

**Comment by LexManos** [comment]
Alright, this is a stupid one. This DOES happen in vanilla just very rarely.
Vanilla uses the formula: ```eyes < (double)(pos.getY() + state.getHeight() + 0.11111111F);```
Forge uses the formula: ```eyes < (double)(pos.getY() + state.getHeight() + 0.1F);```
Spot the difference.

getHeight() is ```level / 9.0f``` which is odd considering the max a fluid can be is 8, so ```8/9 = 0.88888888F```
Which is why they add the stupid number ```0.11111111F```, turns that into ```0.99999999F```. And considering vanilla uses double for positions, TECHNICALLY this can occure for ```0.99999999F < Y < 1.0D```

Forge's side just expands the issue because I used ```0.1F```, instead of ```0.11111111F```.

**Comment by Niko-sk2x** [comment]
Actually, `8.0F/9.0F + 0.11111111F == 1.0`, so this is not an issue in vanilla at all. More specifically, there is no `0.99999999F`. When you try to get such float, you get `1.0F`

**Comment by LexManos** [comment]
That is not held out in the actual code. As I stepped through it and verified it myself before posting/pushing the fix. Unless my IDE suddenly decided to start lying to me about the value of variables. But thanks anyways.
