### ISSUE TITLE
[forge-1.13-24.0.81-1.13-pre] Crash after first launch.

### ISSUE THREAD

**Issue by Kzitold** [MinecraftForge/MinecraftForge#5358]
https://pastebin.com/YcV7t6QG

First launch is fine. Second launch crashed.

And I used a fresh directory.

**Comment by Xalcon** [comment]
The toml serializer doesnt add quotes around the forge modid in the config/forge_chunk.toml

Adding the quotes will work for one launch, but since the file gets overwritten each time forge launches, it will crash again the next time it launches.
One workaround would be to set the `mods` setting to an empty array as this will persist across multiple launches.

**Comment by ThexXTURBOXx** [comment]
Should be fixed in latest version. Did you try updating?
