### ISSUE TITLE
[Suggestion] Add global weather API

### ISSUE THREAD

**Issue by anar4732** [MinecraftForge/MinecraftForge#5374]
many mods have different wind turbine systems.
and they all calculate the wind in different ways.

Add global weather API
- Weather heat, wind, humidity.
- Every blocks has own heat.
- Every fluid has own heat and its changing over time depending weather heat.

**Comment by kierajreed** [comment]
In my opinion this falls under "content" and should be a mod rather than a built-in in Forge. However hooks to modify heat values would be good if not already present.

**Comment by 0Navis0** [comment]
Well it could be said the same when Forge added an energy api while RF existed already. Add a weather api wouldn't be a bad idea. It would enable all modders to use the same weather api, ease them to code their mod, and create a retro compability between all mods. Modders will have in a way or another to rewrite all their mods in 1.13. So it is surely the best and only time for adding such content in Forge. I would extend the idea by addind a temperature, humidity, thirst, and tiredness API.

**Comment by Daomephsta** [comment]
> It would enable all modders to use the same weather api, ease them to code their mod, and create a retro compability between all mods.

None of that requires the API being in Forge. Modders can and should create their own APIs to make similar systems in different mods compatible. Every new hook or API added to Forge has to be maintained, so Forge is very picky. The only APIs that go in Forge are those that are very commonly used, like the fluid & energy APIs.

> a temperature, humidity, thirst, and tiredness API

These aren't useful to many mods, and the mods that do add these features usually shouldn't be compatible with other mods adding the same features. If compatibility is necessary, it is perfectly possible for the respective mod teams to create a common API.

**Comment by Alpvax** [comment]
Temperature could be viable, only because torches melt ice. Light shouldn't melt ice, heat should.
However, none of the other weather has any effect in vanilla

**Comment by kierajreed** [comment]
> Well it could be said the same when Forge added an energy api while RF existed already.

Wrong! The reason Forge added its energy API was because there were a large amount of mods all using different energy APIs and it was decided that one standard API would be better than having to convert between 3-4 different APIs (if you don't believe this, look at the [conversion table](https://gist.github.com/DeflatedPickle/403e1eb0bb0bed7f2509142e63630726/)). However, very few mods have exising weather APIs and very few modders would benefit from a weather API being added to Forge.
<br/>
> I would extend the idea by addind [sic] a temperature, humidity, thirst, and tiredness API.

The former two somewhat exist in Minecraft itself as biome properties but could be improved. The latter two are, as mentioned earlier, not worthwhile to implement in Forge because so few mods would use them.
<br/>
Edit: just realized Daomephsta said this right above me but I'll leave this here just because deleting it is pointless. And as they said, the Forge team is very picky as to what to add.
