### ISSUE TITLE
[1.13] Dedicated server fails to start because of a config related problem

### ISSUE THREAD

**Issue by ashpieboop** [MinecraftForge/MinecraftForge#5430]
It looks like a server starting from an empty working directory won't create the required server configuration files, and I can't figure out if these actually exist in the code and if there's any way to fix it temporarily, definitively preventing from running a dedicated server until fix.

Tested in 1.13 mdk 150

See : [latest.log](https://github.com/MinecraftForge/MinecraftForge/files/2825547/latest.log)
[crash-2019-02-03_14.27.35-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/2825548/crash-2019-02-03_14.27.35-server.txt)

**Comment by ashpieboop** [comment]
Is [this commit](https://github.com/ArisuOngaku/MinecraftForge/commit/6abcc938c4fb3dd3a25f583519a74b94d9b27a3a)
pull request ready ? It fixes it and makes it work, but I don't know if it's a good idea to do that.
@tterrag1098

**Comment by tterrag1098** [comment]
No, the issue is somewhere in the new config code from @cpw, it needs to be fixed there. I've already notified him of the problem.

**Comment by LexManos** [comment]
I have fixed this in the current version, by moving the Forge config to manually loading.
This is a temporary fix until I can have some time to talk this setup through with cpw.
Leaving this issue open as a reminder to talk to him.

**Comment by LexManos** [comment]
cpw says he has re-vamped the config system so this should be fine.

**Comment by RobertSkalko** [comment]
I am getting Cannot get config value without assigned Config object present on the 191 version of forge.
Here's a recent one from today
https://hastebin.com/ixaduyowoj.cs

It is extremely random. I could start my mod in my IDE, and everything works fine. Start it again and it crashes as soon as the player connects (because it tries to attach capability but checks for a config value that's null-which shouldn't be).

Hopefully here is the right place to report.

**Comment by RobertSkalko** [comment]
I'm pretty sure i fixed my problem by loading the config in my mod class instead of FMLCommonSetupEvent. I got inspiration to do that because i wanted to use a config value in an item registry event, which happens before commonsetup apparently.
