### ISSUE TITLE
[1.13.2] Texture map no longer allows adding new atlas sprites

### ISSUE THREAD

**Issue by LordMonoxide** [MinecraftForge/MinecraftForge#5555]
The `TextureStitchEvent`s have `getMap()` which returns a `TextureMap`.  In 1.12 you could call `setTextureEntry` to register `TextureAtlasSprite`s, but  this method no longer exists.

In 1.13, it's possible to register `NativeImage`s with the `TextureManager`, which is fine for regular TESRs, but I'm fairly certain those can't be used with fast TESRs since you need to actually bind them.

**Comment by tterrag1098** [comment]
Why can't you use `registerSprite` ?

**Comment by LordMonoxide** [comment]
I'm generating composite textures using palettes defined in datapacks.  Whereas `registerSprite` only allows passing in an extra `ResourceLocation` to read from disk, `setTextureEntry` allowed registering custom `TextureAtlasSprite` instances in code.

**Comment by Drullkus** [comment]
This looks a little problematic for me too.

I'm working on a 1.12.2 mod for autogeneration of textures by json looking to be used by a few mods on the fly. I can't generate these textures outside the game as the mod is designed to be adaptable to resourcepack changes. TConstruct also has texture autogeneration. I'm looking to doing this in 1.13.2 as well.

Through my ongoing investigations, Minecraft is appearingly a little more direct with GL management.

It seems instead of having a `TextureMap` store all of the `TextureAtlasSprite` which stores all of the images by a list of double-int arrays and then uploading animation updates from those double-int array lists, it's directly managing the texture atlas using `NativeImage`s as references to textures on the GL's stored texture atlas. I'm most likely wrong but this is my current impression on the situation thus far.

Hypothetically I'm seeing a way that allows a better way for me to auto-generate textures (using a FrameBuffer), but I'm not sure about stitching it in. I'm guessing I can use `Stitcher` to pull it into the `TextureMap`? I'll need to try it out when I get to porting to 1.13.

**Comment by LordMonoxide** [comment]
You're more or less right about `NativeImage`/`TextureAtlasSprite`.  A `NativeImage` wraps a GL texture handle, and a `TextureAtlasSprite` wraps one or more `NativeImage`s that sit in the stitched texture atlas.

Unfortunately `Stitcher` is a dead end.  The `Stitcher` instance only exists in `TextureMap`'s `stitch` method, and stitches together the `TextureAtlasSprite`s that are already registered with the map.

**Comment by Quantum64** [comment]
Still needs a replacement for 1.14.
