### ISSUE TITLE
[1.13] Re-add ability to use mojang credentials

### ISSUE THREAD

**Issue by heisluft** [MinecraftForge/MinecraftForge#5596]
As of now, UserdevLauncher hardcodes an accesstoken:
`"--accessToken", "blah",`
and does not set a username so mc generates one. Back in 1.12 one was able to supply a --username and a --password (now --accessToken) via the run args.
As those are dropped in UserdevLauncher there is currently no way to log in with a mojang account.

**Comment by LexManos** [comment]
We need to decide how we want to do this, while respecting Mojang's wishes as best as possible. Which is difficult because they explicitly don't want people having passwords entered into non-mojang services. Which makes a ton of sense. But there really isn't anything that can launch dev environments.

**Comment by JBYoshi** [comment]
I actually wrote a personal tool for this a while back. It grabbed the UUID and access token from `.minecraft/launcher_profiles.json`, refreshed the access token, downloaded the rest of the profile data from Mojang's servers, and added the relevant launch arguments. While I no longer have the code (the old version I put on GitHub in 2015 doesn't work with the updated launcher), Forge could do something similar.

If it isn't built in, I'd at least want support for supplying my own Mojang-style arguments. No `--password`, but all the properties typically supplied by the launcher.

**Comment by LatvianModder** [comment]
I always use --username and --uuid combo and use ReAuth mod if I ever need an actual profile (which is almost never)

**Comment by LexManos** [comment]
I'm currently re-writing how we deal with the arguments in our test launches, so that overriding/adding more should be functional. Due to how arguments can be formatted, it isn't simple. But I think I have something working.
The current thing we have is just a first pass to get things working.


As for grabbing the auth info from the profile json. I am opting to not write a "Password stealer" which is what people the people who like drama, and not looking into things would accuse us of. However after having some discussions, basically the conses is to login using AuthLib like we did in FG2, but with a big "DO NOT USE THIS UNLESS YOU NEED TO" disclaimer.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/3003e3307425ade9dc4dbebe2069b2534c7e5157#diff-dddeff38152f201f2bd6e50a6abb2978R113

You should now be able to manually specify --authToken and any other arguments we supply defaults for.
As well as re-introduced the --username and --password login functionality. Again, DO NOT use this unless necessary, we are NOT Mojang. We are NOT responsible for your login information. Be VERY careful with logs, run configs, anything that could have your login details.
