### ISSUE TITLE
[1.13.x] Particle types need forge registry syncing

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5605]
Particle types are sent to the client by their integer ID in `SPacketParticles`, but a client can have aesthetic mods that add their own particle types the server doesn't have, which can cause the integer id's to mismatch between server and client.

So forge should use its int id syncing on particle types.

IDK how forge registries work in this regard, but the client shouldn't reject connections where it has more particle types registered than the server, while the server should reject clients that don't have the particles the server has.

**Comment by bs2609** [comment]
#5514

**Comment by williewillus** [comment]
Additional note: the factories map in ParticleManager needs to account for integer id shifts if this becomes a forge registry

**Comment by bs2609** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/5514#issuecomment-474607102

**Comment by LexManos** [comment]
This is a interesting case. Typically our system does not inject anything into the registry that the server does not tell it to. This is why I tell people they should install/register everything always. Because the server will pick the subset that it needs.

This would need to introduce the concept of injecting more from the client, after snapshots are injected. We sorta already do that for "local" worlds... maybe expand upon that.
