### ISSUE TITLE
[1.13.2] Grass Doesn't Drop Seeds

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftForge/MinecraftForge#5675]
Currently, minecraft:grass doesn't drop any seeds, while minecraft:tall_grass does.

**Comment by 5ully** [comment]
Your way to fast xd

**Comment by b268** [comment]
Yea, BlockTallGrass overridden getDrop method; where BlockGrass doesn't. It might be the cause

**Comment by Sollace** [comment]
Is the grass block really supposed to drop seeds, though?

**Comment by ghost** [comment]
Yes, it is supposed to. I tried on 1.13.2 vanilla, it does drop seeds.

**Comment by Sollace** [comment]
Huh. I've never seen it drop seeds before. It's always just given me dirt.

**Comment by 5ully** [comment]
its the grass, and not the dirt variance we're talking about, The grass block will drop dirt, the grass and tall grass should drop seeds

**Comment by b268** [comment]
We are talking about https://minecraft.gamepedia.com/Grass
😅

**Comment by Sollace** [comment]
Oh.

Dammit, mojang, stop renaming stuff... >.>

Okay, it's tall_grass and double_tall_grass for me. XD

**Comment by ghost** [comment]
Ops, I were wrong, I looked at the wrong file

**Comment by williewillus** [comment]
just to clear things up

`minecraft:grass_block` is the full grass block that transforms to/from dirt. It does not drop seeds.

`minecraft:grass` is the one-high shrub tall grass. It should drop seeds.

`minecraft:tall_grass` is the two high double tall grass. It should also drop seeds.

So the issue is the second one, probably due to a patch issue because mojang renamed everything

**Comment by bs2609** [comment]
It's because Forge's seed list isn't populated, as it may be migrated to a better system (e.g. #5497).

This was already reported previously, although discussion has ended up being on #5434 for whatever reason.

In this instance, this would also suggest that tall grass doesn't use any Forge hook currently, which will need addressing.
