### ISSUE TITLE
[1.13] DataFixer and Schema registry/hooks

### ISSUE THREAD

**Issue by itsmeow** [MinecraftForge/MinecraftForge#5695]
I've been looking around the vanilla fixer system to find a way to make my data not be ignored by the vanilla save converter/datafixer system. I found it. It's line 279 and 280 in DataFixesManager adjusted for whatever TE I need. The first bit is done, I can make a Schema with what data I want fixed. The issue is, I cannot add it to the schema list and register a fixer on it without modifying vanilla classes. I know no one really has an understanding fully of how the DataFixerUpper lib works yet, but some sort of way to add onto it would be beneficial for now so I can offer world compatibility (I have datafixers on 1.12 that flatten my TEs/items in preperation for 1.13, but I can't get MC to accept and convert my old data without something like this)

It might possibly be better to get a firm grasp of how it works before messing with it, but I spent around 3 hours looking at it and it still makes less sense than every other program I've ever looked at.

**Comment by Gamebuster19901** [comment]
Duplicate of #5650.

I also tried to work on this but wasn't able to figure it out either.

I believe the new DataFixerUpper system is fundamentally incompatible with mods. Minecraft's datafixer can only work with a single fixer version number. Each mod will have its own fixer version number however.

I'll post more about what I know about the datafixer system when I get internet hooked up to my place.

**Comment by itsmeow** [comment]
Looks like Forge needs to make a complete rewrite of the vanilla fixer with a kind of wrapper that separates vanilla and mods into their own categories. Luckily the only place the fixer instance is actually used is in `AnvilChunkLoader` when it calls `NBTUtils.update()` on older Schema IDs, so it should be possible to allow adding of fixers up until postinit/world load when the build has to actually be run so the fixer is not null. I hope Forge can also provide some simplified fixing classes and/or automatic preservation of TE, Entity, Item, and Block data given they are registered (so data from 1.12 isn't just ignored). I still do not have a firm grasp of how the fixer system works yet, but I think with a bit of work it would be possible to get fixers working (and not too complicated).

**Comment by Gamebuster19901** [comment]
>Luckily the only place the fixer instance is actually used is in `AnvilChunkLoader`

This is false. DataFixesManager.getDataFixer() is called from 5 places. (net.minecraft.data.CommandsReport, net.minecraft.entity.EntityType.Builder, net.minecraft.server.MinecraftServer, net.minecraft.client.Minecraft, net.minecraft.tileEntity.TileEntityType)

<hr>
<h2> Here is my current understanding of the Data Fixer system:</h2>

Note: A DataFixer and a DataFix are two completely things, A DataFixer holds Schemas and DataFixes, and uses them to fix data. I'll be referring to DataFixers as DataFixerUppers for clarity.

1. You begin by creating a new DataFixerBuilder, supplying an int as the current version
2. You then add Schema's and DataFixes to the DataFixerBuilder
3. You can obtain your DataFixerUpper instance by calling DataFixerBuilder#build(ForkJoinPool.commonPool)

<details><summary>Here is an excerpt showing we are currently are. (From vanilla):</summary>
<p>

```java
public class DataFixesManager {
    ...
   private static DataFixer createFixer() {
      DataFixerBuilder datafixerbuilder = new DataFixerBuilder(1631);
      addFixers(datafixerbuilder);
      return datafixerbuilder.build(ForkJoinPool.commonPool());
   }
    ...
```

</p>
</details>

4. When you encounter data you need to fix, you then call DataFixerUpper.update(). DataFixerUpper.update will then send you the fixed data. If the data doesn't get fixed, it should return the data you supplied.
(the only place DataFixerUpper.update() is called in vanilla is net.minecraft.advancements.PlayerAdvancements#load() and net.minecraft.nbt.NBTUtil.update()

<h2>The current (known) problems I have found are as follows:</h2>

1. Minecraft currently only supports one data version. We would need some sort of system that allows multiple DataFixerUppers, and each DataFixerUpper would need its own version. We would also need to need to save the current fixer version for each mod when we save data.

2. If the above is implemented, what should we do if two or more DataFixerUppers try to fix the same set of data? Personally I'd crash since there could irreversible data corruption.

3. Some data fixing is done outside of saving/loading worlds (I think I remember seeing options getting datafixed). So there is a possibility that some datafixing is being done before mod loading. I'm not 100% certain on this though.

**Comment by itsmeow** [comment]
I am currently working on this. I will make a draft PR once I get something remotely workable.
