### ISSUE TITLE
LazyOptional.empty() edge case

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5716]
I have a question about the new LazyOptional System:
I want to check if a tileEntity has an inventory but it returnes LazyOptional.empty(). Can I now still add a listener to listen if this gets invalid?
If so, won't empty() have many tousand listeners since everybody uses the same instance? 
If I should only keep the value when LazyOptional is present, doesnt that mean I have to check each tick /regulary if the tile now has a working inventory ?

**Comment by mcenderdragon** [comment]
> If so, won't empty() have many tousand listeners since everybody uses the same instance? 

As addListener checks for isPresent adding stuff to empty() is not possible, so the frequently checking would be the case.

**Comment by LexManos** [comment]
>doesnt that mean I have to check each tick /regulary if the tile now has a working inventory ?

No, if the TE is something that can loose/add any cap. They should notify neighbors when that happens to allow them to recheck. Or, if they do it frequently, they should return a Dummy inventory, instead of a empty optional. The point is to not require checking every tick.

Also use the forum for basic discussion.
