### ISSUE TITLE
[1.13] Classes loaded from a jar or sourceset use the wrong classloader.

### ISSUE THREAD

**Issue by mattmess1221** [MinecraftForge/MinecraftForge#5721]
While debugging, I have noticed that classes loaded from the classpath are using the system classloader rather than FML's. This is causing some classloader hell if it happens to load a minecraft class.

In my test repo (linked below, fresh mdk), I demonstrate this by creating 2 copies of a simple class which extends `GuiButton`.  One in **main**, another in a source set **libs**. The one in the source set fails to load at all, while the one in main runs perfectly.

The result is a `VerifyError` complaining that `Button` is not an instance of `GuiButton`.

Stacktrace: https://gist.github.com/killjoy1221/27c32bb13af93379c4f6c16f29f01535
Repo: https://github.com/killjoy1221/test-fml-sourceset-loading

**Comment by cpw** [comment]
I don't think this is fixable. The additional sourceset is visible on the primary classpath, and doesn't go through FML processing, because you haven't told FML about it (via MOD_CLASSES). If anything this is a forge gradle problem, but in reality, this is going to be expected. Resources cannot load from the regular classpath, and if they do, problems like this _will_ arise.

**Comment by cpw** [comment]
From @tterrag1098 : add `source sourceSets.lib` to the run configuration and that should fix it for you.
