### ISSUE TITLE
[1.14.2] PlayerInteractEvent.RightClickBlock is fired on server only

### ISSUE THREAD

**Issue by MercurialPony** [MinecraftForge/MinecraftForge#5802]
The event is fired only from PlayerInteractionManager#func_219441_a which is called by ServerPlayNetHandler#processTryUseItemOnBlock when a CPlayerTryUseItemOnBlockPacket arrives on the server. The event is not fired on the client like before which potentially causes desyncs when the event is cancelled.

**Comment by LexManos** [comment]
Yes the client side got rewritten in 1.14 so our initial injections dont work. hence why they are in patches_old. There has always bee the potential for 'desyncs' if the client and server logic disagree. we just need to find the extent of these 'desyncs' and minimize them. Honestly tho, I would much prefer scrapping the idea of the Interact events on the client side as they have caused nothing but headaches for the several versions. Having a way to rollback any client side predictions if the server is canceled would be the better way to go. NOT making any client side predictions would probably be the best way to go. 

So,

**Comment by BlayTheNinth** [comment]
I have a client-side-only mod (not required on servers) where I used the event to cancel undesired torch placements, since Vanilla's offhand system can get in your way sometimes during building.

It wasn't fully functional on servers in 1.12 because packets would still be sent to the server even when the event was cancelled on the client (#3272), but if that is fixed it feels like a valid usecase to also provide this event on the client.

**Comment by MercurialPony** [comment]
@LexManos 
That's fine and all with me, but there's nothing I can do for cases, for instance, like when a vanilla door bugs out when the event is cancelled.

**Comment by cjm721** [comment]
To add onto this, Left Click Block is affected as well. I use both of these events to do some client side processing of action taking into account client settings before passing a request to server to execute (where I do sanity checking).

I also use this event combined with Left/RightClick Air to do client side entity raytrace, as it is an expensive operation, and then server side do the cheaper block ray trace (canBeSeen) check to validate.

Personally I would be fine with these events being world read only to address Lex's https://github.com/MinecraftForge/MinecraftForge/issues/5802#issuecomment-500908989

**Comment by Alpvax** [comment]
I think the best approach would be to have a canclelable interact event fired on the client, BEFORE sending the packet to the server. This would allow e.g. cancelling of miss-clicked torches, and the server wouldn't care (and indeed would not even know that a miss-click had occured). You would be unable to change anything in-game, as with anything on the client. If all you wish to do is cancel the event, why waste the bandwidth telling the server that an interaction wasn't performed?

NB: I haven't actually looked through the source to see how feasible this would be.

**Comment by Tschipp** [comment]
This is weird... I'm experiencing it only firing on the client

**Comment by Aeltumn** [comment]
I wouldn't mind spending some time to sort out all interaction events, methods and whatnot.

I really need some opinions on this, but would it be a good idea to basically write the entire left-/right click processing system as net.minecraftforge code. Just replace the net.minecraft implementation of this with one reference to the forge API and let that handle everything. That way forge has much more control over the system and as many hooks can be added as anyone could need and as many optional settings to disable certain methods getting called as necessary. (and also partially ditch client-side predictions in the process by splitting block breaking into LogicalBreak and VisualBreak or something, because we do need client predictions for the initial visuals, this would probably involve splitting all current InteractEvents into a client variant and a seperate server variant with the client one being purely visual)

This would probably be easier than making tons of small patches everywhere to get the hooks everywhere they need to be. Also, updating the system to future versions would only require checking if vanilla didn't decide to rewrite everything and otherwise just make sure vanilla click handling is disabled.

Also let me know if this is a dumb idea, I'm new to forge specifically but I don't mind spending some time to make a PR and I don't mind having to change it 'til it's good.

EDIT: Thinking about it more, I don't know if this is even possible if you consider that forge clients can log onto spigot/sponge servers. Modifying this code could break spigot/sponge because they specifically work with vanilla. It'd make it so this new system needs to have the exact same behaviour as vanilla and removes the possibility to add extra packets to improve the client-server communication. (probably not impossible but the limitations might make having a custom implementation much less useful because there isn't much room to differ from how vanilla works)

**Comment by Alpvax** [comment]
I know that forge takes the standpoint of change as little as possible, but I think that a complete rewrite may not be a bad idea in this instance. Every time I have dealt with interaction it has consisted of half an hour trawling the code to try to work out what is going on, which events fire when and on which side.
Separating events into client/server would definitely be a great start, at which point maybe we can see if the changes/hooks that we want are feasible without a rewrite.

**Comment by Aeltumn** [comment]
To get back to the original question of this issue, RightClickBlock is fired on the client-side now, if you're looking for an event to detect right clicking before the server is notified see either #6047 or #6144

**Comment by Aeltumn** [comment]
> To get back to the original question of this issue, RightClickBlock is fired on the client-side now, if you're looking for an event to detect right clicking before the server is notified see either #6047 or #6144

As stated before, RightClickBlock is actually fired on the client-side again. I do not know in when it was re-added but the event is called on the client currently. This issue can be closed.
