### ISSUE TITLE
[1.14.2] ISelectiveResourceReloadListener is still not server-safe

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#5837]
The majority of the classes relating to selective reloading have had their `@OnlyIn` markers removed, except ReloadRequirements, which still has it, and causes the entire class to be unusable on a server.

**Comment by LexManos** [comment]
ISelecxtiveResourceReloadListener is deprecated until we fully grok the new threaded resource management system introduced in 1.14.

**Comment by williewillus** [comment]
IMO the benefit is not that clear anymore to me. It was introduced to prevent laggy reloads but since the threaded system lets you do a bunch of stuff in parallel it's not clear how much of a performance win it is anymore.

At a high level, the threaded reload system is simple, the `ReloadListener` class has two methods, one for parallel work (reading files, expensive local computation, etc.), and one for serial work (uploading textures, inserting into global maps, etc.).
