### ISSUE TITLE
Realms loads missing classes in dev environment.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5864]
Forge: 26.0.63
MCP: 20190624

Clicking on the realms button on the main menu will crash your game. Something is referencing an unobfuscated class name `czt`. [Here](https://gist.github.com/darkhax/3dd1afec162608769975dcea09590573) is the stacktrace.

**Comment by LexManos** [comment]
This is known, due to Mojang messing up their obfuscation system (changing realms to no longer be arms length from MC Obf). We do not support realms at this time. We will need to provide deobfed dependencies.
If you want to help feel free to move on to https://github.com/MinecraftForge/ForgeGradle to fix this.
