### ISSUE TITLE
[1.14.3] Allow Specified items to get specified enchants

### ISSUE THREAD

**Issue by RobertSkalko** [MinecraftForge/MinecraftForge#5929]
I had a problem, in my mod swords are not SwordItems, because i don't want sweeping attack. (this is hardcoded in PlayerEntity and not part of sworditem, so i can't override it away).

Players complain they can't get looting enchant.

Looting enchant seems to have a type that requires the item to be an instanceof SwordItem.

I made a simple hacky workaround for my mod here https://paste.gg/p/anonymous/bc4381a55a0b490d8480d0b2b47c624e/files/efe09ac874794ebd82b2aa2036e0f8c0/raw

(this would break if any other mod decided to do the same)

But i think forge could implement a much better system, that is compatible with all mods. Here's my solution idea

https://paste.gg/p/anonymous/ecf8ecf358a6498db73769db44a44c6f/files/4edf065bcebc4e74bea2bba7dec991bd/raw

Possible uses:
* you can't/don't want to extend a class but want the enchants that are hardcoded for that class
* you want to blacklist certain enchants from being possible on your item
* you want your item to be special, and say recieve feather falling on your ring.

Edit: i think i missed a problem, seems this way you can't choose which enchants are possible, just for the whole EnchantmentType, any ideas? Maybe return enchantment.type.canEnchantItem(stack.getItem()); should also be changed to put Enchantment as an argument.

**Comment by MajorTuvok** [comment]
Why not use Tags? This would also allow mod pack makers to configure this...

**Comment by RobertSkalko** [comment]
I didn't think about that. Idk how tags work nor if they can get the same functionality.

I assume you mean 2 types of tags, a whitelist and a blacklist?

**Comment by MajorTuvok** [comment]
I meant whitelist only Tags [how would you define a black and whitelist at the same time? In the end you loose the benefits of the blacklist, by whitelisting stuff, right?]... The Problem would be that modders would need to define the Items, which should be enchantable by something, but I don't think adding to that Tag would be a Problem in comparison to the benefit of migrating enchantability to Tags(?)

**Comment by RobertSkalko** [comment]
How both? Simple. 1 has priority over the other. Either that, or it would be something like

"item": "no" or "item": "yes". So i don't think having both whitelist and blacklist will be hard. I just don't know enough about tags to help here.

It would also need a way to connect to code like loottable functions do. Cus some would want to say make it dependent on nbt.

**Comment by MajorTuvok** [comment]
Tags contain Lists of Items or other Tags. You could therefore interpret the presence of an Item in one Tag as a white list of that Tag/Item and in the other of a Blacklist of that Item.

The Problem I meant with having both, is that if you whitelist stuff in one List, the only thing the Blacklist can do is remove stuff from the whitelist in which case you wouldn't have added it there in the first place. (normally a blacklist would let everything through, except whatever is specified, but becaude the whitelist already specifies a finite list of things that may go through, nothing else will be allowed. Regardless of whether black or white list have higher prio.)

**Comment by RobertSkalko** [comment]
Maybe my definition of blacklist and whitelist is wrong. I meant the system to work as:

if not in blacklist > if in whitelist

Cus you want to be able to both restrict and allow enchants.

**Comment by MajorTuvok** [comment]
What I meant has nothing to do with Tags themselves, but rather with how whitelists and blacklist are defined. Yes you can have both, but it doesn't change the fact that in the end the only thing that will go through is something that is in the whitelist and not blacklisted. Because you already needed to define it in the whitelist, I don't see why you'd gain any benefit from blacklisting stuff at all. 

In the case of Tags, a mod or data pack author could even append a remove to the Tag in question, which work as if you added something to a virtual blacklist (because it is no longer whitelisted).

**Comment by LexManos** [comment]
The problem is there are about 6 existing ways to define what gets added to what and each side gets to veto things and then who gets to veto a veto. Currently the hooks we have in place allow for both sides to veto with out overriding the otherside.
Any discussion of changing that would need to define all parties involved, {the item, the enchant, the enchant source, etc} and define whos opinion is the one to follow.

**Comment by MajorTuvok** [comment]
Using Tags there would no longer be much of a discussion between Item, enchant or enchant source, as it would be entirely the Server's/data pack makers decision to enchant stuff. Mod authors would have a say in that they can define their own Items for specific enchants or specify their enchants for specific Items. They'd also be able to remove them, who get's in depends on how Tags handle add remove cases, but I guess if sonmone removes it, I guess the only way it would get back in, if someone (data pack author?) replaces the whole Tag.
There are the following **disadvantages** I can see:
- A remove overrides any add (correct?) 
- it is independent from the enchant source (Though whoever defines the enchant source can still manipulate the Tag) 

And the following **advantages**:
- data pack authors get to configure precisely what can be enchanted with what
- data based Tag's can be used instead of software classes to define groups of Items which can be enchanted

**Comment by MajorTuvok** [comment]
Yamahari just suggested a sword tag on Discord - No idea why we didn't think of that earlier, but sounds like a nice idea.

**Comment by RobertSkalko** [comment]
Sorry, i forgot i had this issue solved. Apparently IForgeItem has a method canApplyAtEnchantingTable that can allow enchants. Which solved my issue. Closing. If someone actually needs a way to modify enchants of items of other mods, open a new issue.
