### ISSUE TITLE
Villager profession unlocalized name not using mod ID

### ISSUE THREAD

**Issue by sguest** [MinecraftForge/MinecraftForge#5977]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.18

**Logs/Gist:** https://gist.github.com/sguest/2f3e10f7753bf962ab74e9ce45f0c490

**Steps to Reproduce:**
 1. Register profession using resource location with mod's modid
 2. /summon a villager of the custom profession

**Description of issue:**
If modid is `mymod` and villager profession is `myprofession` I would expect the unlocalized name to be `entity.mymod.villager.myprofession` however it is `entity.minecraft.villager.myprofession`.

This unlocalized name is used both for the chat notification that the villager was spawned as well as the title on the trading screen.

The profession correctly displays as `mymod:myprofession, myprofession` in the debug registry dump when starting up the client.

**Comment by LexManos** [comment]
Actually, since this is a combination of both the entity type, and the profession type there would need to be two namespaces in the translation string to be properly compatible.
For people who add custom Villager entity types that can have professions.
So it would have to be something like `entity.minecraft.villager.mymod.myprofession` using the un-namespaced version when using vanilla professions for compatibility sake.
