### ISSUE TITLE
[1.14.4] FML not loading from folders

### ISSUE THREAD

**Issue by VirxEC** [MinecraftForge/MinecraftForge#6054]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.45

**Logs:** None
**Steps to Reproduce:**
 1. Get Forge for a pre-1.13 version, for this example, it will be for 1.12.2.
 2. In /mods/, create a new folder called 1.12.2 and place all 1.12.2 mods in there.
 3. Load Forge. Forge will ignore every folder that isn't called 1.12.2 and will load every file in the folder.
 4. Get Forge for 1.14.4.
5. In /mods/, create a new folder called 1.14.4 and place all 1.14.4 mods in there.
6. Load Forge. None of the mods will load.

**Description of issue:**
Forge 1.14.4 doesn't load mods from /mods/1.14.4/, despite pre-1.13 Forge version from doing so. (Ex. Forge 1.12.2 loaded mods from /mods/1.12.2/). The 1.14.4 mods DO load when placed into /mods/.

**Comment by m00nl1ght-dev** [comment]
This is intended. Instead of putting mods in subfolders, just create a seperate game directory for each version and specify it in the launcher profile.

**Comment by VirxEC** [comment]
You shouldn't have to create a separate game directory for every profile!

**Comment by m00nl1ght-dev** [comment]
You should. And in 1.14.4, you have to.

**Comment by FireController1847** [comment]
@VirzEC This is not a battle worth fighting. People have begged forge for years to add the ability to load from folders, and they've always made some stupid excuse as why not to. No intention to bash the Forge team and the work they do, they do amazing work and I love what they do. But their reasoning for this one specific thing is stupid and doesn't make sense.

**Comment by DaemonUmbra** [comment]
The reason is "use the mechanism that Mojang themselves are providing rather than trying to force us to hack something else in".
Stop being lazy.

**Comment by theicyphoenix** [comment]
> 
> 
> The reason is "use the mechanism that Mojang themselves are providing rather than trying to force us to hack something else in".
> Stop being lazy.



so "being lazy" means not wanting to buy a new hardrive? cuz that's what i had to do,i have mods seperate for each version now,and have different resource and shader packs that weight alot of gigabytes...so at the end of the day i just bought a new hardrive because i filled my old one because each new version needs a different resource  and shader pack location,so i basicly had to copy same large file resource and shader packs over and over again....you stop being hypocritical...everyone has their own reasons for usage of some feature...and id like not to have to buy 2 new harddrives in next month just because version changed and i had to copy resource and shader packs again.

**Comment by gigaherz** [comment]
Having multiple versions in the same folder was a support nightmare. People would have configs that work on one version but not the other, resource packs that work on one version but not others, etc. Having multiple versions in the same installation folder causes more trouble than it's worth. So it was decided not to reimplement it on the rewrite. Yes it can mean more data usage, although in the vast majority of cases people weren't actually reusing that much to begin with.
That said, this issue has been closed for 1.5 years. Don't necro old issues.
