### ISSUE TITLE
Can't remove Forge version

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#6082]
**Minecraft Version:** 1.12.2

**Forge Version:** 1.12.2-forge1.12.2-14.23.5.2838

**Logs:** No logs/see image

**Steps to Reproduce:**
 I don't know, it just doesn't work

**Description of issue:**
Whenever I want to boot up Forge, it gives me this message. 
![image](https://user-images.githubusercontent.com/48418465/63637739-8f12d380-c680-11e9-91f0-49c7a60fedfc.png)

I tried reinstalling it, but I cannot remove this one.
![image](https://user-images.githubusercontent.com/48418465/63637751-bec1db80-c680-11e9-8e4f-b3427f3e5cca.png)

The one you see below works, but I want to get rid of the upper one.

**Comment by ghost** [comment]
I didn't put the Triage label who put the Triage label

**Comment by Unnoen** [comment]
Triage label is put automatically for every new issue. It means someone needs to confirm this bug.

However it seems this issue is best suited for the forums, not the issue tracker. 
https://www.minecraftforge.net/forum/forum/18-support-bug-reports/

The Minecraft launcher handles instances, this most likely isn't a Forge issue anyway.

**Comment by ghost** [comment]
Alright, I'll copy/paste there. Closed.
