### ISSUE TITLE
Couple bugs with new fluid system 1.14

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#6104]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.74

**Description of issue:**
1.  `FluidStack#getTranslationKey` returns `fluid.fluid.water.name` for a fluidstack of water. From what I can tell the proper lang entry is actually `block.minecraft.water` and `block.minecraft.flowing_water`
2. The texture for water no longer seems to have a default blue built in. This means when attempting to render water into a gui, it is uncolored. This is because `getColor()` returns `-1` instead of figuring out what the default color should be. I am unsure if passing a world position would make get color return the correct value but looking at the code for how it is defined I doubt even this would work properly.

**Comment by gigaherz** [comment]
-1 color means use the color from the biome, you will have to default to blue yourself.

**Comment by gigaherz** [comment]
On second thought, we probably should specify the default color + a separate "use biome coloring" flag.

**Comment by ShetiPhian** [comment]
Noticed the "fluid.fluid.water.name" just a couple of minutes ago myself.
Both FluidAttributes.getTranslationKey() and FluidAttributes.Builder are adding "fluid."

**Comment by gigaherz** [comment]
Yup, I decided to remove the extra one in getTranslationKey so that fluids can fully customize the entire key, eg by using the block key if they want to. I also removed the name suffix since vanilla doesn't use it anymore. However while doing that I realized that defaulting to `fluid.x` is missing a namespace, since the fluid builder takes a string and not a resourcelocation.

**Comment by gigaherz** [comment]
Fixed in b0c9d7c
