### ISSUE TITLE
Minecart events are missing

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#6155]
Minecart events are commented out/missing in the patches/forge code. I relied on e.g. MinecartUpdateEvent in Botania to implement the ghost rail, for example. There's no generic entity tickevent, and I don't think iterating the entity list of the entire world every tick is good.

So count this as a request to put them back in

**Comment by LexManos** [comment]
Minecart's hooks have been a massive hack since they were introduced. We need real use cases and figure out what systems we need to do that are not spamming the eventbus with 50/events/cart/tick.

**Comment by ben-mkiv** [comment]
You can attach a capability to a minecart which ticks on worldTick, not ideal but it does work for most usecases.

But im still missing an event when Minecarts get killed, so that for example an attached capability could drop its inventory to the world, too.

(Also for special rail types which do something to the cart it would probably be less cpu intense if the cart could collide with the rail block to fire a collision event, which then gets canceled by its handler?!)
