### ISSUE TITLE
Missing registry entries screen is shown on every subsequent world load after removing a mod, even after playing in that world

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#6167]
This is actually what was reported in https://github.com/Yamahari/I-Like-Wood/issues/13.
I mentioned it on discord before, but I'm not sure it it has been noticed there, so reporting it here.

Relevant debug.log files: https://gist.github.com/Barteks2x/3085235c16b06a7d2d477c949a9b5298

The reason simple testing may not show the issue is https://github.com/MinecraftForge/MinecraftForge/issues/6095

Forge seems to "remember" the user answer to the query and auto-apply it on next world load without asking, until game restart.

Restarting the game after loading a world with mods removed makes forge show the question again.

**Comment by TeamSpen210** [comment]
I believe this is somewhat intentional. For blocks, they're not actually removed from the registry - instead a dummy air block is registered in their place. This allows the blocks to be resurrected if you reinstall the mod. To fix this I believe there'd need to be some additional registry to record which of these dummy blocks have been seen before, so the warning could be suppressed.

**Comment by Niko-sk2x** [comment]
In 1.12.x, it was still possible for blocks to be "resurrected" after readding a mod, but it didn't show the message every single time.

I think this confirms that it's not intended (this is before I confirmed that this is what happens):
![image](https://user-images.githubusercontent.com/1349112/65193405-55fd3180-da7b-11e9-8ae2-53583e8e3ebb.png)

And there is also the other issue I linked that somewhat hides this one.
