### ISSUE TITLE
[1.14.4] PointOfInterestType breaks when a referenced block is replaced.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#6184]
PointOfInterestType keeps a cached set of BlockStates as valid states.  When replacing a block that represents a point of interest, the point becomes invalid and has to be edited to represent the new states.

POITypes are found by state from a static map  
`private static final Map<BlockState, PointOfInterestType> field_221073_u = Maps.newHashMap();`
It might be ideal to patch in BlockState#equals and BlockState#hashCode that use the registry delegate and the property values.

**Comment by williewillus** [comment]
mmm, it's very worth it to have reference-identity-comparable blockstates, since otherwise equals comparisons in the equal case would get quite a bit slower.

Perhaps just recompute the map in one of the registry callbacks for the block registry (or the poitype registry).

**Comment by 3TUSK** [comment]
Is #6410 related to this issue? Both involves block registration override and vanilla caching things…

**Comment by Tfarcenim** [comment]
Yep, because the cached blockstate is no longer valid as it has been replaced, and needs to be force updated which of course requires other hacks.

Vanilla also caches them in several other classes that also need to be updated post registration and it only seems to be getting worse..

This is why I've moved away from registry replacement to alter vanilla objects, and just apply my own patches so  that I don't suffer the issues that come with multiple mods wanting to replace the same blocks and avoid the issues that vanilla caching causes.
