### ISSUE TITLE
Duplicate Tags between Forge and Minecraft

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#6190]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.22

**Description of issue:**

There are tags that are both declared by forge and minecraft.

Exact duplicates:
- `forge:arrows`, `minecraft:arrows`
- `forge:music_discs`, `minecraft:music_discs`

These tags overlap to an extent except the forge variant has sub versions of them as well, but it makes it unclear which one should be used:
- `forge:fences`, `minecraft:fences`
  - `forge:fences/wooden` overlaps with `minecraft:wooden_fences`
- `forge:sand`, `minecraft:sand`. The forge variant inherits from the subvariants colorless and red

**Comment by LexManos** [comment]
In most cases it's probably due to tags being added in vanilla after tags being added in Forge. Or.. Just missing some.
Simplest solution would be to keep both, but have Forge's include vanilla's.
Especially in cases where Forge's are more refined then vanilla's.

**Comment by pupnewfster** [comment]
That makes sense, though it may also make sense then in some places in the code (such as for `FenceBlock` where it checks for `BlockTags.FENCES` then should also be rerouted to the forge tag so that mods that only add to the more refined forge variant of a tag still have the expected vanilla behavior.

**Comment by tterrag1098** [comment]
In those cases we could just override the vanilla tag, as long as the default values don't change, right?

**Comment by LexManos** [comment]
I am not a real fan of tags being used as game logic, but I can see it's uses.
Rather then patch all the massive amount of usages in code, we'd probably just have to inject our tags into the Vanilla one. IF we can make sure that the Forge tag we inject is the intended one. The problem is the side effects could be not what we intend due to Forge's tags being more refined. 
Each would need to be taken on a case, by case.

**Comment by liach** [comment]
In my opinion, a mechanism to merge tags (i.e. two resource locations refer to the same tag) may be helpful to redirect all forge/vanilla usages to the same tag when using two different resource locations to point to a tag of the same purpose. Should be a few easy patches in the tag manager.

**Comment by pupnewfster** [comment]
Not quite sure how much sense that makes (unless it is just for forge/vanilla tags), as mods may use common names for things they want to process a specific way and then the names may overlap. (Unless you mean if the contents are identical then merge them, which at that point may not help as soon as someone adds a single item to one of them.

**Comment by KingLemming** [comment]
I think if nothing else, the 100% duplicates should be removed. I'd also be cautious of a straight merge due to uses in logic.

**Comment by AfterRebelion** [comment]
**Analyzed duplications in Forge-1.15.2-31.1.30:**
Usages of `forge:arrows` & `minecraft:arrows`:
- Forge version in _net.minecraftforge.common.Tags_:
  - net.minecraftforge.common.data.ForgeItemProvider#RegisterTags
    - getBuilder(Tags.Items.ARROWS).add(Items.ARROW, Items.TIPPED_ARROW, items.SPECTRAL_ARROW);
- Minecraft version in _net.minecraft.tags.ItemTags_
  - net.minecraft.data.ItemTagProvider#RegisterTags
    - this.getBuilder(ItemTags.ARROWS).add(Items.ARROW, Items.TIPPED_ARROW, Items.SPECTRAL_ARROW);
  - net.minecraft.item.ShootableItem
    - public static final Predicate<ItemStack> ARROWS = (p_220002_0_) -> { return p_220002_0_.getItem().isIn(ItemTags.ARROWS); };

Usages of `forge:music_discs` & `minecraft:music_discs`:
- Forge version in _net.minecraftforge.common.Tags_:
  - net.minecraftforge.common.data.ForgeItemProvider#RegisterTags
    - getBuilder(Tags.Items.MUSIC_DISCS).add(Items.MUSIC_DISC_13, Items.MUSIC_DISC_CAT, Items.MUSIC_DISC_BLOCKS, Items.MUSIC_DISC_CHIRP, Items.MUSIC_DISC_FAR, Items.MUSIC_DISC_MALL, Items.MUSIC_DISC_MELLOHI, Items.MUSIC_DISC_STAL, Items.MUSIC_DISC_STRAD, Items.MUSIC_DISC_WARD, Items.MUSIC_DISC_11, Items.MUSIC_DISC_WAIT);
- Minecraft version in _net.minecraft.tags.ItemTags_
  - net.minecraft.data.ItemTagProvider#RegisterTags
    - this.getBuilder(ItemTags.MUSIC_DISCS).add(Items.MUSIC_DISC_13, Items.MUSIC_DISC_CAT, Items.MUSIC_DISC_BLOCKS, Items.MUSIC_DISC_CHIRP, Items.MUSIC_DISC_FAR, Items.MUSIC_DISC_MALL, Items.MUSIC_DISC_MELLOHI, Items.MUSIC_DISC_STAL, Items.MUSIC_DISC_STRAD, Items.MUSIC_DISC_WARD, Items.MUSIC_DISC_11, Items.MUSIC_DISC_WAIT);
  - net.minecraft.data.loot.EntityLootTables#addTables
    - this.registerLootTable(EntityType.CREEPER, LootTable.builder().addLootPool(LootPool.builder().rolls(ConstantRange.of(1)).addEntry(ItemLootEntry.builder(Items.GUNPOWDER).acceptFunction(SetCount.builder(RandomValueRange.of(0.0F, 2.0F))).acceptFunction(LootingEnchantBonus.builder(RandomValueRange.of(0.0F, 1.0F))))).addLootPool(LootPool.builder().addEntry(TagLootEntry.func_216176_b(ItemTags.MUSIC_DISCS)).acceptCondition(EntityHasProperty.builder(LootContext.EntityTarget.KILLER, EntityPredicate.Builder.create().type(EntityTypeTags.SKELETONS)))));

As you can see, they register the exact same blocks, but the vanilla tags has logic associated with them.
In the case of the `ARROWS` it may be desirable to remove the Forge tag, since it also adds them to the list of Shootable items.
But in the case of `MUSIC_DISCS` vanilla adds them to the Creeper LootTable. Mods that add music disc will probably want to add his own method of obtaining those discs, and won't expect to have them also added to the vanilla way of obtaining discs just by adding a tag.

So my sugestion would be to retain the forge added version, but change the way they register to mark them with the vanilla ResourceLocation.

So this `public static final Tag<Item> MUSIC_DISCS = tag("music_discs");` to `public static final Tag<Item> MUSIC_DISCS = ItemTags.makeWrapperTag("music_discs");`

This way you can use the builder to add items to the `minecraft:music_discs` tag without affecting that logic.

Note: This has only analyzed the usage of the fields, not direct references to the json files, so it's possible that Mojang referenced this tags in another part of logic (Like the one everyone uses tags for: Recipe handling)

**Comment by kellixon** [comment]
MC 1.16.5. Forge 36.1.4. I have an error with duplicate keys. Because of this error, it does not allow you to enter the world a second time.
_[05apr2021 20:57:03.694] [Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@2d6a5e33_
Full log - https://gist.github.com/kellixon/b4702c40b39d88bf23785054894227fc
