### ISSUE TITLE
No lang file of mod loaded on dedicated server when mod is no datapack

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#6223]
The languages of mods are not loaded if the mod does not have a datapack folder in their resources (data/[modid]). Even if the directory is empty, the english lang files for the mod are loaded, but not if the folder is missing.

**Comment by DaemonUmbra** [comment]
Aren't lang files a client-only resource or have I missed something?

**Comment by tedstardev** [comment]
@DaemonUmbra Yes, but technically the server console is a text-based client.

**Comment by DaemonUmbra** [comment]
Except it's not a client

**Comment by williewillus** [comment]
Yeah I'm not sure if this is an actual bug. As far as my understanding goes, the dedicated server does not load any language files besides vanilla en_us (and maybe mod en_us?), and that this has been the case since at least 1.12.

Logs and technical info are provided only in English (that's just a result of our technological world being us-centric). Anything user-facing, should be sent as a textcomponenttranslation and localized client-side. Combined, this means langs should not need loading on the dedicated server.

**Comment by ichttt** [comment]
Forge also loads en_us lang files on the server to translate command feedback in the console and send pre-translated text if the client does not have the localization files (e.g. the client is vanilla and cannot translate the forge strings, so command feedback has to be translated on the server in this case)

**Comment by williewillus** [comment]
ah I see, so the bug is that mod en_us.langs aren't loading, thanks for clarifying
