### ISSUE TITLE
[1.14.4] NullPointerException for MissingMappings#getMappings()

### ISSUE THREAD

**Issue by Cheaterpaul** [MinecraftForge/MinecraftForge#6252]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.40

**Logs:** https://gist.github.com/Cheaterpaul/4cdd6427ca232fa06e3e817f76ab85fa (line 131)

**Steps to Reproduce:**
1. Load a 1.14.4 world without the new registryname of the entity

**Description of issue:**
I am just calling MissingMappings#getMappings()

(could be same #4067)

**Comment by DaemonUmbra** [comment]
This is due to the activeMod field of the event not being set so when getMappings is run and attempts to filter the mappings list by the mod ID of the activeMod we get an NPE.

Should this event be moved and/or changed to set activeMod or should an error message be added to tell modders to set it themselves in their handlers(example below)?

Workaround is to setModContainer before trying to use getMappings:
```java
 public static void RemapBlocks(RegistryEvent.MissingMappings<Block> event)
    {
        ModList.get().getModContainerById(MOD_ID).ifPresent(event::setModContainer);
        // Remap
    }
```
(Yes I know it crashes if the mod container isn't present but I think there would be crash-worthy issues in that case)

**Comment by noobanidus** [comment]
Is setting the mod container in this case still the recommended solution? As I knew precisely which mappings were changed I chose to use `getAllMappings` instead, but I'll happily go change to this method instead.

**Comment by uecasm** [comment]
I just ran into this in 1.16, so it's still an issue.  Forge throwing NPEs *by default* seems like a serious bug, no matter how you look at it.

Possibly related weirdness that at least should be documented better, if not fixed:
* The event gets posted to the regular event bus, not the MOD event bus like all the other registry events.
    * If you're using `@Mod.EventBusSubscriber` this means you need to put it in a different class from your registration, which is a bit inconvenient (and surprising).
* The event isn't fired for missing tile entities; instead later you just get a log message (and the entity gets destroyed and re-created from the block, with apparently no opportunity to "rescue" data):
    `[minecraft/TileEntity]: Skipping BlockEntity with id modid:oldtileid`
* The logs still contain ERROR messages about missing blocks/items even if the handler successfully remaps them.
* Despite that error message claiming that it will create a world backup, it doesn't appear to actually do so.  (Not sure if that's because it was actually handled in the end or not.)

**Comment by LexManos** [comment]
Seems this slipped through cpw's assignments.
Oh well, for now i've fixed the direct issue, we'll see if cpw wants to re-enable the per-mod variant of this event.

**Comment by uecasm** [comment]
> Seems this slipped through cpw's assignments.

That's because you have stalebot enabled.  It's only purpose is to cause these kinds of problems.
