### ISSUE TITLE
Add a way for modpacks to ship datapacks in the same way they can ship configs.

### ISSUE THREAD

**Issue by ExpensiveKoala** [MinecraftForge/MinecraftForge#6273]
I recently released a mod that is extensible via datapacks, but I realized that this might actually be limiting for end users.

Right now datapacks are dependent on the end user to know how to install a datapack (in vanilla), or to use a mod that provides the specific datapack for the modpack.

The issue is that you end up with each modpack requiring a mod to be created to add datapacks.

**Comment by Tfarcenim** [comment]
Doesn't a datapack loader already exist that can load external datapacks in the same way Resource Loader handles resource packs without requiring a secondary mod?

**Comment by williewillus** [comment]
+1 for the ability for a mod to expose multiple datapacks (instead of just one for the entire mod. think how MC exposes both the default RP and the programmer art RP). But it'd be tricky to declare exactly what resources go in which pack.

in the meantime, mods like resource loader (if it's ported?) can take responsibility of exposing everything in a given folder as a pack.

**Comment by ExpensiveKoala** [comment]
@Tfarcenim I don't know if one already exists like that, but I also don't want to point people to use a mod to customize a feature that is using a vanilla mechanic... if that makes sense. I leave it up to the forge maintainers to decide if this should be a forge feature or be left up to mods to be created to handle this specific task.

@williewillus I agree on that +1, but it should be it's own issue/PR.

**Comment by Tfarcenim** [comment]
Here you go @ExpensiveKoala https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack does it in the same way Resource Loader does.
