### ISSUE TITLE
Exceptions thrown during pre/post sided setup callbacks are swallowed

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#6374]
**Minecraft Version:** 1.14.4+

**Forge Version:** Through at least 30.0.11

In #6364 a check was added that validates that all entities have a renderer assigned. This is invoked during the post-sided-setup callback (where entity renderers are copied from forge to vanilla) here:

https://github.com/MinecraftForge/MinecraftForge/blob/f1c649bc4f7cb5c4adbbae7c41dd9c5013f44afa/src/main/java/net/minecraftforge/fml/client/registry/RenderingRegistry.java#L47-L51

Because the pre/post callbacks are implemented using the vanilla main-thread executor, they run as scheduled tasks. Scheduled tasks swallow exceptions and do not stop the game process. Additionally, this represents a race-condition as there is no guarantee the pre-callback will finish executing before sided setup begins.

I recommend moving to a full `CompletableFuture` system, where the pre/post callback are run via `CompletableFuture#thenRunAsync(Runnable, Executor)` which allows configuration of the Executor and so can use the on-thread executor passed in by vanilla, as well as handle errors and block the sided-setup events until completion of the pre callback.

This would involve major refactoring of `ClientModLoader#onreload` and the other methods it calls, starting from here:

https://github.com/MinecraftForge/MinecraftForge/blob/155836258384da2efe80c566b73fc1ca3e3ee48f/src/main/java/net/minecraftforge/fml/client/ClientModLoader.java#L104-L132

As well as `ModLoader#loadMods`:

https://github.com/MinecraftForge/MinecraftForge/blob/155836258384da2efe80c566b73fc1ca3e3ee48f/src/main/java/net/minecraftforge/fml/ModLoader.java#L149-L160

Which would most likely be a breaking change. So this should strongly be considered before a 1.15 RB.

**Comment by pupnewfster** [comment]
This is still very much an issue and due to the breaking changes that tt said it would probably require, this is hopefully something that can be addressed before a 1.16 RB

**Comment by cpw** [comment]
Is this still an issue since the rewrite? These methods are gone now.

**Comment by pupnewfster** [comment]
For the most part no (the two issues I linked relatively recently are from people reporting bugs about mek 1.15). Exceptions still get swallowed though and then mods get blamed for things like particles (which is all in vanilla code when it crashes) so mods can't even safeguard against being blamed for it. If I remember on discord when I mentioned it to you, after looking into it it seemed the theory was it is because the particle types get registered but then a crash happens before the event that we are supposed to register particle factories in so it never gets fired and mods don't get a chance to register their particle factories then (or something like that), when vanilla then loops all the registered particle types it can't find the files that exist and crashes early providing the wrong stack trace in the crash log and swallowing the actual crash (which shows in the latest.log).

**Comment by Cyborgmas** [comment]
Pretty sure it is any mod loading error that happens before ParticleFactoryRegisterEvent that will cause further events to not be posted. but client loading still happens to get to the error screen and during this indeed particles will try and get loaded but vanilla will find missing particle factories for a particle type and hard crash

**Comment by cpw** [comment]
That's fixed with build 40. Rollback of registries actually works now.
