### ISSUE TITLE
[1.15.1] HarvestDropsEvent not registering

### ISSUE THREAD

**Issue by pant4321** [MinecraftForge/MinecraftForge#6420]
Can this event be reimplemented pls :(

**Comment by LexManos** [comment]
No, there are loot events, and loot tables.

**Comment by chylex** [comment]
One of my use cases is to prevent block drops when *any* block was mined with a certain item. I cannot override `canHarvestBlock(BlockState)` or use `HarvestCheck` because they get ignored if the block doesn't require a tool. The only loot event I can see is `LootTableLoadEvent`, so I could add a condition to every single block, but the event doesn't trigger for non-vanilla loot tables anymore. I don't see a clean way to do this without the event.

**Comment by diesieben07** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/6401
