### ISSUE TITLE
Mining Animation is Broken

### ISSUE THREAD

**Issue by bageldotjpg** [MinecraftForge/MinecraftForge#6432]
**Minecraft Version:** 1.15.1

**Forge Version:** 30.0.36

**Steps to Reproduce:**
 1. Break a Block

**Description of issue:**
When mining a block, the animation on the side and top sometimes seems to be screwed up.

**Comment by Nevrai** [comment]
I’m having the same issue and came here to report it.

This only happens when you mine a block (any block; doesn’t matter which) while facing east or west. It never happens while facing north or south. Quite a strange bug indeed.

[**I recorded a video of it**](https://giant.gfycat.com/DarkApprehensiveEider.webm) to show off what it looks like. I had no resource or data packs enabled and no mods installed.

#### Versions

* **Minecraft:** 1.15.1
* **Forge:** 30.0.39

#### Specs
* **Graphics card:** GeForce GTX 1070
* **CPU:** Intel Core i7-6700 @ 3.40GHz
* **Display resolution:** 2560 × 1440

**Comment by Nevrai** [comment]
Thanks for the quick fix!
