### ISSUE TITLE
Issue specific warnings when certain non-Forge files are found

### ISSUE THREAD

**Issue by magneticflux-** [MinecraftForge/MinecraftForge#6459]
It is becoming commonplace for modders to experience users that assume a mod is for Forge when in reality it is for a different loader (Rift, Fabric, etc.). To avoid confusion, FML should check for the presence of key files when an invalid Forge mod is found, and print an additional recommendation.

I can submit a PR with this feature if it is desired/approved.

I expect to modify [this file](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModFileParser.java#L48) to implement this feature.

**Comment by DaemonUmbra** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/InvalidModIdentifier.java

**Comment by magneticflux-** [comment]
@DaemonUmbra Why is it delayed until after mod loading? Is it for lang strings or something else?

I assumed this wasn't implemented because the first round of mod validation prints a warning that _doesn't_ include this info, and I received an invalid bug report about that log entry here: https://github.com/magneticflux-/fabric-mumblelink-mod/issues/21.

**Comment by DaemonUmbra** [comment]
I can't say I was involved in the creation of this code, but I would assume it was made this way to both make sure every mod that failed to load is recorded, and to keep the warnings together so if there are multiple you don't need to hunt through the log to find them individually.

Note: If you haven't yet, I would suggest setting up [Issue Templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) in your repo to guide people on what details you want in a report (this would include providing full logs rather than snippets).
