### ISSUE TITLE
LivingEntity#getBedPosition.isPresent() return false even if player has bed.

### ISSUE THREAD

**Issue by MairwunNx** [MinecraftForge/MinecraftForge#6581]
**Minecraft Version:** 1.15.2 and 1.14.4

**Forge Version:** 31.1.0 and 28.2.0

**Steps to Reproduce:**
 1. Just with code check it, e.g after some event, e.g in PlayerRespawnEvent event.

**Description of issue:**
LivingEntity#getBedPosition.isPresent() return false even if player has bed.

**Comment by jamierocks** [comment]
I was able to reproduce this, using

```java
@Mod("player_bed_position_test")
@Mod.EventBusSubscriber()
public class PlayerBedPositionTest {

    private static final boolean ENABLE = true;
    private static Logger logger = LogManager.getLogger(PlayerBedPositionTest.class);

    @SubscribeEvent
    public static void onPlayerRespawn(PlayerEvent.PlayerRespawnEvent event) {
        if (!ENABLE) return;
        Optional<BlockPos> bedPosition = event.getPlayer().getBedPosition();
        logger.info("Has Bed Position: " + bedPosition.isPresent());
    }

}
```

Will investigate.

**Comment by AtlaStar** [comment]
@jamierocks just from a quick observation it seems to look like neither the recreatePlayerEntity nor copyFrom methods are copying any DataParameter's from the old player dataManager into the new rather than having those values set outside of the method. It also appears that the BlockPos for the bed grabbed from the old player is solely used to set spawn state in the recreatePlayerEntity function and not to set a bed location.

If this proves to be the cause it sort of poses a design problem though; should one of those methods be modified to provide a consumer to the old players optional to set the new player entity or should the respawn event be broken up into pre and post events that provide the pre-clone and the post-clone entity respectively? Essentially intercepting the entity before respawning in a pre-respawn event will allow you to modify the old player entity and have those changes be reflected after cloning, but at the same time copyFrom not copying DataParameter's crucial for having proper state seems like a mistake but one that could very well be intentional as doing so may not be thread safe (I haven't looked in depth enough)

EDIT: I wasn't thinking about the Clone event before that the copyFrom event posts which provides the same functionality that breaking the respawn event into two parts would provide.

**Comment by jamierocks** [comment]
Ah I should have responded to this - yeah this method doesn't do what you expect, given its name is the gist iirc.

I believe this is a non-issue, I was just going to confirm how to do what was likely expected here.

**Comment by AtlaStar** [comment]
Yeah I imagine it is just a matter of subscribing to the Clone event and accessing the old entity by using getOriginal() on the event and chaining getBedPosition(). Should then be able to perform needed logic on the clone using getPlayer() on the event which seems pretty straightforward to test.
