### ISSUE TITLE
Parameter to config KeepAlive time on high latency servers (fast implementation)

### ISSUE THREAD

**Issue by Oltrox** [MinecraftForge/MinecraftForge#6619]
Well, it's a feature that is fast to implement, because I've made on a version of Forge. The point it's to configure the value of 15000L (via system.getProperty) on the line where is the variable this.field_194402_f (version 1.12.2, NetHandlerPlayServer.java) for example (I know this is in another package in 1.15.2). This feature is for high latency servers (around 130 ms), like amazon ec2 virtual servers. I've mounted a server with around 44 mods in there, some players can enter, but others gets Timed out response or the java error that terminated the connection, because the loading take more time for some players. I added more time (15 sec. to 150 sec.) and worked for all players. That's it!

**Comment by LexManos** [comment]
The original reason this was added as because our handshake would not tick the normal handler and allow the timeouts to happen.
Now the network handler is continuously ticking.pinging so there should never be a timeout unless you have crappy networking. Which is exactly what this time out is designed to check for.
So no.
