### ISSUE TITLE
[1.15.2/minor bug] ModListScreen won't return to previous screen when pressing Esc

### ISSUE THREAD

**Issue by BloCamLimb** [MinecraftForge/MinecraftForge#6672]
ModListScreen only return to previous screen when pressing the "Done" button, but not when Esc is pressed, which just closes current screen

**Comment by jamierocks** [comment]
![https://i.jamierocks.uk/t3hTng74ZU.png](https://i.jamierocks.uk/t3hTng74ZU.png)

Is that the screen you mean? If so, Escape works for me.

**Comment by BloCamLimb** [comment]
[Done](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/fml/client/gui/screen/ModListScreen.java#L281-L282) button is the only way to display the previous screen, Escape only closes current screen... I don't think it's an issue though

**Comment by jamierocks** [comment]
> I don't think it's an issue though

Yeah, I don't see the bug here - like I said pressing Escape works.

**Comment by jamierocks** [comment]
Right, I've looked through the code and I believe I've worked out what you mean - essentially you're asking for `Screen#onClose()` to be overriden to use the parent screen that `ModListScreen` already has rather than `null` which causes a new `MainMenuScreen` to be created.

Essentially so we can avoid the following in `Minecraft#displayGuiScreen(Screen)`:
```java
      if (guiScreenIn == null && this.world == null) {
         guiScreenIn = new MainMenuScreen();
      }
```
With the helpful side-effect that the mods list could be opened in contexts other than the main menu too.

Looking at Minecraft itself, this is seldom implemented - though I would argue that it is best-practise to do so (especially to match Done / Escape behaviour), I'll make a pull-request shortly to address this.
