### ISSUE TITLE
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6692]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.87

**Logs:** https://gist.github.com/Darkhax/029b35d1c26340cfdf59aee8ec923b82

**Steps to Reproduce:**
 1. Try to start the game.
 2. Sometimes this happens.

**Description of issue:** When I launch the game it will sometimes throw this exception and crash. This specific log is from a dev environment with basically nothing in it. I've reproduced it across a few different projects however not consistently.

**Comment by BedrockLegends** [comment]
I have ran into this same issue on my packs

**Comment by LexManos** [comment]
Unable to reproduce in any of our tests. You're gunna have to dig into this.

**Comment by TheCurle** [comment]
Small update: it looks like this is caused by the early launch window, something about the state of the thread just before starting the game - meaning it's basically random. Will look into adjustments to fix this, and narrow down the exact cause

**Comment by josephtarbit** [comment]
I’m having this issue too, it’s very intermittent.

**Comment by Darkhax** [comment]
I am trying to get indepth OpenGL logs for this issue however attaching the program RogueLogic mentioned is not realistic to run 24/7. I did manage to reproduce it on 1.16.1. Here is a [1.16.1 log](https://gist.github.com/Darkhax/ae979215dadd056f2375c0fe7d9aa4f7).

**Comment by TheCurle** [comment]
We have sufficient logs (about 20 each for 1.15 and 1.16). We know it's caused by the early progress window so a `-Dfml.earlyprogresswindow=false` will work as a quick workaround. 

Without a proper GL debugging trace, though, we can't do much. Try as I might, most of the computers i can cause this error reliably on, are simply not fast enough to run the trace and cause the error before filling its drive. 

We *need* a proper trace, and we're trying. Expect updates on this.

**Comment by mrp-v2** [comment]
I consistently get this error, even on the latest 1.16.4 forge version, whenever I minimize the early loading window.

**Comment by TheCurle** [comment]
Looking into this with the provided dumps. https://mega.nz/file/9ZQyUD4I#9CNgPYHh1rXxahnuPVP-P5pXW14agVZmbWwX8OILpcE - Early Window Disabled
https://mega.nz/file/pAIUWBRT#bw62OiQf1WUJAAQ4n-h5ShSMjKjfrd94gdkPGJ-SRdM - Early Window minimised (seems to be a reliable reproduction of the crash for some people)

Thanks to Coziest Devil from Forge Discord.

**Comment by TheCurle** [comment]
More logs, courtesy of AterAnimAvis on the Forge Discord.
 https://mega.nz/file/lq4wlRiK#0c7VgV3E1u8hAV8dRd1ETNWemJ2On_DGZSZC7VpMk7w - Crash

https://mega.nz/file/BvoCgJQS#YFHSpdfNkeprIbxNVATf_57Op3yLdBaV03ULcmSbNuY - Early Window Disabled

**Comment by AterAnimAvis** [comment]
I can reliably reproduce by minimizing the EarlyProgressWindow when it appears (Seems like any point before the loading progress bars) and leaving it minimized.

**Comment by TheCurle** [comment]
I cannot reproduce this way. This needs more investigation.

**Comment by FinnT730** [comment]
Some more trace files: https://mega.nz/file/EwoySYDD#IXHXqgKHvK3d-bAAI1QcL7-vvYEW8kwoZK6TecaSUEo

**Comment by TheCurle** [comment]
Tagging @cpw to make sure he's aware of this influx of trace files.

**Comment by cpw** [comment]
mega logs are useless. I am unable to reproduce, this is likely something highly specific to a particular driver/OS combination. Someone expert in lwjgl will need to review.

**Comment by TheCurle** [comment]
"mega logs"? these are apitrace dumps as requested by you. :P

**Comment by FinnT730** [comment]
I sure do love the mega logs... :P

Anyway, they are the trace files

**Comment by TheCurle** [comment]
Okay, after some testing with a friend, this IS a VANILLA bug, but the creation of the Early window extends the interval in which this issue can occur. 
Working on a fix with some people in the Discord server.

**Comment by AterAnimAvis** [comment]
I believe I've found the issue. 

(Iconified is the term in GLFW for Minimized)

### Issue
The issue is an interaction with `GLFW#glfwGetFramebufferSize` and `OpenGL Framebuffers`.

- `GLFW#glfwGetFrameBufferSize` should/does return [0, 0] for the size if the window is iconified. (https://github.com/glfw/glfw/issues/931).
- Theses sizes get passed to `Framebuffer` on creation and it creates a texture of width 0, height 0 and tries to attach it triggering the crash.
- According to the [Khronos OpenGL docs](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glCheckFramebufferStatus.xml) `GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT` can occur when `... an attached image with a width or height of zero ...`

This issue can be [triggered programatically](https://github.com/AterAnimAvis/Forge6692/blob/testjar/src/main/java/forge/bug6692/mixin/AutoMinimizeMixin.java#L21-L25), on an effected machine, any point between Window creation and the `glfwGetFrameBufferSize` call. (This also means Vanilla can be effected)

### Fix

The fix is to call `GLFW#glfwGetFrameBufferSize` when the window isn't iconified.

We can restore the window if it is iconified before the `GLFW#glfwGetFrameBufferSize` before reiconizing it after if that was the original state (Note: this prevents issues with Maximized windows being reduced to a smaller size).

Heres the [fix as a mixin](https://github.com/AterAnimAvis/Forge6692/blob/testjar/src/main/java/forge/bug6692/mixin/FixCrashMixin.java#L24-L27) (Done as a `Mixin` so it can be easily distributed as a mod to check this actually works for all cases). 

[Fix as a Mod](https://github.com/AterAnimAvis/Forge6692/releases/tag/testjar) - drop this in your mods folder and it should fix the crash, Note: the mod should auto minimize the window before the `glfwGetFrameBufferSize` call so it should trigger the crash. You can add a -Dforge.bug6692.fix=false to disable the fix and -Dforge.bug6692.minimize=false to stop the auto-minimizing.

An alternative fix (Which may be technically incorrect) would be just to set the `MainWindow#framebufferWidth/Height` to  `MainWindow#width/height` when framebufferWidth/Height is 0 after the call to `updateFramebufferSize`

### Extra

I have no idea why this only occurs on certain machines as looking at the documentation it should be more prevalent.

Its probably worth checking the provided jar does fix this issue for everyone.
