### ISSUE TITLE
Classloading Issues (NoClassDefFoundError)

### ISSUE THREAD

**Issue by Raycoms** [MinecraftForge/MinecraftForge#6719]
**Minecraft Version:** {Minecraft version}
1.15
**Forge Version:** {Forge version. *Version number, not latest/rb*}
Any
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/0Chameleon0/942dfce57b0d78b688d002a2c1580a1e

We get, fairly regular reports for crashed due to "NoClassDefFoundError" I have heard other mods had similar issues already. It seems to be related to inner classes not being loading accordingly. This issue never persists so restarting always fixes it.

**Steps to Reproduce:**
 1. Random

**Description of issue:**

**Comment by someaddons** [comment]
maybe related to https://github.com/cpw/modlauncher/issues/42 ?

**Comment by mcenderdragon** [comment]
This also happened in 1.14.4.

**Comment by Aeltumn** [comment]
This issue really needs to be addressed, my mod crashed on 30% of startups on both 1.14.4 and 1.15.2. Different classes crash every time, here's an example error: (stacktrace just points to the first time this class is used)
`Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class nl.dgoossens.chiselsandbits2.client.render.chiseledblock.model.FaceRegion$1`
I think it is indeed related to inner classes not loading as I get this issue with lots of different classes but they're always inner classes.

I've "solved" this issue by forcefully loading all classes in my mod on startup, it does fix the issue for. But it's a hacky solution that I would like to remove asap if the issue is properly fixed.

**Comment by someaddons** [comment]
I've seen it with outer classes aswell, those are the few I've experienced the past month
https://gist.github.com/someaddons/b0f1fe2b55acbc22f1fd7b08afda9471
https://gist.github.com/someaddons/b07a2e8967141bab0f28a13954440116
https://gist.github.com/someaddons/43dad1dd0d3086dbc4c8578ee41ef8fa
https://gist.github.com/someaddons/5645fc1c1668df8a682bb00050c51881
https://gist.github.com/someaddons/6fd6cd764ea34509388a949e10173899
https://gist.github.com/someaddons/0cbe0e9e56aecb33b6ee99d0d58adc32
https://gist.github.com/someaddons/5a0f2bbad83704541d9b1a95cf27482f
