### ISSUE TITLE
I would like to request a Furnace Processed Event (Output item(s) produced)

### ISSUE THREAD

**Issue by Harmonised7** [MinecraftForge/MinecraftForge#6736]
There currently exists a `PlayerEvent.ItemSmeltedEvent` event, which triggers when a Player takes out a smelted itemstack from a furnace.

I would really like to see an event that is instead fired everytime an item gets processed by the furnace (example: iron ore -> iron ingot)

Extra reason why to implement this:
This event could be called ItemProcessedEvent instead, and would support any mods' items being processed into new items

**Comment by DaemonUmbra** [comment]
To me this sounds like something that should be handled by recipes

**Comment by KingLemming** [comment]
So, one of two things will happen here:

-Mods use such an event and modded servers instantly stop working because modded environments are *heavy* with instances where this event could in theory be called.

-Modders (correctly) ignore the event due to the above eventuality, and it remains unused, unsupported, and un-useful.

To elaborate, no this should not be added, and this can already be handled via the recipe itself if that behavior is so desired. No actual good can come from this event. It allows for recipe hijacking (I'm guessing this is a very misguided "ore unifying" feature) and will almost certainly cripple servers in a heavily modded environment if supported, hence why it won't be.
