### ISSUE TITLE
Unnecessary Smelting Recipe limitation

### ISSUE THREAD

**Issue by Orothuin** [MinecraftForge/MinecraftForge#6741]
[1.14.4]
IRecipe has the two methods `getCraftingResult`, `getRecipeOutput`. According to the coments 
the first one is meant to give the actual result of the recipe, via its `IInventory` parameter able to make the result depend on the ingriedent (like shield does). The second one is meant for displaying purposes. 
Now the problem is that when a custom recipe of `IRecipeType`: SMELTING is used, the `AbstractFurnaceTileEntity` Class just calls the `getRecipeOutput` when it should really call `getCraftingResult` like the CraftingBench does for example to process the shields.
Since` getRecipeOutput` does not provide any parameters it limits the modders possibilitys in working with the recipe. 
When looking into `AbstractCookingRecipe` one can see that the `getCraftingResult` is already used like it should but never called. So with that change I mentioned all recipes should still work, and one could maybe use `getRecipeOutput` as fallback, to make older customsmelting recipes still working and change it with a new Version.

**Comment by LexManos** [comment]
Smelting uses get output because it doesn't want you to mutate the input inventory while canSmelt is checked. It also doesn't want to you to change the output between the two because it'd cause weird things to happen during the process where the output couldnt be placed in the output or merges wrong.
