### ISSUE TITLE
FluidUtil#tryEmptyContainer() is ignoring the doDrain parameter 

### ISSUE THREAD

**Issue by desht** [MinecraftForge/MinecraftForge#6796]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.20

**Logs:** n/a

**Steps to Reproduce:**
 1. See https://github.com/TeamPneumatic/pnc-repressurized/issues/537

**Description of issue:**
`FluidUtil#tryEmptyContainer()` is ignoring the `doDrain` parameter and always transferring fluid to the destination fluid handler, even for simulated transfers.  This result in fluid dupe bugs under some circumstances (see linked issue report above).

**Comment by gigaherz** [comment]
FluidUtil needs a **major** redesign/refactor, changing the fluid handler API in the process if necessary. The current API makes certain things effectively impossible, which I didn't realize at the time because I'm not the right person to work on fluids (I have never used the fluid handler API in any of my mods). If anyone wants to give FluidUtil a complete makeover for 1.16, please do so!

**Comment by KingLemming** [comment]
What certain things are impossible right now? I'll see if I can actually get some time for 1.16...

**Comment by gigaherz** [comment]
I can't remember all the details anymore, but: there was one of the methods, I think the one mentioned in this issue, for which "simulate" needed to know the resulting stack after draining, but in order to know the resulting stack, the code had to duplicate the input. But removing the duplication caused the return value to be incorrect.
At the time, I tried to think of how to fix it, and I really wanted to scrape the entire FluidUtils, and start over from a list of requirements, seeing exactly what the system *needs*, and not try to patch up what it currently does. I really wish I could explain why I went "ugh, this entire thing is a mess", but I can't remember anymore.

**Comment by LordMonoxide** [comment]
I've worked/struggled with the fluid stuff in 1.15 a fair bit. Here's a couple issues:

- Things that are bucket-interactable implement `IBucketPickupHandler`. You can take the fluid from it by calling `pickupFluid`, but there's no way to check what fluid is inside before you do that. You get a fluid that you might not want, with no way to know how to put it back. For fluid source blocks, you can call `World.getFluidState`, but source blocks also implement `IBucketPickupHandler`, so it's possible that `World.getFluidState` could return something other than what `pickupFluid` returns.
- `pickupFluid` only returns a `Fluid`, so no amount or NBT
- `FluidUtil` only knows how to interact with `IFluidHandler` capabilities in the world. In 1.12 it also allowed interacting with fluid blocks, etc. Modders currently have to be aware of all the different ways fluids can exist in the world and work around the quirks I mentioned above.

This isn't an exhaustive list but I'm just having a quick break at work. If anyone wants to discuss improvements or rewrites, feel free to shoot me a message on Discord (Monoxide#4818). I'll contribute to a better implementation.

**Comment by Wabbit0101** [comment]
I have checked the code and this issue is still relevant because...**FluidUtil::tryEmptyContainer** is still calling the fludDestination TWICE with "execute=true" causing double the fluid to be added. A simple test I used was to set the max stack size of a vanilla water bucket to 2; gave myself a stack of two water buckets (it's important to have more than 1 stack size to branch to the broken code...); and then right clicked on an empty tank that used the FluidUtil::interactWithFluidHandler to implement most of its onBlockActivated logic. For that one bucket drain, 2000 mb is inserted into the tank.
(note: I did the water bucket hack just to eliminate possibility that the source item had a broken fluid handler)

Forge version: --fml.forgeVersion 36.0.7 --fml.mcVersion 1.16.5
FluidUtil.java: line 185

**Comment by sciwhiz12** [comment]
Reopening as issue still exists in 1.19, as PR #8955 was closed which would've forwardported the "fix" 1.18 PR #8318.

Note that according to comments on both PRs and a brief discussion I had with @Technici4n on the Discord server, it seems that the naive fix which passes `doDrain` as implemented in both PRs is technically incorrect. @Technici4n is working on a more proper fix which addresses the concerns from those comments for 1.19: #9004.
