### ISSUE TITLE
Cannot craft stone tools with blackstone

### ISSUE THREAD

**Issue by LotsOfCheese** [MinecraftForge/MinecraftForge#6894]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.38

**Logs:** https://pastebin.com/vDW3VkrD

**Steps to Reproduce:**
 1. Have sticks and blackstone in inventory
 2. Click on a crafting table
 3. Open recipe book, no recipe for tools show up
 4. Manually place sticks and blackstone in crafting table using any tool recipe shape, yields no result

**Description of issue:**
In vanilla Minecraft you are able to craft stone tools using blackstone since the Nether update. These recipes appear to be missing in the latest version of Forge.

**Comment by diesieben07** [comment]
The cause of this is that Forge overwrites the stone tool recipes to use the `forge:cobblestone`, which does not include blackstone.
Possible solutions/ideas:
- We cannot just include blackstone in `forge:cobblestone`, because that is really not intended (would change dispensers as well, for example).
- We could overwrite the `minecraft:stone_tool_materials` tag to extend from `forge:cobblestone` and not overwrite the recipe anymore.
- We could not overwrite the recipe at all and instead add a secondary recipe with `forge:cobblestone`, leaving both the original and Forge's recipe intact.

**Comment by Cyborgmas** [comment]
Weird, when I reran datagen (here https://github.com/MinecraftForge/MinecraftForge/pull/6865) the recipe for furnaces changed, since there is a vanilla tag for it now, but the recipes for tools did not

**Comment by marchermans** [comment]
@diesieben07 I think the best option would be to not override that recipe at all anymore. Since the way it currently stands that Tag exists for the specific reason to add materials to tool crafted with some stone like material, and if a modder wants to add support for it, they should add it to the tag themselfs.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/7b43b9f8c0a2a200ade96b0b3c497c724807f017
