### ISSUE TITLE
Bone meal drop block in 2nd hand

### ISSUE THREAD

**Issue by deedllit** [MinecraftForge/MinecraftForge#6947]
**Minecraft Version:** 1.16.1

**Forge Version:** 1.16.1.-32.0.61

**Logs:** None

**Steps to Reproduce:**
 1. Create a new world
 2. Put a sand block in your 2nd hand (shield slot)
 3. Use bone meal on grass or anything.
 4. Use bone meal on tall grass or full age crop

When bone meal is used it will drop the item store in the 2nd hand when it can't be use on the block you targeted.

**Comment by sciwhiz12** [comment]
As far as I can tell, this is vanilla behavior. Testing using the given steps reproduces the same behavior in vanilla Minecraft 1.16.1 and Forge 32.0.61. 
Either your expectations of how it should work is wrong, or you have misworded your issue; I've assumed that "drop" means "place", since your steps did not result in any items being dropped.

Regardless, please post your bug reports to the forums first. See the [FAQ entry][faqbug].

[faqbug]: https://github.com/MinecraftForge/MinecraftForge/wiki/Frequently-Asked-Questions#i-have-a-crashbug-and-none-of-the-above-applies

**Comment by deedllit** [comment]
yeah same bug in vanilla, i close it
