### ISSUE TITLE
[1.16.1] AnvilRepairEvent getInputItem().getItem() always returns AIR as input item

### ISSUE THREAD

**Issue by m1k3s** [MinecraftForge/MinecraftForge#6950]
**getInputItem().getItem()** always returns AIR regardless of the actual item input in AnvilRepairEvent. This makes using a conditional such as **if (event.getInputItem().getItem() instanceof 'actual item input')** impossible.

AnvilUpdateEvent works fine.

**Comment by DaemonUmbra** [comment]
Next time please use the template.

**Comment by sciwhiz12** [comment]
This issue goes much deeper that what is reported. `getInputItem()` will always return `ItemStack.EMPTY`, `getIngredientItem()` will return the remaining items in the ingredient slot (if the item is non-stackable or all the items are consumed, then `ItemStack.EMPTY` is returned), and setting the break chance does *nothing* (~~from what the code tells me, am verifying right now~~ verified, does nothing).

Apparently, the `AnvilRepairEvent` is called too late in the process, since by that time, the input item is set to `ItemStack.EMPTY` and the ingredient item is deducted according to the recipe (if it is more than required, the remaining item stack, else `ItemStack.EMPTY`). Additionally, the break chance is not referenced by the code following the statement; it is hardcoded to check `0.12F`. 
A patch would involve moving the call futher up, before the items are edited by the anvil container, and changing the hardcoded break chance to use the Forge-edited value. I will try make a PR for this.
