### ISSUE TITLE
Crying obsidian drops with incorrect pickaxe

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#7187]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.93

**Logs:** _N/A; in-game behavior_

**Steps to Reproduce:**
 1. Place a crying obsidian block
 2. Try to break it using a pickaxe below diamond level _(I suggest golden pickaxe for speed)_
 3. _Observe that the crying obsidian drops its item_
 4. Repeat steps 1 and 2 on Vanilla 1.16.1
 5. _Observe that the crying obsidian **does not** drop its item_

**Description of issue:**
Crying obsidian should only drop its item when broken by a pickaxe of diamond level and above. This is the case with vanilla; however, in Forge, crying obsidian drops when broken by a pickaxe of lower harvest level: iron, golden, stone, and wooden.

_This issue was first [reported on the forums][forumreport], and confirmed by me._

[forumreport]: https://forums.minecraftforge.net/topic/89092-crying-obsidian-can-be-harvested-with-any-pickaxe/

**Comment by TheCurle** [comment]
This is a known issue, harvestLevel is still dodgy.

**Comment by pupnewfster** [comment]
My best guess is that this is caused by forge not adding the corresponding harvest level for any of the new 1.16 blocks, not sure if crying obsidian is the only one or not. For reference where forge adds harvest levels: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/ForgeHooks.java#L208-L229

Looking at that method it also seems that harvest levels for hoes are not being set on any block for blocks that hoes are effective on.

**Comment by sciwhiz12** [comment]
I'm making a PR to fix this; should I only add the harvest levels for the new 1.16 blocks, or should I also include adding the harvest levels for the hoes?

**Comment by pupnewfster** [comment]
My suggestion would be add both, given hoes becoming a harvest tool is a 1.16 thing as well so logically makes sense to go with fixing their harvest levels while you are at it.
