### ISSUE TITLE
Removing structures leads to chunks being permanently unsaveable

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#7363]
This is a vanilla issue (MC-194811) but affects modded worlds a lot more often, so a fix should probably be made in forge.

In `ChunkSerializer.unpackStructureReferences`, the structure reference map `field_236365_a_` is queried but the resulting value is not null-checked. The result could be null if the mod that added that structure was later removed.

This means the returned map has a entry with key=null. Later on, when the game tries to save this (`ChunkSerializer.writeStructures`), it doesn't null check the keys of the map and blows up, meaning any progress made in this chunk is never saved.

Recommended solution: Add a null check to `unpackStructureReferences` and just skip it if the structure is not in the registry.

**Comment by TelepathicGrunt** [comment]
Mojang bug report of the issue: https://bugs.mojang.com/browse/MC-194811

Along with the null check, you can also have the chunk immediately save afterwards so that the missing structure reference can be removed from the chunk.

 Downside of this fix is it will not stop the log spam but that's still much better than an world that's unable to be saved. The second downside is it would mean any generated structure would lose it's chunk reference if the mod that made it is removed. (think ocean monuments no longer spawning Guardians forever if vanilla minecraft was a mod that was removed). however, very few mods actually use structure references to do these kinds of stuff so impact should be minimal anyway.

**Comment by TheCurle** [comment]
This was fixed with 56e538e8a9f1b8e6ff847b9d2385484c48849b8d.
