### ISSUE TITLE
[1.16.3] Config values range bug

### ISSUE THREAD

**Issue by Aizistral** [MinecraftForge/MinecraftForge#7367]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Logs:** https://gist.github.com/Extegral/49da83149b9dc246f227dbb93a4b127e

**Steps to Reproduce:**
 1. Make some config via `ForgeConfigSpec`;
 2. Add the value with defined range;
 3. Make this value to be used somewhere in the game;
 4. Lauch the game and enter into any world;
 5. Change the value in the config to be beyond defined limit and save it;
 6. Wait until it's called;
 7. Behold!

**Description of issue:**
As I have noticed, Forge automatically updates config values after they are changed in config file, without requiring to reload the world or whole client or server. I've used what I've found out as default config implementation, it basically looks as following:

```
public class ConfigHandler {
    public static ForgeConfigSpec COMMON;
    public static final ForgeConfigSpec.IntValue IMPORTANT_VALUE;
    
     ...
    
static {
        final ForgeConfigSpec.Builder common = new ForgeConfigSpec.Builder();

        common.comment("Very important stuff down there").push("Important Options");
        
        IMPORTANT_VALUE = common
                .comment("Important value. VERY.")
                .translation("configGui.somecoolmod.important_value")
                .define("importantValue", 4, 1, 100);

       common.pop();

       COMMON = common.build();

 }

}
```

```
public SomeCoolMod() {

       ...

       ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, ConfigHandler.COMMON, "somecoolmod-common.toml");

}
```

But when the values are updated after file changing, they are not checked to be within the range that they should. So, when you define a value like shown above, and simply call it somewhere like so:

`ConfigHandler.IMPORTANT_VALUE.get()`

The integer it returns may end up being beyond expected bounds, like zero, negative or bigger than 99. Values that are out of bounds are corrected upon [re]launching the client/server, but other than that, they effectively persist. Needless to say, it may break some things badly if one fully relies on the values bounds they have defined.

Even more than that, values could be defined as object they should not represent at all. You can easily enter boolean value in place of integer and end up with `ClassCastException` as soon as it get's called, instead of showing up the parser error in log file. Invalid keys like this are also corrected on startup, but for whatever reason this is not done when config changes after, naively trusting user's competence. The log refenced above shows an example of crash caused by this.

This issue is the exact duplicate of #6181, which I reported two major Minecraft versions ago, and which have never received any attention, later being marked as stale and closed. It seems to have never been addressed since.

**Comment by diesieben07** [comment]
I don't quite follow you here.
> But when the values are updated after file changing, they are not checked to be within the range that they should.

What do you mean by this? How are they being updated?

**Comment by sciwhiz12** [comment]
The problem here is the way that config file changes are detected and processed. 

When loading the config files, `ConfigFileTypeHandler` configures `FileWatcher` to run a `ConfigWatcher` runnable each time the config file on disk is changed (e.g. manually edited by the user). When `FileWatcher` detects that the file change, it runs the `ConfigWatcher`, which reloads the backing configuration object. 

However, because `ConfigWatcher` only reloads the backing configuration object, and neither calls `ForgeConfigSpec#correct` (to correct the values in the newly loaded config object), nor calls `ModConfig#setConfigData` which calls `ForgeConfigSpec#setConfig` which then calls `ForgeConfigSpec#correct`, **any changes to the config file on disk will not be corrected by the spec, and may be outside of the value ranges of the spec**, which may cause undesired/problematic behavior.

This behavior will hold for any of the config types; server, client, common. _However_, because the syncing of configs from logical server to logical client (such as for the `Type.SERVER` config) do use `ModConfig#setConfigData`, there is the possibility that the synced configs between the server and client do not match; in that the server config will have out-of-spec values, but the client config will be corrected and in-spec.
_(I actually discovered this bug a while ago, but I was busy on trying to do a [failed] attempt to fix the config corruption bug.)_

**Comment by Aizistral** [comment]
> What do you mean by this? How are they being updated?

Looks like @sciwhiz12 outlined it better than I ever could.

**Comment by scottctd** [comment]
I think I need to add another bug that I set the config min value to be 0 for example, but the actual config file gives me 
![image](https://user-images.githubusercontent.com/35100768/103601895-a1c03c80-4f45-11eb-91de-b1949c23c6d0.png)
which I think it should be Range >= 0.
And, I can actually set the value to 0.
