### ISSUE TITLE
[RFC][1.17] Removal of positional isAir.

### ISSUE THREAD

**Issue by LexManos** [MinecraftForge/MinecraftForge#7409]
Our hooks to allow tile entity based air have been around for a long time.
However, they were created in an age where we were limited to 4 bits for metadata.
A time where blocks themselves were limited to 256/4096. But now that both of those restrictions are removed I think it's time to align our hooks and modders more with vanilla's design.

As it sits, we require 50 patches for this one feature as is. Combined with another 130 that could be needed to deal with vanilla edge cases. This is very costly maintenance wise for a feature I am not sure anyone uses anymore.

So I'm proposing in 1.17, that we remove the positional arguments to isAir and use the state based system like most other block properties. Unless we get a valuable argument from this that isn't statistical fear mongering then it'll be headed for removal in 1.17. 

Update: As people seem confused, this is only asking people who OVERRIDE this function. It won't effect people who call this function. As callers do not need to know implementation of the isAir function.

**Comment by alcatrazEscapee** [comment]
One minor complaint: As of right now, both `BlockState#isAir()` **and** `BlockState#isAir(IBlockReader world, BlockPos pos)` are marked as `@Deprecated`. Both essentially pointing to the other and saying "use that one instead".

Given the positional one is being queue'd for removal, would it be possible to un-deprecate the non-positional one instead? As it stands, it's not really clear (imo) which one should be used, from a caller stand point.

**Comment by LexManos** [comment]
Unfortunately, for 1.16's life, modders should call the positional one.
In 1.17 it'll disappear, and thus become a compiler error. This is the best we can do for now.

**Comment by covers1624** [comment]
This is currently used in CBMultipart, when the block space has no more parts, it's marked as air. However, we manage things properly and remove the block/tile when empty to never hit this case anyway.
After discussing with CB, we likely added this to cover for some jankyness, and we can safely not use this anymore.

**Comment by LatvianModder** [comment]
![](https://i.latvian.dev/pc/2021-01-09_16.44.14.png)

Should this be un-Deprecated now?

**Comment by gigaherz** [comment]
No we can't un-deprecate isAir currently, because the positional patches are in place, so it's not recommended to use the non-positional variant right now. But the positional one is slated to be removed, so it's deprecated. Both need the deprecation, for different reasons.

**Comment by flowtender** [comment]
There's nothing for it in Java 8 other than to make a custom annotation like `@Experimental` or `@Beta` or `@NotYetUsed`. Java 9 added additional parameters for `@Deprecated` in `forRemoval` (boolean) and `since` (string) which could help to communicate these subtleties, but since we're bound to Java 8 by Vanilla, maybe an `@FutureStandard` annotation would be better?

Either way, completely removing a deprecated method in the same update that we enable the replacement isn't very graceful. Couldn't an intermediate step be to patch the current default implementation of `IForgeBlock.isAir(BlockState state, IBlockReader world, BlockPos pos)` to redirect to the state-only version, and moving the default implementation of the state-only version (`return state.getMaterial() == Material.AIR;`) over to the `AbstractBlock.Properties.create(Material material ...)` methods? Right now the default implementation of `.isAir(BlockState state)` on both `AbstractBlockState` and `AbstractBlock` just point at the state's `.isAir` field.

It's *possible* this will lead to bugs if people are setting `material == Material.AIR` and then overriding `.isAir(2 or 3 arg version)` but not the 1 arg version... but that method has been deprecated for a while now right?

**Comment by pupnewfster** [comment]
Closing as this has been done/implemented in the 1.17 branch.

**Comment by mgood7123** [comment]
is it possible to use `blockState.is(Blocks.AIR)` ?

**Comment by LexManos** [comment]
No
