### ISSUE TITLE
ModConfigEvent fired after registry events fired

### ISSUE THREAD

**Issue by FlashFyreMods** [MinecraftForge/MinecraftForge#7423]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.45

**Logs:** Not required.

**Steps to Reproduce:**
 1. Run the debugger of your IDE and put breakpoints on any registryevent (I used RegistryEvent.Register<Enchantment>) and a ModConfigEvent
2. You will notice the breakpoint in the RegistryEvent pauses the debugger first

**Description of issue:**
I noticed this issue when I was trying to make enchantments registered/unregistered using boolean values in the config. I bake the config values during a ModConfigEvent but because this is fired before RegistryEvent the values are obtained as "False" during this time.

**Comment by LexManos** [comment]
That is correct, you are explicitly told not to make config based registry objects.

**Comment by FlashFyreMods** [comment]
How would you recommend to enable/disable things like enchantments form being present in the game?

**Comment by LexManos** [comment]
Crafting recipes. Not adding them to itemstacks for loot or whatever. Or disabling them in the enchantment table via can apply or some other hook we have.
Point is all registry objects should always exist, so that if you say, connect to a server with different configs, you dont have issues.

**Comment by FlashFyreMods** [comment]
How would you prevent enchantments from spawning on books and being offered by villagers as a trade then?

**Comment by LexManos** [comment]
By not listing them in the loot table that generates the books, or the list of villager trades.

**Comment by FlashFyreMods** [comment]
So you're saying I should access the vanilla map of villager trades and replace the value for the librarian? Wouldn't that be awfully incompatible with other mods? 
I'm gonna try to use a loot modifier to iterate back over items from loot tables and remove the disabled enchantments that way, so I think that takes care of that. But afaik there's no simple way to "not list them in the loot table". You could override the vanilla loot table, which is incompatible with other mods. Vanilla loot tables use the EnchantRandomly loot function which I think just picks a random enchantment form the registry. So good luck "not listing" them.

**Comment by LexManos** [comment]
You shouldn't need loot modifiers to remove them from the tables. You should just NOT add them to the tables.
As for villager trades, if what you say is true, then it sounds like a case where we could add a hook.
The point still stands that you should be registering things always and then letting Forge/Vanilla build the registry as needed for the world/server.
Having a registry object just not exist because your config differs from the server means major hassle on the end users part. Where it could just automatically work.

Either way, move this to the forums or discord while you look into and flesh out what you want.

**Comment by FlashFyreMods** [comment]
I know exactly what I want. And I am not justifying the use of enabling/disabling objects from being registered. 
I don't think you understand how vanilla loot tables work. These are VANILLA enchanted books with the VANILLA EnchantRandomly function on enchanted books in them. I'm not making them. The EnchantRandomly function is applied which does [this](https://pastebin.com/bFE6k8TA) to an itemstack to be enchanted. As you can see it just picks a random enchantment from the registry with no other checks. So would you explain in this case how you would like me to "not add them to the table". Thanks.

**Comment by LexManos** [comment]
> ... if what you say is true, then it sounds like a case where we could add a hook.
> ...
> Either way, move this to the forums or discord while you look into and flesh out what you want.

**Comment by FlashFyreMods** [comment]
Yes I was referring to loot tables not villager trades where you aren't really explaining anything. Will pursue this on the forums or elsewhere.

**Comment by FlashFyreMods** [comment]
I asked in the Forge discord and I was told "you can't without hacks" in 1.15. Also forum page with a response: https://forums.minecraftforge.net/topic/92681-1152-no-way-to-prevent-enchantments-from-appearing-in-villager-trades-or-on-vanilla-enchanted-books/ 
What do you say now?

**Comment by pupnewfster** [comment]
The same thing he said earlier:
> then it sounds like a case where we could add a hook.

aka make a PR so that they can be filtered out of that without hacks. (Targeting 1.16.3 not 1.15 and then once that gets merged you can make a PR backporting it to 1.15 as that is how the LTS system works). Alternatively making an issue requesting that it is possible to filter that, and *hope* someone decides to make a PR implementing it, though that is likely to be a lot slower and depending on who ends up being the one implementing it, they may just implement it into latest and not also backport it to LTS which may leave you waiting even longer.

**Comment by TheCurle** [comment]
As I understand, 1.16 added some functions to make this easier. It's just a matter of backporting the vanilla helper functions, or at the very least their functionality.

**Comment by Tfarcenim** [comment]
Yep, vanilla added a method for both village trades and selection from loot tables directly into Enchantment.class, so it's not needed for 1.16.x since vanilla already has it, so a 1.15 backport would patch those methods back in and patch in the functionality to the relevant places so mods can make use of it.

**Comment by LexManos** [comment]
~~From the looks of it there is no such hook as you're talking about in 1.16.~~ NVM I found it. Now lets see if he tries in the slightest.
I've told Fla5hFyre to figure out what hes actually doing many times now. So i've blocked him from this repo for 24 hours.
During that time, I expect him to actually talk to other developers, or look at the code himself and come back with a better suggestion then "do it!"
If someone else wants to help out on his behalf, you all know how Pull Requests work.
Submit them properly.
