### ISSUE TITLE
[1.16.4] Using /give with EntityJoinWorldEvent set lifespan > 6000 ticks creates duplicate ghost item

### ISSUE THREAD

**Issue by ricksouth** [MinecraftForge/MinecraftForge#7481]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.0.15

**Logs:** N/A

**Steps to Reproduce:**
 1. Set the lifespan of an item in EntityJoinWorldEvent to above 6000:
```
	@SubscribeEvent
	public void onItemJoinWorld(EntityJoinWorldEvent e) {
		World world = e.getWorld();
		if (world.isRemote) {
			return;
		}
		
		Entity entity = e.getEntity();
		if (entity instanceof ItemEntity == false) {
			return;
		}
		
		ItemEntity ie = (ItemEntity)entity;
		ie.lifespan = 6020;
	}
```
 2. Load the event and use /give @p minecraft:diamond_sword 1. Or any other item.
 3. The result with the example code will be a ghost item lasting 1 second (20 ticks). The player will still receive the item and the ghost item will not be able to be picked up, even after a reload of the world. Setting the lifespan to less than 6000 in the event will result in normal behaviour.

**Description of issue:**
If you increase the lifespan to for example 6100, the ghost item will remain for 5 seconds. I assume this means that 6000 is extracted from the lifespan if an item is picked up, instead of setting the lifespan to 0.

Here's an extra GIF showing the ghost item will appear for 2 seconds after using /give with a lifespan of 6040:
https://i.gyazo.com/e59616e99f3752f70d9ba53ad5abd2ba.gif

**Comment by diesieben07** [comment]
`/give` first tries to put the item in the player's inventory directly - if it can do so it creates an item entity that is only used for visual purposes: It has a special value for pickupDelay (Short.MAX_VALUE) which is used to denote "forever", i.e. it can never be picked up. Additionally it's `age` is set to 1 tick less than the maximum lifespan (which is 6000 by default). so the entity will just show up very briefly for one tick - as a visual hint. If you increase its lifespan it will remain for that much longer, but still can't be picked up (and won't combine with others, for that matter). You still get the item, because `/give` actually gives it to you directly, you are not picking up an item entity at all when using `/give`.

Only if the item you are given does not fit into the inventory fully is an actual item spawned which remains and can be picked up.

**Comment by ricksouth** [comment]
@diesieben07 Thanks for the explanation. Does this mean the issue can't be resolved? I've read that there are certain mods which allows animals to pick up the ghosted /give items created with a higher despawn timer. Or do you have a different solution?
