### ISSUE TITLE
Multi-Layer model datagenerators incorrectly write submodel children to disk

### ISSUE THREAD

**Issue by itsmeow** [MinecraftForge/MinecraftForge#7493]
**Minecraft Version:** 1.16.3

**Forge Version:** 31.1.42

**Code to reproduce:**

```java
this.models().withExistingParent("example", "minecraft:block/block").customLoader(MultiLayerModelBuilder::begin)
            .submodel(RenderType.getSolid(), this.models().withExistingParent("somename", "whisperwoods:block/wisp_lantern_wall"))
            .submodel(RenderType.getTranslucent(), this.models().withExistingParent("somename2", "minecraft:block/block"));
```

**Resulting JSON:**

example.json

```json
{
  "parent": "minecraft:block/block",
  "loader": "forge:multi-layer",
  "layers": {
    "solid": {
      "parent": "whisperwoods:block/wisp_lantern_wall"
    },
    "translucent": {
      "parent": "minecraft:block/block"
    }
  }
}
```

**Unexpected behavior:**

The submodel JSONs are also written as separate files even though they are already included in the parent.
![image](https://user-images.githubusercontent.com/10366817/99162435-cfb69c80-26cb-11eb-9c1f-acd78e8a10c7.png)

somename.json

```json
{
  "parent": "whisperwoods:block/wisp_lantern_wall"
}
```

somename2.json

```json
{
  "parent": "minecraft:block/block"
}
```

**Comment by itsmeow** [comment]
Another extension of this issue is that in order to have functional submodels, the name of the submodel has to be globally unique otherwise all resulting files will contain the parent of the last file that used that name. The name should only be unique to the submodel itself. (ex: if the second submodel has a name of "somename" and not "somename2", the solid layer would have a parent of "minecraft:block/block", erronously)

**Comment by sciwhiz12** [comment]
This issue is caused by your use of `BlockModelProvider#withExistingParent`. That method eventually calls `ModelProvider#getBuilder`, which returns a (in this case) `BlockModelBuilder` that is internally cached by the model provider and, as a result of being cached, will be written to disk by the datagenerator.

A solution would be to create the `BlockModelBuilder` yourself using its constructor, which prevents the model being cached by the model provider (and therefore prevents it from being written to disk). _(For this, I'd suggest making a helper that imitates what `ModelProvider#getBuilder` does, but without the caching to the `generatedModels` table part)_

I also suggest probably adding a javadoc or helper to the `MultiLayerModelBuilder` (and other classes which are also affected by this) to use this given solution when making their block model.

**Comment by gigaherz** [comment]
I added a `nested()` method to help with that. See <https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/test/java/net/minecraftforge/debug/client/model/NewModelLoaderTest.java#L247-L252>

**Comment by itsmeow** [comment]
Nice! Thanks :)
