### ISSUE TITLE
[1.16.4-35.0.17] - EntityMinecart.registerCollisionHandler does not exist, contrary to documentation

### ISSUE THREAD

**Issue by SnapperTT** [MinecraftForge/MinecraftForge#7506]
The documentation of `IMinecartCollisionHandler` (see the java file) instructs you to register it with `EntityMinecart.registerCollisionHandler`, however `EntityMinecart` no longer exists (replaced by `AbstractMinecartEntity`), and it has no such method.

Forcing a registration by directly assigning `IForgeEntityMinecart.COLLISIONS = ...` is not permitted by the compiler despite the static member being declared public.

Forge version: 1.16.4-35.0.17

Relevant files:
net.minecraftforge.common.IMinecartCollisionHandler
net.minecraftforge.common.extensions.IForgeEntityMinecart
net.minecraft.entity.item.AbstractMinecartEntity

EDIT: I have made a workaround a week ago on my end by using a mixin. If this is a nofix or something that is halfway through a feature rewrite I would appreciate it if the comments in the files were updated instructing the modder to not use this for the time being.

**Comment by sciwhiz12** [comment]
The move of the global `IMinecartCollisionHandler` from the `EntityMinecart` class to `IForgeEntityMinecart` was done in b6ddb0a7cf2b1ff353ff450c895c09f55753c7e9 (which created the aforementioned interface), which was in _2018_. It seems that nobody used that field, and therefore didn't find that error about it, until you did.

The fix here would be to move the field and getter back into `AbstractMinecartEntity`, since it cannot exist in the interface due to all fields in interfaces being implicitly `public static final`.

**Comment by TheCurle** [comment]
I made #7748 to address these concerns. The current minecart system is a little bit of a mess, but we can work it out...
