### ISSUE TITLE
1.16.4 - 35.1.0 : Ender Dragon does not spawn on a dedicated server.

### ISSUE THREAD

**Issue by Jusey1** [MinecraftForge/MinecraftForge#7510]
Minecraft Version: 1.16.4
Forge Version: 35.1.0.
Logs: N/A (this isn't a crash and doesn't show up anywhere on logs when I read them).

This is a rather straight forward issue and a major one that is... Essentially, the Ender Dragon boss just doesn't spawn on a dedicated online server with Forge. The game and server still runs just fine but she just doesn't spawn. Her little bedrock pedestal doesn't spawn. Everything else in the End works. The Obsidian pillars spawn with the End Crystals and technically the Ender Dragon herself does work if you /summon her but she will have no health bar and defeating her like this doesn't spawn an exit portal or gateway, which means it is pointless.

She works as intended in singleplayer at least but in an online forge server...? She simply doesn't exist. I originally thought this was a mod until I tested my server with no mods installed, just Forge and yeah... She isn't there.

**Comment by TheCurle** [comment]
Confirmed. Looking into this.

**Comment by xjcl** [comment]
Thanks a lot to the reporter and maintainers for fixing this. I was fiddling about with a mod that modifies spawn rates (InControl! to be exact) and was just going crazy trying to add rules to force the dragon to spawn.

Any way to change the recommended Forge download on the website from 35.1.0 to 35.1.5? I think this issue is severe enough to deprecate 35.1.0.
