### ISSUE TITLE
[Linux/X11] Forge messes up Minecraft Window Class breaking Window Manager Rules

### ISSUE THREAD

**Issue by Janfel** [MinecraftForge/MinecraftForge#7531]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.1.0

**Logs:** N/A

**Steps to Reproduce:**
 1. Start Minecraft with Forge
 2. Read out window properties with `xprop`

**Description of issue:**
The `WM_CLASS` property reads "FML early loading progress", where it would be "Minecraft 1.16.4" for Vanilla Minecraft. This makes breaks any window manager rules targeting Minecraft windows and makes it impossible to differentiate based on the Minecraft version.

**Notes:**
When using Minecraft 1.14.4 with Forge 28.2.0, the window class starts out as "FML early loading progress", but then correctly switches to "Minecraft 1.14.4". This switch does not happen with the versions listed above.

**Comment by LexManos** [comment]
Just confirming that it does switch just fine for me, and the intended mechanic is that it switches.
![](https://i.imgur.com/nYH72U4.png)

So you'll have to look deeper into your drivers or lwjgl for not updating the name.
And wait for someone on linux who can reproduce this to take a look.

**Comment by diesieben07** [comment]
GLFW started setting WM_CLASS here: https://github.com/glfw/glfw/commit/8194f1e2ae72715efbcc03de34c9a8e5bd8e8de5
It's officially called a "hack", because GLFW has no way to specify the application name - so they just use the first window title.
So really this is a missing feature in GLFW.

Edit: Apparently there is a way. See PR.
