### ISSUE TITLE
Foxes do not post LivingEntityUseItemEvent's when eating item.

### ISSUE THREAD

**Issue by Lemon-Lord** [MinecraftForge/MinecraftForge#7540]
My request is that the appropriate event posts be added to the "fox eating item" logic present in FoxEntity.java. Players, Skeletons and Pillagers seem to be the only entities that set off the event but are not the only entities that use items in the game.

**Specifically**, I would like the following line of code to be present between theses two lines in `net.minecraft.entity.passive.FoxEntity`:
![image](https://user-images.githubusercontent.com/62090471/101517812-e56a6980-39cc-11eb-9ad1-0e59ddc0bca6.png)

```
net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(new LivingEntityUseItemEvent.Finish(entity, item, duration, result));
```

Or, alternatively, replace lines 187-190 of the following with the already implemented `onItemUseFinish` method FoxEntity inherits from LivingEntity:
![image](https://user-images.githubusercontent.com/62090471/101518837-29aa3980-39ce-11eb-8245-bdf429cfaddd.png)

It's possible this second implementation would cause some discrepancies as foxes do not eat with their hands so I chose to mention it second, though if it does work, I find it likely it would be a more sound solution.

I am laughably new to modding though so if I got the code wrong or the line I wrote would better go somewhere else, I apologise. Event bus posting in the appropriate places for `LivingEntityUseItemEvent.Tick` and `LivingEntityUseItemEvent.Start` would possibly also be useful for other creations, just not mine and I'm not actually sure where in the code they should be run.

Thanks a million :)

**Comment by diesieben07** [comment]
Unfortunately foxes do not use the normal "use item" mechanism, which would involve many more events than just `LivingEntityUseItemEvent.Finish`. For a consistent view from the outside, the code would have to be completely changed to actually use the normal "use item" mechanism used by other entities.
Witches are another entity that do "use" items (they drink potions), but completely bypass the normal "use item" mechanism.

What is your use case for this?

**Comment by LemonLord1** [comment]
It’s strange that foxes, skeletons, witches, players, piglins and pillagers (I could be missing a few) all use items but only four out of six of them run the event. It is a little inconsistent and perhaps inconvenient for those starting out modding but as it turns out, I no longer need it.

What was my use case for this? I wanted to have a way to automate eating certain items that felt integrated with vanilla. Foxes already ate items with no player interaction, seemed like a good match. Do not need events to do this though, SpongeForge mixins work just fine.

You’re right though, foxes do not use items and then finish using items, they use a separate mechanic entirely that would likely be very hard to modify. I’ll go ahead and close this issue as I think we agree its  benefits do not justify its difficulty to implement.

Tangent:
That’s very bizarre that witches don’t. I understand why they wouldn’t run the event as that’s up to the Forge team to implement it not but why they don’t run the `ItemStack#onItemUseFinish` method is on Mojang. They just grab the effects from the item instead of actually using it, that’s a strange mechanic. I’m sure there’s a justification but I don’t expect you to explain it to me.
