### ISSUE TITLE
Command redirect Issues

### ISSUE THREAD

**Issue by Darkere** [MinecraftForge/MinecraftForge#7551]
**Minecraft Version:**1.16.4

**Forge Version:** 31.0.7

**Steps to Reproduce:**
```java
LiteralCommandNode<CommandSource> command = dispatcher.register(LiteralArgumentBuilder.<CommandSource>literal("test")
            .requires(x -> x.hasPermissionLevel(4))
            .then(Commands.literal("one")
                .executes(ctx -> {
                    ctx.getSource().sendFeedback(new StringTextComponent("Working"), true);
                    return 1;
                })));
        dispatcher.register(Commands.literal("te")
            .redirect(command));
```

**Description of issue:**
With the setup above the command `/test one` is as expected inaccessible to people without permission level 4.
The redirect below however is NOT restricted. So `/te one` is working even without permissions. <- this does not synchronize the client making it very difficult to recognize (if it was intended at all).

I'm unsure if this is a bug in Brigadier or caused by forge's changes to commands. 

EDIT: Also might be related. Redirects to intermediate commandnodes don't sync either.

**Comment by diesieben07** [comment]
This seems to be either a bug or intended behavior in Brigadier. A CommandNode with a redirect still has its own `canUse`, which is used, not the redirect.

**Comment by Darkere** [comment]
If it was intended it should be synced to the client.

**Comment by diesieben07** [comment]
`Commands#commandSourceNodesToSuggestionNodes` checks `CommandNode#canUse` for all commands it processes. Since the redirect target will have that evaluate to `false`, it won't be processed. Then later when the redirect is checked, the `commandNodeToSuggestionNode` map does not contain the redirect target (since it was skipped), so the redirect source gets created with `redirect(null)`. So this code is bugged, it must also include redirect targets, even if they themselves have `canUse` false, if the redirect source has `canUse` true. This is not trivial to implement with the current structure of that code.

**Comment by lclc98** [comment]
This seems to be caused in Commands#fillUsableCommands because of the way it is looping in alphabetical order (being sorted at the bottom of CommandNode#addChild) so the CommandNode map doesn't contain test yet, so te fails to have a target so it can't suggest test arguments. You can temporarily fix this by registering the LiteralCommandNode to te and use test as the alias instead.

**Comment by sciwhiz12** [comment]
A investigation reveals that, while this issue still exists on 1.18, there is a potential solution for this in the form of existing code in Forge which can be adapted to replace `Commands#fillUsableCommands`. 

[`ClientCommandHandler#mergeCommandNode`][mergeCommandNode], used by the client commands feature, can fulfill the same purpose as `Commands#fillUsableCommands`, but with the added feature of handling command redirects properly by visiting the redirect target node (instead of the vanilla method's behavior of blindly pulling from the map, which may not have an entry for the node at that point as noted above).

Locally testing this in a singleplayer scenario shows that the issue is fixed when `fillUsableCommands` is substituted for `mergeCommandNode`: the argument/literal subcommand is correctly suggested for `te one`. For reference, the following is the snippet I had in `Commands#sendCommands` for testing _(the `if`-expression was to avoid commenting out the `mergeCommandNode` call, which would have caused hotswap failures due to lambdas)_:

```java
if (true)
this.fillUsableCommands(this.dispatcher.getRoot(), rootcommandnode, p_82096_.createCommandSourceStack(), map);
else
   net.minecraftforge.client.ClientCommandHandler.mergeCommandNode(this.dispatcher.getRoot(), rootcommandnode, map, p_82096_.createCommandSourceStack(), ctx -> 0, suggest -> SuggestionProviders.safelySwap((SuggestionProvider<SharedSuggestionProvider>) (SuggestionProvider<?>) suggest));
```

I will note that this solution would need some amount of refactoring in order to extract `mergeCommandNode` and its related methods into a class that does not reference client-only classes, and would mean `mergeCommandNode`'s access level would be raised to `public`.

[mergeCommandNode]: https://github.com/MinecraftForge/MinecraftForge/blob/3b754fef5e5008259a0cc6f4830140d06078e92c/src/main/java/net/minecraftforge/client/ClientCommandHandler.java#L173-L174
