### ISSUE TITLE
[RFC][1.17] Removal of Capability Storage/Default Factory

### ISSUE THREAD

**Issue by LexManos** [MinecraftForge/MinecraftForge#7622]
So, the entire point of the Storage/Default system in capabilities, was to hopefully force modders to document and give an example of their capability. That didn't seem to ever happen. So I'm proposing in 1.17, we just strip both those functions out. Unless there is a compelling reason to keep it. 

Basically it would be the removal of:
Capability.IStorage
Capability.getDefaultInstance
Capability.getStorage
Capability.readNBT
Capability.writeNBT
And the change to CapabilityManager.register to just take in Class<T> type.

Additional question: 
Should we force capabilities to be Interfaces. Right now it could be either as we don't validate the type. But we could easily add a  `if (!type.isInterface()) throw IAE` to CapabilityManager.register.
This would somewhat point people in the correct dimension that these capabilities SHOULD be interfaces {Ideally with good javadocs}, not concrete classes.

**Comment by Alpvax** [comment]
I always found the default unhelpful, because I needed to pass in additional data (usually whatever I'm attaching the capability to).
As for storage, the only advantage that could have given is for different implementations to use the same storage, but generally that is done with inheritance.
Personally, I'm in favour of removal.

**Comment by gigaherz** [comment]
I'm all in for it. I understand the intention, but I haven't really encountered the situation where I want to expose an API that would truly benefit from default instances. All my use cases always require at least an instance of the parent object (usually a PlayerEntity) passed into the constructor (to be able to make the owner a final field), and making the capability API use Function<Object, T> would be rather untypesafe.

**Comment by josephtarbit** [comment]
Forcing interfaces seems like a good idea to me. I see a lot of people miss-using capabilities and using concrete classes.

**Comment by gigaherz** [comment]
> Forcing interfaces seems like a good idea to me. I see a lot of people miss-using capabilities and using concrete classes.

Oh I missed that last bit from Lex's message. I would have to disagree with that part. In many cases (at least many of *my* use cases) a capability isn't a public API, but rather the only way we have to attach a concrete data object to a thirdparty object, and that data is never meant to be accessed by other mods because it contains *only* implementation details.

I may be overthinking this, but if we require that all capabilities are designed as public APIs, then it feels like we should also have some parallel API, which is designed for attaching "plain data"?

Example: In one of my mods I have a pair of non-serializable capabilities, a World capability and a Chunk capability, for managing a list of special blocks currently loaded in memory. The Chunk capability allows the data to be automatically discarded when the chunk unloads, keeping the memory tidy without risk of leaks, while the World capability provides the actual API -- although this API is only meant for internal use, but I can't discount other mods wanting to access it, to implement Addons for mine. Accessing the list in Chunk without going through World would actually cause problems, and possibly crash if done at the wrong time.

**Comment by TheOnlyTails** [comment]
What would this change mean to the average modder? What would we have to change in our code?

**Comment by josephtarbit** [comment]
That’s true, perhaps the parameters of Capability usage should be adjusted. At the moment they are very targeted at providing an API, hence the name “Capability”.

**Comment by 3TUSK** [comment]
> Should we force capabilities to be Interfaces

In case that you use capability solely to store extra data on entities (think thirsty, skills, etc.), it would sound superfluous to use an interface. Thus I don't agree with forcing interfaces.

As for gigaherz's

> some parallel API, which is designed for attaching "plain data"

If my memory holds, one of original goals of capability system is to phase out the old `IEntityAdditionalData` whose purpose is exactly "attaching plain data" (to entities only, tho). 
As such, having such a parallel API sounds like "going back to the dark ages" to me.

**Comment by LexManos** [comment]
With 1.17's announcement for next week, I wanted to do one final call for comments on this.
The current state of my decision is that we remove the serialize/default instance because people can't understand the original intent.
And we do not force interfaces because others like using it for simple data.

**Comment by pupnewfster** [comment]
Closing as this has been done/implemented in the 1.17 branch.
