### ISSUE TITLE
Config files keeps making bak files inconsistently for my mod

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#7669]
My mod is Repurposed Structures and I am using Forge's config system to create multiple config files for my mod. The issue started with Forge 1.16.5-36.0.39 as before then, no bak files were made. 
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

![image](https://user-images.githubusercontent.com/40846040/109433860-82430e80-79e0-11eb-9b38-adeb215fd79b.png)

After doing some extensive testing, the configs for my mod still works and doesn't get nuked or anything. Just extra bak files gets created but not affect anything. The creation of the bak files are also inconsistent as well. First time I load Forge 36.0.39, three config files gets bak. I restart the game and now only 1 of the previous config file gets a second bak and several new config files gets their first baks. Third time, 2 more gets a second bak and others gets their first. Very odd.

Here's my latest.log file. It only mentions that it is correcting config files but doesn't say what is incorrect or invalid.
https://paste.ee/p/UC8XD

My config registration:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/13adb79556c2f087ac72daf276109f85297153e8/src/main/java/com/telepathicgrunt/repurposedstructures/RepurposedStructures.java#L79

The ConfigHelper class I got from a friend to make doing configs less verbose:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/master/src/main/java/com/telepathicgrunt/repurposedstructures/utils/ConfigHelper.java

My config file setup (using ConfigHelper to make it less verbose):
https://github.com/TelepathicGrunt/RepurposedStructures/blob/13adb79556c2f087ac72daf276109f85297153e8/src/main/java/com/telepathicgrunt/repurposedstructures/configs/RSMainConfig.java

I cannot tell exactly what NightConfig is thinking is broken in my config files and looking over my config files, I cant seem to find what the issue could be. Would it be possible to make Forge have an option for printing additional info to the log on what it thinks is broken in config files?

**Comment by TheCurle** [comment]
The only thing your configs (that are creating backups) have in common is that they define an empty list as a default.
According to the [ForgeConfigSpec:](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L338) that's an invalid state.
Perhaps this should be changed?

**Comment by TelepathicGrunt** [comment]
(Continuing from the conversation on discord)
I used a String for blacklistedDimensions, blacklistedFortressBiomes, etc. But what was suggested is that by me using "" for the string's default in blacklists, it gets parsed as null and creates the empty list in the backup. At least, that's the theory. Very odd and might had been a hidden problem until Forge 36.0.39 reported it.

**Comment by ModernGamingWorld** [comment]
I think it has something to do with this pr request that got pushed through, I noticed mods breaking after it happen https://github.com/MinecraftForge/MinecraftForge/commit/d2cfda3fb47d2006adbbe8ee3289f7218ba77f1e

**Comment by TelepathicGrunt** [comment]
Forgot to close this. Forge 1.16.5-36.0.53 fixed this issue

**Comment by P3rf3ctXZer0** [comment]
This is not fixed - I am experiencing the same issue in 2-3-2023 on 1.16.5 forge 36.2.39 all the way through 1.19.3 44.1.8

**Comment by AterAnimAvis** [comment]
This **is** considered fixed on our side <https://github.com/MinecraftForge/MinecraftForge/pull/7671> (36.0.51+), if your still encountering the issue then it's likely a mod issue (commonly it's not using the specifc defineList / defineListAllowEmpty for Config options instead using the generic method, or using Floats instead of Doubles for config values).

**Comment by P3rf3ctXZer0** [comment]
Okay so you consider it fixed - but it does not happen with any specific mod also it does not happen consistently ... so how is that fixed? Could more than one variable be at fault and you only fixed a specific variable? When high esteem modpacks Like FTB and ATM6 - ATM8 suffer this issue - when mods like McJity based mods and other skilled devs have this issue it cannot be a one off. Its just not possible.

**Comment by TelepathicGrunt** [comment]
@P3rf3ctXZer0 Do not use Notepad++ to edit the config. The NightConfig library that Forge uses doesn't work well with Notepad++'s way of editing files.

**Comment by P3rf3ctXZer0** [comment]
These are files I never edited --- also WHAT? Why is that the case? Links please cause this is the first I am hearing about it.

So I did my own research its not that Notepad++ its that some users are not understanding to close the app before opening forge causing a "File cannot be accessed" bug. I personally have never ever experienced this personally but then again I am not clueless to the windows file system.

Okay so apparently this is an issue in a strange way. https://github.com/MinecraftForge/MinecraftForge/issues/8535 this doesn't account for files that I never touched XD

**Comment by TheCurle** [comment]
Notepad++ also has some other issues; it occasionally inserts a BOM into files that don't use UTF-BOM encoding, which makes NightConfig trip out on parsing; and occasionally it just errors out entirely and replaces the config file with 11 `NUL` characters.

Note also that modders like McJty (no offense to them) are not infallible, and in fact game-breaking bugs have been found uncountably many times in "highly esteemed" (as you put it) modpacks like All The Mods or Feed The Beast.

For example, Quark (a mod by Vazkii, one of the most popular mods and authors!) did this exact config situation so badly in the past that it bypassed all of the fixes I implemented! 

Truth is, I've gone to the ends of my wits to debug this exact issue, spending over 170 hours trying to find every edge case and possible issue in our config system that could lead to backups, and I believe I found them all.

If configs are generating BAK files, it's because modders are doing something wrong. It's definitely not Forge's doing any more.
