### ISSUE TITLE
Registry load order prevent proper usage of DeferredRegistries for worldgen

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#7674]
Currently, the registries are non-deterministic and parallel which sounds great on paper but in reality, it has been causing severe issue for worldgen modders who wish to make their biomes in code instead of json. 

Specifically, the issue becomes very apparent when making custom Features or Structures for a biome and try using DeferredRegistries for all of them. When the biome registry fires, the biome's builder is ran which requires modders to add ConfiguredFeatures or ConfiguredStructures to it. However, those configured forms requires the base Feature and Structure. The issue is that those registries has not fired yet and thus, those RegistryObjects are null for the two. I have made an example mod here to demonstrate the issue.
https://github.com/TelepathicGrunt/biome-init-test

Here are two console outputs for when the initialization error is on the Feature or Structure.
https://paste.ee/p/4xlI9
https://paste.ee/p/YcnO1

To make matters worse, it impacts all of the worldgen registries shown below. 
![image](https://user-images.githubusercontent.com/40846040/110192850-aa76a700-7dfe-11eb-86a2-a43821d6f47d.png)

The only workarounds for code based biomes to work is for people to not use DeferredRegistries or to abuse BiomeLoadingEvent. I wish I was kidding about the last part but I just recently came across mods using that event to fully populate their own custom biomes and broke compatibility with another mod that was trying to check if the biome had Mineshafts (due to the first mod's event firing after the second mod's and thus, skipped their Mineshaft check). BiomeLoadingEvent also make it impossible for players to customize the biome by using json as well which is why that should be discouraged as much as possible.

If DeferredRegistries are to be encouraged (and they should), the registry load order will need to be changed so that the biome registry is always after all the other worldgen registries. Or alternatively, and I do not know if this is a good idea, perhaps an alternative class instead of RegistryObject that works with DeferredRegistry could be considered so that people can keep the clean style of DeferredRegistries and still have the references they need for worldgen.

**Comment by Tslat** [comment]
I really don't think this would work out properly lol

What about if we have a biome factory registration, where you can pair biome ids to a biome factory - that way the biome can be done via datapack as normal, but instead of having a default Biome instance, you get an instance of your own custom class, for whatever dynamic stuff you need?

**Comment by 50ap5ud5** [comment]
I can concur this is an issue. I previously wanted my biome to use a custom surface builder, but the Surface Builder Deferred Registry is always fired after the Biome Registry, which means my Surface Builder is always null when my Biome Builder is being called.

The way I worked around this issue was by static initialising the Surface Builder and not giving it a value, then passed it around until the Surface Builder Deferred Register was fired. That was pretty hacky so I ended up having to use Json biomes instead.

- [Biome Builder that was forced to use a statically initialised Surface Builder](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/ecca011e716a46c792ab331d8c1a140ac1378dc8/src/main/java/net/tardis/mod/world/biomes/TBiomes.java#L62)
- [The statically initialised Surface Builder I had to make to prevent NPEs](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/ecca011e716a46c792ab331d8c1a140ac1378dc8/src/main/java/net/tardis/mod/world/surfacebuilders/TSurfaceBuilders.java#L24).

If we are to encourage the use of Deferred Registers for World Generation objects, then it is important that issues like this should be addressed.

**Comment by Tslat** [comment]
Why couldn't you have just done that via json?
It seems to me a big chunk of the issue is people refusing to use the proper system for making biomes or other worldgen objects

**Comment by pupnewfster** [comment]
> Currently, the registries are non-deterministic and parallel which sounds great on paper but in reality, it has been causing severe issue for worldgen modders who wish to make their biomes in code instead of json.

Registry event order is both deterministic and not parallel https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/registries/GameData.java#L351-L364

**Comment by TelepathicGrunt** [comment]
@Tslat Indeed but however, not everyone knows about the worldgen datapack system and some people despise json in all of its form for no reason. I can't really think of any cases that json biomes can't really cover except for extremely dynamic stuff like creating structures based on what mod is on or some weird stuff like that. 

For the most part, people could even just do dummy configuredfeatures using vanilla features and then have the json override that in their own code-based biomes. But that's more niche knowledge from when I talked to others

(edit: I was misunderstood by others. I'm not trying to say we should stick with code biomes but trying to give reasons why people may want to. Json biomes should be encouraged but there is a lack of documentation and tutorials about them for modders)
  
@pupnewfster ah my apologies. I have been lied to by a different Forge Triage member. RIP. Then it is just a matter of re-ordering the registries.

**Comment by LexManos** [comment]
Registries will not be reordered.
Use the json system. You can generate your jsons via code. That's the whole point of the data gen systems.
But beyond that, registry order should have no effect on your systems that use it. As things should be using suppliers/delegates to alllow replacements.
