### ISSUE TITLE
Ore Placeholder Blocks

### ISSUE THREAD

**Issue by ChrisBkt** [MinecraftForge/MinecraftForge#7675]
Sometimes, you want to add a mod after starting with the modpack.
Often, the chunks around you are already generated, so its hard to find new ores from the modpack.
Maybe, it's possible to add "placeholder blocks" of the type stone, so when stone is being generated, there's a little chance that the stone block get a nbt tag "ore_placeholder" so that mod creators can implement a feature, when the mod get loaded first time, it'll use these placeholder blocks.

**Comment by ChrisBkt** [comment]
*If the feature isn't already exist...
I'm not sure

**Comment by Alpvax** [comment]
This would be hard to implement in a good way, because ores do not generate the same from every mod.
If this is something that might be used, it would be better in a separate mod, not built into forge.

I could maybe see an argument for a new post-generation event, called the first time after the mod is added, but I personally think that it is too much effort for such a small return (there would be a lot of potential issues). It is always better to start a new world after adding/removing mods.

**Comment by LexManos** [comment]
You're thinking about retrogen when is a feature already existing in a lot of mods.
You dont need a 'placeholder' block you just run your world gen the same as normal and replace normal stone.
It's up to the mods themselves to implement this type of thing, similiar like it is up to them to implement their own data fixers.
It's just that very few of them actually do.
