### ISSUE TITLE
Custom Ladders no longer work fully

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#7692]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.45 and above

**Logs:** see https://github.com/mcenderdragon/Futurepack-API/issues/775#issuecomment-802175694

**Steps to Reproduce:**
 1. Observer Ladder behavier in 36.0.44
 2. compare it to 36.0.45
 3. ...

**Description of issue:**

commit https://github.com/MinecraftForge/MinecraftForge/commit/9602c22083aacc51eb398c7709f8aea66a99b885 seems to have caused this.

-> it removed isLadder with no visible alternatives (?), so now even when creating a custom instance of LadderBlock its not working.

**Comment by pupnewfster** [comment]
Do you add your block to the climbable tag that vanilla checks? The change in that commit was made because as it was it changed vanilla behavior when connected to vanilla servers that cleared that tag as the client would still think it is a ladder, when it is "not", so we removed the specific overrides in the various blocks and let it fallback to the default implementation in IForgeBlock which matches vanilla (checking vanilla's climbable tag). Also from what I can tell, if you didn't have your ladder in that tag in the first place even before this change, there are various other places that it would have bene "properly" working anyways.

**Comment by TheCurle** [comment]
From a quick test mod, manually overriding isLadder in a class that extends LadderBlock replicates prior functionality.
But yes, it was removed to bring Forge to parity with vanilla's checks for tags.

Closing for now, unless there's something terrible we're all missing.
