### ISSUE TITLE
[HELP] Forge won't open

### ISSUE THREAD

**Issue by xMilkTea** [MinecraftForge/MinecraftForge#7742]
Version: 1.12.2
Forge: 14.23.5.2847
I tried uninstalling and reinstalling java, restarting my pc, reinstalling forge, installing AdoptOpenJdk and doing the command prompt, nothing worked

Error:

java.net.preferIPv4Stack=true
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.installer.Java6Gate.main(Java6Gate.java:48)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraftforge.installer.ClientInstall.getSponsorMessage(ClientInstall.java:401)
	at net.minecraftforge.installer.InstallerAction.getSponsorMessage(InstallerAction.java:60)
	at net.minecraftforge.installer.InstallerPanel.updateFilePath(InstallerPanel.java:334)
	at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:315)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:167)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:54)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at net.minecraftforge.installer.MirrorData.buildMirrorList(MirrorData.java:84)
	at net.minecraftforge.installer.MirrorData.<init>(MirrorData.java:63)
	at net.minecraftforge.installer.MirrorData.<clinit>(MirrorData.java:17)
	... 11 more

**Comment by TheCurle** [comment]
This isn't where you ask basic questions for outdated versions.
We don't support 1.12.

**Comment by Raidobw2** [comment]
Hello,

I don't want to necro this thread @TheCurle, but I've seen too many issues to not say anything, I'll have to necro and use this issue as base. Their question was not basic, and was legitimately a bug.

DISCLAIMER: Any reference to "you" will reference Forge as an entity. Please don't take it personally, I know TheCurle and sciwhiz12 are simply part of the triage team and are not necessarily linked to Forge development.

The installer is broken on 1.12, I assume some files got changed when you made 1.16 and it broke all installers. I see this happen all the time with the FTB App and I have to give users the files manually. Very annoying to do so and not understand why, even by referencing a manual installation procedure (which give you $, to the contrary of automated installs) that does not work. source: https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13

Yes 1.12 might be deprecated for you but that's an issue most likely caused by your own changes, and not the user's fault at all.
This is what happens when you run a 1.12 installer with Java 8, just like @sciwhiz12 said we had to do so in MinecraftForge/MinecraftForge#6946:
![image](https://user-images.githubusercontent.com/17010632/138981163-6ea785cf-f050-40b6-88b5-9f4c16b6db29.png)

Here's the available switches:
![image](https://user-images.githubusercontent.com/17010632/138981353-763b858f-7914-4767-bc47-038ccbf503ea.png)

Let's run it with offline to avoid network calls:
![image](https://user-images.githubusercontent.com/17010632/138982075-04930c87-d6c9-4e6b-a1ce-b4f3fea22dff.png)
The installer opens up.
 
Here's the content of that mirror-brand.list:
```
Forge!!https://forums.minecraftforge.net/!https://maven.minecraftforge.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/
CreeperHost!!https://creeperhost.net/!https://maven.creeperhost.net/

```

Let's try with the installServer switch this time as well:
![image](https://user-images.githubusercontent.com/17010632/138982404-d18e76e4-581b-454f-8600-efc6c23b45d6.png)

Giving you the benefit of the doubt, let's give it the server jar since we omitted it with the offline switch.
It's available from https://www.minecraft.net/en-us/article/minecraft-1122-released alright.
I get a "server.jar", let's rename it to "minecraft_server.1.12.2.jar" to skip the download, and run the script again. It does skip that download at least thanks to that old 2017 article from Mojang.
![image](https://user-images.githubusercontent.com/17010632/138983099-cb00c160-a946-4384-aa91-0a489720cb81.png)
But of course, we're running it offline mode so it fails downloading files.
Here's the log for that image: https://paste.feed-the-beast.com/view/373f2432

Now. I can run the installer offline with all those workarounds and manually download each one of the libs, plus I'll have to throw some of my own old libs in there since they don't seem to have a download link.

- The online installer is broken because it looks like you're trying to slip an ad in there and it fails.

- The offline installer is broken because the libs cannot be downloaded, it's offline.

Basically, your installer on 1.12 is fully broken, and although that's legacy content, it's odd that you would leave it broken like that. I don't want to be rude of give orders because you guys do that on free time and it's been amazing work, but seeing those errors being denied so much when the fault is (I assume) yours makes me steam a bit, please fix it.

Or at least make it so that users can run the manual installer (GUI) if that's about money, because right now surely you're missing spots for ads with that error, all and all it's a loss for us and for you.
The client installer has the same problem and is broken too.

Please reopen this issue, although unsupported, it is not a request for support and is not any user's fault.
Your program is broken and this is a bug in your code and with your/Mojang's dependencies, due to most likely changes after 1.12 (if you had reorganization, download changes or installer modifications, etc.).

I'm a consumer and I use Forge. Forge won't allow 3rd party redistribution for its files, meaning I cannot get the files anywhere because their own and only installer is broken. I'm left with 0 solutions to use said product, and all 1.12 content falls to the void.
Is this your philosophy? Is Fabric more reliable for the future?

Raising some questions for you so that this can be addressed properly.
Thank you for your work and your comprehension,

Cordially,

Raidobw2, a.k.a. R3GEN
FTB Triage Team

**Comment by TheCurle** [comment]
We're aware of that - something got broken by the installer fixer script we used, we're working on it, as is public knowledge on our discord server.

You're correct, but i suggest searching for more... sensible ways of communicating before necroing threads that are nothing to do with your issues..

**Comment by DaemonUmbra** [comment]
I should note that the installer you used in your demonstration was the last build published with the older toolset, all 1.12.2 installers after that version were built with the newer toolset and, to my knowledge, do work.
![image](https://user-images.githubusercontent.com/5004171/138987214-aface66a-9591-4604-8507-ae21153dbef9.png)

**Comment by Raidobw2** [comment]
Hello,

I thank you both for your quick replies.

However, that's part of my duty to write here for the good functioning of our App. The FTB App is a product by our means and uses your installer and CurseForge's repos and indexes to download Forge installers and unpack them correctly.

This means that handpicking downloads for Forge when installing modpacks in the App is not the ideal solution because some modpacks were never compatible with higher 1.12.2 Forge versions, which would break them.

I understand those pack makers don't feel obligated to update their packs for newer Forge versions, so perhaps you shouldn't feel obligated either to fix the Forge installer. However I think that's not part of your vision to act like so, since you've been providing infrastructure for modders for a very long amount of time now. Maybe I'm wrong, then I apologize.

Sorry if that felt distant and formal, but I felt like this problem required that kind of punch in my original message to get the right information to you, as it is a problem I've been investigating for long until now, thinking the FTB App was at fault. Other launchers surely have that problem as well while installing some older 1.12 Forge versions.

As an example, FTB Interactions will fail to install because of this older Forge version.

I was not aware of the old and new toolset, I appreciate this information and will use it to help users out when installing servers and modpacks, that's all I can do for now.

Thank you very much,

Sorry for the formal approach at first and have a nice day,

Raidobw2, a.k.a. R3GEN
FTB Triage Team

**Comment by LexManos** [comment]
R3gen, you seem very antagonistic and hostile towards us. As well as demonstrating your severe ignorance of how curse, and ftb work. I don't know who you are, of if you really have any affiliation with either of those two groups. 
I will also mention that nothing we have done on our end, to our installers should have any effect on those projects. The fact that you do not know that leads me to doubt your credentials.

However im going to lock this, as those groups have proper channels for contacting us with concerns. 

So if there is a real issue have your higher ups contact me through the proper channels.
