### ISSUE TITLE
Fail load on runClient

### ISSUE THREAD

**Issue by Mysterious-Dev** [MinecraftForge/MinecraftForge#7896]
Minecraft Version: 1.17.1

Forge Version: 1.17.1-37.0.1

Logs:
![image](https://user-images.githubusercontent.com/40738104/126803306-7a10f820-942d-47aa-8f0c-815394e621af.png)

**Comment by RealYusufIsmail** [comment]
My runClient also fails

<img width="780" alt="Screenshot 2021-07-23 at 18 56 50" src="https://user-images.githubusercontent.com/67903886/126822365-af3e40eb-9ec9-4b3c-b8b9-3e058ce83e11.png">

**Comment by Cheaterpaul** [comment]
Create a breakpoint at `String#checkBoundsBeginEnd` in front of the throw and tell us what the `name` parameter in `ModuleClassLoader#loadClass` is.

**Comment by Cheaterpaul** [comment]
I have the same problem because the client extra jar gets generated with the classfiles `a`-`zz` causing the `name.substring()` in `ModuleClassLoader#loadClass` throwing the StringIndexOutOfBoundsException because the filenames do not contain a dot.

For me the name `eez` throws the exception.
(Additional note: I must use 1.17 for the mappings version instead of 1.17.1 otherwise the jars would not get mapped)
Producing the exact same result with the 37.0.8 mdk

Using openjdk on manjaro
