### ISSUE TITLE
[1.17.1] TierSortingRegistry.isCorrectTierForDrops returns misleading results

### ISSUE THREAD

**Issue by Sinhika** [MinecraftForge/MinecraftForge#8006]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.33

**Logs:** N/A

**Steps to Reproduce:**
 1. Create a tool tier A with the same level, tags as Tiers.STONE, registered between (Tiers.WOOD) and (Tiers.IRON).
 2. Create another tool tier B with the same level, tags as Tiers.STONE, etc as per step 1
 3. Create a pickaxe made from B. Attempt to harvest iron ore. The harvest attempt will fail, breaking the ore block without any drops.

**Description of issue:** If two or more custom tiers are registered that are between the same vanilla tiers, and using either the same tags as the vanilla tiers or custom "needs_x_tool" tiers, TierSortingRegistry.isCorrectTierForDrops() will return false for the 2nd and subsequent tier when queried, even if it is intended that all custom tiers function at the same level for harvesting blocks.

This happens because TierSortingRegistry.isCorrectTierForDrops(tier, state) checks to see if the next tier in the sorted tier list after 'tier' has the same block_tag ("needs_x_tool") as 'state'; if so, it returns false. This is at best misleading and at worst incorrect when multiple tiers have the same block_tag. The function assumes that there is only ever one tier per level/block tag.

Workaround: don't register tool tiers with the TierSortingRegistry that have the same harvest levels as vanilla levels; just assign them the appropriate tag and harvestLevel when created as class ForgeTier objects.  Only use the TierSortingRegistry for tiers that go "off scale" from vanilla, or fit between vanilla tiers--but don't assign more than one tool material to the same "in between" or "off scale" level, or you'll run into the same error.

Suggested Fix: re-write the algorithm for TierSortingRegistry.isCorrectTierForDrops() to check to see if the current tier matches the desired state first, and skip over subsequent tiers in the list that are the same as the current tier.

**Comment by gigaherz** [comment]
This is intentional. We made the decision to not support equivalent tiers. In fact, the level value specified in the tier is completely ignored by the sorting system. If there's 2 tiers with the same after/before dependencies, one of them will be sorted as lower than the other.

I think you may be misunderstanding how the algorithm is intended to work. By design, if a block is present in a tier tag higher than the tier of the block, the highest tier is used. That means if a block specifies it needs both iron and diamond, the diamond takes precedence. **This is consistent with the vanilla logic.**

**Comment by gigaherz** [comment]
I forgot to clarify: 

The correct way to register a tier equivalent to a vanilla tier, is to register a tier as being after the vanilla tier, **with an empty tag**. That way no block will match your tier and the algorithm will be happy.

EDIT: As a note for someone reading this in the future: If your tier is added between vanilla tiers, remember to specify both the tier below yours in the "after" set, and the tier above yours in the "before" set, Otherwise it will be added after all of vanilla.
