### ISSUE TITLE
Can't start 1.17.1 server in a VPS.

### ISSUE THREAD

**Issue by KEVINIIE123** [MinecraftForge/MinecraftForge#8031]
Minecraft Version:1.17.1

Forge Version:37.0.44

Logs:I can't start the server so there is no log.

Description of issue:Hi! I can't start my server in a VPS because the is no jar file. Maybe add an option to still download the jar.

**Comment by TheCurle** [comment]
Modern java features do not support executable jars.

What you are asking for is not possible.

Ask the VPS to do their job and update to support 5 year old Java.

**Comment by DaemonUmbra** [comment]
This is not a situation of Forge removing Jars... they are still there... but they don't work on their own anymore due to the Java Platform Module System (JPMS) requiring extra command line arguments to work properly, so they were moved out of the root and replaced with the scripts that run Java with the arguments JPMS needs, so users wouldn't try to run the jars and complain about them being broken when they aren't.
