### ISSUE TITLE
Wrong glMode in VertexFormat.Mode Enum and RenderSystem.lineWidth doesn't work

### ISSUE THREAD

**Issue by Charismara** [MinecraftForge/MinecraftForge#8083]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.61

**Steps to Reproduce:**
Wrong GLMode in VertexFormat.Mode Enum:
 1. Create a GUI
 2. Draw a Line using bufferBuilder.begin(VertexFormat.Mode.LINE_STRIP, DefaultVertexFormat.POSITION_COLOR);
 3. The Line will be invisible

RenderSystem.lineWidth doesn't work:
1. Create a GUI
2. Draw a Line using bufferBuilder.begin(VertexFormat.Mode.DEBUG_LINE_STRIP, DefaultVertexFormat.POSITION_COLOR);
3. The Line won't change it's size

**Description of issue:**
Wrong GLMode in VertexFormat.Mode Enum:
By looking at the Enum you'll find the "asGLMode" field which contains the glMode value. This value is incorrect for the enum values "LINES", "LINE_STRIP and "QUADS". Which causes them to not render (except QUADS... somehow that one works anyway).

RenderSystem.lineWidth doesn't work:
When using RenderSystem.lineWidth the actual width of lines doesn't change at all.
There is a [Discord conversation](https://discord.com/channels/313125603924639766/867851603468615740/888114699651145858) between me and PlatinPython which might be helpful '\\( '_' )/'

**Comment by Nightenom** [comment]
The `asGLMode` for these enums is correct. If you would investigate more, you will find the following:
a) quads are illegal in OpenGL 3 core profile (with forward compatibility), but changing everything from quads to triangles would require massive work, so they've (Mojang) decided to hack quads back in using ebo (as far as I understand what the heck they actually did)
b) lines and line_strip are triangles too because gl_lineWidth is gone (for the same reason as quads). Look at RenderType.LINES and its shader, there you will find another hack (which I find somewhat buggy)

edit: to answer your problem with RenderSystem.lineWidth not working for debug_line_strip:
RenderSystem.lineWidth is connected to uniform and said uniform must be used in shader otherwise it simply has not any effect, the vertexFormat.Mode ~has no impact on the shader~ doesn't select the shader. I suggest you to read basic tutorials on how modern (3+) opengl works to get more info

**Comment by Charismara** [comment]
but why are lines and line_strip invisible but debug_lines and debug_line_strip work as expected?

> RenderSystem.lineWidth is connected to uniform and said uniform must be used in shader otherwise it simply has not any effect

Which means i need to create a shader which contains that uniform value to be able to change the line width?

**Comment by Charismara** [comment]
> RenderSystem.lineWidth is connected to uniform and said uniform must be used in shader otherwise it simply has not any effect

Which means i need to create a shader which contains that uniform value to be able to change the line width?

**Comment by sciwhiz12** [comment]
Looking at the [specification for OpenGL 3.2 (Core Profile)][3.2-core-profile-spec] and some Minecraft code shows that Nightenom's statements are correct: 
 - In the case of OpenGL 3.2 Core Profile in a forward-compatible context (which Minecraft uses), `LineWidth`s greater than 1.0 and the quadrilateral primitives (including the drawing mode `QUADS`) are removed features and cannot be used. This means that, as Nightenom concluded, the GL modes of the `VertexFormat`s are correct in how they're used by the rendering code for mimicking `LINES`, `LINE_STRIP`, and `QUADS` primitives using `TRIANGLES` and `TRIANGLE_STRIP`.
 - `RenderSystem.lineWidth` looks to set a field which is used to populate the value of the `LineWidth` uniform (`ShaderInstance#LINE_WIDTH`), and it is up to the shader to use the value of the uniform. From my brief diving, only the lines render type (`RenderType#LINES`, `minecraft:shaders\core\rendertype_lines.vsh`) uses that particular uniform at the moment (though I may be wrong).

For these reasons, I am closing this issue.

[3.2-core-profile-spec]: https://www.khronos.org/registry/OpenGL/specs/gl/glspec32.core.pdf

**Comment by ghost** [comment]
>     3. The Line won't change it's size

its*
