### ISSUE TITLE
Forcing chunks via ForgeChunkManager can lock up the game

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#8099]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-37.0.70

**Logs:** [latest.log](https://github.com/MinecraftForge/MinecraftForge/files/7193286/latest.log)

**Steps to Reproduce:**
 1. Have a BlockEntity forcing a chunk in its ClearRemoved method. E.g.:
```
@Override
    public void clearRemoved() {
        super.clearRemoved();
        if (level instanceof ServerLevel) {
            ExampleMod.LOGGER.info("Attempting to force chunk.");
            ChunkPos pos = new ChunkPos(this.getBlockPos());
            for (int i = 0; i < 100; i++) {
                if (ForgeChunkManager.forceChunk((ServerLevel)level, ExampleMod.ID,
                        this.getBlockPos(), pos.x+i, pos.z, true, false)) {
                    ExampleMod.LOGGER.info("Forced chunk.");
                }
            }
            ExampleMod.LOGGER.info("Attempted to force chunk.");
        }
    }
```
2. Have a chunkloading callback that removes all tickets upon world load:
public class Validator implements ForgeChunkManager.LoadingValidationCallback{

    public void validateTickets(ServerLevel world, ForgeChunkManager.TicketHelper ticketHelper) {
        LogManager.getLogger().info("Callback executed.");
        for (BlockPos pos : ticketHelper.getBlockTickets().keySet()) {
            ticketHelper.removeAllTickets(pos);
        }
        return;
    }
}
4. Have a world which has the BlockEntity placed in it (I used a superflat world, but I also encountered this in a standard world)
3. Start Minecraft and load the world, with the BlockEntity in loading range of the player.
    a. Or, load a world where the BlockEntity is in a non-spawn chunk outside the player's load distance, then teleport into the BlockEntity's chunk.
4. Game hangs.

Basically, if you have the following conditions:
*Have a chunk being loaded from disk
*A BlockEntity in that chunk attempts to force a chunk via ForgeChunkManager.forceChunk(...) in its "clearRemoved" method
*The chunk also supposed to be loaded to the player immediately (either upon world load, or by teleporting into the BlockEntity's chunk from beyond their render distance)
The game hangs - no further chunks load, no entities move, and attempting to save and exit does nothing.
Also, I don't believe this is an issue with forcing 100 chunks in a row - the game locks up on the first forceChunk attempt.
Notably, if the Block Entity is in a spawn chunk, the game only hangs if the BlockEntity's chunk is within the player's load distance upon loading the world. Otherwise, it simply doesn't force the chunks.

I understand if loading a chunk this way, or at this time isn't a good idea (I'm fairly new to modding Minecraft). But I expect it to crash the game, or ignore the attempted forceChunk, if that's the case.

**Comment by XFactHD** [comment]
The behaviour you are seeing is to be expected.
Towards the end of the loading process of a chunk `BlockEntity#clearRemoved()` is called on all `BlockEntities`. This whole process happens inside a chain of `CompletableFuture`s. When your BEs `clearRemoved()` is called, you request the `ForgeChunkManager` to force-load a chunk. The `ForgeChunkManager` therefore adds a chunk ticket for that chunk which implicitely requests the loading of that chunk. The aforementioned chain of `CompletableFuture`s is then built and the server thread starts waiting for that chain to be completed. Due to the `Runnables` backing the `CompletableFuture`s being enqueued to be run after those of the chunk with your BE in it, they will never finish until the chunk with your BE is done loading but that chunk will not finish loading until the chunk you requested to be force-loaded has loaded. This is a classical example of a deadlock and it being a deadlock is also the reason why it hangs and doesn't crash: To the JVM there is nothing inherently wrong with that situation, it is still executing code just fine.

To alleviate this problem you would have to call this from a method that is called after exiting the `CompletableFuture` chain. The intended place for that would be in `IForgeBlockEntity#onLoad()` but that method is currently not called, see PR #7946 for the progress on getting that to work again in a way that would support this kind of stuff. (Do note that using `IForgeBlockEntity#onLoad()` for this will NOT work in 1.16 because in 1.16 that method is also called from the `CompletableFuture` chain. A "first tick" construct - which `onLoad()` is intended to replace - in `ITickableTileEntity#tick()` would be needed).

**Comment by ghost** [comment]
Okay, that makes sense.
I was actually using the `BlockEntity` with a `ChunkManager` type class, which every second checks a set of conditions for each chunkloading `BlockEntity`, to see if the block entity's chunkloading should be enabled/disabled, via a `Activate`/`Deactivate `pair of methods.
I was just trying to enable the `BlockEntity`'s chunkloading via calling the `ChunkManager`'s `Activate` method in `ClearRemoved`, so it could be activated immediately after placement. That's why the deadlock happened. So I just removed the call to `Activate` from that method, and left it to the manager to handle it.
Is there any way for the `ForgeChunkManager `to detect if it's being called from within a `CompletableFuture`?
Or a way to detect if the chunk that's being requested is in the process of loading/generating? And if so, return false/throw a `RuntimeException`? Not very elegant, and it would require that modders account for the chance that their chunkloading request fails, seemingly randomly.

**Comment by XFactHD** [comment]
Detecting if the `ForgeChunkManager` is called from a `CompletableFuture` is definitely not possible.
Checking if the requested chunk is loading won't help in most cases because requesting any chunk to load from within a `CompletableFuture` that is loading a chunk will cause this deadlock. Therefore this is probably also really tricky if not imposible.

**Comment by Shadows-of-Fire** [comment]
This is simply unsupported behavior - even if the deadlock were resolved it would be replaced with an exception.
These calls will very likely work from `onLoad` once https://github.com/MinecraftForge/MinecraftForge/issues/7926 is resolved.
