### ISSUE TITLE
[RFC] Removal of the Animation State Machine API

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#8180]
The Animation State Machine API (ASM API) is a Forge-provided API for the creation of state-driven animations for block entities, located at the `net.minecraftforge.client.model.animation` and `net.minecraftforge.common.animation` packages.

It is proposed that **the Animation State Machine API be marked deprecated in 1.17 for removal in 1.18** for the following reasons:

 - There are a perceived lack of users of the ASM API;
 - There is a lack of documentation regarding the ASM API, both in the code itself and in the official Forge documentation site _(for reference, see https://github.com/forgecommunitywiki/Documentation/pull/21)_;
 - There exists the maintenance burden of carrying an unused (and therefore undermaintained and/or nonfunctioning) API; and
 - There exists alternatives to the use of the ASM API, most prominently the [GeckoLib][geckolib] animation library which has an active user base, active maintainer team, up-to-date documentation, and "support for complex 3D keyframe-based animations, 30+ easings, concurrent animation support, sound and particle keyframes, event keyframes, and more."

This RFC is especially targeted towards those who are actively using without issue this API in 1.17, or plan to (continue to) use the API in future versions. **After a period of 1 month** (ending roughly on November 30), if there seems to be a tiny or empty fraction of users of the API, it will be marked as deprecated for removal.

> Please see this [conversation in the official Discord server][discordconvo] for discussion prior to the creation of this RFC. The above statement regarding GeckoLib is not an official endorsement by the Forge team, however it is mentioned due to its usefulness and its existence as an alternative to the ASM API.

[discordconvo]: https://discord.com/channels/313125603924639766/852298000042164244/904301504037539850
[geckolib]: https://github.com/bernie-g/geckolib

**Comment by JTK222** [comment]
While I am not actively using the ASM API actively right now, I'd like to give some feedback.
Back when I used it, it was a terrible mess. It took me days to get a simple chest opening working properly.
Something that could be done in 5 lines of code...
While I can't say that I've fully mastered it, I understand it for the most part now.

For that reason, I'd suggest replacing the ASM API with 2 separate and smaller APIs.
1. The State Machine can be handy for various things, especially with some cleanup, documentation and generalization, I can see people using it for many things beyond just model animations. (E.g. AIs or machines)

2. One major advantage of the API was that you could easily use data driven models for animated blocks entities (& entities). So a minor API to more easily render a baked model inside a BER might be a good replacement.
(Right now it requires about ~5-7 lines actual rendering (can't recall a 100%),
if you want to cache the model, you'll have to double this, as it needs the resource reload event)
While the amount of required code isn't really the problem,
it requires knowledge of code that a majority of people probably never used.
And many people probably don't even know that it would be possible.

These 2 smaller APIs would basically cover ~60% of the ASM API, 
only thing missing would be data driven state machine & the math expression parsing that went with it.
Oh, and b3d model loading, which tbh I have yet to see someone using those.

**Comment by ChampionAsh5357** [comment]
I think there were two main benefits revolving around the ASM system:

1. It could lazily cache states to reduce computational complexity.
2. Animations can be purely defined without the need for a BlockEntity.

Additionally, since the original system was just a wrapper around vanilla models, it could be integrated as a custom model loader provided that we fix the current bugs within the system. However, that would require a semi redesign of the current system, probably as a extension of a composite model.

Whether the ASM system should be maintained by Forge is a different story. It seems as though for most use cases, GeckoLib does already implement a working form of the above system. Also, it has an integration with the model creator Blockbench for ease of use for the system.

For those reasons, the current system in its whole probably doesn't need to exist. Instead we could split it into smaller, more maintainable portions to which would be more useful as a general concept within Forge similar to those JTK suggested.

**Comment by JTK222** [comment]
> Animations can be purely defined without the need for a BlockEntity.

That is incorrect to my knowledge, the ASM did basically just render baked models using a BER,
and iirc a BE was still required to track some data ~~(that was actually optional if the animations were just aesthetic)~~
(unless things changed massively since 1.12, which I honestly doubt)
So just creating a new model loader won't be enough.

The only massive benefit/downside it brought was data-driven everything,

Actually, here's an example of a simple block (chest) using the ASM API 
(don't kill me, that stuff is ancient, I was still a newbie back then 👀)
[State Machine](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/blob/feature/other/animation-rework/src/main/resources/assets/drpmedieval/asms/block/simple_chest_top.json), [Armatures (file containing the animations)](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/blob/feature/other/animation-rework/src/main/resources/assets/drpmedieval/armatures/block/wood_blocks/simple_chest_top.json) and [TileEntity to go along with it](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/blob/feature/other/animation-rework/src/main/java/net/dark_roleplay/medieval/objects/blocks/utility/storage/chests/simple_chest/TileEntitySimpleChest.java)

**Comment by marchermans** [comment]
> That is incorrect to my knowledge, the ASM did basically just render baked models using a BER,
> and iirc a BE was still required to track some data ~(that was actually optional if the animations were just aesthetic)~

This is accurate

**Comment by McJty** [comment]
The only time I came into contact with this when I actually wrote a tutorial section about it in my 1.12.2 version of my tutorial series. I found it pretty annoying to use and too much hassle. I wouldn't mind seeing it gone to be honest

**Comment by SwanX1** [comment]
Commenting to voice my support **for** the removal of the ASM API.

**Comment by gigaherz** [comment]
Considering that so far as I know, the API is currently in a broken state (and 1.18 breaks it even further), and no one has voiced their need for this API to be maintained/fixed, I'm going to approve this removal.
If someone wants to redesign the API and bring it back, we will then evaluate if it's worth reintroducing (demand vs maintenance cost).

**Comment by sciwhiz12** [comment]
The Animation State API has been removed as of 1.18.
