### ISSUE TITLE
Unable to install forge on the new minecraft launcher (applies to all minecraft versions)

### ISSUE THREAD

**Issue by RedCarlos26** [MinecraftForge/MinecraftForge#8186]
**Minecraft Version:** {All versions}

**Forge Version:** {All versions}

**Logs:** {[forge-1.12.2-14.23.5.2855-installer.jar.log](https://github.com/MinecraftForge/MinecraftForge/files/7464782/forge-1.12.2-14.23.5.2855-installer.jar.log)}

**Steps to Reproduce:**
 1. Install the new minecraft launcher and uninstall the old one
 2. Basically do a fresh installation to reset the file names

**Description of issue:**
The forge installer is not able to install because the new name for launcher_profiles.json is launcher_profiles_microsoft_store.json

**Comment by sciwhiz12** [comment]
There are currently two issues due to the new launcher storing its profiles in a new `launcher_profiles_microsoft_store.json` file:

1. The installer is programmed to installed the automatically generated Forge profile/game installation in the `launcher_profiles.json` file, which means _if the file is present_, installation will succeed but the newly (re)generated profile/game installation will only be visible in the old launcher. 

   However, in this case the installation of Forge as a game version still succeeds, which means you can create a new profile/game installation and manually select the Forge version in the dropdown menu.

2. _If the `launcher_profiles.json` is **not** present_, then installation will fail early on due to a check in https://github.com/MinecraftForge/Installer/blob/5d8bc959d2cca9424b7fe37a93f74f567b575fa3/src/main/java/net/minecraftforge/installer/actions/ClientInstall.java#L52 for the presence of said file. 

   This is the problem reported in this issue, and can be worked around by copying the new `launcher_profiles_microsoft_store.json` file to `launcher_profiles.json` in the same directory, and running the installer again.

A fix has been committed (see https://github.com/MinecraftForge/Installer/commit/5d8bc959d2cca9424b7fe37a93f74f567b575fa3) to the Installer code, and the team is actively working to retroactively fixing all previous installers as well. Until this process is completed, we suggest following the workarounds suggested about.

> _Sidenote:_ Because the launcher profiles file is separate for the old launcher and the new launcher, the existing profiles in the old launcher will not be visible in the new launcher, and vice-versa. To remedy this, you may copy the contents of the old launcher profiles file to the new one (more specifically, the `"profiles"` section of the file) to move your existing profiles to the new launcher.

While this issue has been opened for 1.12, an unsupported version of Minecraft, and would normally be closed by procedure, in the interests of keeping the community up to date on this issue, it shall remain open until the retroactive fixing of the installers has been completed.

**Comment by RedCarlos26** [comment]
Just to be sure, is it planned to fix all previous installers since this is an issue that affects them all at once and that is global @sciwhiz12?

**Comment by sciwhiz12** [comment]
@RedCarlos26: Yes, the team is currently in the process of retroactively updating all previous and current installers with the fix for this issue (alongside fixes for some other issues that may have cropped up during the first retroactive rewrite-update of the installers).

**Comment by RedCarlos26** [comment]
Ah perfect. Thanks for the information!

**Comment by LexManos** [comment]
Should be fixed now, be sure to redownload the installers. Clean your cache if needed.
