### ISSUE TITLE
1.18-38.0.4 Block Override Crash

### ISSUE THREAD

**Issue by JeremyJBrennan** [MinecraftForge/MinecraftForge#8230]
**Minecraft Version: 1.18**

**Forge Version: 38.0.4**

Crash Report:
https://gist.github.com/JeremyJBrennan/10be7cd1b80107542c4bb1acb9bedcf7

**Steps to Reproduce:**
 1. Set up new 1.18-38.0.4 mdk examplemod
 2. Launch it and make a new world, then close
 3. Make a BlockRegistry class with the below code that overrides the vanilla dirt block (with the exact same properties). Run BlockRegistry.init(); from the ExampleMod constructor
 4. Launch again and try to open world.
 5. Crash

    public static DeferredRegister<Block> BLOCKS_VANILLA = DeferredRegister.create(ForgeRegistries.BLOCKS , "minecraft");

    public static void init() {
        BLOCKS_VANILLA.register(FMLJavaModLoadingContext.get().getModEventBus());
    }

    public static final RegistryObject<Block> DIRT = BLOCKS_VANILLA.register("dirt", () ->  new Block(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.DIRT).strength(0.5F).sound(SoundType.GRAVEL)));

This should also work without making a new world and just clicking on play single player without a world made.
This seemingly works for overriding any block, not just dirt. Crashed with oak planks or amethyst clusters.

**Comment by Commoble** [comment]
Some clarification on why this is happening:

* Minecraft creates and registers builtin dynamic registry objects (biomes, configuredfeatures, etc) with vanilla static registry objects (blocks, etc) in static init in java. Some of these dynamic registry objects have references to vanilla static registry objects (such as blocks).
* When you start creating a world, minecraft serializes all builtin dynamic registry objects, imports datapack dynamic registry objects, and deserializes everything
* When dynamic registry objects are serialized in the previous step, their references to static registry objects are also serialized.
* In order to serialize static registry objects (like blocks), minecraft does a reverse lookup to find its key (it asks the block registry for the key of the given block instance).
* However, the (original vanilla) block instance it's trying to serialize is no longer in the block registry, because we've replaced it with our replacement block, so the reverse lookup fails, the serializer doesn't recognize the block as a valid block, and the whole datapack import process falls apart (leading to the weird unknown registry data errors).

For example, the ice patch configuredfeature uses the (vanilla) dirt block in its list of blocks the feature is allowed to replace. When the datapack import process tries to serialize the ice patch feature, it fails because the vanilla dirt block is no longer in the block registry (having been replaced with our own dirt block).

I'm not very well-versed on how forge registries work, but I imagine fixing this would involve at least one of the following (in order of easiest solution to most complicated):

The simplest fix for this would be to change ForgeRegistry#getResourceKey to use the object's forge registry name (if it's available) to provide the resource key. This would, however, cause overridden vanilla blocks to be serialized and deserialized as their replacements, which may cause strangeness.

Alternative solutions would involve patching Registry#byNameCodec to try to use the forge registry name if available (which is essentially a worse and clunkier version of the first solution), or to magically cause all constructions of builtin vanilla objects to refer to forge overrides instead.

**Comment by LexManos** [comment]
The proper solution would be to fix these dynamic registries to use the snapshots of the registries they were created with. And/Or update their internal references to the overridden object so that they don't use stale data. But that isn't feasible. So I went with this approach.
