### ISSUE TITLE
Forge does not get started with library dependencies correctly when running in IDE

### ISSUE THREAD

**Issue by MartinTheDragon** [MinecraftForge/MinecraftForge#8240]
**Minecraft Version:** 1.17, 1.18

**Forge Version:** 38.0.8

**Logs:** [latest.log](https://gist.github.com/MartinTheDragon/290deda64cb70c411d90fccb154a2c25), [crash.txt](https://gist.github.com/MartinTheDragon/1d01b92aec01bbc754f129005a4be9dd)

**Steps to Reproduce:**
 1. Start a raw Forge project
 2. Add a non-mod library to the `dependencies` block in `build.gradle`
 3. Reference a class from that library in code
 4. Task 'runClient'
 5. Crash

**Description of issue:**
Presumably since Forge for 1.17, libraries are not loaded correctly when running in IDE, creating a `ClassNotFoundException`. However, when packaging the library with the mod jar and running Forge in a user environment, loading succeeds.
More details can be found in [my post in the Forge Forum](https://forums.minecraftforge.net/topic/106283-forge-for-1171-does-not-include-kotlin-standard-library-at-runtime/).

**Comment by sciwhiz12** [comment]
This is a known issue, brought about IIRC because of certain peculiarities with Java's module system and the classpath information. The [MinecraftForge/bootstraplauncher](https://github.com/MinecraftForge/bootstraplauncher/pull/7) project uses the classpath information to bootstrap the modular environment needed for ModLauncher 9.x and the various programs running under it (such as Minecraft Forge) to function correctly. For a JAR to be included in this environment correctly, it must either be loaded by the FML mod locators (as a mod, library, language provider, or game library) or be present in the classpath information.

In the production/user environment, this issue does not occur, as the mod JAR shades in its non-mod library dependencies and therefore no extra JAR needs to be added to the classpath. In the user development environment, however, the non-mod library JAR must be added manually to the classpath information through some tweaks in the Gradle buildscript: (These tweaks have been known for quite some time in the Forge discord, so I do suggest to poke in as well as the forums.)

1. Ensure you are on the latest ForgeGradle version.
   This can be done by refreshing your dependencies by running gradlew --refresh-dependencies.

2. Add this snippet of code to your Gradle buildscript (`build.gradle`), below the `minecraft {}` block (you may exclude the explanatory comments):
	```gradle
	configurations {
		// Create the library configuration, where our non-mod libraries will be added to
		library
		// Any dependency in the library configuration will also be added to the implementation configuration
		implementation.extendsFrom library
	}

	// Configure all runs with the following
	minecraft.runs.all {
		// Set the minecraft_classpath token to the paths of all jars in the library configuration
		// This is added with the actual Minecraft classpath to get the real classpath information later on
		lazyToken('minecraft_classpath') {
			configurations.library.copyRecursive().resolve().collect { it.absolutePath }.join(File.pathSeparator)
		}
	}
	```

3. Define all of your non-mod libraries under the `library` configuration in the `dependencies {}` block:
	```gradle
	dependencies {
		/* ... other defined dependencies ... */
		library 'com.example:examplething:1.0.0'
	}
	```

4. If you are shading dependencies, add `<shade configuration>.extendsFrom library` in the `configurations {}` block to automatically add all non-mod libraries defined in the `library` configuration to the shading configuartion.

5. Regenerate your run configurations for your IDE. _This must be done every time you add or remove a library._

No better solution has been devised since this workaround, so we recommend this to be used if you are depending on non-mod libraries.

As the above instructions should resolve your issue, I am closing this.

**Comment by MartinTheDragon** [comment]
Ok, thanks a lot!

**Comment by SizableShrimp** [comment]
This solution is outdated. Find new solution [here](https://docs.minecraftforge.net/en/fg-6.x/dependencies/#non-minecraft-dependencies). Only posting because someone found this issue and tried to use the old solution.
