### ISSUE TITLE
[1.18] Cancelling PotionShiftEvent renders the effects middle of the inventory

### ISSUE THREAD

**Issue by strikerrocker** [MinecraftForge/MinecraftForge#8252]
**Minecraft Version:** 1.18

**Forge Version:** 38.0.4

**Steps to Reproduce:**
 1. Create a mod subscribing to PotionShiftEvent
 2. Cancel the event
 3. The potion effect gui renders on top of the inventory

**Screenshot:**
![image](https://user-images.githubusercontent.com/28724985/144756293-81c77cfc-552b-411d-b196-52a73629b8f9.png)

**Cause**:
Vanilla Minecraft now renders the potion gui on the left side now and automatically resizes itself to small size when there is less space. This was overlooked in 1.18 patchening. 

**Forgecord Conversation link** https://discord.com/channels/313125603924639766/852298000042164244/916317333163765790

**Comment by sciwhiz12** [comment]
Confirmed both the buggy behavior of `ScreenEvent.PotionShiftEvent` and the new behavior in vanilla 1.18.x where the effects are rendered on the _right_ side of the screen and do not cause the screen to shift over, and shown in a compact, icon-only manner when space is not available (such as using GUI Scale 4 and opening the recipe book in the inventory screen).

Since `PotionShiftEvent` was added on the use-case of preventing the shifting of the inventory screen when potion effects are being rendered on the side, and the screen shifting was removed in 1.18, the solution here is to remove `PotionShiftEvent`.

---

## Screenshots of vanilla behavior, for reference
Uses **GUI Scale 4**.

### No effects
![no effect](https://user-images.githubusercontent.com/21304337/146673666-73a47b7d-4671-4178-8f64-e8acea4b3f74.png)

### Single effect
![effect](https://user-images.githubusercontent.com/21304337/146673664-b1ea2a27-dba4-41d7-993c-3d9394794a1f.png)

### Single effect, with recipe book open
![effect with recipe book](https://user-images.githubusercontent.com/21304337/146673662-9320bf02-bb6f-4b89-b456-28c4d5483087.png)

**Comment by KnightMiner** [comment]
Would a similar event be worthwhile to tell the potions to render small instead of canceling shift?

**Comment by sciwhiz12** [comment]
That sounds fair enough, something like `ScreenEvent.PotionSizeEvent` (tentative name) with possibly using `Event.Result`, where `ALLOW` means compact mode (icon only), `DEFAULT` means vanilla behavior (depends on the width of window and screen), and `DENY` means classic mode (full bar).
