### ISSUE TITLE
Server Crash at start

### ISSUE THREAD

**Issue by Mithandill** [MinecraftForge/MinecraftForge#8266]
**Minecraft Version:** {Minecraft version}

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. use version 38.0.15/12
 2. launch server 
 3. server crashes

**Description of issue:**
Since 10/12/2021 3 am approxiamtely, server crashes on start
[crash-2021-12-10_03.34.40-fml.txt](https://github.com/MinecraftForge/MinecraftForge/files/7689768/crash-2021-12-10_03.34.40-fml.txt)

.

**Comment by XFactHD** [comment]
I looked into this issue because it was brought up again today on Discord.

The issue is as far as I can see that the `BiomeDictionary` is being used from the `FMLCommonSetupEvent` (which runs concurrently) while not being thread-safe at all.
The call to `BiomeDictionary.init()` from the common setup handler in `ForgeMod` leads to the static init of `BiomeDictionary` being run. This adds the vanilla biomes and in the process iterates the supertypes of a given `BiomeDictionary.Type` in `BiomeDictionary.listSupertypes()`.
When a mod calls `BiomeDictionary.Type.getType()` for a type that is not registered yet while a call to `BiomeDictionary.addTypes()` from another mod (in this case Forge itself) is in the process of listing the subtypes of a type (which iterates over the `BiomeDictionary.Type.byName` map), the game crashes with a `ConcurrentModificationException` because the constructor of `BiomeDictionary.Type` has the side effect of adding the new type to the `BiomeDictionary.Type.byName` map.

There are probably a few more cases where such a crash could happen because none of the collections in that class are thread-safe.

**Comment by sciwhiz12** [comment]
Though I myself have not encountered this issue (and therefore cannot confirm it in the usual sense of being able to reproduce the issue), I've seen enough reports of this to mark it as confirmed.

**Comment by LexManos** [comment]
Nobody has been able to confirm this, and this report is for an older version. But I added some protection. Let me know if you're able to reproduce on modern versions.
