### ISSUE TITLE
[1.18.1] [Bug] Item duration bar renders as black after item takes damage if IForgeItem.getMaxDamage is overriden.

### ISSUE THREAD

**Issue by rosevcook** [MinecraftForge/MinecraftForge#8294]
**Minecraft Version:** 1.18.1
**Forge Version:** 39.0.0

**Steps to Reproduce:**
- override `IForgeItem.getMaxDamage(ItemStack stack)` in an item class.
- have this item take damage (via `ItemStack.hurt` or `ItemStack.hurtAndBreak`)

**Description of Issue:**
- Item duration bar renders as black after item takes damage.

**Image of Issue:**
![image](https://user-images.githubusercontent.com/96022374/145726878-b8c03629-aa1d-4411-9985-4db870c6c280.png)

**Comment by OneLemonyBoi** [comment]
Hey, can you post a snippet of the code that causes this issue?

**Comment by sciwhiz12** [comment]
While I have not recreated the effect shown in the issue, it is likely that this is caused by `Item#getBarWidth` and `Item#getBarColor` not calling `IForgeItem#getMaxDamage(ItemStack)` for the ItemStack-dependent maximum damage, but instead uses the hardcoded `maxDamage`. This is only a rendering glitch, as the bar width and color do not meaningfully affect the operation of these items.

For testing, I placed the following block of code in `CustomShieldTest.CustomShieldItem` in the test sourceset:
```java
@Override
public int getMaxDamage(ItemStack stack)
{
    if (stack.getDisplayName().getString().contains("dQw"/*4w9WgXcQ*/)) {
        return 8;
    }
    return super.getMaxDamage(stack);
}
```
After adding that, I used an anvil to rename the custom shield item (obtained through a `/give @s custom_shield_test:custom_shield{Damage:3s} 1`) to rename the item to `dQw`, and used the hot reload functionality of my IDE to patch `Item#getBarColor` and `Item#getBarWidth` to use `IForgeItem#getMaxDamage` on-the-fly and observe the effects.
