### ISSUE TITLE
Patch in SpreadSnowyDirtBlock is misplaced

### ISSUE THREAD

**Issue by JTK222** [MinecraftForge/MinecraftForge#8308]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.5

**Description of issue:**
The patch on line 39 is there to prevent grass spreading from chunk loading.
But it's placed in the condition block where grass turns back into dirt.
And does not execute when the grass spreads and loads neighbor chunks.
Depending on whether the grass block being set to dirt can load neighboring chunks,
the check might still be necessary, but its range should be lowered.

**Comment by sciwhiz12** [comment]
This seems to be a misaligned patch during the 1.15 update and patch cycle (see https://github.com/MinecraftForge/MinecraftForge/commit/1933d05e36245ef7461b29853b4854fa769a807f#diff-e793813ade75d7d367cb775c3dcf7c18ac5824055d921d3cd6c9b184c9cc952bL5-R10). The patch in 1.14 inserted the hook just below an `if (!worldIn.isRemote)` check, with the normal tick code following. In 1.15, the `isRemote` check was removed, but instead of preserving the hook at its position just above the tick code, it was instead placed within the tick code, below the `if` condition.

```java
// Code in 1.14.4 with the hook in the proper position
/* L32 */ public void tick(BlockState state, World worldIn, BlockPos pos, Random random) {
/* L33 */    if (!worldIn.isRemote) {
/* L34 */       if (!worldIn.isAreaLoaded(pos, 3)) return; // Forge: prevent loading unloaded chunks when checking neighbor's light and spreading
/* L35 */       if (!func_220257_b(state, worldIn, pos)) {
/* L36 */          worldIn.setBlockState(pos, Blocks.DIRT.getDefaultState());
/* L37 */       } else {
```

```java
// Code in 1.15.2 with the hook improperly placed inside the tick code
/* L32 */ public void tick(BlockState state, ServerWorld worldIn, BlockPos pos, Random rand) {
/* L33 */    if (!func_220257_b(state, worldIn, pos)) {
/* L34 */       if (!worldIn.isAreaLoaded(pos, 3)) return; // Forge: prevent loading unloaded chunks when checking neighbor's light and spreading
/* L35 */       worldIn.setBlockState(pos, Blocks.DIRT.getDefaultState());
/* L36 */    } else {
```
