### ISSUE TITLE
FakePlayer class does not seem to decrement the itemCooldowns affecting watering cans

### ISSUE THREAD

**Issue by jack-flash** [MinecraftForge/MinecraftForge#8392]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.*

**Logs:** No direct logs on this

**Steps to Reproduce:**
1. Install Cyclic and Mystical Agriculture mods (Pickle Tweaks watering can is also affected)
2. Place the cyclic:user (Item User) in the world with power
3. Put any of the Mystical Agriculture watering cans in the Item User slot
4. The watering can will water once, it will add a cooldown, then never water again as the cooldown is not getting decremented.

**Description of issue:**
The FakePlayer class does not seem to have implemented the itemCooldown code correctly.  Not sure if this is an upstream code issue or not.

I submitted a pull request for Mystical Agriculture to bypass their cooldown check  if being used by a FakePlayer here::

https://github.com/BlakeBr0/MysticalAgriculture/pull/475

However, in discussions with metalshark, it may be better to address this issue directly in Cyclic's code to enable all watering can type items until this can be fixed.

**Comment by Shadows-of-Fire** [comment]
I don't even believe this is a bug - FakePlayers do not tick unless the owning mod ticks them (which, usually, you don't, because you wouldn't want to tick a FakePlayer). 

Cooldowns are tick-based, so if the entity does not tick, cooldowns do not increment.

**Comment by jack-flash** [comment]
Thanks.  I am new to this so appreciate the insight.  So if the FakePlayer is not intended on being ticked, then mods should not expect to use the cooldown feature for their items I would think? In the alternative, is there any example you can point me to which properly implements the FakePlayer tick?  Appreciate the help...

**Comment by KnightMiner** [comment]
The way you word that is as if mods should not use cooldown as it breaks fake players. Its the fake player's job to ensure item cooldowns are processed. I also disagree that it is the mod's responsiblity to ensure fake players can use them properly. That should be the fake player's job. If the fake player wants to ignore cooldowns they can easily override the cooldown tracker to say nothing is on cooldown.

----

As for properly doing this so you don't bypass cooldowns, you really don't need to tick the fake player, just tick its cooldown processor. The best way to do this is adding a setter for cooldown to the fake player and overriding `getCooldowns` to return that instance. This allows you to tie the cooldowns to the current object using the fake player (if you use the fake player's own instance, it means all usages of your fake player share cooldowns, probably not a good design).

So for example, if you use a single fake player for all of your autoclicker block entities, have each block entity maintain its own `ItemCooldowns` instance, ticking it as needed. Before clicking with the fake player, call the setter on your fake player so it uses your block entites `ItemCooldowns`. You can either tick the cooldown in the block entity's tick, or rig up a system that does not require ticking (`ItemCooldowns` is extendable, you can for example have a "finish cooldown" world time instead of ticking it).

If you want to discuss this more Discord is probably a better place, as there really are no need for changes in Forge (I don't see any impl needed in forge for this to work, I feel like a default forge no-op for item cooldown sets a bad precedent, fake players shouldn't bypass cooldowns)

**Comment by jack-flash** [comment]
Thanks!
