### ISSUE TITLE
Incorrect tag for minecraft:cut_copper

### ISSUE THREAD

**Issue by jeremiahwinsley** [MinecraftForge/MinecraftForge#8403]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.36

**Description of issue:**

PR #7891 adds the `forge:storage_blocks/copper` tag to `minecraft:cut_copper`, but this is not a storage block and should not have the tag. The vanilla stonecutter recipe converts one copper block to four cut copper blocks, and they cannot be converted back into copper blocks, or copper ingots.

**Comment by sciwhiz12** [comment]
Looking at the discussion in the linked PR regarding the cut copper block in the copper storage blocks tag at https://github.com/MinecraftForge/MinecraftForge/pull/7891/files#r750795997, it seems it was decided at the time that, because of existing precedent—namely, quartz block (which is craftable one-way) being marked in the quartz storage block—the PR is to maintain that precedent and keep cut copper block in the copper storage blocks tag, with a later separate RFC to discuss that issue and potentially change it.

**Comment by jeremiahwinsley** [comment]
It looks like that decision considered copper blocks and cut copper blocks equivalent in cost, which isn't the case given the stonecutter recipe. So if a mod adds processing recipes for storage_blocks, without a special case for the cut copper, that results in a dupe. That's not the case with quartz, where all vanilla blocks do cost the same 4 quartz.

**Comment by SuperMartijn642** [comment]
This is indeed an oversight on my end when creating #7891 and not intended. I simply thought cut copper had a 1:1 ratio with regular copper blocks.
