### ISSUE TITLE
[1.18.1] Capabilities on a ServerPlayer are not revived correctly when transferring dimensions

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#8426]
**Minecraft Version:** 1.18.1
**Forge Version:** 39.0.59

**Steps to Reproduce:**
 1. Attach a capability to a ServerPlayer
 2. Add a listener to invalidate the LazyOptional of the capabilities provider
 3. Load a world, go through a nether portal, LazyOptional will be empty.

**Description of issue:**
When transferring dimensions, capabilities attached to a `ServerPlayer` are invalidated and the LazyOptional in their providers are also invalidated. The `Entity#revive()` call in `ServerPlayer#changeDimension` does not revalidate the `LazyOptional` from the capability provider, rendering the capabilities broken and unusabl;e This issue is fixed in versions prior to 1.18 but was not reimplemented. The fix is half implemented in 1.18 as seen in the method `ServerLevel#removeEntityComplete` but `keepData` is not passed to the entity. `keepData` was used to prevent the listeners from running.

**Comment by sciwhiz12** [comment]
Previous investigations and testing (by @TheCurle, @Commoble, and @TelepathicGrunt) show that, due to changes in the semantics of invalidation in 1.18, one should _not_ register a listener during `AttachCapabilitiesEvent` to invalidate the `LazyOptional` of the attached capability provider. This was noted [by a change by @TheCurle][fcw-caps-change] in the Forge Community Wiki page for Capabilities. In this case, step 2 should be left out to fix the problem.

See this gist for an example of a known-working entity capability which is preserved across dimension changes (on the server-side; the client-side capability is wiped across dimension changes): https://gist.github.com/sciwhiz12/4d1ca06c1cfd7bd0c0c012daa478c5d0.

[fcw-caps-change]: https://forge.gemwire.uk/index.php?title=Capabilities&diff=prev&oldid=3100

**Comment by TheCurle** [comment]
Indeed, the entity removal system was reworked and it seemed like the keepData flag would no longer be feasible  to patch in.

Because of this, if you use the invalidation listeners, you'll be manually removing the capability before the entity is actually finished processing the dimension change. This means that nothing can revive the capability manually.

Instead, entity capabilities should not register an invalidation listener, prefer to instead manually invalidate on entity death.

The semantics of teleportation is an interesting and bizarre edge case, and we're going to work on improving this for the next update.

**Comment by MrCrayfish** [comment]
Thanks for clearing this up. I did have second thoughts before posting that maybe this isn't actually a bug due to the rework with capabilities.
