### ISSUE TITLE
BonemealEvent can have a FakePlayer from another level

### ISSUE THREAD

**Issue by Lupicus** [MinecraftForge/MinecraftForge#8455]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.66

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Use a dispenser to place bonemeal in overworld
 2. Then go to the nether and do the same thing

**Description of issue:**
The FakePlayer you get from the BonemealEvent has a level for the overworld, but BonemealEvent#getWorld() is the nether.

**Comment by sciwhiz12** [comment]
Confirmed using 1.18.1-39.0.66. This is caused by the caching behavior employed by both `FakePlayerFactory#get` and `FakePlayerFactory#getMinecraft`. 

First, `FakePlayerFactory#get` accepts both a `ServerLevel` and `GameProfile` (username) as arguments for creating the `FakePlayer`. However, it caches `FakePlayer`s based solely on the `GameProfile`/username: as long as it remains in the cache, all subsequent accesses with that username use the same instance. 

This means that, if a previous call with a username and level caused the creation and caching of the instance and a subsequent call with the same username but _different_ level happens while the instance was still cached, the returned `FakePlayer`'s level will have the level from the _previous call_, not the level provided to the factory.

Second, the `FakePlayer` used by `BoneMealItem#growCrop` is retrieved using `FakePlayerFactory#getMinecraft`. Though this has its separate caching for the `FakePlayer` using a `WeakReference`, it still calls `FakePlayerFactory#get` to create a `FakePlayer`. Because the caching does not account for the `ServerLevel` parameter, this also suffers from the same problem as above.
