### ISSUE TITLE
custom ITransformerDiscoveryService not used

### ISSUE THREAD

**Issue by Chaos02** [MinecraftForge/MinecraftForge#8467]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.64

**Logs:** [debug.log](https://pastebin.com/vB5UHcAk)

**Steps to Reproduce:**
 1. Try to implement ITransformerDiscoveryService
 2. Supply service file in META-INF
 2. Never constructed nor called even tho service file is supplied
([Source](https://github.com/Chaos02/SubFolderLoader/tree/787f575303a2a9d5b988b4938669203f68f67459))

**Description of issue:**
I am trying to implement a TransformerDiscoveryService but my Transformer service is never found even tho my `/src/main/resources/META-INF/services/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService` points to the class that implements it. I believe this is a bug in forge, if not, sorry to post on the wrong "forum" but if you could help me pinpoint why this wont get loaded I would greatly appreciate it!

**Comment by Chaos02** [comment]
can this please be looked into as I cannot work on my mod during the meantime? I am hardstuck here

**Comment by sciwhiz12** [comment]
To my knowledge and understanding, mods cannot provide `ITransformerDiscoveryService`s because they are loaded in ModLauncher, before mods are even discovered by the game. 

However, mods can provide `ITransformationService`s because FML provides the `ModDirTransformerDiscoverer` for discovering transformation services from the mods folder during mod loading. (Though, it must be noted that, according to #8095, they are not presently loaded in the development environment due to a lack of a transformer discovery service for the classpath.)

Closing as this is a technical limitation of when transformer discovery services are loaded vs when mods are discovered and loaded.

**Comment by Chaos02** [comment]
Thank you for your input @sciwhiz12 but I DO believe that it is possible to implement pluggable discovery services because of this:
```Java
/**
 * Called early in setup, to allow pluggable "discovery" of additional transformer services.
 * FML uses this to identify transformers in the mods directory (e.g. Optifine) for loading into ModLauncher.
 */
public interface ITransformerDiscoveryService {
}
```
(cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService)
Can you please re-open this issue as it doesn't seem to be solved?

EDIT:
BTW I am not testing in a development environment, I use a regular minecraft installation.

**Comment by sciwhiz12** [comment]
I re-affirm my statement: mods cannot implement `ITransformerDiscoveryService` because the point at which mods are loaded by FML is well after the time when ModLauncher first searches for `ITransformerDiscoveryService`s.

`ITransformerDiscoveryService` is used to search for and identify additional `ITransformationService`s, which is implemented by FML's [`ModDirTransformerDiscoverer`](https://github.com/MinecraftForge/MinecraftForge/blob/f0c2554b1c56f6e079e7a1899a21a199b6e987be/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java) for searching the mods folder for such transformation services (such as OptiFine, or other mods which may have those services).

To my knowledge and understanding, it is _impossible_ for a mod to provide a transformer discovery service simply because of the design of ModLauncher and the difference between when discovery services are called and when mods are loaded. (We'd need to have a `ITransformerDiscoveryDiscoveryService` to allow a mod to provide an `ITransformerDiscoveryService`.)

**Comment by Chaos02** [comment]
Thank you again for the fast answer @sciwhiz12 tho I believe you understood me wrong:
My "Mod" is loaded far earlier than regular FML mods (tho I am working on providing it as a mod for version control etc in MC aswell)
If I understand you correct you say that FML mods cannot locate other transformers or mods but:
My "Mod" already can locate mod files via `IModLocator` (which is why I provided a link to my source code) but I also want to scan for transformers such as optifine. The problem is, even tho I provide the service it is never even constructed.

How would I point forge to use my TransformerDiscoveryService aswell when not in the mods folder? I'ts documentation clearly states that it is designed for pluggable discovery.

**Comment by sciwhiz12** [comment]
As I've said twice already, a mod **cannot** provide an `ITransformerDiscoveryService`. [ModLauncher searches for `ITransformerDiscoveryService`s][ml-discoverServices] very early in the process, only from the boot module layer. That module layer does _not_ (and by the nature of the module layer design, cannot) contain any mods; its contents ara composed of the McModLauncher libraries (securejarhandler, modlauncher, ModLauncher), FML (the loader subproject), and their dependencies.

In fact, the very method by which `IModLocator`s are discovered in the `mods` folder _is an `ITransformerDiscoveryService`_, specifically FML's [`ModDirTransformerDiscoverer`][fmlloader-moddirtransformerdiscoverer]. That discovery service provided by FML is also responsible for discovering `ITransformationService`s such as those provided by OptiFine or other mods in the `mods` folder.

With regards to the documentation claiming the fact of "pluggable discovery", it may likely mean that it allows applications using ModLauncher (such as FML/Forge) to provide for the discovery of transformation services which would otherwise not be discoverable by ModLauncher itself. (In this case, FML uses it to allow mods to anchor themselves on the server module layer and provide either transformation services or mod locator.)

Again, this is a _technical design limitation_ of how and when ModLauncher discovers transformation discovery services. It is **impossible** for a mod to provide an `ITransformerDiscoveryService`. Neither Forge nor FML can provide a remedy to it, as this is a ModLauncher problem.

[ml-discoverServices]: https://github.com/McModLauncher/modlauncher/blob/9b69c82a176c0896b264ab167813a52adc6f12cb/src/main/java/cpw/mods/modlauncher/TransformationServicesHandler.java#L120-L125
[fmlloader-moddirtransformerdiscoverer]: https://github.com/MinecraftForge/MinecraftForge/blob/4011c3fb07dfedc234949b429f853349e0526470/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java
