### ISSUE TITLE
[1.18.2-40.0.12] Modded structures deletes and regens chunks when updating 1.18.1 or older worlds into 1.18.2

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#8505]
So if you put on a structure mod in 1.18.1 like Repurposed Structures and make a world and save it while looking at a modded structure, updating the world to 1.18.2 without the structure mod on (or even still have it on) will make those chunks with the structure be regenerated entirely. Like everything placed in those chunks will be gone as if the structure or your changes never existed.

The old behavior before 1.18.1 was the chunk keeps the chunk's blocks the same and not regen it. It would logspam about missing structures tho. In 1.181, it now regens the chunks which is destructive while also logspamming about missing structures. This should be something forge should fix (the chunk regen and logspam) as otherwise, people updating worlds are going to have a lot of pain and lost builds when they think they are just updating to a newer minor mc version.

Mod: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

Example 1.18.1 Repurposed Structures world to test with. Go to /tp @s -448 ~ 7248 for a mansion in 1.18.1. Save. And then load the world in 1.18.2 
https://www.dropbox.com/s/1qa1vd2kagmhuve/oldworld.zip?dl=0

Pics:
![image](https://user-images.githubusercontent.com/40846040/157352759-4c3e1176-076c-4022-86af-4d9fefda43c1.png)
![image](https://user-images.githubusercontent.com/40846040/157352763-2346d3a1-dd09-4e5a-b5b8-7d7936efc841.png)
![image](https://user-images.githubusercontent.com/40846040/157352771-974c47dc-34e0-4031-a7b8-990a8b29c0ad.png)

The desired result is that when updating 1.18.1 or older worlds to 1.18.2, all blocks remain as is in the chunks and no chunk is regenerated regardless if the 1.18.2 mod is on or not.

**Comment by sciwhiz12** [comment]
Confirmed on **1.18.2-40.0.12**. See screenshots below as complement to the first pair of screenshots provided by the issue author. The issue author has also provided the [relevant snippet of their `latest.log`](https://gist.github.com/fa9d71fae0606f212af7c1d7f21d5ba6)[^1] for this error. I also [have a `debug.log`](https://github.com/MinecraftForge/MinecraftForge/files/8212827/debug.log) from my own reproduction of the issue using the provided world.

<details>
<summary>Screenshots of before and after migration across 1.18.1-39.0.88 and 1.18.2-40.0.10</summary>
<img src="https://user-images.githubusercontent.com/21304337/157398984-ef95ea7d-408f-446b-8ef7-9dc344bfb07e.png">
<img src="https://user-images.githubusercontent.com/21304337/157399007-77f5534a-9074-4221-b56e-cadf8297e76f.png">
</details>

## Problem Investigation

The problem here is caused in the `StructuresBecomeConfiguredFix` datafixer. This datafixer contains a `CONVERSION_MAP`, which maps the _old structure name_ to conversion data for the corresponding new configured structure names.

The details of the method by which the datafixer converts the old structure names is largely irrelevant to the problem, but I have also provided it here:
<details>
<summary>Details for the `StructuresBecomeConfiguredFix` datafixer's method of operation</summary>
<blockquote>

The <code>StructuresBecomeConfiguredFix</code> datafixer has this <code>CONVERSION_MAP</code>, which maps the old structure names (like <code>shipwreck</code>) to conversion data. This conversion data has two parts: 
<ul>
<li>a map of biome names to the _biome-specific_ configured structure (for example, <code>minecraft:beach</code> and <code>minecraft:snowy_beach</code> biomes to the <code>minecraft:shipwreck_beached</code> structure); and</li>
<li>a fallback configured structure (for the above examples, <code>minecraft:shipwreck</code>).</li>
</ul>

To my understanding, the datafixer does the following steps:
<ol>
<li>Look at every existing structure in the world, which uses <em>old structure names</em> at this point.</li>
<li>Look up the conversion data for that structure from the conversion data map <em>(and if cannot find it, throw an <code>IllegalStateException</code>)</em>.</li>
<li>Using the biome palette from the chunk, guess if there is a biome-specific configured structure, and use that if available.</li>
<ol>
<li>Iterate through each biome within the structure's chunks.</li>
<li>Look up each biome in the biome to configured structure name map in the conversion data.</li>
<li>Tally the amount of configured structure names found from lookups to the map.</li>
<li>Select the configured structure with the most amount of tallies as the guess.</li>
</ol>
<li>If there is no biome-specific configured structure according to the previous step, use the fallback configured structure name.</li>
</ol>

</blockquote>
</details>

Our problem occurs because the datafixer is hardcoded to understand only those old structure names which are listed in the `CONVERSION_MAP`, which contain only vanilla structure names. When it encounters a structure which is _not_ in that map, it throws an `IllegalStateException` with the message "Found unknown structure: [old structure name]". 

Because the datafixer throws an error while being applied to that chunk, the server fails to load the chunk entirely and wholly disregards the data. This means that, in the eyes of the server, the chunk has never been generated before[^2] and will be treated as such: (re)generating the contents of the chunk to the natural state of the world generation.

## Potential Solutions

We have three potential solutions for modifying the datafixer:

1. For any old structure name which does not have a namespace of `minecraft` when converted to a `ResourceLocation` to be a modded configured structure, and pass it along unfettered. This is the simplest solution to implement, but the least flexible one as mods cannot make use of the configured structure conversion datafixer to fix their own structures.
2. For each failed lookup to the conversion map, fire an event which gives mods the opportunity to map the structure name manually. This is the most flexible solution, but it requires firing an event a _lot_ of times for large levels (as each chunk containing a structure is passed through the datafixer) which can have performance penalties.
3. During loading and just before acutal datafixing, fire an event which allow mods to contribute their own conversion data to a map, which is then used as a secondary when the initial lookup to the vanilla conversion map fails. This compromises the full flexibility that option 2 provides for the sake of performance.

**My own recommendation is a hybrid solution of options 1 and 3**: an event to allow mods to contribute custom old structure conversion data, while providing a sensible default of passing through structures whose namespace is not `minecraft`. 

This means mods which employ sensible structure naming practices (which I expect is the majority of mods) will just work, while mods that wish to convert old structure names to newer ones have an event by which to do so.

[^1]: Provided through Discord communications. The gist's creator is a machine user used by a Discord bot to automatically create gists for file uploads to Discord.
[^2]: There is a difference between a chunk which has not yet been generated and a chunk whose contents is empty: the former does not have stored chunk data, while the latter does (but full of air and no entities).

**Comment by TelepathicGrunt** [comment]
Requested direct upload of logs and world for documentation purposes here
[oldworld.zip](https://github.com/MinecraftForge/MinecraftForge/files/8214516/oldworld.zip)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/8214517/latest.log)

**Comment by ChampionAsh5357** [comment]
> My own recommendation is a hybrid solution of options 1 and 3: an event to allow mods to contribute custom old structure conversion data, while providing a sensible default of passing through structures whose namespace is not minecraft.

My intuition for this can probably be built into the DFU PR very simple. Within `StructuresBecomeConfiguredFix`, since as mentioned the map is just making it such that non-namespaced structures have the `minecraft` namespace, we can probably just check the string for a non-minecraft namespace in `#findUpdatedStructureType` and just defer to a forge implemented map when present. Since the method doesn't get called until the datafixer is running anyways, this could be done at the same time as DFU or within common setup.

**Comment by marchermans** [comment]
It is possible yeah to handle this from the DFU PR.
But that PR has a flaky history with the first version failing due to me missing a concurrency case.
Besides that the DFU PR in its current state would not solve it since this is a remapping procedure, but we can use the same PR to apply the fix.

**Comment by MightyLuu** [comment]
would it be possible to just delete the information about the structures from affected chunks?
So the game doesn't know it is there and the blocks remain like build by a player?

**Comment by TelepathicGrunt** [comment]
@MightyLuu That’s basically what would be ideal and has been done in the past. However, forge’s goal right now is to change the system to try and persist structures through Mc versions and maybe provide a way for mods to rename old structure refs as well.

if you’re looking to try and clean your world of old structure refs, try running your world through this first and then update it to 1.18.2 https://github.com/Nyveon/MCStructureCleaner
