### ISSUE TITLE
Forge Energy Cable Block

### ISSUE THREAD

**Issue by MrScautHD** [MinecraftForge/MinecraftForge#8523]
Hi!
me and many other Modders are finding difficulty when making a Energy Cable Network System.
And i think it was a good idea to ask Forge if they can do one and so if a developer want to make a system , simply use "AbstractForgeEnergyCableBlockEntity" for exemple 
I would like to see this implemented because it is really hard to do it and Forge Energy exists to so it only makes sense :) 
note : tutorial would cool too if anyone make one, i would pay for it!)

**Comment by Aulluna** [comment]
that would be very useful and make cable development much easier

**Comment by ConmineLP** [comment]
I like that Idea.
As he said currently it is pretty difficult to make a energy cable network system. 
A "universal" system from forge would be very nice

**Comment by DaemonUmbra** [comment]
I'm not sure I understand the issue here, Forge provides an interface for it but you want an implementation as well?

**Comment by MrScautHD** [comment]
yea a implementation for EnergyCable because it is very hard to do a network System

**Comment by MrScautHD** [comment]
> I'm not sure I understand the issue here, Forge provides an interface for it but you want an implementation as well?

yea a implementation for the EnergyCable because it is very hard to do a network System

**Comment by TheCurle** [comment]
If you know the concepts (which you have demonstrated otherwise) it is *not* difficult to create a network power system. In fact, it's regularly one of the first things in beginner's modding tutorials.

If you know how to implement an interface, override a method and read capabilities from other nearby blocks (about one line of code each!) then it's trivial.

As such, no. We're not going to implement your mods' features for you, just because you struggle to understand the basic concepts of Java. That's not what Forge is. That's not what we do.
