### ISSUE TITLE
Any audio using "'stream': true" does not play.

### ISSUE THREAD

**Issue by bconlon1** [MinecraftForge/MinecraftForge#8531]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.20

**Logs:** https://gist.github.com/bconlon1/03b67c26897432c9fdce0c3500df4342

**Steps to Reproduce:**
_(For easiest verifiable testing of this issue)_
 1. Set up a Forge-only instance of Minecraft on 40.0.20.
 2. Open Minecraft and open a world.
 3. Place down a jukebox.
 4. Insert a music disc.

**Description of issue:**
No in-game audio that makes use of `'stream': true` plays in-game, this includes the menu music, music discs, and in-game music. This appears to have arisen due to #8295 and 7f23b3b as testing this with 40.0.19 works fine while 40.0.20 doesn't (which implemented the changes from this PR and commit).

**Comment by ChampionAsh5357** [comment]
This seems to be a result of a incorrect method. Specifically using [`Sound#getLocation`](https://github.com/MinecraftForge/MinecraftForge/pull/8295/files#diff-0a25d40364e5239a691077ab99da838dfee37f8d491a7d5d7814780782912a86R11) instead of [`Sound#getPath`](https://github.com/MinecraftForge/MinecraftForge/pull/8295/files#diff-b10b48d51d8a26cfdaa1ed3363724a06db9b05b9fa7a005bc0fbdb57dfc53a7bR43).

This would make sense as `#getPath` returns the actual ogg file as a resource location while `#getLocation` just references the unique name of the sound instance.
