### ISSUE TITLE
Optional RegistryObjects are filled with air instead of being absend

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#8589]
when using optional registry object like:
`public static RegistryObject<Block> lootr_barrel = RegistryObject.createOptional(new ResourceLocation("lootr:lootr_barrel"), ForgeRegistries.Keys.BLOCKS, Constants.MOD_ID);`
then when the mod is absent the RegistryObject is still present but filled with air

Quoting @diesieben07 on this:
> Honestly that seems unintntional
> It really should not fill it with the default value (air)
> it should be absent

Expectation:
Object to be absend when mod is not installed.

**Comment by KnightMiner** [comment]
To verify, is this before or after a world loads? Forge has a feature where removed blocks get replaced in the registry with a custom air, meaning if the world had that block but no longer does it may show up as present with air instead of absent.

Would be worth verifying the issue happens with items (`Items.AIR`). Probably also worth discussion what missing blocks should do with optional registry objects, is it more useful to declare its missing or return the fake air?

**Comment by mcenderdragon** [comment]
It was used after the world loaded. (and it would be nice if there was a config to define such behavier if possible - replace optionals with air or not)

**Comment by KnightMiner** [comment]
This might not be a registry object bug in that case, but a bug with forge replacing missing blocks with fake air then.

Can you verify by testing another registry and seeing if only blocks have this issue?

**Comment by mcenderdragon** [comment]
> This might not be a registry object bug in that case, but a bug with forge replacing missing blocks with fake air then.
> 
> Can you verify by testing another registry and seeing if only blocks have this issue?

items should work right? as they dont get replaced ?

**Comment by KnightMiner** [comment]
Forge replacing missing values with fake air only happens with blocks to my understanding. My question is whether this issue still happens if you don't use a registry that forge adds missing values to (that is, every single registry that is not blocks). In other words, what is causing the bug? Broken registry object code, or registry objects not handling the block registry special case?

**Comment by marchermans** [comment]
This is intentional as far as I know
The default object is generally air...

**Comment by mcenderdragon** [comment]
> This is intentional as far as I know The default object is generally air...

can a optional depedency then be not Present?

**Comment by mcenderdragon** [comment]
> Forge replacing missing values with fake air only happens with blocks to my understanding. My question is whether this issue still happens if you don't use a registry that forge adds missing values to (that is, every single registry that is not blocks). In other words, what is causing the bug? Broken registry object code, or registry objects not handling the block registry special case?

I tested the lootr barrel item and it was null and not present - so this is something isolated to blocks.

**Comment by sciwhiz12** [comment]
Just to confirm, is the type of the stored `Block` actually `Blocks.AIR`? Or is it a regular instance of `AirBlock` (or a subclass of it) and not specifically the air block registered as `minecraft:air`?

**Comment by mcenderdragon** [comment]
> Just to confirm, is the type of the stored `Block` actually `Blocks.AIR`? Or is it a regular instance of `AirBlock` (or a subclass of it) and not specifically the air block registered as `minecraft:air`?

its DummyAir I dont remember the exact class name tough

**Comment by marchermans** [comment]
Yes if the requested entry was never in the registry or the world was saved with the mods missing again after it was loaded.

**Comment by sciwhiz12** [comment]
I presume then it is [`net.minecraftforge.registries.GameData$BlockDummyAir`](https://github.com/MinecraftForge/MinecraftForge/blob/8ade7bbaebdaa263b0391fd165d5e4e033b52c60/src/main/java/net/minecraftforge/registries/GameData.java#L526), which is the dummy block inserted by Forge to a block registry mapping when it was previously present in a level according to the save data yet there is no such registry mapping in the active registries (such as, for example, the mod which registered the block mapping was removed between the last time the level was saved and the time of load).

Reading the definition of an optional registry object shows that the 'optionality' is for the _existence of the registry_. This means that the use case offerred by the issue author also happens with regular (`RegistryObject#create`) registry objects.

**Comment by LexManos** [comment]
Just to be clear, it is intentional that RegistryObjects get dummies entries, as dummies entries are real entries for all external intents. The Optional refers to the registry itself. Not the entry. So your use of it on the Block registry is incorrect.

We are currently discussing if they should continue to get dummies. But that would be an existing logic break that I'm not sure what we should do about.

**Comment by KnightMiner** [comment]
One possibility is making it opt in, have a boolean on the registry object to filter out dummy values. To prevent hardcoding it to the blocks registry dummy air behavior, have the registry include a method to check if its a dummy/empty object (for most always return not empty, but for blocks check against dummy air). This could be useful in gameplay to determine if the returned value from the registry is empty or default, to allow empty to warn for cases like migrated values referenced in JSON.

Alternatively, let the filter be part of the registry object, add a constructor that takes a predicate and anything that does not match the predicate is considered not present. Could be useful to have a registry object that depends on a value being present, and is considered valid only if the value extends a specific class

**Comment by mcenderdragon** [comment]
> Just to be clear, it is intentional that RegistryObjects get dummies entries, as dummies entries are real entries for all external intents. The Optional refers to the registry itself. Not the entry. So your use of it on the Block registry is incorrect.
> 
> We are currently discussing if they should continue to get dummies. But that would be an existing logic break that I'm not sure what we should do about.

ahh with this explanation it makes sense - did not think about optional Registries.

**Comment by sciwhiz12** [comment]
The case presented in this issue occurs when a dummy entry is inserted in the place of another entry when that entry previously existed when a level was previously saved but does not exist in the current environment. This dummying behavior is used notably by the `Block` Forge registry to preserve the data of blocks from removed mods, for possible resuscitation if the mod is added back.

As @LexManos has stated above, this is intentional behavior that a dummy entry is inserted and held by a `RegistryObject`. Note that the reference updating logic in `RegistryObject` checks if the registry contains the key for the value before retrieving the value, ruling out the possibility of a registry's default value somehow populating a `RegistryObject`.

In a fresh situation of a world without being prior loaded with a mod and then said mod being removed, a `RegistryObject` for said mod's blocks will have no value and be absent, as expected.

In addition, as noted in above comments, the optionality of a `RegistryObject` refers to the (non-)existence of the _registry_, not the value within the registry. A regular `RegistryObject` throws an exception when its registry does not exist, and will exhibit the same behavior in this circumstances.

@KnightMiner, I've asked about being able to filter out dummy entries in `RegistryObject`s, but no response from the core team yet. If there is a genuine want and use case for being able to filter out dummy entries or filtering when capturing the value for `RegistryObject`s in general, feel free to file a feature request.
