### ISSUE TITLE
[1.19] PlayMessages$SpawnEntity mistake

### ISSUE THREAD

**Issue by AzureDoom** [MinecraftForge/MinecraftForge#8701]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.5

**Logs:** N/A

**Steps to Reproduce:**
 1. Summon modded projecticle.
 2. Projectile spawns at 0, 0, 0

**Description of issue:**
Issue lies here: https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/network/PlayMessages.java#L145

It is using `setPos` instead of `syncPacketPositionCodec`, which causes modded projectiles to spawn at 0,0,0 in the world instead of where it's meant to.

**Comment by Random832** [comment]
The equivalent vanilla code calls syncPacketPositionCodec followed by moveTo, I am not sure what the difference is between setPos and moveTo.

**Comment by sciwhiz12** [comment]
The functionality provided by 1.19's `VecDeltaCodec` existed in 1.18, but split across two parts: the `packetCoordinates` field in `Entity` (which corresponds to the `base` field in `VecDeltaCodec`), and the various methods at the beginning of `ClientboundMoveEntityPacket` (which corresponds to the methods in `VecDeltaCodec`). 

In particular to this issue, 1.18's `Entity#setPacketCoordinates` call become 1.19's `Entity#syncPacketPositionCodec`. During the patching cycle, someone must have encountered the compile error due to `Entity#setPacketCoordinates` and (understandably) didn't dig too deep into the issue, opting to quickly fix the error by replacing it with `Entity#setPos`.

**Comment by AzureDoom** [comment]
Fixed in latest release as the PR was merged.
