### ISSUE TITLE
[1.19] Game loads to main menu despite exception in registry event

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#8720]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.17 (latest at the time of writing)

**Logs:** [debug.log](https://gist.github.com/malte0811/1b87b90595f5124381acff5d0c667f95)

**Steps to Reproduce:**
 1. Download the MDK for 41.0.17.
 2. Apply [this](https://gist.github.com/malte0811/094a42210d70090270dd703a265f4612) change (i.e. throw an exception in one of the suppliers passed to `DeferredRegister#register`).
 3. Launch the game (`./gradlew runClient`).
 4. Observe that the game appears to load, but then crashes with an exception that does not point to the actual problem when joining a world.

**Description of issue:**
Throwing an exception during registration should produce a crash like other exceptions during loading. Instead the game continues to load to the main menu after reverting to the vanilla registry state and does not show the crash screen.

**Comment by ljfa-ag** [comment]
The problem is that the aggregated exceptions during the registry events are only being logged and not rethrown in https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/registries/GameData.java#L356 .
Maybe a `throw aggregate;` should be added (possibly change the aggregate to be more than a plain RuntimeException).

I think this is a serious issue since it will actually corrupt the savefile if you unsuspectingly try to load one. In my case, all modded block entites were gone.
