### ISSUE TITLE
Faulty mod versions can crash both minecraft and java resulting in no crash report or latest.log files

### ISSUE THREAD

**Issue by Peca21** [MinecraftForge/MinecraftForge#8748]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.35

**Logs:** No logs, that's the problem

**Steps to Reproduce:**
 1. Place a mod that has version set as "unspecified" in the mods folder. (MANIFEST.MF has Implementation-Version: unspecified)
 2. Start MC
 3. Get both half a crash report then Java crash (Exit code 1) in the middle of the crash report

**Description of issue:**
When you Place a mod that has version set as "unspecified" in the mods folder. (MANIFEST.MF has Implementation-Version: unspecified) minecraft will crash but in the middle of the crash report the java itself would crash with exit code 1 resulting in no crash report and no latest.log (sometimes it prints like the first two lines).
I know that a faulty mod is causing this but it should not crash bot minecraft and java at the same time, and should create a proper crash report.
Here is the crash report I managed to pull from launcher console:
https://paste.ee/p/W8glB

**Comment by TheCurle** [comment]
Hmm, i'm going to transfer this issue to securejarhandler, since it seems like this should be handled there or not at all.

The reason this crashes Java is because Forge since 1.17 uses Modules to load mods. 
Modules are a Java feature, and for a Module to be valid, the version must be a number (or at least, start with one. ie, 1.5-pre).
When you don't give it a number, Java cannot construct a module for the mod and thus Forge has no way of knowing anything about the mod in question to be able to create a clean crash report.

It's simply not valid in Java.

**Comment by TheCurle** [comment]
... apparently I can't transfer it to the other repository. Github y u be like this

**Comment by LexManos** [comment]
Issues can not be transferred across Orgs. You'll have to recreate it there.

**Comment by TheCurle** [comment]
Understood. https://github.com/McModLauncher/securejarhandler/issues/32 is made.
