### ISSUE TITLE
[1.18.2] UnitSprite class load crash outside of dev environment

### ISSUE THREAD

**Issue by nonamecrackers2** [MinecraftForge/MinecraftForge#8795]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.0

**Logs:** [Crash report](https://gist.github.com/nonamecrackers2/fee8178daff5195ab4ddfb1c9bf2ef6c)

**Steps to Reproduce:**
 1. Class load UnitSprite outside of dev environment (I've called UnitSprite.LOCATION under my main mod class constructor)
 2. Observe the game crash

**Description of issue:**
When UnitSprite is class loaded, UnitSprite.INSTANCE is created, which calls the private UnitSprite constructor which uses the UnitSprite.LOCATION static field which is null, due to what I presume is because LOCATION is initiliazed *after* INSTANCE. I've encountered this using the new OBJModel#bakeRenderable. This issue happens only outside of mod dev.

**Comment by sciwhiz12** [comment]
Confirmed to exist on both 1.18 and 1.19, since the introduction of `UnitSprite` (or `UnitTextureAtlasSprite` as renamed in 1.19) in PR #8259 which added the class with the erroneous ordering of fields causing `LOCATION` to be `null` during the class constructor.

Note that we could not observe the reported crash, but the underlying issue (the ordering of the static fields) is still the same and remains to be fixed.
