### ISSUE TITLE
[1.18.2 and 1.19.0] Removal of dimension mods will make singleplayer and server world saves unable to be loaded anymore. 

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#8800]
The patch from this PR seems to have been broken in 1.18.2 and remains an issue in 1.19 as well:
https://github.com/MinecraftForge/MinecraftForge/pull/7527

This can be reproduced by creating a world with Bumblezone mod. Closing game. Remove mod, And then try to enter the world again: 

https://paste.ee/p/wMNg2
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/9219117/latest.log)
![image](https://user-images.githubusercontent.com/40846040/175819060-7721380c-214d-4ca2-b2b2-b0ec6ad2b941.png)

Not sure what else needs to be specified but it is a very easy to reproduce issue

**Comment by stepsword** [comment]
In case it's helpful to anyone who stumbles on this trying to save their world before this is eventually fixed:

Get NBTExplorer, and open up your world.

Delete the mod you're trying to remove from `level.dat > fml > LoadingModList`, and from `level.dat > Data > DataPacks > Enabled`, and from `level.dat > Data > WorldGenSettings > dimensions`.

I haven't tested it in detail to know which of these specifically needs to be deleted, but deleting all of them has fixed the issue for several people, so it's what I've been recommending.

**Comment by TelepathicGrunt** [comment]
You only need to remove the dimensions that no longer exist (from the mods removed)

**Comment by OrionDevelopment** [comment]
Same issue as #8915 DFU has problems loading modding chunk generators and dimensions.

**Comment by Commoble** [comment]
okay so what I think is going on in 8800 is that the level.dat parser is trying to parse a bad dimension entry (because the mod with the datapack that added the dimension and dimensiontype was removed), and it's sneaking a dimensiontype holder into the dimensiontype registry as it parses it (via getOrCreateHolder or getOrCreateHolderOrThrow), which never becomes bound because no json for that dimensiontype exists

then when datapack registries freeze shortly afterward, you get this loading failure:

```
Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:dimension_type]: [the_bumblezone:the_bumblezone]
```

I wonder if it'd be viable to have MappedRegistry#freeze just log and discard its unbound holders instead of throwing an exception

I dunno if it's the best fix but it'd probably be the simplest one

though doing that has complications where you end up with things that probably should be crashing on datapack load (because you have jsons that refer to other jsons that don't exist) but don't (delaying the crash until you get an NPE at runtime later)

another option would be to somehow parse level.dat (filtering out invalid dimension entries) with one set of registries, then discard those registries, load another set of registries, and parse the (pre-filtered) level.dat with those
though this would increase world load times and it's already pretty chunky

**Comment by marchermans** [comment]
@Commoble Any idea how to solve this properly?

**Comment by Commoble** [comment]
I have reproduced this with the attached datapack in both vanilla and forge (the datapack has just one dimension and dimensiontype in it)

[dimension_removal.zip](https://github.com/MinecraftForge/MinecraftForge/files/9312985/dimension_removal.zip)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/9312986/latest.log)

* Create a datapack that has a dimension json and a dimensiontype referred to by that dimension
* Create a world using that datapack and verify that the dimension exists
* Close world
* Remove datapack from world
* Attempt to start the world again
* The following error happens when loading datapacks:
```
[Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:dimension_type]: [dimension_removal:fake_nether]
```
https://bugs.mojang.com/browse/MC-255158 <- vanilla bug report

**Comment by flabberghastio** [comment]
still happening 3 years later lol

**Comment by LexManos** [comment]
We've addressed the issues related to this post. Be sure to use the correct version of Forge.
Beyond that yes, Mojang's data system for dimensions is horrible and they havent addressed it in years. 
Yell at them to fix their issues, as we've fixed it on our end.
