### ISSUE TITLE
Enum interface obfuscation bug "AbstractMethodError"

### ISSUE THREAD

**Issue by ZephaniahNoah** [MinecraftForge/MinecraftForge#8808]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.34

**Steps to Reproduce:**
 1. Make an enum that implements IArmorMaterial and IItemTier.
 2. Make a tool or an armor piece that uses the enum
 3. Try to repair the item

**Description of issue:**
I tried to make a material enum that can be used for armor and tools.
It works fine when testing in my IDE. But, because these two interfaces have some of the same method names, after obfuscating the mod it renames the methods to the obfuscated names in one of the interfaces. So the methods from the other interface are now missing.
For example, `getRepairIngredient` would get renamed to `func_200924_f` causing an AbstractMethodError when I try to repair the item because it couldn't find `func_200898_c`.

For now I am dealing with the issue by adding the func_200898_c method myself.
```
public Ingredient func_200898_c() {
    return this.repairIngredient.get();
}
```

Maybe it should create a copy of the method when obfuscating. Or maybe make one method call the other.

**Comment by KnightMiner** [comment]
I doubt this is fixable, its simply one of the awkward things we have to deal with in regards to the obfuscator. You would run into the same issues if you tried to implement a non-obfuscated interface with the same name as a method in an obfuscated one.

I would suggest making separate enums, and making a method such as `MyTier MyArmorMaterial::getTier()`. Better separation of code as you can then reuse the tier enum for non-armor material.

**Comment by ZephaniahNoah** [comment]
Yea, probably way too much work for something easy to get around.
What about changing the mappings though? Something like `getArmorRepairIngredient` and `getArmorEnchantmentValue`.

**Comment by gigaherz** [comment]
Any workaround is not worth the effort. Just make 2 classes/enums. This issue isn't really fixable.
If you want to use a custom mappings provider that's your choice but you'll spend weeks working on something that will save you 5 minutes of splitting an enum into 2.

**Comment by ZephaniahNoah** [comment]
Awe come on. Have a little faith in me. It wouldn't take me *that* long to change the mappings, :stuck_out_tongue_winking_eye:
Anyways, I ended up adding the `func_200900_a` and `func_200898_c` methods. Creating one more enum for over 50 values didn't make sense considering they would both hold the same stats.
I guess you can close this if it's not worth fixing. Thanks

**Comment by LexManos** [comment]
This happens when you make collisions in the inheritance tree that Mojang doesn't. Its perfectly valid to do in java. But not something that's supported by reobf tools.
It *is* possible to fix, it would require the reobf tool to detect such cases, and inject synthetic bouncer methods into your class. Which is not something any tool supports so far.
As for making different mappings, you could the point of the mapping system is to allow you to use whatever ones you want without us needing to care. We just don't provide any mappings {MCPBot used to provide a channel, and the other one we use now is provided by Mojang's official mappings}

So ya, this is basically a edge case that is currently working as intended. If you want to look into it, feel free to see if you can detect and support it in <https://github.com/MinecraftForge/ForgeAutoRenamingTool>
