### ISSUE TITLE
glitching textures in 1.7.10

### ISSUE THREAD

**Issue by banaconda88** [MinecraftForge/MinecraftForge#8841]
Whenever I try and use 1.7.10 forge with any mods on, I can never hold items or go into a creative inventory without my screen becoming a single color. My game is only partially fixed when I hold a chest in my hotbar.

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue seems to be for an unsupported version of Forge, as we only support the Latest and LTS versions. Please update to a modern and supported version of Minecraft to receive support in the official Forge forums or Discord server.
