### ISSUE TITLE
Game Crashes Whilst Starting On 1.19 - F41.0.98

### ISSUE THREAD

**Issue by AceSardonyx** [MinecraftForge/MinecraftForge#8862]
![image](https://user-images.githubusercontent.com/77860646/178587494-d28fe3a9-f6c7-4de4-9427-9a022019c002.png)

Minecraft Version 1.19
OS: Ubuntu 20.04.4
Forge Version 41.0.98
[Error Log Here](https://gist.github.com/AceSardonyx/14cb00b085e149b08ed9377118cf0d0e)

Steps:
 1. Downloaded  mincraftlauncher.deb
 2. I downloaded the latest version of Optifine & Forge
 3. I loaded the game like normal, and that's it.

~Loading Game Issue~
I believe this doesn't matter since I didn't see mentions of it in forge, but I have Optifine installed, that's it.
But yeah, that's it :p

**Comment by PaintNinja** [comment]
You'll need to report this issue to Optifine. Due to the very old custom build system that Optifine uses, it essentially downgrades large parts of Forge to the version it's based on, which can sometimes cause issues like this.

To fix this, downgrade Forge to the version Optifine states on their download page or remove Optifine altogether.

**Comment by Bruh2801** [comment]
have a similar issue,no optifine though,just the newest version of forge (41.0.99) and nothing else,just crashes
