### ISSUE TITLE
[1.19] Conditional RenderTypes causes block model to become invisible

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#8913]
**Minecraft Version:** 1.19
**Forge Version:** 41.1.0

**Description of issue:**
I'm currently updating my mod to use the new `RenderType` system since the `setRenderLayer` methods are now deprecated. I am however having an issue when creating the same behaviour of leaves, where graphics on fast would be `SOLID` and Fancy/Fabulous would be `CUTOUT_MIPPED`. As suggested on the comments of the `setRenderLayer` methods, overriding `BakedModel#getRenderTypes` seems to be the new solution.

I am currently using the code below to switch between the different `RenderTypes`
```java
@Override
public ChunkRenderTypeSet getRenderTypes(@NotNull BlockState state, @NotNull RandomSource rand, @NotNull ModelData data)
{
    return ChunkRenderTypeSet.of(Minecraft.useFancyGraphics() ? RenderType.cutoutMipped() : RenderType.solid());
}
```

However when switching between Fast and Fancy/Fabulous doesn't seem to reflect the new `RenderType`. If I load the game initially with Fast graphics, switching from Fast to Fancy causes the block model to become invisible and vice versa.

![image](https://user-images.githubusercontent.com/4958241/181447034-602e677b-7dca-48ec-a6a6-7c46199cea1e.png)
![image](https://user-images.githubusercontent.com/4958241/181447146-8cb74a5c-281d-48f6-9564-25789a33d0a5.png)

Reloading resources also seems to have no effect on updating to the new `RenderType`. Also continuing to use the deprecated method has the same effect as shown.

**Comment by MrCrayfish** [comment]
I've created a test mod demostrating the bug. While writing, I discovered it may be related to multipart models. The bug doesn't exist when I copied the same blockstate/model as leaves but when I started using my own custom blockstate/multipart model the bug occurs. Hope this helps!
https://github.com/MrCrayfish/RenderTypeBug

**Comment by amadornes** [comment]
As I pointed out in the GH discussions channel on Discord, it is indeed caused by the way you wrap the models.

Multipart baked models are composed of other baked models, and as such they have to respect their requested render types. This means that querying `getQuads(...)` with an unexpected render type will cause the method to return nothing. And that's exactly what is happening in your case.

You can tackle this in one of two ways:
1. At the source, by using a custom model loader which returns a model with the correct render type that is then used in the multipart blockstate
2. Bypassing the problem entirely by calling the wrapped model's `getQuads(...)` with a `null` render type, which will request all quads regardless of the render type they're bound to

The former should be easy enough to implement, and is (in my opinion) a more correct approach. One way you could do it is by extending Forge's `ElementsModel` and wrapping the model returned in the `bake(...)` method in the same way you're doing it right now.

Hope that helps!
