### ISSUE TITLE
TagsProvider does not correctly handle remove/replace options

### ISSUE THREAD

**Issue by FiniteReality** [MinecraftForge/MinecraftForge#8949]
**Minecraft Version:** 1.19

**Forge Version:** 41.1.0

**Logs:** N/A

**Steps to Reproduce:**
 1. Create a `TagsProvider` for data generation
 2. Add a tag with `replace(true)` or `remove(entry)`
 3. Observe that the generated JSON does not include these options.

**Description of issue:**
From what I can tell, it looks like the .patch file for this explicitly hardcodes `false` when serializing tag values, and provides no way for serialising the remove list either: https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/data/tags/TagsProvider.java.patch#L45

This is a small snippet that reproduces the issue, using `WorldPresetTagsProvider`, but it should reproduce using any subclass of `TagsProvider<T>`.
```java
public final class MyTagsProvider extends
    WorldPresetTagsProvider
{

    public MyTagsProvider(DataGenerator generator,
        @Nullable ExistingFileHelper existingFileHelper)
    {
        super(generator, "mod", existingFileHelper);
    }

    @Override
    protected void addTags()
    {
        tag(WorldPresetTags.NORMAL)
            .replace()
            .addOptional(new ResourceLocation("test"));

        tag(WorldPresetTags.EXTENDED)
            .remove(new ResourceLocation("test"));
    }
}
```

**Comment by sciwhiz12** [comment]
In 1.18, tags were serialized using GSON. `Tag#serializeToJson()` was patched to include the `replace` value and to call `IForgeRawTagBuilder#serializeTagAdditions` to include the Forge-added `remove` entries.

In 1.19, it seems tag serialization was moved to the `TagFile` record and its `Codec<TagFile>`, where vanilla hardcodes `replace` to `false` (since they have no need of wholesale replacing tags in vanilla datagen) and Forge's `remove` entries are not accounted for in the record and codec.

Because the record and codec are unaware of the `remove` entries, deserialized tags do not have the `remove` entries. This used to be done by the `ForgeHooks#deserializeTagAdditions` method, which was patched into 1.18's `Tag.Builder#addFromJson`.
