### ISSUE TITLE
Many data packs broken by Forge due to mishandling of the `/execute` command

### ISSUE THREAD

**Issue by GrantGryczan** [MinecraftForge/MinecraftForge#8994]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.1, 43.1.2

**Logs:** (Seemingly not relevant, but I can provide them if asked.)

**Steps to Reproduce:**
 1. For singleplayer, join a world with cheats disabled. For multiplayer, join a server you administrate.
 2. For singleplayer, open to LAN with cheats enabled. For multiplayer, op yourself from the server console.
 3. Give yourself a command block: `/give @s minecraft:command_block`
 4. Place it and paste this command into it: `execute as @a run tellraw @s {"text":"If you see this message without command permissions, there's no issue!","color":"green"}`
 5. Place a button on the command block.
 6. For singleplayer, leave and rejoin the world. For multiplayer, deop yourself.
 7. Press the button. In vanilla, it displays a green message in chat. In Forge, it does nothing.

**Description of issue:**

`/execute` is one of the most common commands for data packs to use, allowing a data pack to execute a command as a player, among other things. In vanilla, the permissions of whoever or whatever ran the `/execute` command are used to execute the command as the target player, not the permissions of the target player. For example, you can do `/execute as <deopped player> run <command that requires op>`, and it will run just fine despite the target player not being opped, as long as the person running the `/execute` command has sufficient permissions.

But in Forge, without any mods, the permissions of the target player are used to determine whether the player can run the command, so this will not work unless the player is opped or unless they have cheats enabled, breaking many data packs that depend on this functionality (which is likely the majority of function-based data packs), including my own, which is how I found out about this (due to reports from multiple users).

This issue did not exist in Forge for 1.18.2. I'm not sure when it was introduced. I may or may not do some testing to find out which version it was introduced in, and edit this issue accordingly.

**Comment by sciwhiz12** [comment]
Ah, this is probably my fault. I'll look into it soon.

**Comment by sciwhiz12** [comment]
The cause of why the command in the issue's steps does not work on Forge is because of its use of the entity selector `@s`. In vanilla, entity selectors can only be used by operators with permission level 2 (`Commands#GAMEMASTERS`) and above, which includes commands blocks and functions by default.

When I made PR #8947 which redirects the entity selector permission check from the permission level alone to using a Forge-added permission, I failed to consider the point that I should be checking the actual command source (which could be an operator or a command block) rather than the target entity.

> **Note**
> As noted by the issue author, there is a difference between the command source, which originally executed the command, and the target entity/player. In the case where the console runs the command `/execute as Dev tellraw @a {"text":"Hi!"}`, the console is the command source and the `Dev` player is the target entity/player.
> Permission checks should run against the command source, not the target entity/player.

Fixing this should be as simple as opening up `CommandSourceStack#source` and using that in [`ForgeHooks#canUseEntitySelectors`](https://github.com/MinecraftForge/MinecraftForge/blob/b5d585555964b6149707514454ec3202a69cb66f/src/main/java/net/minecraftforge/common/ForgeHooks.java#L1501) instead of `CommandSourceStack#getEntity()`.

To be clear, the actual permission checks of the commands still respect the original command source rather than the target entity/player (as they use `CommandSourceStack#hasPermission(int)`). The problem here is that the permission check for the _entity selector_ is using the target entity/player rather than the original command source.

**Comment by GrantGryczan** [comment]
Ah, I see. Still an extremely common case though. Thanks for fixing this so quickly!

**Comment by The8BitMonkey** [comment]
I didn't see this issue at the time of posting my own.
However I would like to state that this is still an issue in the latest version of Forge (1.19.2 - 43.1.47) which I didn't make clear in my original post.

I've attached a video showing the bug in action: https://youtu.be/eJkrgG1bQSc
I've also a datapack to easily reproduce the bug yourself: https://www.dropbox.com/s/80dpejouiec01l1/forge_bug_test.zip?dl=1

If you use the datapack and you're opped, whenever you place a dirt block it will say "Hello (PlayerName)" but if you're not opped then it will simple come back with "Hello @s"

**Comment by GrantGryczan** [comment]
@The8BitMonkey It is fixed for me, last I tested it in 43.1.47. Are you sure your server is using an updated Forge version? Your client version doesn't matter.

**Comment by The8BitMonkey** [comment]
> @The8BitMonkey It is fixed for me, last I tested it in 43.1.47. Are you sure your server is using an updated Forge version? Your client version doesn't matter.

Hi, yeah it was the latest version on the server, I literally only installed it on the server not the client.
The issue has been fixed as far as effecting running a function directly or running it via a command but when it's ran from an advancement (using the reward option) the connection between the player that was rewarded the advancement and the function that is run from it is broken, so the game treats the function as if the server is running the command and not the player.

If you download the datapack I attached to the previous reply and add it to the server, if you start as opped and place down dirt it will say "hello (youname)" but when you deop yourself it will just say "hello @s" instead

Looks like it' might have just been an oversight when they implemented the changes and then the fixes and will hopefully be an easy solve for them
