### ISSUE TITLE
PlayerDestroyItemEvent deletes items if they are in the original item's slot

### ISSUE THREAD

**Issue by GekidoLukas** [MinecraftForge/MinecraftForge#9058]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.54

**Logs:** https://pastebin.com/W3vyhSuH (I did a debug message in chat when it happened that says: "This is the item + ItemStack")

**Steps to Reproduce:**
 1. Subscribe to the PlayerDestroyItemEvent 
 2. Get the hand that the item was in
 3. Replace the hand with any new ItemStack
 4. It will get deleted right after being placed there
 (A Debug message in the log will show that the item has been there)

**Description of issue:**
The Slot the original item was in is basically unusable during the Event, because any ItemStack that is put in there will be deleted at the end of it.

A possible case of this is this one:
https://pastebin.com/FZi3CQWu

**Comment by LexManos** [comment]
There are many code paths that call this event. You'll have to be more specific.
Also we use this as a place for confirmed issues. So use the forum or discord to do preliminary investigations.

**Comment by KnightMiner** [comment]
This issue was brought up again in the discussion of #9343 as potentially worth fixing in a new PR, so I would recommend reopening.

Three cases were mentioned as deleting the item:
* `Player#attack`
* `Player#interactOn`
* `Player#hurtCurrentlyUsedShield`

This may not be an exhaustive list, so a PR fixing this issue should verify all places firing the event will allow the item to persist after.
