### ISSUE TITLE
.GLB/.STL/.NIF Support possible?

### ISSUE THREAD

**Issue by LordRelentless** [MinecraftForge/MinecraftForge#9095]
I'm doing this here as I'm really not sure where to put it and I'm not familiar enough with Github to do a Pull Request.

Long story short; I'm very new to modding minecraft, and I'm currently using MCreator (yes I know, sometimes janky, some people don't like it and there's a million reasons why people seem to be against it, but for a novice and someone who doesn't know how to do Java yet, it's a good starting point). When I attempt to integrate .obj objects and their associated .mtl and texture pngs I can't seem to get them to show up correctly. I've spoken with the MCreator crew via Discord and they don't seem to have an answer. The textures just don't apply correctly and the objects always seem to be far smaller than they should be (this is in spite of setting offsets and so on). I think part of the issue from what I've read through multiple troubleshooting forums on importing 3D objects is that Forge is a limiting factor. Now I understand Minecraft is a huge part of this limitation, but I was wondering if there was anyway to integrate support for other 3D formats like .GLB (the native output for Microsoft's 3D Paint app). .GLBs as far as I understand are basically an integrated .obj .mtl and texture saved into a single file. It'd make modding, especially for novices such as myself, a bit easier. Especially if all we're trying to do is make set dressing, not inherently anything over the top. Like a static computer terminal or lamp. 

If it's not possible I fully understand, but I'm hoping it is something that can be implemented support wise with the Forge API so that MCreator might also gain that support.

**Comment by gigaherz** [comment]
Forge has an API for registering model loaders. If you were to write a loader for one of those formats, there's no reason why it shouldn't work. Do consider however that the block/item model system is really basic, only supports static models, no animations or such.
If you need more information you should visit the forums or discord server.

**Comment by LordRelentless** [comment]
I'm aware that the API does allow for registering model loaders, but for novices like me that's difficult, I have no idea really where to start to write such a model loader. Looking more closely at .gltf and .glb 3D object formats, .gltf is a native Java 3D model format which integrates the model and texture mapping. So native Forge support, at least to me, would make sense. In fact .gltf is a .json format, see https://sbcode.net/threejs/loaders-gltf/ By adding native support it'd really help new modders like me who are just learning Java. I started modding literally four weeks ago in an attempt to create some custom assets for a Minecolonies schematic I'm building. I haven't the knowledge nor the skill presently to write a loader, or know how to implement it. If I did, I wouldn't be here asking that such a feature be integrated so it can simply be pointed to when creating a mod. 

Not only that, but .obj can be easily converted to .gltf. If implemented natively as part of the API you could actually reduce bloat and improve performance. Since, if my understanding is correct, by having the model integrated into one file, you reduce load times and streamline the actual scripting. Or at least that's what's implied on sbcode.net You get the benefit of .obj support, but without needing to implement .mtl and textures separately.

**Comment by sekwah41** [comment]
Im not sure where you’ve got the info that gltf is a native java 3d model because you require either custom code or to use a library like JglTF.

```
glTF™ is a royalty-free specification for the efficient transmission and loading of 3D scenes
and models by engines and applications. glTF minimizes the size of 3D assets, and the runtime
processing needed to unpack and use them. glTF defines an extensible, publishing format that
streamlines authoring workflows and interactive services by enabling the interoperable use of
3D content across the industry.
```

While we may see a size improvement, given that most people load quite simple models into mc the improvements mentioned would not be as significant as you mention.

The main design of this model format is for browsers where network speeds are a big factor as well as mobile devices which have lower performance. Also three.js is javascript not java.

Im not arguing that more model support wouldn’t belong in forge, its just that its a lot more work or the bulk of adding another library.

I am not too familiar with glTF so I could be entirely wrong.

**Comment by LordRelentless** [comment]
Well from the site I linked you to with the example model loader "Assets can be provided in either JSON (.gltf) or binary (.glb) format."  Furthermore, it would appear that even according to the GLTF devs on their github suggests it's a Java based script modeling system not a Javascript based one, unless I'm missing something. https://github.com/KhronosGroup/glTF https://www.khronos.org/api/index_2017/gltf. It's also becoming a common standard for 3D printing and game modelling. It's supported by Maya, Unity, Unreal Engine 4/5, Red Engine, even Creation Kit for Bethesda games. So it's intended to be cross-platform. 

The thing is, the integration of the model, the UV Map, Texture Map, in a simplified single file and the fact that a Java based loader exists already, would mean it's easier to implement in game and reduces resource needs when loading 3D models vs current .JSON and OBJ 3D Models. 

I'm just saying it'd make introducing new 3D models to Minecraft easier for modders and reduce resource overhead on Servers. And GLTF can also integrate animation. Which means more complex animations and models can potentially be used in game while not seeing any major hit to performance.

**Comment by TheCurle** [comment]
Nowhere on the page you linked does it mention Java, nor is the repo even tangentially related to anything Java, nor is a Java implementation contained as an example.

The repo itself:
![image](https://user-images.githubusercontent.com/42079760/196226346-9617e0d8-b93a-46c7-8cca-33d8fdfabd44.png)

It's an arbitrary binary format that can be serialized (hence compatible with JSON), but by that logic Minecraft's builtin model system is also... whatever you claim it to be.

Adding support for reading this format does not magically solve the problems with it, does not magically make animations exist  in-game (there's still a lot of maths and expensive calculations to do behind the scenes!) and does not magically make it easier for modders to make models.

The fact of the matter is that including gltf, stl or any other format creates a maintenance burden for us, provides no utility for mod developers who do not already have these (extremely expensive!) tools that are designed specifically to make models in these formats, and requires rewriting every major version when Mojang rewrite how their model and rendering system works.

You seem to fatally misunderstand how gltf works, what it is on a most basic level, and what is involved in us implementing it into our *mod launcher*.

Our current format is shared with vanilla, so we get the benefit of the tools the community have made. Our current format works with a LOT of tools; BlockBench is used by the Mojang developers to make models for the game, and FREE tools like Blender can already output Minecraft-compatible model files. Our current format has almost zero maintenance burden for us, because it's maintained by Mojang. 

There's no benefit to us, to the community, or to modders if we add support for these.

Modders are not developers at triple-A studios using enterprise grade tools, which is what gltf is designed for.

However, the story is different for modders who wish to make a library mod, and don't have the problems associated with porting and updating the entirety of Forge in one go.

**Comment by LordRelentless** [comment]
Well, one, there are plenty of free software that utilize .gltf, and even the designer of the standard states it is a .json form. While I may not be fully in the understanding of how it works, I have been working with 3D modelling software for years now and with 3D printing. 

Blockbench is far from perfect, I've been trying to use it for the last four weeks to make basic models to create a Forge mod. Even a basic block exported to the Minecraft Asset format doesn't load correctly in 1.19.2. Whereas, at the very least, I was able to get a .obj to load even if the .mtl and texture didn't load. 

The problem I see that you've ignored, is that the method by which even static 3D models are loaded is convoluted require many steps to get them to appear correctly. Mainly because of limits in associating the .mtl and texture with the .obj 3D model. An integrated .json native (meaning it doesn't need to be translated into a loadable asset within the java based game engine for Minecraft, as it is already .json compatible and has the necessary information to be read) wherein the textures and UV mapping is already built into the model is simply easier. 

While yes AAA devs use this format, that doesn't mean it cannot and shouldn't be used in Minecraft. As Kronos says, .gltf is the jpeg of 3D modeling. 

Let me ask you a simple question which is easier for a computer, program, app, game engine to load; a multilayer RGB Raw image with hundreds if not thousands of layers, or a compressed .jpg image where all elements are combined into one thing that is read? The answer is the .jpg is easier, yes it may lose some quality (actually a lot compared to a raw RGB file) but it is easier to load, render, and manage. 

The same is true of the .gltf format. And because it's used across several hundred programs now and the 2.0 version has been around since 2017, it makes sense to find a way to use it. Just as you need a .obj .mtl and texture loader for a 3D .obj you need a loader for .gltf, but the difference is you only need one loader for the .gltf, not three.

**Comment by FinnT730** [comment]
You do realize that Forge needs to create that model loader and maintain it right? And for who? For very little amount of people.
All in the hopes that Mcreator might give support for it at the end of the day?

**Comment by LordRelentless** [comment]
I'm aware that Forge needs to create that loader, but let me ask you this; you say very little people would use it, but how do you know that is the case? Many people want to use higher quality models in Minecraft, and .gltf format would make it easier to do so.  In fact it could usurp .obj and even the very baser .json format used by Blockbench if actually implemented. Not to mention that the very entry level modeling software Paint 3D which comes from Microsoft saves in this format. Which means any number of novice people who are overwhelmed by the modding methods needed for Minecraft will have an easy to use tool to create their own models which is, sorry to say, far more intuitive than Blockbench or Blender, or other 3D modeling programs. 

You need to see past the upfront programming investment to the value of at least supporting one integrated 3D model format. Especially as Minecraft (Java and Bedrock) becomes more and more complex with each update.  And it isn't just about MCreator, it is about the overall functionality of modding with 3D models in Minecraft. MCreator is merely a tool to generate java code for a mod. It's limitations are based wholly upon the plugins and APIs available to it. If Forge integrates .gltf support, it opens doors for all levels of modders to introduce 3D models in an easier way. Be they a novice like me, or the most experienced modder and even Mojang Devs.

**Comment by FinnT730** [comment]
_removed my comment mainly since I am not the one suited to answer these things_

**Comment by KnightMiner** [comment]
@LordRelentless have you spent any time looking into how the vanilla model format works? You have spent a lot of time ranting about how great this model format is, but you have put zero effort into explaining what is insufficient about the existing formats (mojang's and .obj). You even mentioned that you can convert .obj formats to this other format easily, doesn't that mean you can convert from that other format to .obj easily?

Ultimately, you are asking someone to add code for you that you do not know how to add yourself. It would be a lot easier to justify this feature if you make the model loader yourself. Baring that, its on you to prove its useful by gathering those statistics. The Forge team does not need to gather statistics to justify not putting in hours of dev time to add a feature no one besides you asked for, its on you who wants the feature to justify its inclusion.
