### ISSUE TITLE
[1.19.x] Fix Level::getEntities() gatekeeping making multipart entities

### ISSUE THREAD

**Issue by GudBoiNero** [MinecraftForge/MinecraftForge#9109]
So I found this post recently about multipart entities and it's exactly what I'm trying to do currently.
As it mentions-
 [https://forums.minecraftforge.net/topic/102905-1171-multipart-entity-interaction/](url)
-the checking of if the entity is an ender dragon or not inside of `Level::getEntities()`  prevents the actual use of the `PartEntity` class in our own way to try and replicate the multipart hitboxes that the ender dragon takes advantage of. 
It's specifically set that way and makes it even more complicated to just simply make our own multipart entities. 

```java
if (p_151522_ instanceof EnderDragon) {
    for(EnderDragonPart enderdragonpart : ((EnderDragon)p_151522_).getSubEntities()) {
        if (p_151522_ != pEntity && pPredicate.test(enderdragonpart)) {
            list.add(enderdragonpart);
        }
    }
}
```
This `instanceof` check should be replaced with some other in between class like `MultipartEntity` or even just some way that allows us to mark our entity as having multiple parts. It's something that has been an issue for years as I've seen while researching this topic.

```java
if (p_151522_ instanceof MultipartEntity) {
    for(PartEntity part: ((MultipartEntity)p_151522_).getSubEntities()) {
        if (p_151522_ != pEntity && pPredicate.test(part)) {
            list.add(part);
        }
    }
}
``` 
I'm not a Java wiz, and I know computer science often it's not easy to "Just do this"; but this seems to be an unnecessary exception. I'm quite sure something along the lines of this example above could be possible.  

Now don't get me wrong- it's possible. But it's not very efficient to basically make it all yourself.
I request some redesign to this function to allow for a generalized class or interface to allow us to make our own multipart entities.

**Comment by sciwhiz12** [comment]
If you check the code below the `if (p_151522_ instanceof EnderDragon)` inside the two `Level#getEntities` methods, you will see that there _is_ code which handles `PartEntity`s. I suggest looking at `IForgeEntity#getParts` (implemented by the patched-in `EnderDragon#getParts`).

Please note that the forum post you linked (which you seem to have linked incorrectly, because clicking on the link itself leads nowhere) is for 1.17.1 and a year old at this point.

If you still believe that there is an issue, please file an actual bug report with steps and code example to reproduce the issue. If you have not ensured that the issue exists with a minimum reproducible example, your code may be at fault; please head to the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.gg/forge) to seek assistance.
