### ISSUE TITLE
Boat passengers don't burn in lava

### ISSUE THREAD

**Issue by itashki** [MinecraftForge/MinecraftForge#9256]
**Minecraft Version:** 1.19.2, 1.19.3

**Forge Version:** 43.2.0, 43.2.1, 44.0.37

**Steps to Reproduce:**
 1. Place lava on a sign (so it wouldn't flow down)
 2. Place a boat with a mob under the lava (or let a survival mode player sit in it)
 3. Observe that boat passenger doesn't burn nor take any damage from lava despite having it's hitbox inside lava block

**Description of issue:**
Boat passengers don't burn in lava.
![image](https://user-images.githubusercontent.com/41128086/209464320-26a8c871-d78c-4faf-9d6a-371758fe7550.png)

**Comment by ChampionAsh5357** [comment]
Ok, so in an effort to clean up multiple calls when implementing the fluid API, I migrated the `updateFluidHeightAndDoFluidPushing` method to be called only once and iterates through all fluids. The issue with this is that the fluid height does not update if the entity is in a boat. Vanilla got around this by calling the lava check regardless. However, the fluid API removed it so that the method, which is a bit computational, doesn't get called twice. This is still possible to implement and fix as we can just only update the states that doesn't support boating on the fluid, but it'll require a bit of thinking.

**Comment by bageldotjpg** [comment]
Was about to open an issue for this as I have been experiencing it lately. Worth mentioning that this issue also prevents Water from putting out fire in this situation.
