### ISSUE TITLE
inside_step_sound_blocks is ignored

### ISSUE THREAD

**Issue by KaBob799** [MinecraftForge/MinecraftForge#9315]
**Minecraft Version:** 1.19.3

**Forge Version:** 44.1

**Steps to Reproduce:**
 1. Place carpet on a noisy block like sand, then walk over it to hear the sand walking noise

**Description of issue:**
You can hear the block underneath the carpet instead of the carpet walk noise. Looking into the code, playStepSound in Entity sets a flag for inside_step_sound_blocks but then instead of using that flag it just checks if the block is snow or not.

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.3 (44.1.5) and 1.18.2 (40.2.0). It looks to be caused by a patching error. `Entity#playStepSound` has a patch that harkens from pre-1.17 that changed the plain `BlockState#getSoundType()` method calls to a context-sensitive Forge extension method that passed in the level, position, and triggering entity. 

In 1.17, the condition for the ternary changed from a simple check on `Blocks.SNOW` to a tag check against `BlockTags.INSIDE_STEP_SOUND_BLOCKS`. However, this was not noticed during the 1.17 patching process, and so the condition was patched back to the original simple block check. (There is a slight change in 1.19 where the tag check moved to a boolean variable, because the value is now also used in the `if` expression's condition.)
