### ISSUE TITLE
[43.2.0 (1.19.2)] Melons won't grow on mud

### ISSUE THREAD

**Issue by Collier9** [MinecraftForge/MinecraftForge#9336]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.0

**Steps to Reproduce:**
 1. Place water, farmland, mud adjacent
 2. Wait
 3. Keep waiting because nothing will happen

**Description of issue:** After testing the exact same farm on vanilla and on forge, I noticed melons would never actually grow on mud in forge, but would in vanilla.

**Comment by Collier9** [comment]
The issue persists on 43.2.4 as well

**Comment by ferriarnus** [comment]
It seems like there's a wrong patch in StemBlock

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.2-43.2.1, but not on 1.19.3-44.1.8. 

It seems the differences between 1.19.2 and 1.19.3 are: `StemGrownBlock`, the superclass of `MelonBlock`, implements the `IPlantable` interface; and `StemBlock#randomTick` passes the fruit block (in this situation, the melon block) to `BlockState#canSustainPlant` rather than the stem block itself. `Block#canSustainPlant` already uses the `dirt` block tag, which is why the issue doesn't manifest in 1.19.3.

**Comment by ferriarnus** [comment]
Is this change from 1.19.2 to 1.19.3 wanted? So that the fruit is passed along instead of the stem itself? It sounds like that would be wrong in 1.19.2? 

edit: #9270 seems to be the fix, but has not been backported to 1.19.2

**Comment by tmvkrpxl0** [comment]
They grow now(forge-1.19.3-44.1.16)
![2023-02-08_09 36 51](https://user-images.githubusercontent.com/41675181/217398865-e800603c-0533-4697-8931-769414116ab9.png)

**Comment by Collier9** [comment]
Hate to be a pain, but when can we expect a forge update for 1.19.2? The mods I am running on my server have not updated to 1.19.3 yet and this issue has broken some of our players' farms
