### ISSUE TITLE
Where is fix for ClientChatReceivedEvent in 1.19.2

### ISSUE THREAD

**Issue by Thomas7520** [MinecraftForge/MinecraftForge#9352]
Hello, i did an issue last month because ClientChatReceivedEvent in 1.19.X wasn't work for System Chat. It was fixed however the fix isn't exist for 1.19.2 ( seems 43.1.31 doesn't exist on https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.4/forge-1.19.2-43.2.4-changelog.txt ) 

Version : 1.19.2 
Link : https://github.com/MinecraftForge/MinecraftForge/issues/9267

**Comment by TheCurle** [comment]
I'm not sure what you're asking. 43.1.31 is in the changelog file:

```
 - 43.1.31 Fix ClientChatReceivedEvent for system messages
```

And as the changelog is created by the same tools that build and publish all the Forge artifacts, that's a version of Forge that you can download and run.

There's no other way to describe it. All versions of Forge after 43.1.31 have the fix, because Github is an iterative process and all prior patches and inclusions are included in future versions.

**Comment by Thomas7520** [comment]
@TheCurle of course, i know that the fix are included in future versions. However, If I say that the update is not there, it is precisely because there is a problem. so where is onClientSystemChat in 1.19.2 ? https://i.imgur.com/DTgHtnZ.png https://i.imgur.com/CO5pHF0.png I'm confused

**Comment by ChampionAsh5357** [comment]
I mean...you're trying to search a text file instead of just following the reference call using your IDE. So, yes, it isn't the location you are trying to find it in, but it is definitely there as I can confirm.

**Comment by Thomas7520** [comment]
@ChampionAsh5357 It was just a screenshot to illustrate my remark about the lack of code.

**Comment by ChampionAsh5357** [comment]
What lack of code? Again, follow the reference call using the tools supported by your IDE. I don't know why you're showing two different versions from 1.19.2 and 1.19.3 since their incomparable as the event changed. All you would need to do is check if `#isSystem` returns true in the event. You can do that just by reading the javadoc on the class.

**Comment by Thomas7520** [comment]
@ChampionAsh5357 look https://github.com/MinecraftForge/MinecraftForge/issues/9267 ( and the pull request in the link ) , This should inform you about the situation, because I think you don't understand what I am getting at. This patch should have been set for 1.19.X, so whether it's 1.19.3 or 1.19.2, it should be the same "piece of code"

**Comment by ChampionAsh5357** [comment]
No? 1.19.2 is a separate branch and has been since December. So, that would only be for 1.19.3 and onward unless somebody backported it.

**Comment by Thomas7520** [comment]
i don't know, but that i'm sure is the patch was implemented on 1.19.2 https://i.imgur.com/mDJmC78.png but for me it did not take effect. That's why I'm here

**Comment by ChampionAsh5357** [comment]
So...literally what I mentioned earlier. Read the event javadocs since it works as intended. Here is literally the patch showing the fix for system messages in 1.19.2.

https://github.com/MinecraftForge/MinecraftForge/blob/ac94478ae71229c82babcd880b1ed8621b1c5a94/patches/minecraft/net/minecraft/client/multiplayer/chat/ChatListener.java.patch#L25-L32

**Comment by Thomas7520** [comment]
Actually, this is the wrong fix post, it must have been yet another fix, it has no relation to the one I posted. That's why the patch is not in 1.19.2... I'm sorry for this mistake, but I would like to see this patch in 1.19.2 as well.

here is the pull : https://github.com/MinecraftForge/MinecraftForge/pull/9284

**Comment by ChampionAsh5357** [comment]
Then create a PR backporting the fix if you would like to see it in 1.19.2.

**Comment by Thomas7520** [comment]
I don't know how to do that.

**Comment by SizableShrimp** [comment]
Fixed by #9355.

**Comment by Thomas7520** [comment]
> Fixed by #9355.

love you <3
