### ISSUE TITLE
[1.19.4] Precipitation doesn't seem to be cancelled in biomes where it should be

### ISSUE THREAD

**Issue by bconlon1** [MinecraftForge/MinecraftForge#9397]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.9

**Logs:** N/A

**Steps to Reproduce:**
 1. Create a new world.
 2. Locate a desert (e.g. through `/locate biome minecraft:desert`).
 3. Turn precipitation on with `/weather rain`.

**Description of issue:**
Rain/precipitation occurs in biomes where it shouldn't according to `"has_precipitation"`. This extends to modded/datapack biomes as well.
![2023-03-19_12 54 55](https://user-images.githubusercontent.com/67203206/226205684-a413dfd4-ee90-4edf-912e-fce37b6077d8.png)

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.4-45.0.10. 

In 1.19.4, `ClimateSettings` was modified from storing a `Precipitation` enum value to a boolean `hasPrecipitation` value. (The game checks the biome temperature to determine whether to rain or snow.) Thus, `ClimateSettingsBuilder` had to be modified accordingly, but [the `#build` method](https://github.com/MinecraftForge/MinecraftForge/blob/d552ce5eac046c3d8bc3dc1f13b1a19aebd7c6ae/src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java#L57-L60) was mistakenly modified to always set `hasPrecipitation` to `true`. 

As all biomes (such as `minecraft:desert`) are recreated from builders due to the biome modifiers system, this error caused all biomes to have precipitation, regardless of whether their original data marks them as having no precipitation.
