### ISSUE TITLE
[1.19.4] Cannot exit swimming mode while underwater

### ISSUE THREAD

**Issue by Cinex20** [MinecraftForge/MinecraftForge#9399]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.9

**Steps to Reproduce:**
 1. Jump into a body of water deep enough to swim.
 2. Start swimming by moving forward and pressing sprint.
 3. Stop moving forward.
 4. Try standing on the bottom. Look up and down without pressing any movement buttons.

**Description of issue:**
Once you enter swimming mode, you cannot go back to neutral without getting out of the water. Looking up or down will move your character up and down without pressing any keys. The issue is not present in vanilla version of Minecraft.
It's also impossible to swim while in elytra mode, but this issue seems present in vanilla as well.

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.4-45.0.10. [An error in `LocalPlayer#aiStep()`](https://github.com/MinecraftForge/MinecraftForge/blob/d552ce5eac046c3d8bc3dc1f13b1a19aebd7c6ae/patches/minecraft/net/minecraft/client/player/LocalPlayer.java.patch#L66-L67) due to a combination of local variable shifting and fuzzy patching caused this issue.

In 1.19.4, the boolean variable used to determine whether the player is holding down forward or has enough food to sprint was renamed in decompiled code [from `flag5`](https://github.com/MinecraftForge/MinecraftForge/blob/1f44339d6ef80827910b8db11de4907611c082e4/patches/minecraft/net/minecraft/client/player/LocalPlayer.java.patch#L66-L67) to `flag7`. However, because of fuzzy patching and not enough scrutiny, the Forge patch kept the use of `flag5`, which is incorrect.

The solution is to fix the variable being used from `flag5` to the correct `flag7`.
