### ISSUE TITLE
Blocks such as Sculk Blocks and Redstone Ore do not drop experience when blown up by a player source

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#9423]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.25

**Logs:** https://paste.ee/p/tTcij

**Steps to Reproduce:**
 1. Place Sculk Blocks
 2. Place TNT
 3. Detonate TNT in a manner that is player-sourced. This includes firing a flame-bow arrow at it, or directly igniting it with flint and steel
 4. Observe that exploded Sculk Blocks do not drop XP
 5. Repeat in vanilla
 6. Observe that exploded Sculk Blocks do drop XP

**Description of issue:**
As title/repro steps.

**Comment by LexManos** [comment]
Because of how Mojang implemented this 'generic' exp drop block. We are going to have to choose between droping double experience when a player digs certian blocks, or it not droping when broken by world mechanics, including pistons/neighbor updates. Unless someone else can figure out a good system that doesn't involve completely re-writing the resource drop codepaths.

**Comment by Darkhax** [comment]
This issue is far more widespread than the sculk block and Mojang's `DropExperienceBlock`. It affects seemingly all vanilla blocks that drop EXP when removed by a player.

Tested the following on 45.0.40
- `RedstoneOreBlock`
- `SculkCatalystBlock`
- `SculkSensorBlock`
- `SculkShriekerBlock`
- `SpawnerBlock`
