### ISSUE TITLE
[1.19.4] Pick Block results in unusual behaviour

### ISSUE THREAD

**Issue by Andromander** [MinecraftForge/MinecraftForge#9459]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.46

**Logs:** https://gist.github.com/Andromander/5a84755d67f7cac30c42eb4e017977b9

**Steps to Reproduce:**
 1. Pick a block.
 2. Place it to ensure that it is able to be placed in the world.
 3. With the selection box over the occupied slot, pick a different block.
 4. Attempt to place the first picked block

**Description of issue:**
When attempting to place the first picked block in the above description, it seems to fail placement. It emits a sound and briefly displays, but it doesn't last more than a tick before it phases out of existence, not breaking. Unfortunately, the debug log I've provided doesn't have anything of use from what I've seen.

I've recorded a video of the steps taken to best illustrate the problem:

https://user-images.githubusercontent.com/29526717/233573110-e9aedaf7-d556-415b-9b3f-fbcd09f59c2f.mp4

The issue appears to stop when entering another menu. Since this issue is affected by block picking, entering the Creative Menu is the easiest menu to access, and placing the affected block afterwards shows no issues. I've tried this with various blocks, including modded blocks and vanilla blocks.
~~Something else I have observed but not entirely certain is a vanilla feature, but when picking a block when the highlighted slot, it shifts the old item over. In previous versions, the new item would occupy the next available slot or move the occupied slot's item into the Inventory if the hotbar was full.~~ Correction: the first item will be shifted over to the first available item slot. If the cursor is, for example, in the 5th slot with an item and nothing in the 1st slot, the new item will occupy the 5th slot and push the first item into the 1st slot. Same applies if the 1st slot is occupied, it moves to the second slot. Again, not entirely certain if it is vanilla behaviour.

Further testing with other kinds of items such as Bows and Spawn Eggs, their behaviour is similarly affected. If the original item was a Bow, it will pull but no arrow is shot. If the original item was a Spawn Egg, the entity fails to spawn. Behaviour persists when changing game mode to Survival to test if the item is consumed on use, which turns out it does not.

Additional note: looking into what happens during interactions, such as SpawnEggItem's useOn method, the ServerLevel is never passed in. Digging further into the process, it turns out all the inventory can see is Air where the affected item is.

**Comment by Andromander** [comment]
Upon further investigation into the pick block function, I noticed something rather odd [in these lines](https://github.com/MinecraftForge/MinecraftForge/blob/b398f52a7f9885b2a181092d04af9679d4fb3e6b/patches/minecraft/net/minecraft/world/entity/player/Inventory.java.patch#L11-L16). I can't say quite for certain if this is the root cause, but it is something I have noticed. Seems like it may have been introduced in the 1.19.4 port.

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.4-45.0.46 in a Forge development workspace.

You are on the right track: that patch [was modified during the 1.19.4 port](https://github.com/MinecraftForge/MinecraftForge/commit/44c689f1712fcfb7ccb13262d1c02f0a880055be#diff-c89adf95d1b939b0e5e8093cd4c835fb08c75131d07ac30b64888a64764725f1) to move a brace downwards. This causes `getSuitableHotbarSlot()` to behave differently; instead of checking first for empty hotbar slots (the first loop) then checking for a slot with an item that can be replaced by a pick action[^replacable] (the second loop), the erroneous brace placement causes the second loop to happen for every iteration in the first loop. This means that if the selected slot is not empty, as is the case in this issue, it proceeds to check for pick-replaceable hotbar slots instead of checking for empty hotbar slots.

Now, the issue with the seemingly-useless item that was moved over (the original item in the selected slot before the pick action) is what I believe to be a desync between the server and the client. The client calls `Inventory#setPickedItem(ItemStack)` with the new picked item stack, which calls `getSuitableHotbarSlot()` above and does the work of moving the original item over to a free slot if available, and setting the picked item stack to the selected slot.  

However, the client only informs the server about (and the server only acts on) the change in the selected slot.[^abnormality] This means the moved-over original item is a ghost item that exists only on the client; at least (as far as I understand it), until the client's creative-mode inventory authoritatively[^authority-ex] tells the server the actual contents of the player's inventory, syncing both sides and restoring the moved-over original item to be usable.

Removing the erroneous patch that moved the brace in `Inventory#getSuitableHotbarSlot()` fixes the issue.

[^replacable]: Examples of items which _cannot_ be replaced by a pick action are enchanted items. This allows a player who normally wields an enchanted sword or pickaxe to retain that tool in its original slot, instead of being replaced with what they picked (and inadvertently leaving themselves defenseless).
[^abnormality]: I believe this is because in normal circumstances, the creative-mode inventory will either use an empty slot, replace the selected item, or move the slot selection to another hotbar slot; there's no logic to handle the case of the original item being moved and a new item in its place, as is done in the regular inventory to preserve the original item.
[^authority-ex]: The creative mode inventory is one of the very rare exceptions to the general rule that the server is the authority on the game state; another such exception is the player's movement.
