### ISSUE TITLE
[RFC] Removal of in-code render type registration

### ISSUE THREAD

**Issue by Matyrobbrt** [MinecraftForge/MinecraftForge#9468]
Forge [has been patching `ItemBlockRenderTypes`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch#L94) with render type registration methods that are compatible with vanilla.
 During the 1.19 client refactor, a property in block models has been added, and the patched-in methods are deprecated for removal in 1.20.

This issue is to be used for discussing the benefits and downsides of the removal of in-code render type API during the 1.20 lifecycle.

**Comment by Technici4n** [comment]
Hello, AE2 dev here. I would like the code registration to be un-deprecated and kept for the following reasons:
- It works well, and is aligned with what vanilla is doing.
- If the code registration gets removed, the path of least resistance for us is to reimplement the hook ourselves using Mixin (we're not gonna be changing 100s of model files), and I suspect many other community members would do the same.

**Comment by alcatrazEscapee** [comment]
I will also add two points:

- Having vanilla-like render type registration is a helpful when considering multiloader / multiplatform mods, where having to ship both functionalities (in code registration + in model render types) is more work to maintain.
- Removing default registration means that any resource packs need to be made aware of default render types - you cannot make a default resource pack for a mod, which changes a model, without being aware of Forge's render types and how they apply to your model, unlike for resource packs for vanilla. Again, I think this is a significant downside.

**Comment by LexManos** [comment]
Just tossing my two cents in here because we've talked about it a few times internally.

Moving the data to the json file is not a bad thing. However until Mojang does it themselves with their models I see no reason to remove the in-code functionality. My proposal is that we keep the methods, still mark them as deprecated just not for removal. With comments to explaining the json system and the difference between expicit and default values.
We should be able to detect when a model is loaded with NO type set in the json. When that happens we can fall back to the in-code registry. This would solve the issue with resource packs 'not knowing' about render types. But also give them the power to edit things however they like.

I will also say this, that if someone makes a resource pack for a mod. Without consulting that mod's default resource pack {and thus seeing the render type if specified in the json} then, in my opinion, that's just a broken resource pack. Which is something I don't think we should put TOO much emphasis on. There are plenty of things users can derp up if they arnt paying attention to their data files. 

Unfortunately, there is no other annotation out there that has IDE integration that means a 'Hey be careful when using this there are things you should know', so best we got is @Deprecated

**Comment by gigaherz** [comment]
I currently rely on in-code registration for my Json Things mod, for the purposes of default render types. When someone declares a json block for say, a leaves, that model is set to cutout such that the user can reliably have a model equivalent to vanilla without having to manually specify a custom render type for every model.

Removing it wouldn't be a huge break for me, but it would mean I have to tell people that they are required to set the render type themselves, and I would have to deal with with the extra support requests of people's models not working.

So overall, I would prefer those methods to continue existing, although I don't mind them remaining deprecated (hopefully without the `forRemoval` flag).

[EDIT: oops I accidentally some swapped words]

**Comment by TheCurle** [comment]
We have decided, therefore, to not remove the code render type. The deprecation for removal will be rescinded, but a general deprecation pointing to the JSON system will stay in place, to aid visibility of the new feature.

I expect this will remain the case for the forseeable future, or until Mojang changes how they do their own render types.
