### ISSUE TITLE
[1.19.2] IConditions for worldgen jsons do not work

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#9490]
In 1.19.2 Forge, this PR was merged and says this: `Conditions can be added to ANY datapack registry JSON file`
https://github.com/MinecraftForge/MinecraftForge/pull/9113

I did a test with 43.2.10 Forge of putting it on a structure JSON file like so in this picture but the structure remained registered and shows up in game. Thus the ICondition is not working to keep the structure JSON file from being loaded when modid is not present.
![image](https://user-images.githubusercontent.com/40846040/236704692-682c65a7-fbe4-4a1c-b018-1618a599372b.png)

Let me know if any additional info is needed. If you need structure json to quickly test with, you can use these from vanilla and put it under your own modid to see if it shows up in game or not with the locate command: https://github.com/misode/mcmeta/tree/data-json/data/minecraft/worldgen/structure

**Comment by Shadows-of-Fire** [comment]
Issue root-caused:

Structures in isolation will behave as expected, due to being loaded from `RegistryLoader#overrideRegistryFromResources`.  

However, other references to structures, such as structure tags, cause a Holder to be generated via `RegistryLoader#overrideElementFromResources` (the package-private variant).

There are two options here - either this is working as intended, and all references to the conditional structure need to be similarly guarded behind conditions, or this is an issue, and `overrideElementFromResources` needs to be patched to also check conditions before passing to the private `overrideElementFromResources`.

The concern with doing the condition check in `overrideElementFromResources` is how errors will propagate when the condition causes a load failure, as that is an unknown at this time.  Based on the current implementation, returning `DataResult.error` is an acceptable result, but it may cause the entire LevelStem loading stack to explode, depending on how other components handle the lack of one being present (if they fail hard or fail soft).

**Comment by Shadows-of-Fire** [comment]
Additionally, this issue should be unique to 1.19.2, as the loading process was changed in 1.19.3.
