### ISSUE TITLE
PlayerDestroyItemEvent doesn't trigger for Fishing Rods

### ISSUE THREAD

**Issue by Insane96** [MinecraftForge/MinecraftForge#9508]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.50

**Logs:** None

**Steps to Reproduce:**
 1. Subscribe to `PlayerDestroyItemEvent`
 2. /give @p fishing_rod{Damage:200}
 3. Use and retrieve the bobber
 4. The event is not triggered

**Description of issue:**
As the title says, `PlayerDestroyItemEvent` is not triggered for Fishing Rods.

**Comment by ChampionAsh5357** [comment]
The event mentions it should be triggered on `ServerPlayerGameMode#useItem`; however, it isn't. While the event is called on the client, as the fishing rod is only removed on the server, it has no understanding that the item has changed. It looks like the change was never implemented server side, so I'm not sure why this was mentioned.

Regardless, it can be fixed by implementing the event within `ServerPlayerGameMode#useItem`, probably within the `ItemStack#isEmpty` check.

**Comment by MCStreetguy** [comment]
I can add that this is still the case for Version 47.1.0 / MC 1.20.1, the event is not firing at all for fishing rods.
