### ISSUE TITLE
[1.18.2] Cannot place water

### ISSUE THREAD

**Issue by Paultje52** [MinecraftForge/MinecraftForge#9514]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.7 (also happens on 40.2.6) 

**Steps to Reproduce:**
1. Go into the overworld
2. Try to place a water bucket

**Description of issue:**
You cannot place a water bucket in the overworld or the end. If you place one, you'll get the same evaporation particles as in the nether.

This happend after #9341

**Comment by Matyrobbrt** [comment]
This seems to be caused by a difference in the (refactored) 1.19 fluid API and the 1.18 one.

In 1.18, `doesVaporize` is a "simulation" of whether the fluid should vaporize *if* it were to be placed in a warm dimension, meaning that it relies on an external check, rendering the level parameter it is given useless.
In 1.19, after the refactor, the default implementation [also checks](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/fluids/FluidType.java#LL826C47-L826C47) the dimension's properties to see whether the fluid should vaporize,
