### ISSUE TITLE
[1.20] GLM is not applied to entities when killed

### ISSUE THREAD

**Issue by JaisDK** [MinecraftForge/MinecraftForge#9551]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.12

**Steps to Reproduce:**
 1. Create a loot modifier for an entity that adds a loot item
 2. Kill entity
 3. no custom loot

**Description of issue:**

Looks like in 1.20 the LivingEntity::dropFromLootTable method is calling a different loottable.getRandomItems method which is not triggering net.minecraftforge.common.ForgeHooks.modifyLoot

Getting loot with the loot command works fine

**Comment by Jackbusters** [comment]
I am also experiencing this issue.

**Comment by Eelt** [comment]
I'm also experiencing this, but it seems like--at least for me--this is occurring since 1.19.4 (1.20.x inclusive). But I'm not sure if it's a "me" problem or a Forge problem for 1.19.4.

This loot modifier doesn't fire since 1.19.4, and doesn't in 1.20.x:
https://github.com/MikeTheShadow/VoluminousEnergy/blob/1.19.4-0.4/src/main/java/com/veteam/voluminousenergy/loot/modifiers/AnimalFatLootModifier.java

EDIT: The 1.19.4 issues seem to be fixed in the RB for 1.19.4, but the Issue in 1.20/1.20.1 still stands

**Comment by vectorwing** [comment]
Testing on 1.20.1, and I'm also having this issue. None of my loot modifiers which target entities (`minecraft:entity_properties`) seem to be working, despite no syntax changes in this version.
