### ISSUE TITLE
Key Modifiers are ignored in Forge > 47.1.22

### ISSUE THREAD

**Issue by djnifos** [MinecraftForge/MinecraftForge#9806]
**Minecraft Version:** {Minecraft version}
1.20.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}
Any version from 47.1.23 -> 47.2.8

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/djnifos/ffb0da53ad6174f83190d246011b4799

**Steps to Reproduce:**
 1. Bind a keybind to a modifier + a key
 2. Press the key without the modifier
 3. Action happens anyways

**Description of issue:**
The game ignores the modifier keys missing.  Tested shift, control, and alt.  Behavior does not exist in 47.1.22 or previous.  This reduces available keybinds to users which impacts playability in large packs. 

The debug log doesn't show anything from what I could tell but it's included.

**Comment by LexManos** [comment]
Unable to reproduce in any of those versions using any modifier. Tried a simple setup, making move forward require a modifier and it worked as expected.

**Comment by djnifos** [comment]
Should I make a video?  I did open achievements with Alt-G Ctrl-G and Shift-G.  Just G will open it

**Comment by LexManos** [comment]
Ah, so this only effects things that use the keybindings in a certain way. Which happens to be the way the advancement screen uses it, but not the way the movement keys use it. Which explains why my tests didn't work. Which is also why explicit instructions are appreciated.

**Comment by djnifos** [comment]
I had verified quite a few different ones in a full pack, then only the advancements with just forge installed.  I will be more explicit in the future, should I need to file any more.  Thanks!

**Comment by Eragonawesome** [comment]
I am having this same issue in version 47.2.20 in the All The Mods 9 To The Skies pack version 1.0.6

To reproduce:
Bind shift to sprint
Bind E to inventory
Bind open wireless crafting grid to Shift + E
Press the E key on its own to open your inventory
Close your inventory
Press the shift key on its own
The wireless crafting grid opens if you have one equipped, or puts a message in chat telling you that you don't have one equipped

**Comment by LexManos** [comment]
The key events work fine on our end.
There may be some mods who relied on broken behavior, so you can ask them. I would bet that whatever provides the 'wireless crafting grid' is doing their conflict resolver incorrectly. Not an issue on my end.

**Comment by ninjomoe** [comment]
im just gonna post it here just in case it helps, this bug is still happening on all refined storage versions for 1.20.1 with forge version 47.3.5

It didnt happen on 1.18 or 1.19
And it doesnt happen on Forge Version 47.1.22

**Comment by ninjomoe** [comment]
ok so i tested it on every forge version on 1.20.1.

The Ctrl + E interaction for the refined storage wireless terminal works as usual on forge version 47.2.8 and doesnt work for 47.2.14 and any version above.

**Comment by ninjomoe** [comment]
I FOUND A MOD THAT FIXES THIS!!! 

https://www.curseforge.com/minecraft/mc-mods/key-binding-patch

This works on 1.20.1 on the newest forge version 47.3.5 and the newest refined storage version 1.12.4

**Comment by LexManos** [comment]
For future note, the few cases that were brought up here, the issue is the modder and their mod having invalid conflict contexts. Most cases they just blindly set their [context](https://github.com/MinecraftForge/MinecraftForge/blob/1.21.x/src/main/java/net/minecraftforge/client/settings/IKeyConflictContext.java#L18) to [always inactive](https://github.com/yyon/grapplemod/blob/61dd2af68a403dc9f6dbb6e659bfffa4b9bbad5f/src/main/java/com/yyon/grapplinghook/client/NonConflictingKeyBinding.java#L16), so obviously Forge never calls their keybinding.

**Comment by ajaxnotmeta** [comment]
> For future note, the few cases that were brought up here, the issue is the modder and their mod having invalid conflict contexts. Most cases they just blindly set their [context](https://github.com/MinecraftForge/MinecraftForge/blob/1.21.x/src/main/java/net/minecraftforge/client/settings/IKeyConflictContext.java#L18) to [always inactive](https://github.com/yyon/grapplemod/blob/61dd2af68a403dc9f6dbb6e659bfffa4b9bbad5f/src/main/java/com/yyon/grapplinghook/client/NonConflictingKeyBinding.java#L16), so obviously Forge never calls their keybinding.

may i ask? why every mods on Forge hapen to have this issue? this drives me nuts! heck Even Project Architect 2 and ATM9 have this same issue
edit : i might need to dig deeper as it seems more strange, using same mods(sophisticated Backpacks, Curios and "On a Stick") i het the same bug when directly running the game on 47.3.12(Currently lastest i think?) but when i tried to run the game on 47.1.22 then 47.2.14 and lastly on 47.3.12 the issue was gone. 
*do keep in mind im not developer, but im tryng to find a way to replicate the issue here
