### ISSUE TITLE
Game crash in Chinese path

### ISSUE THREAD

**Issue by Yttrin** [MinecraftForge/MinecraftForge#9888]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.33

(Also happen in Minecraft 1.19.2 Forge 43.3.7)

**Steps to Reproduce:**

 1. Put .minecraft folder in a Chinese path (e.g. ```C:\Program Files (x86)\中文名\.minecraft\```) and start it. It crash before anything starts.

**Description of issue:** 

By removing Forge the crash can be avoided.

I tested in [HMCL](https://github.com/HMCL-dev/HMCL) and PCL. If there's some better way to reproduce I'll try.

**Comment by LexManos** [comment]
I need log files of some kind in order to help you. As I made a folder named `D:\中文名` and it loaded just fine. Logger was a bit weird because it used UTF8 but other then that everything loaded fine.

**Comment by Jonathing** [comment]
This could also be a permissions issue, as iirc `%ProgramFiles(x86)%` is owned by admin.

**Comment by LexManos** [comment]
Quite possible, which is why a log of the actual crash is needed.

**Comment by burningtnt** [comment]
I think you should do these steps to solve your problem.

(Chinese Solution: )
在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-03/zsLRF3LrcD0we0hj.png

This problem happends so often on Chinese Minecraft players..., which is NOT caused by Forge. Actually, it's because of the bad compatibility of your JVM.
