### ISSUE TITLE
Vault Block crash in 1.20.6

### ISSUE THREAD

**Issue by BelgieYT** [MinecraftForge/MinecraftForge#9956]
1.20.6 (you have to have 1,21 experimental toggles enabled

1.20.6 50.0.0+

Crash report - https://pastebin.com/mfueBq8F

**Steps to Reproduce:**
1. Create new world (you need experimental toggles enabled
2. Place down a vault block
3. The game will crash due to rendering enchanted items in the vaults (this can sometimes take some time as it cycles items)

When placing down a vault block part of the 1.21 update the game will crash due to rendering enchanted items, it can render any item that isn't enchanted but as soon as it shows one with enchants the game will crash

**Comment by Jonathing** [comment]
Ok, the stacktrace directly points to `IForgeItem`.

**Comment by azure-bluet** [comment]
This bug also happens when experimental datapacks are disabled.
[crash-2024-05-03_18.11.26-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/15198847/crash-2024-05-03_18.11.26-server.txt)
[crash-2024-05-03_18.17.58-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/15198851/crash-2024-05-03_18.17.58-server.txt)
[crash-2024-05-03_18.27.40-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/15198852/crash-2024-05-03_18.27.40-server.txt)
